### ISSUE TITLE
Please Add Copy Header Name

### ISSUE THREAD

**Issue by datauduong** [microsoft/vscode-mssql#1000]
Please Add Copy Header Only, very handy would be cool (available in ssmsboost).
eg:
if a row is selected, then **copy header** would copy all the column name with comma separated.
-- Extra Also Put the Name in Single Quote where there is a space
---- eg: "Hello World" = 'Hello World' or [Hello World] (SQL Column Syntax)
if a cell is selected, then **copy header** would copy the current column name.

**Comment by kevcunnane** [comment]
Adding the `Help Wanted` tag as this is a good community contribution candidate.

**Comment by mukunku** [comment]
Please add this feature
