### ISSUE TITLE
keyboard navigation of the results

### ISSUE THREAD

**Issue by BenjaminPhillips22** [microsoft/vscode-mssql#1001]
- MSSQL Extension Version: 1.2.0
- VSCode Version: 1.15.1
- OS Version: Windows 8.1

Steps to Reproduce:

1.  execute sql query
2. press ctrl+2 to move to the output of the query
3. Can not use the arrow keys to navigate the output.

Other information;
The only way I have found to navigate the output with the arrows is to minimize and maximize the output results with the mouse, then use the mouse to click on an entry in the output. At this point, navigation with the arrow keys is possible.

**Comment by stuartisaac** [comment]
This is happening for me as well on Windows 10. I've also found that once I click on a cell in the results grid and arrow around, arrow key navigation can get stuck again. It seems to happen most consistently when I issue a `select top whatever * from table` query  and there are more columns in the results grid than can be shown, thus requiring horizontal scrolling. Once I arrow to the last visible column, arrow key navigation gets stuck. If I unstuck it with the mouse, I can move one additional column to the right before getting stuck again. This happens for moving left in the grid as well.

**Comment by brokenthorn** [comment]
This is happening for me as well. Using MacOS Mojave 10.14.3 Beta (18D39a).
Basically when you try to use the keyboard to scroll the output, it only moves 1 rolumn/row outside of the currently visible viewport, then you cannot move the selection any more in any direction without first clicking with the mouse somewhere, it's like focus changes to something else but which is not visible.

**Comment by jianboli** [comment]
Same issue met on windows server 2016 when trying to replace SSMS with vsCode for the vim mode and mouseless coding. But stuck here.
