### ISSUE TITLE
Syntax highlighting for OPENQUERY

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-mssql#1010]
I just switched the textmate grammar used in the built-in SQL extension in VSCode to use the mssql grammar from this repo.
Going through the PRs to the original grammar, there is only one change that could also be adopted:
Highlight `OPENQUERY` as keyword:

From the PR by @gontadu :
> USE is used to select a database in SQL Server when a database is connected to.
> EXEC and OPENQUERY are both used to get data on other servers.

**Comment by abist** [comment]
@aeschli This should be fixed in the latest versions of the extension. Feel free to reopen the issue if you see it again in the latest versions.
