### ISSUE TITLE
MSSQL queries no longer supported

### ISSUE THREAD

**Issue by mhokanson** [Microsoft/vscode-mssql#1024]
After the last update of VSCode I'm unable to execute queries against an MSSQL database using the MSSQL extension.

MSSQL extension v1.2.1
VSCode Version: 1.18.0
OS Version: Windows 10 Pro 1703
Steps to Reproduce:

Open a new tab in VSCode
Set the Language Mode to SQL
Connect to a MSSQL database
Write a valid query
Run code
View the Info bar stating "Code language not supported or defined."
![image](https://user-images.githubusercontent.com/13987308/32668243-da50625e-c5f1-11e7-9c03-895f2ce15191.png)

**Comment by MattIrv** [comment]
Thanks for reporting this. I'm trying to investigate this and was wondering if you could give more info about how you're trying to run the code? For example, are you right clicking on the editor and choosing the "Execute Query" option, using the ctrl+shift+e keyboard shortcut, or manually choosing the "MS SQL: Execute Query" or "MS SQL: Execute current statement" options from the command palette? Does this error happen when doing all of those things, or only for some of them?

**Comment by mhokanson** [comment]
I've tried the following:

- 'Execute

 Query' command, which I'd mapped to F5 to bring in line with SSMS

- 'Run Code' play button in the upper-right corner of VSCode

Execute Current Statement appears to be working though

**Comment by mhokanson** [comment]
I'm willing to help troubleshoot this further, but for now have re-mapped my keybinding from 'Run Code' to 'Execute Current Statement' and am back in business.

**Comment by MattIrv** [comment]
Glad to hear you have a workaround! Be aware that "Execute Current Statement" only runs the statement that your cursor is on; to execute the entire script, you want the "Execute Query" command.

It sounds like you may have ended up with multiple commands mapped to f5 in VS Code, causing it to try to execute some command not associated with this extension whenever you press f5. If this no longer happens after ensuring that there are no duplicate key assignments for f5, can I mark this issue resolved? Or is there some larger issue here that still needs to be addressed? Thanks

**Comment by mhokanson** [comment]
Sorry for the delay in getting back to you. I've removed most of my user-specific keybindings and am still experiencing this problem.

**Comment by mhokanson** [comment]
I've just successfully used Execute Query (Ctrl+Shift+e), but the 'Run Code' button in the top right corner of VS does not execut the query.

**Comment by kevcunnane** [comment]
@mhokanson that sounds like the debug button - is that what you're trying to use? If so, this isn't something we hook into. That's for live debugging of code (C#, Javascript, Python etc.). 

![image](https://user-images.githubusercontent.com/10819925/32803931-06987194-c93a-11e7-83bf-2c1f76f41cac.png)

**Comment by mhokanson** [comment]
Nope. It's the 'Run Code' button further right.
![image](https://user-images.githubusercontent.com/13987308/32804117-c251e6b8-c93a-11e7-8501-9338cca8a056.png)

**Comment by MattIrv** [comment]
It looks like that button is coming from another extension that you have installed ("Code Runner" maybe?), rather than being built into VS Code, and so it doesn't hook in with our extension. If you're interested, I'd suggest contacting that extension's maintainers and asking whether there's some way to configure it to execute our "MS SQL: Execute Query" command.

**Comment by mhokanson** [comment]
I didn't even remember installing that plugin. Thanks for setting me straight.
