### ISSUE TITLE
Add Git version control?

### ISSUE THREAD

**Issue by rsmolkin** [Microsoft/vscode-mssql#1026]
Is it possible to add Git version control to this tool?  We are looking to bring our MS SQL Server under version control and are trying to avoid using RedGate and ApexSQL...

**Comment by kevcunnane** [comment]
Could you elaborate? Git support is built-into VSCode. In terms of this plugin we're focusing on the lightweight query execution, intellisense and code navigation parts of the developer problem - I suspect other tools / approaches will combine well to solve your issue.

If you're looking to source control your database contents, we would recommend using the [mssql-scripter](https://pypi.python.org/pypi/mssql-scripter) tool to script it out and get started. Depending on your preference for migration-based deployments vs. declarative deployment, there are a lot of options such as EF Migrations, Flybase etc. for migrations, or SSDT / RedGate for declarative deployment support. If you're running on Windows you can integrate MSBuild actions fairly easily into VSCode and get many of the benefits of SSDT without loading up a full IDE.

**Comment by rsmolkin** [comment]
Thanks,  Yes, I meant to source control the database contents.  Will check out your suggestions.
