### ISSUE TITLE
Idea: Implementing TreeView / Quick Search ?

### ISSUE THREAD

**Issue by datauduong** [microsoft/vscode-mssql#1031]
- MSSQL Extension Version: 1.2.1
- VSCode Version: 1.18 x64
- OS Version: Windows 10 Pro x64

Sample of Tree View like - GitLens
Showing SQL Database/Objects (Table, View, Store Procedure ...)
Very handy so that, Simple SQL Task can be perform without leaving the editor and switch to ssms tool.

Example:
+-------------------------------------------+
 | Type in Object Name for Quick Search |
+-------------------------------------------+
 | Tree View of Objects                              |
 |         Database                                        |
 |               Object Name | Type                 |
 |               MyTable        |  Table               |
+-------------------------------------------+

**Comment by datauduong** [comment]
Is this the answer to my question?
https://blogs.technet.microsoft.com/dataplatforminsider/2017/11/15/announcing-sql-operations-studio-for-preview/

Very Sleek UI, It look very much like Visual Studio Code, but targeted to SQL Server.

It would be interesting to see if this can merge into Visual Studio Code
"One Tool"

![sql_connection](https://user-images.githubusercontent.com/2460101/32971837-452f63fc-cc43-11e7-91f4-ea68c72dda54.png)
![sql_treeview](https://user-images.githubusercontent.com/2460101/32971838-45763e94-cc43-11e7-8363-4ca9d7366245.png)

**Comment by MattIrv** [comment]
Thanks for the suggestion. I'm glad you found SQL Ops Studio (https://github.com/Microsoft/sqlopsstudio on GitHub), but I'll also leave this open as well. The way that GitLens shows tree-style information is pretty neat, so thanks for pointing it out!

**Comment by mika76** [comment]
I second this request - even just as a lookup to columns, tables, stored procs. Currently I have to either write whole query to just look something up or have to open SSMS on a windows machine. (haven't tried ops studio yet)

One other thing - please make the search work without the dbo. prefix (it's the most irritating thing in SSMS object explorer)

**Comment by abist** [comment]
Closing this as it's being tracked here - https://github.com/microsoft/vscode-mssql/issues/586
