### ISSUE TITLE
mssql: SQL Tools Service component exited unexpectedly. Please restart SQL Operations Studio.

### ISSUE THREAD

**Issue by seanrockster** [Microsoft/vscode-mssql#1039]
- MSSQL Extension Version: ??
- VSCode Version: 1.18.1
- OS Version: 8.1 pro

Steps to Reproduce:

1. start sqlops.exe
2.

The app worked the first few times i started it. I toyed with the git integration which caused problems (warn: to many changes or words to that affect). After that, i don't know if its related however, I then started getting this error and now it will not establish a db connection.

**Comment by MattIrv** [comment]
Thanks for the report. I've moved your issue to the SQL Ops Studio repo at https://github.com/Microsoft/sqlopsstudio/issues/286, so please look there for any additional information
