### ISSUE TITLE
one connection for all sql files

### ISSUE THREAD

**Issue by penwon** [microsoft/vscode-mssql#1048]
Hello, friends!
Is it possible to use one connection for all of opened sql files? In my opinion this is thery very useful feature for sql project developing.

**Comment by MattIrv** [comment]
Right now connections are managed on a per-editor basis, so this isn't possible. I'll leave this issue open as a suggestion

**Comment by trobbins** [comment]
This would be really helpful.  When working with a large SQL Project, it would be super convenient to have a default connection for the entire workspace or folder rather than having to specify the same connection over and over for each file.

**Comment by kburtram** [comment]
Closing older issues that are planned in the near-term.  The connection model is to have one connection per query editor document.  We do have the concept of a current-active connection that we can try to attach to newly opened SQL files to help with working with several SQL files in a workspace.
