### ISSUE TITLE
VARCHAR(MAX) gets truncated

### ISSUE THREAD

**Issue by Calidus** [microsoft/vscode-mssql#1052]
- MSSQL Extension Version: 1.3
- VSCode Version: 1.19
- OS Version: Win 10

Steps to Reproduce:

1. SELECT a VARCHAR(MAX) Column with data larger than ~75k characters

**Comment by kevcunnane** [comment]
@Calidus the default behavior is to truncate long results, but the right solution would be to make this configurable like in SSMS. I believe it's 65K as the current per-column limit.

@erickangMSFT  and @benrr101 we have the `MaxCharsToStore` and `MaxXMLCharsToStore` setting values in the backend, but neither ops studio nor the vscode-mssql extension seem to expose them. Did we deliberately drop support for this option, or miss putting it through? I think we've seen a few bugs on this topic so we should consider bringing in the option based on user feedback.

**Comment by Calidus** [comment]
@kevcunnane in SSMS you can output directly to a file which gets the user passed any length limits imposed by the UI. This might be a good option to also think about.

**Comment by kkostalkowicz** [comment]
Issue confirmed with v. 1.9.0 (vscode 1.45.1, win10)
This is a bug, not an enhancement!

If for some reason a limit is necessary, it should be configurable in the extension preferences.

**Comment by pvvpraveen** [comment]
Is there any possibility to fix this bug in the near future?
Or there are any workarounds?

**Comment by dsouza0217** [comment]
@kevcunnane  This is a bug with no workaround.  Look at the same issue marked as a bug in Azure Data Studio and was fixed years ago.  https://github.com/microsoft/azuredatastudio/issues/392

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra FYI, guess this never got ported over to VS Code MSSQL
