### ISSUE TITLE
[Linux] SQL Tools Service component quit unexpectedly

### ISSUE THREAD

**Issue by probonopd** [Microsoft/vscode-mssql#1054]
- MSSQL Extension Version: sqlops-linux-0.25.4.tar.gz
- VSCode Version: sqlops-linux-0.25.4.tar.gz
- OS Version: xubuntu-16.04.1-desktop-amd64.iso

Steps to Reproduce:

1. Unpack `sqlops-linux-0.25.4.tar.gz`
2. Run `sqlops`

It says "Starting SQLToolsService..." forever. On the command line, I see

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

At the top says, it has "SQL Tools Service component quit unexpectedly."

**Comment by MattIrv** [comment]
@probonopd Thanks for reporting this, however this is the repository for our VS Code extension. You can find the GitHub repository for SQL Ops Studio at https://github.com/Microsoft/sqlopsstudio/

With regard to the issue, there are some additional dependencies you need to install for Linux, which you can find at https://docs.microsoft.com/en-us/sql/sql-operations-studio/download. Can you make sure they are installed?

I'll close this issue out, but if you still run into this error after ensuring all the dependencies are installed, can you please open a new issue in the SQL Operations Studio repo I linked above? Thanks!
