### ISSUE TITLE
Copy non-UTF-8 data, paste is garbled

### ISSUE THREAD

**Issue by Bingbingyan** [Microsoft/vscode-mssql#1059]
- MSSQL Extension Version: 1.3.0
- VSCode Version:1.19.3
- OS Version: Mac 10.13.3

Steps to Reproduce:

1. SELECT "中文"
2. copy result
3. paste: ‰∏≠Êñá

**Comment by MattIrv** [comment]
Thanks for reporting this. This is likely the same issue being discussed in #1036. @Bingbingyan would you mind sharing the output of running `locale` from a Terminal window as others have done there?

**Comment by MattIrv** [comment]
This should be fixed now in version 1.3.1. If you upgrade and it still happens please let me know
