### ISSUE TITLE
Support T-SQL SQLCMD mode and :SETVAR variable definition 

### ISSUE THREAD

**Issue by puruzio** [Microsoft/vscode-mssql#1063]
- MSSQL Extension Version:1.3.0
- VSCode Version:1.20.1
- OS Version:Windows 7

Steps to Reproduce:

1.In a sql file, type :setvar FOOBAR foobar` 
2.VS code recognizes :setvar line and $(FOOBAR) throughout the sql code as errors.

It will be nice if VS Codes support SQLCMD, specifically :setvar variables.

**Comment by kevcunnane** [comment]
This is definitely a good suggestion. It's the same as https://github.com/Microsoft/sqlopsstudio/issues/596 so we should track both when prioritizing this issue.

**Comment by puruzio** [comment]
I see #599 is the same issue. Will close this one and follow that one instead. Thanks!
