### ISSUE TITLE
RAND() function using GO N produces the same result

### ISSUE THREAD

**Issue by macdo5** [Microsoft/vscode-mssql#1066]
**Issue Type**
Bug

**Description**
Executing batch script to produce random values using **GO N** doesn't change the seed.

- MSSQL Extension Version: 1.3.0
- VSCode Version: 1.20.1
- OS Version: 10.0.16299 Build 16299

**Steps to Reproduce**:

1. Open Visual Studio Code
2. Connect to local SQL Server
3. Execute T-SQL:
```
SELECT RAND() AS Randomvals;
GO 5
```
4. Export results as JSON:
```
[
  {
    "Randomvals": "0.409168548858607"
  },
  {
    "Randomvals": "0.409168548858607"
  },
  {
    "Randomvals": "0.409168548858607"
  },
  {
    "Randomvals": "0.409168548858607"
  },
  {
    "Randomvals": "0.409168548858607"
  }
]
```
5. Execute same T-SQL in SQL Server Management Studio 17.5 and export results as JSON:
```
[
  {
    "Randomvals": "0.914936876182325"
  },
  {
    "Randomvals": "0.0864878534629798"
  },
  {
    "Randomvals": "0.400794151918763"
  },
  {
    "Randomvals": "0.325317352563939"
  },
  {
    "Randomvals": "0.370678372074297"
  }
]
```
SSMS generates random values when using GO N, but mssql in VS Code produces the same value.

**Comment by kevcunnane** [comment]
I can repro this. It looks like the handling of result sets when the batch is executed multiple times is wrong - it always returns the same resultset instead of handling a case where there are many of them. I will look to fix this given I added support for this feature.

**Comment by nishihere19** [comment]
Is the issue solved?
I am still getting same results from rand() function.
