### ISSUE TITLE
Enhancement: Error messages color

### ISSUE THREAD

**Issue by ibrowne** [microsoft/vscode-mssql#1068]
- MSSQL Extension Version: 1.3.0
- VSCode Version: 1.21.0
- OS Version: 10.12.6

This is merely an enhancement request regarding the color of the text in the messages pane if the SQL code you are running returns an error.  It would be nice to have a setting where you could set the text color to whatever you wanted or at least a toggle to enable/disable red error message text.

**Comment by ibrowne** [comment]
I guess to be more clear, it would be nice if SQL server raised an error (not the VSCode extension) that the results pane would not show at all but rather just the message pane.  And that the message text would be red.  It's way to easy to think your query is not returning any results when in reality there's an error preventing it from doing so.

**Comment by abist** [comment]
Error messages now show up in red.

**Comment by ibrowne** [comment]
Thank you!  I noticed this in the most recent update!  So helpful!  Keep up the good work.

**Comment by PeterV989** [comment]
The problem I have is that I am color blind AND I like a dark theme. The dark red color of the SQL error is a challenge to read. I would like to change it to a lighter red or a pink or an anything I want.
