### ISSUE TITLE
Plugin is broken for VS code 64 bit?

### ISSUE THREAD

**Issue by leolorenzoluis** [microsoft/vscode-mssql#1076]
- MSSQL Extension Version: 1.3.0
- VSCode Version: 1.21.1 (64 bit)
- OS Version: 7 64 bit

Steps to Reproduce:

1. Open VS Code
2. Execute command MS SQL: Connect
3. I get command 'extension.connect' not found

It was working before VS Code 32 bit and I upgraded to VS Code 64 bit

**Comment by MattIrv** [comment]
@leolorenzoluis Some users have been reporting this bug. Unfortunately we haven't been able to reproduce it to fix it for everyone yet, but you should be able to fix it for yourself by deleting and reinstalling the extension as suggested in the last comment at https://github.com/Microsoft/vscode-mssql/issues/1022. If that doesn't work please let me know

**Comment by leolorenzoluis** [comment]
I have repro steps that you can try.

1. Install VS code 32 bit with MSSQL exte sion.
2. Uninstall VS code 32 bit.
3. Install the 64 bit and try any mssql extension commands.

Let me know if that didn't help I cqn investigate further to give you an actual repro steps

**Comment by MattIrv** [comment]
I tried following those steps but wasn't able to reproduce it, so any additional information that could be relevant would definitely help. I'll keep trying to find a repro

**Comment by leolorenzoluis** [comment]
Hm, sometimes without doing anything and after some few days the issue came back. I had to redo the temporary solution which is to clean uninstall the plugin and reinstall it. Could it be some enterprise IT guys doing something over the weekends and suddenly apply some patches that might break it? I can't think of anything else.

**Comment by MattIrv** [comment]
@leolorenzoluis We released an update about 2 weeks ago on April 10, so I think it may have broken again when it auto-updated, which it should have done whenever you opened VS Code. Does that timing seem right? Thanks for bearing with us while we try to track this down

**Comment by mikes-gh** [comment]
@MattIrv Just broke for me 

`command 'extension.connect' not found`

but I hadn't used it for a bit.  

I have been on 64bit for some time so I would say its a recent update that broke it.  Can I install the previous version?

**Comment by kburtram** [comment]
The extension should be working with current VS Code x64-bit builds.  Please let us know if the issue persists.
