### ISSUE TITLE
Keymap Shortcut CTRL-SHIFT-E shadows `Show Explorer`

### ISSUE THREAD

**Issue by fbehrens** [microsoft/vscode-mssql#1088]
I am learning the shortcuts, so i am used to CTRL-SHIFT-E opening the FileExplorere Sidebar.

It happend that I did this from an `.sql` file, and surprisingly the `Execute Query` was invoked.

I am safe and I remapped CTRL-SHIFT-E to ALT-ENTER, which I am used from VisualStudio.

Maybe you wnat to change this.

PS. Thanks for the greate Extension

**Comment by ches** [comment]
I would strongly urge prioritizing this, it is _dangerous_ (I'd classify it not just a suggestion but a bug). You're shadowing probably one of the most used shortcut mappings in VS Code, with something that in the most unfortunate circumstances can drop a database in someone's production environment…

More than once I executed a file by accident when I was innocently trying to open the Explorer. Fortunately those files happened to be only innocuous queries. I've now remapped the shortcut like @fbehrens to avoid the footgun. Eventually it's going to catch a user in those most unfortunate circumstances.

My thanks also for all the work on making this a great extension.

**Comment by kburtram** [comment]
@MattIrv @yualan I think this issue raises a good point.  What do you think?

**Comment by R-i-c-h-B** [comment]
Morning all, 
On the similar subject I'd also like to mention that at least on Fedora under Gnome, ctrl+shift+e triggers the enter Emoji command...

eg if you hit ctrl+shift+e it shows an e in the editor - if you then type joy it gives you the emoji on screen in vscode.

Cheers all.

**Comment by abist** [comment]
@yualan Do you have ideas for the shortcut here?

**Comment by leonardder** [comment]
I noticed that this issue was closed, but there doesn't seem to be a fix, right. If so, could closure be reconsidered?
