### ISSUE TITLE
Intellisense not Working for Synonyms

### ISSUE THREAD

**Issue by thutch10** [microsoft/vscode-mssql#1093]
- MSSQL Extension Version: 1.3.1
- VSCode Version: 1.23.1
- OS Version: Windows 10 pRO 64-bit

Steps to Reproduce:

1. Use a synonym in a query

The query will still run correctly, however you receive the red squiggly showing an error in the query syntax and the intellisense will stop working.

**Comment by abist** [comment]
Closing as fixed.
