### ISSUE TITLE
SQL keyword theming, missing or large differences from SSMS

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode-mssql#1095]
- MSSQL Extension Version: 1.3.1
- VSCode Version: 1.23.1
- OS Version: Windows 10 1709

I have to start out saying, I don't know where to file this, who's responsible for it, but here goes...

Steps to Reproduce:

1. Start a new SQL editor
2. type ALTER PROCEDURE

or Open an SQL file with these keywords already within

ALTER PROCEDURE is not being recognized as a keyword for theming .  CREATE PROCEDURE is recognized and colored accordingly.  However, ALTER is in IntelliSense.  If I try ALTER TABLE, TABLE is recognized as a keyword, but not ALTER.

I was spying on the TM Scopes, and notice that keywords like SELECT which is themed differently than other keywords in SSMS, is not so specifically scoped as to allow it to be picked out, and also that AND/OR etc. are just labeled KEYWORD (keyword.other.dml.sql, not sure they should be considered DML)  instead of as an operator, another difference in SSMS's theming.

On the other hand, I am seeing NAME and TYPE being themed, but am not finding NAME in IntelliSense and am not finding it as a keyword in MS SQL, must be in some other variant?

**Comment by abist** [comment]
@msftrncs This should be fixed in the new updated versions. I'm going to go ahead and close this issue. Feel free to reopen the issue if you see it again in the newer versions of the extension.
