### ISSUE TITLE
UPDATE is missing from Intellisense

### ISSUE THREAD

**Issue by RodBarnes** [Microsoft/vscode-mssql#1098]
- MSSQL Extension 1.3.1
- VSCode 1.23.1
- macOS 10.12.6 Sierra

Steps to Reproduce:

1. Use Command K,M and select SQL as the language.
2. In a new file, type "upd".  It finds "UPDATETEXT" only, no "UPDATE" is found.

Screen-shot: <img width="840" alt="screen shot 2018-05-25 at 10 55 47 am" src="https://user-images.githubusercontent.com/3944607/40559029-395a39ca-600a-11e8-8604-8a080d0f2e3a.png">

**Comment by MattIrv** [comment]
This will be fixed in our next release

**Comment by MattIrv** [comment]
The new release is out so I'll close this issue now. If you update to the latest version of the extension you should see it working correctly. Thanks!
