### ISSUE TITLE
TypeError: Cannot set property telemetryService of #<t> which has only a getter

### ISSUE THREAD

**Issue by lyndonjohn** [Microsoft/vscode-mssql#1108]
Issue Type: <b>Bug</b>

1. Create profile connection for MSSQL
2. Successfully connected
3. Create sql file, write sql query, execute query
4. Error appears:
TypeError: Cannot set property telemetryService of #<t> which has only a getter

Extension version: 1.3.1
VS Code version: Code - Insiders 1.25.0-insider (fa7ded2f007be6ae288b29392501f3dc34105abd, 2018-06-12T08:15:14.394Z)
OS version: Darwin x64 17.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.21GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by MattIrv** [comment]
Thanks for the report @lyndonjohn. I can't reproduce this on my machine, though it looks like my insiders version of VS Code may be a bit newer than yours. Could you try updating to the latest insiders build of VS Code and seeing if it still happens?

**Comment by lyndonjohn** [comment]
Hey Mattlrv!

I have resolve the issue just now when i received the latest update (1.25.0-insider). Thanks!
