### ISSUE TITLE
untitled dirty file opened from hot-exit without focus lacks mssql support via status bar

### ISSUE THREAD

**Issue by msftrncs** [microsoft/vscode-mssql#1122]
Issue Type: <b>Bug</b>

Have a session of VS Code with an untitled dirty SQL language mode file which has been selected to use MSSQL langauge, but also other files of any other types (including titled SQL editors), and close VS Code (hot-exit) with one of the other files last focused, then open VS Code, so that it reloads the previously open editors including the untitled dirty SQL editor (but not in focus), after VS Code is fully open, switch to the untitled dirty SQL editor, and note that in the status bar, the previously set MSSQL mode is not displayed.  However, if VS Code is reopened where the untitled dirty SQL editor was in focus, the MSSQL mode and 'disconnected' status will be displayed in the status bar.   When the issue occurs, I find it much more difficult than normal to get a connection to a database, since the MSSQL and 'disconnected' status is not shown on the status bar.  I have not noticed this issue occurring for titled SQL file editors.

see:  https://github.com/Microsoft/vscode/issues/53643 for my post of this issue to VS Code.

This is the status bar, after opening with a different editor having the focus, then switching to the untitled editor:
![image](https://user-images.githubusercontent.com/26179051/42735988-8e122216-8823-11e8-8cc5-70ba78315f7a.png)
If I choose command 'MS SQL: Choose SQL handler for this file' I get this:
![image](https://user-images.githubusercontent.com/26179051/42736002-cede176e-8823-11e8-9e38-90e6e343a03b.png)
At that point I have trouble being able to select a connection.  (I am not currently at a computer where any connections are available to me, and cannot remember the error I get, but if this editor had the focus when VS Code started, there would be no issues)

Extension version: 1.4.0
VS Code version: Code 1.25.1 (1dfc5e557209371715f655691b1235b6b26a06be, 2018-07-11T15:43:53.668Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5 CPU       U 430  @ 1.20GHz (4 x 1197)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|1.74GB (0.44GB free)|
|Process Argv|C:\Program Files\Microsoft VS Code\Code.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by abist** [comment]
This issue is now fixed since the editors a pinned and focus editor every time.
