### ISSUE TITLE
SQL not recognized anymore after uninstalling the extension

### ISSUE THREAD

**Issue by jvalecillos** [microsoft/vscode-mssql#1134]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.26
- OS Version: Linux 4.17.14

Steps to Reproduce:

1. Install vscode.
2. Open any SQL file, observe that the syntax of SQL is highlighted.
3. Install this extension.
4. Uninstall this extension.
5. Open the SQL file again, now it is recognized just as plain text and there is no SQL highlighting anymore. :man_shrugging:

**Comment by abist** [comment]
@jvalecillos This issue should be fixed in the latest version of the extension. Feel free to re-open if you come across this problem in the latest version of the extension.
