### ISSUE TITLE
Feature Request: Support Windows AuthenticationType (not just Integrated)

### ISSUE THREAD

**Issue by gpattersonm** [Microsoft/vscode-mssql#1135]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.26.1
- OS Version: Windows 10

Please add support for a 'Windows' authenticationType that allows for specifying a domain/user and password. It would be really handy to have something like this when trying to connect to multiple domains.

**Comment by MattIrv** [comment]
Thanks for the suggestion. Please see https://github.com/Microsoft/vscode-mssql/issues/756 for more discussion of this issue - I'll close this one as a duplicate
