### ISSUE TITLE
when scrolling down showing multiple resultsets table content start to disappear

### ISSUE THREAD

**Issue by taxdev** [microsoft/vscode-mssql#1150]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.28.1
- OS Version: Win 10 pro x64

Steps to Reproduce:

1. paste all following sample selects into one code editor tab and execute:
SELECT TOP 1 'A';
SELECT TOP 100 'A', name FROM sys.all_objects;
SELECT TOP 1 'B';
SELECT TOP 100 'B', name FROM sys.all_objects;
SELECT TOP 1 'C';
SELECT TOP 100 'C', name FROM sys.all_objects;
SELECT TOP 1 'D';
SELECT TOP 100 'D', name FROM sys.all_objects;
SELECT TOP 1 'E';
SELECT TOP 100 'E', name FROM sys.all_objects;

2. once the results pane has loaded, start scrolling down.

The further down you get, the resultsets start to turn empty to the point where the bottom ones dont view any content at all.
probably depending on screensize a bit, but on a FullHD screen the snippet above should be enough to make the problem apparent.

**Comment by MattIrv** [comment]
Looks like we may be calculating some heights wrong or something, since many of the empty result sets seem to appear once I scroll down a bit more. I'll investigate

**Comment by abist** [comment]
Closing this as it's fixed in the new version.
