### ISSUE TITLE
mssql: The platform is not supported

### ISSUE THREAD

**Issue by morillo-9302** [Microsoft/vscode-mssql#1153]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.28.2
- OS Version: linux mint 19

Steps to Reproduce:

1. mssql: The platform is not supported
2. mssql: Unable to execute the command while the extension is initializing. Please try again later.
@jdalton @joaomoreno @adduc @pensivebrian

**Comment by MattIrv** [comment]
Looks like our code is detecting only mint 18 and not mint 19. I'll update it to support 19

**Comment by kevcunnane** [comment]
Matt - given the backend is Linux agnostic, can we simplify the logic to be a blacklist rather than a whitelist? How does the C# extension work right now? We've previously tended to look at their implementation since it's very popular and covers the most set of distros.
