### ISSUE TITLE
 Connection refused when running SQL Server Query 

### ISSUE THREAD

**Issue by xutianao2015** [microsoft/vscode-mssql#1157]
- MSSQL Extension Version: 1.4.0
- VSCode Version: Code 1.28.2 (7f3ce96, 2018-10-17T00:23:51.859Z)
- OS Version:Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Connecting to SQL Server
2. Use a database and Run a Select INTO statement. 
3. Even though the a new table is created the following results page is returned:
![mssql error](https://user-images.githubusercontent.com/29332016/48035359-ba8f0500-e1b7-11e8-8c41-1fa0fd7d0126.PNG)

**Comment by MattIrv** [comment]
The results view works by essentially creating a local web server to display a webpage with the results and then rendering that webpage inside of VS Code. Is it possible there are some security configurations or anything like that on your computer that could be interfering with that process?
