### ISSUE TITLE
The BETWEEN keyword is not highlighted

### ISSUE THREAD

**Issue by jaxspades** [Microsoft/vscode-mssql#1158]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.28.2
- OS Version: Windows 7 Enterprise, Service Pack 1

Steps to Reproduce:

1. Create a query that uses the BETWEEN keyword in the WHERE clause
2. Notice that it is not highlighted as the same color as the rest of the SQL keywords

**Comment by MattIrv** [comment]
Looks like this fix has made it into the SQL Tools Service back end so I'll grab a newer version for the next release so that it gets included

**Comment by jaxspades** [comment]
Excellent, thanks @MattIrv!
