### ISSUE TITLE
Output of SELECT includes the word "affected"

### ISSUE THREAD

**Issue by CmTheLuke** [microsoft/vscode-mssql#1160]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.28.2
- OS Version: Windows 10

Steps to Reproduce:

1. Run a simple query
2. Observe that in the messages window it says "N rows affected" rather than "N rows"

The word affected makes the user think that these rows were changed.

**Comment by abist** [comment]
@CmTheLuke This message comes from the engine from any SQL Server tool, to show the number of rows present in any query by design.
