### ISSUE TITLE
"Login failed. Retry using different credentials?" when credentials are tested ok.

### ISSUE THREAD

**Issue by michaelgarde** [microsoft/vscode-mssql#1166]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.29.1
- OS Version: Windows 10
- Microsoft SQL Server: 12.00.5207

I'm getting a "mssql: Error: Login failed. Retry using different credentials?" when i try to connect to our dev/test database. I have tried variations using ip/url, username with or without domain, and i have tested the configuration in the DbVisualizer software, and they work´with no issues. I have also tried the Create Connection Profile guide via ctrl+shift+p.

Steps to Reproduce:

1. Verify connection information in other db tool like DbVisualizer
2. Create a connection profile using the template 
`"mssql.connections": [
    {
      "server": "{{put-server-name-here}}",
      "database": "{{put-database-name-here}}",
      "user": "{{put-username-here}}",
      "password": "{{put-password-here}}"
    }
  ],`
3. Attempt a connect using ctrl+shift+p
4. Get "mssql: Error: Login failed. Retry using different credentials?"

**Comment by abist** [comment]
@michaelgarde Perhaps there was a firewall issue that wasn't letting you connect to the server. In the latest version of the extension, we let you add a firewall rule to the server to get access. Please try again with the latest version of the extension and feel free to re-open this issue if you still can't connect to your server.
