### ISSUE TITLE
Not able to connect to SQL Server (using context_info)

### ISSUE THREAD

**Issue by amandaradara** [microsoft/vscode-mssql#1167]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.29.1
- OS Version: Windows10 1809

Steps to Reproduce:

1. connect sqlserver 
2. Get the error message:
    GUID should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

please release following issue fixed SqlToolsService module
https://github.com/Microsoft/sqltoolsservice/pull/654

**Comment by abist** [comment]
Closing issue as tools service bug seems to be fixed.
