### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by BillKG** [microsoft/vscode-mssql#1179]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.4.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.30.1`

[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/Microsoft/vscode-mssql/files/2709406/ms-mssql.mssql-unresponsive.cpuprofile.txt)

**Comment by eksortso** [comment]
Following that template:

* Issue Type: `Performance`
* Extension Name: `mssql`
* Extension Version: `1.6.0`
* OS Version: `Windows_NT x64 10.0.18362`
* VSCode version: `1.38.1 (user setup)`

[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-mssql/files/3617623/ms-mssql.mssql-unresponsive.cpuprofile.txt)

**Comment by abist** [comment]
@BillKG @eksortso Feel free to reopen this issue if you see the same problem persist in the latest version of the extension.
