### ISSUE TITLE
Copy for selected field or row does not work

### ISSUE THREAD

**Issue by jobe451** [Microsoft/vscode-mssql#1180]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.30.1
- OS Version: MS Server 2008 R2

Steps to Reproduce:

1. write a select
2. execute query
3. in the resulting table select a single value (or a full row)
4. Hit Ctrl + C (or choose "copy" or "copy with header" from context menu)
=> the content of the selected field does not end up in the clipboard. Whatever was in the clipboard before is still there

Maybe a regression to: https://github.com/Microsoft/vscode-mssql/issues/681 ?

**Comment by abist** [comment]
Hi @jobe451, thanks for reporting this issue. Do you still see this issue in the latest extension release? I can't seem to repro it in the latest release, so I'm going to go ahead and close this issue. If you still see this issue occurring, feel free to  reopen.
