### ISSUE TITLE
Adopt extension for no reload on install

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode-mssql#1185]
Hi, I am a developer from VS Code and in the last release `1.31`, we added a new feature - no reload is required on installing an extension - https://code.visualstudio.com/updates/v1_31#_no-reload-on-install

But there are some exceptions to it as mentioned in the doc. If the extension is contributing to external contribution points, then the extension requires reload after installing. Hence, we added a new listener API for the owners of the external contribution point to listen to extension addition/removal and can update its state - https://code.visualstudio.com/updates/v1_31#_extensions-change-event.

Our plan is to give extensions one milestone/month for adopting to the above API and make the other extensions consuming their contribution points ready for no reload. It means that from next release, above exception will be removed and all extensions are added to VS Code window immediately after installation and no reload is shown.

We scanned the extensions in the marketplace and found out that this extension uses an external contribution point `outputChannels` and requires reload on install. Since we cannot find out which extension owns this contribution point filing an issue here and please forward it to the extension that owns this contribution point to adopt.

Thanks

**Comment by kevcunnane** [comment]
@MattIrv / @abist I think we added this in error in our 1st commit, or else the VSCode APIs for contributing output channels changed since 3 years ago. This should be safe to remove, and with that it sounds like we can install without reload?

**Comment by sandy081** [comment]
Correct.
