### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Aleky75** [Microsoft/vscode-mssql#1188]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.4.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.30.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/amaciel/ms-mssql.mssql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
@Aleky75 do you still have the profile file mentioned in the issue comment `/Users/amaciel/ms-mssql.mssql-unresponsive.cpuprofile.txt`?  If so, could you please attach it to the issue?

**Comment by kburtram** [comment]
Closing since there is no log data associated with this bug report.
