### ISSUE TITLE
Intellisense not showing data warehouse variables after Code Update 

### ISSUE THREAD

**Issue by butternutStotch** [Microsoft/vscode-mssql#1191]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.32.1
- OS Version: Windows 10 Version 1709

Problem: After the latest update for VS Code (version 1.32.1), I can no longer use intellisense for tables, table columns, etc that gives me the autofill options from the data warehouse I'm connected to. Now, the only options in intellisense are the headers or tags that exist in local memory in the sql script (picture attached showing with error). When it worked it would show the data warehouse options with the VS code "Variables" icon (blue square). 

Steps to Reproduce:
1. Connect to an MSSQL data warehouse connection
2. When referencing a table column using intellisense, it no longer shows any variables.

![github_novariables](https://user-images.githubusercontent.com/46137394/54227082-274f3e80-44cd-11e9-9825-3aa7e81b627e.png)

**Comment by MrRobboto** [comment]
+1

Yeah, I'm experiencing the same and just came here to report. No table names, columns or anything for code completion. When I type one in by hand that is correct though, intellisense is validating types.

![image](https://user-images.githubusercontent.com/14045888/54234100-c6cbfb80-44e4-11e9-8733-139c072bef22.png)

**Comment by markledwich2** [comment]
I have the same issue

**Comment by butternutStotch** [comment]
As a workaround, I just reverted back to an earlier version and it works again. Looks like an issue with the new VS code update and compatibility with the extension.

Earlier versions found here: https://code.visualstudio.com/updates/v1_31

**Comment by kevcunnane** [comment]
@abist, @MattIrv could one of you take a look at this? If it's caused by a VSCode change we will need to look at pushing an update to fix.

**Comment by rachelfu** [comment]
Same issue. Thanks @butternutStotch, reverting back to the earlier version of VSCode solves the issue for now.

**Comment by jdpepperman** [comment]
Same issue for me as well. Reverting to a previous version fixed it for me.

**Comment by christe90** [comment]
I do have the same issue. The statusbar says i am always connected to the "master"-database.

**Comment by cryocaustik** [comment]
same issue posted here: [70094](https://github.com/Microsoft/vscode/issues/70094).

I've tested it across varying databases and SQL servers, but the same issue persists.
Downgrading to an earlier version of VS Code does fix the issue.
