### ISSUE TITLE
MSSQL Connection problems, hangs, timeouts

### ISSUE THREAD

**Issue by litchfield** [microsoft/vscode-mssql#1193]
Version: Azure Data Studio OSX 1.4.5

Problem: Working with remote mssql connections is very flakey. It works but then times out, hangs then resumes, crashes, and so on. Makes it difficult to be productive and very annoying to use, particularly over poor quality connections. I've tried tuning the timeout settings under "advanced" but that doesn't seem to have made any difference.

Proposed solution: Provide an option to open/close connection on every "run", rather than leaving the connection open. That, together with a low connection timeout will be much more resilient.

**Comment by abist** [comment]
@litchfield We fixed the issue with long opened connections in our latest versions of the extension. I'm going to close this issue, but feel free to re-open this issue if you still see the problem in the latest version of the extension.
