### ISSUE TITLE
Intellisense suggestion window freezes VS Code for 15-20 seconds

### ISSUE THREAD

**Issue by Icebird** [Microsoft/vscode-mssql#1195]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.32.3
- OS Version: Windows 10

Steps to Reproduce:

1.  Open new query window and connect to a database with a large number of tables (~9500)
2.  Begin typing a query and pause to get the intellisense suggestion window
3.  Experience a 15-20 second complete freeze of VS Code every time the window should be popping up

I did not have this issue until around VS Code 1.32.1.  The latest version has not resolved the issue.

**Comment by prae04** [comment]
__Same Issue__

1 Noticed high cpu use until windows is recovered

**Comment by Icebird** [comment]
This issue appears to have mysteriously resolved itself for me without any application/extension updates.

**Comment by kburtram** [comment]
@Icebird thanks for the update.  I'll close then if you are currently experiencing this bug.  Please let me know if the issue comes back.  We did push version 1.5 of the extension and VS Code has shipped 1.33 recently, so perhaps something in one of those releases may have helped.
