### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Farrukh-Sarmad** [Microsoft/vscode-mssql#1207]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Farrukh Sarmad\ms-mssql.mssql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
@Farrukh-Sarmad could you please attach the performance log mentioned in the bug report `C:\Users\Farrukh Sarmad\ms-mssql.mssql-unresponsive.cpuprofile.txt `.  Unfortunately without the trace data there isn't a practical way to address these bugs.

**Comment by kburtram** [comment]
Closing since the required performance trace file is not provided with the bug report.
