### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Edwing95** [Microsoft/vscode-mssql#1209]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\SKYNETT\ms-mssql.mssql-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
@Edwing95 can you please attach the missing performance trace file mentioned in the bug report?

> Note: *"⚠️ Make sure to attach this file from your home-directory: **C:\Users\SKYNETT\ms-mssql.mssql-unresponsive.cpuprofile.txt** ⚠️"*

**Comment by kburtram** [comment]
Closing since required perf log files aren't attached to issue.  Please attach perf log and I can take a look.
