### ISSUE TITLE
How to use mssql extension in my program ?

### ISSUE THREAD

**Issue by chrisolsch** [microsoft/vscode-mssql#1210]
Version: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Date: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Dear all,

sorry, if iam completely on the wrong path. Iam very new.

Iam using the mssql extension. I've done everything successfull like in the readme. I have created a connection with a query and executed it to an JSON file. Very nice, so far. But where is now the trick ? How is is possible to transfer this to my code, so that the code will do the same for me, automatically ?

**Comment by kevcunnane** [comment]
Chris - what is your application? E.g. what are you trying to do? For most applications, using the correct client driver (and maybe an ORM stack) will do what's needed. See http://aka.ms/sqldev. If you're looking to do intellisense, show results like we do, or something tools-specific I can give different advice. Thanks!

**Comment by abist** [comment]
@chrisolsch, I'm going to go ahead and close this issue. Feel free to re-open if you feel your question was unanswered.
