### ISSUE TITLE
Cannot connect to a Sybase Anywhere 16 DB

### ISSUE THREAD

**Issue by qlecler** [Microsoft/vscode-mssql#1212]
- MSSQL Extension Version: 1.5.0
- VSCode Version: 1.33.0
- OS Version: MacOS 10.4.4

Steps to Reproduce:

1. Add a new connection for Sybase Anywhere 16

```
 {
      "server": "192.168.xxx.xxx,2638",
      "database": "xxx",
      "authenticationType": "SqlLogin",
      "user": "dba",
      "password": "",
      "savePassword": true,
      "profileName": "sybase1"
  }
```

2. Connect

`mssql: Error 532344408: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - 53234440)`

**Comment by kburtram** [comment]
@qlecler thanks for opening this issue.  The vscode-mssql extension will only work with SQL Server databases.  I'm not sure if there is a different extension for Sybase databases.
