### ISSUE TITLE
Error saving CSV

### ISSUE THREAD

**Issue by stharrold** [Microsoft/vscode-mssql#1213]
MSSQL is failing to save the results of a SQL query. Is anyone else experiencing this issue? Related Gitter discussion: https://gitter.im/Microsoft/mssql?at=5cab4516bd70a40d5f16db67

- MSSQL Extension Version: 1.5.0
- VSCode Version: 1.33.0
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Execute query `SELECT 1;`.
2. Save results as CSV using icon.

Error message:

"""
mssql: Failed to save results. Failed to save test.csv: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
"""

![20190405_mssql_error](https://user-images.githubusercontent.com/4134823/55810990-69f93c00-5ab6-11e9-911b-185e94239af8.PNG)

**Comment by DrDanRyan** [comment]
Same problem here with Windows 10, VS Code 1.32.3

**Comment by stharrold** [comment]
May be duplicate of #1206

**Comment by stharrold** [comment]
Downgrading to mssql v1.4.0 circumvents the issue.

**Comment by kburtram** [comment]
@stharrold there was a problem with some of the extension dependencies when the 1.5 release was published.  Those have been corrected and you should be able to uninstall then reinstall 1.5 to fix this issue.

**Comment by DrDanRyan** [comment]
I tried:
uninstall, reload window, install, reload window
but it failed to solve the issue for me.

**Comment by stharrold** [comment]
@kburtram I uninstalled the MSSQL extension then reinstalled with v1.5.0, and I get the same error. The changelog shows a release date 3/22 for v1.5.0. Is there anything I can do to troubleshoot?

**Comment by kburtram** [comment]
@stharrold this should be resolved in the 1.6 release.  Please let me know if the problem persists.  Thanks!

**Comment by aegeanboat** [comment]
Still has the issue. v1.14.1

**Comment by dgem** [comment]
For anyone stumbling on this.
I just uninstalled 1.16.0, reloaded and reinstalled 1.16.0 as I had the same issues even though it was a reasonably fresh vscode install (circa May 2023), I'm not sure what version it initially had, but it did get updated along the way to not working.

**Comment by kburtram** [comment]
@dgem just to confirm, you are able to reproduce the original bug reported, with the same steps and error message?  I wasn't able to reproduce myself on the current build, so checking if there are additional steps needed or if you're seeing a different error message.  Thanks!

<blockquote>
Steps to Reproduce:

Execute query SELECT 1;.
Save results as CSV using icon.
Error message:

"""
mssql: Failed to save results. Failed to save test.csv: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
"""
</blockquote>
