### ISSUE TITLE
MSSQL Extension Doesn't work sometime

### ISSUE THREAD

**Issue by mukerong** [microsoft/vscode-mssql#1214]
- MSSQL Extension Version: 1.5.0
- VSCode Version: 1.32
- OS Version: Win 10 Enterprise Version 1709

Steps to Reproduce:

This issue happens randomly, and not very often but annoying. I checked with [this ticket](https://github.com/Microsoft/vscode-mssql/issues/711) but is a different issue.

Normally the MS SQL extension works well, but sometimes after running a big query and getting the result back, I cannot run any query anymore. When I try to disconnect, it will say "Activating extension" and nothing will happen. I waited for a couple of minutes, but it won't work. This has happened several times, has anyone had this issues? Is there a possible way to fix it?

Restarting VSCode will solve the issue, but it is annoying since I need to re-run a long query to get all the temp table back.

Thanks in advance,
Rachel

**Comment by mukerong** [comment]
This happens again without running any query. I updated a user-defined snippet and MS SQL extension doesn't work. There is no intelligence, no snippet and no query can be run.

**Comment by abist** [comment]
@mukerong Could you try the latest version of the extension (1.7.1) and confirm whether still problem still occurs? Feel free to re-open the issue if you still see this problem in the latest version of the extension.
