### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by jnetto23** [Microsoft/vscode-mssql#1216]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Jnetto\ms-mssql.mssql-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
@jnetto23 could you please attach the perf log mentioned in your issue?  That file should contain details necessary to investigate this type of problem.

**Comment by kburtram** [comment]
Closing since the logs needed to investigate haven't been attached.  Please let me know if you have the above mentioned perf logs.
