### ISSUE TITLE
Buggy Return of statement

### ISSUE THREAD

**Issue by casimo** [microsoft/vscode-mssql#1220]
- MSSQL Extension Version: 1.4.0
- VSCode Version: 1.33.0
- OS Version: Win10

Steps to Reproduce:

1. Create a table like this:
CREATE TABLE Employee
{
Name varchar(250)
}
GO
2. Insert some records:
with sql_data as (
select 'Johnson' as name union
select 'Jamerson'  union
select 'Hudson'  union
select 'Peterson'
)
INSERT INTO Employee
SELECT NAME FROM sql_data
GO
3. Retrieve some records
select *
  from Employee
 where **LOWER**(Name) IN ('**JOHNSON**', '**PETERSON**')
4. The statement returns always two records
5. Case sensitve

**Comment by abist** [comment]
@casimo I can't seem to repro this issue in the latest version of the extension. I'm going to close this issue, feel free to re-open it if you face this problem in the latest version of the extension.
