### ISSUE TITLE
Table Columns Not Updating

### ISSUE THREAD

**Issue by djkong7** [microsoft/vscode-mssql#1224]
Issue Type: <b>Bug</b>

I altered a table and added a column in SSMS. Now, VSCode intellisense is telling me that the table doesn't contain the column I just added even after reconnecting to the DB.

Extension version: 1.6.0
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:27:14.102Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@djkong7 the `Refresh IntelliSense Cache` command can be used to force a manual intellisense metadata update.  Currently we don't implement "drift detection" to auto-refresh the cache when the DB schema changes.
