### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by parvinjs** [Microsoft/vscode-mssql#1236]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.6.0`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/parvin/ms-mssql.mssql-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
Please attach the perf log that is referenced in the issue text so the issue can be investigated.

**Comment by kburtram** [comment]
Closing since the perf log required to investigate is missing.
