### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AmosOtis** [microsoft/vscode-mssql#1240]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\eddie\ms-mssql.mssql-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
@AmosOtis please attach the perf log mentioned in the original issue text in order to investigate.  Thanks!

**Comment by kburtram** [comment]
Closing as perf log is not available for investigation.
