### ISSUE TITLE
there is no localizedConstants.ts under src/constants

### ISSUE THREAD

**Issue by Yansongsongsong** [microsoft/vscode-mssql#1242]
- MSSQL Extension Version: 1.6.0
- VSCode Version:  1.33.1
- OS Version: OSX 10.14.3

Steps to Reproduce:

1.  just clone the repo from github in one new folder
2. u can find there is no `localizedConstants.ts` in `src/constants`, but that file is imported by many files many times.

it can actually build, work and debug. i found `src/constants/localizedConstants.ts` in `.gitignore`...
i can't get it for why do we leave such `import` and `calling` for `localizedConstants`... it seems meaningless..

I'm new in TypeScript... I am just curious about that

**Comment by kevcunnane** [comment]
This supports having multiple language strings in the extension so if VSCode is set to use French langugage pack, you get French strings. If I recall correctly, the flow is:
- In the xliff-to-ts gulp task we read from the loc files and create the relevant typescript files
- This is then compiled as part of the build
- On starting the extension we check the language and use the correct set of language constants.

I'll close this out as this should cover the question, and this isn't a product bug. Thanks!

**Comment by Yansongsongsong** [comment]
okay, i get it.  thx for your explanation!
