### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by alvarobasia** [microsoft/vscode-mssql#1248]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.35.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
@alvarobasia Could you elaborate more on the issue? Does the copy-paste not work for you?
