### ISSUE TITLE
Cannot cancel query, neither can start new

### ISSUE THREAD

**Issue by borysl** [microsoft/vscode-mssql#1251]
- MSSQL Extension Version: DWH 
- VSCode Version: 1.35.1
- OS Version: Win10

Steps to Reproduce:

1. Run query
2. Put Windows 10 to sleep
3. Recover from sleep
4. Try run query => editor says some query is still running

5. Try cancel query => editor says  query is running
<img width="253" alt="2019-06-21_18h29_42" src="https://user-images.githubusercontent.com/1067756/59937406-a9e38480-9452-11e9-8858-9be21bb7b1fc.png">

Yes, you actually can receive two message at the same time. See image

Workaround: restart editor

**Comment by abist** [comment]
@borysl This should be fixed in the latest versions of the extension. Feel free to reopen the issue if you see the same problem persist in the latest version.
