### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by jaybproductions** [microsoft/vscode-mssql#1255]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.6.0`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by jaybproductions** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 3054,
		"activateCallTime": 18,
		"activateResolvedTime": 7970,
		"activationEvent": "onLanguage:sql"
	},
	"runtimeErrors": [
		{
			"name": "TypeError",
			"message": "Cannot read property 'localeCompare' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'localeCompare' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'localeCompare' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'localeCompare' of undefined"
		},
		{
			"name": "TypeError",
			"message": "Cannot read property 'localeCompare' of undefined"
		}
	]
}
```

**Comment by abist** [comment]
@jaybproductions You are probably getting this error because it's trying to look up connections in your settings file. If your connection name is null (which is incorrect, give it an empty name instead), it would cause an error. Feel free to reopen the issue if this doesn't resolve your issue.

**Comment by ChrisMiami** [comment]
Well, what the heck is the key value for the connection name? It's not in any documentation that I can find!! I'm having this same issue.
