### ISSUE TITLE
Fail to load sql service tools

### ISSUE THREAD

**Issue by daviosbo** [microsoft/vscode-mssql#1256]
- MSSQL Extension Version: Version: 1.6.0
- VSCode Version: 1.36.0
- OS Version: Windows 10 Pro Version 1709 OS Build 16299.125 

Steps to Reproduce:

1. Install extension 
2. Create file with sql extension 
3. View Command Pallette MS SQL:Connect

![image](https://user-images.githubusercontent.com/52266939/60777620-7a32bd00-a172-11e9-95ad-b3b769e2b229.png)

**Comment by abist** [comment]
@daviosbo Could you please verify if you still see this issue in the latest version of the extension? I'm going to go ahead and close this issue. Feel free to reopen the issue if you still see the problem persist in the latest version of the extension (1.8).
