### ISSUE TITLE
Executing Query hangs on Executing Query while the Output panel shows that the query has been completed

### ISSUE THREAD

**Issue by apoorvagarwal41** [microsoft/vscode-mssql#1258]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Run a Query
2. Open the output panel
![mssqlbug](https://user-images.githubusercontent.com/34867904/61218180-0de62980-a72f-11e9-8a0d-febd57cbcfd7.PNG)

As you can see the query gets finished but the results panel still shows executing query.
Also when you try to cancel the query, a popup comes up stating that no query is running.
I am using WSL on windows (Ubuntu 18.4)

**Comment by dogtail9** [comment]
I have the same issue running in a remote container. I use a docker-compose file to start the dev container and a SQL-Server container. The result window hangs on executing query but the output shows that the query executed. If I look in the database I can se that the query executed if I for example create a table.

**Comment by comfortablynick** [comment]
I am also having this issue using WSL on Windows (Ubuntu 18.04).

**Comment by jeffkempster** [comment]
I am also having this issue using WSL on Windows (Ubuntu 18.04).  It works fine under windows but never displays results from WSL.

**Comment by abist** [comment]
Please try the latest version of the extension 1.8 and see if you still see this issue. I'm going to ahead and close this issue but feel free to reopen it if you still face the problem in the latest version of the extension.
