### ISSUE TITLE
Integrate with Live Share

### ISSUE THREAD

**Issue by asishm** [microsoft/vscode-mssql#1262]
Is there any plans to integrate this extension with Live Share?

For example, I'd like to have a way for my team members (who are collaborating in a live session) to be able to run queries through the shared session. This might be a big ask, but I'm just wondering if this has been discussed and/or in the pipeline.

**Comment by kburtram** [comment]
Closing older suggestions that aren't on roadmap.  We looked at this a while ago and the cost to implement was very high for the "shared query execution" scenario.
