### ISSUE TITLE
Can't set delimiter in csv output

### ISSUE THREAD

**Issue by ihaveknowledge** [microsoft/vscode-mssql#1273]
The documentation seems to indicate that I should be able to use the following command however I don't seem to be able to do so.

"mssql.saveAsCsv.delimiter" : "|"

I am getting a message saying unknown configuration setting.

**Comment by abist** [comment]
@ihaveknowledge I couldn't repro this issue. What version of the extension are you using? And how did you set the configuration setting? I'm assuming you went to `Open User Settings` -> `Extensions` -> `MSSQL` and changed the `mssql.saveAsCsv.delimiter` option there.

**Comment by abist** [comment]
@ihaveknowledge Could you verify if this issue still exists in the latest version? Feel free to reopen the issue if you still see the same problem in the latest version of the extension.
