### ISSUE TITLE
Feedback on vscode's Webview.toWebviewResource API proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode-mssql#1277]
## Overview
VS Code 1.37 added a proposed api to help webviews create uris for local resources: https://github.com/microsoft/vscode/blob/192e15b613dd4f4dab9c735b7556e175580c6011/src/vs/vscode.proposed.d.ts#L1166

The main addition is a `toWebviewResource` method property on webviews that translates a local file uri into a webview uri (i.e. one that uses the special `vscode-resource:` scheme). This api is being added primarily to support running VS Code on the web where the existing `vscode-resource:` scheme will not work

## Request
As a popular user of the VS Code webview API, we'd appreciate your feedback on this api proposal. Does it work as advertised? Does the documentation for it make sense? Is it missing any functionality? Feel free to leave your feedback on this issue or on https://github.com/microsoft/vscode/issues/79242

You can try out the proposed api in VS Code 1.38 insiders by following [these instructions](https://code.visualstudio.com/api/advanced-topics/using-proposed-api). Please let me know if you have any questions about testing it out

*PS: There are no plans at the moment to remove the `vscode-resource:` scheme so your extension should continue to work on desktop VS Code even if it does not adopt this new API*

**Comment by mjbvz** [comment]
Did you adopt this API?

**Comment by abist** [comment]
We are already using the `vscode-resource`, but it's generated this way - https://github.com/microsoft/vscode-mssql/blob/8696a7bb8c5644dca3435f200d152547784c2bf6/src/controllers/webviewController.ts#L101

**Comment by mjbvz** [comment]
Please switch to use the new api

**Comment by abist** [comment]
@mjbvz Is it still in proposed or is this in the actual API now?

**Comment by abist** [comment]
@mjbvz Using this API breaks the existing behavior that used to work fine. The webview doesn't show `svg`'s any more

**Comment by abist** [comment]
@mjbvz From the docs here - https://code.visualstudio.com/api/extension-guides/webview

```
      // Get path to resource on disk
      const onDiskPath = vscode.Uri.file(
        path.join(context.extensionPath, 'media', 'cat.gif')
      );

      // And get the special URI to use with the webview
      const catGifSrc = panel.webview.asWebviewUri(onDiskPath);
```
However, when I convert using the same method, I get something like -

```vscode-resource://file///c%3A...```
