### ISSUE TITLE
Documentation surrounding permissions needed to run intellisense

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/vscode-mssql#1279]
We have different permissions set up on our lower environment servers vs. our prod servers.

We've been able to get intellisense via SSMS but can't seem to get it working for VS Code.

Can you provide some documentation on what permissions are necessary for the `mssql` extension's intellisense capabilities?

**Comment by kburtram** [comment]
@cmeyertons we use the same internal components for IntelliSense in VS Code and SSMS (T-SQL Parser & SmoMetadataProvider).  These components run several queries against metadata DMV (e.g. sys.objects, sys.types, etc.),  

I'm not aware of any permission differences between the applications.  If you run a SQL profiler while ADS is openning a query editor you can see the IntelliSense related queries using the `azdata-languageService` ApplicationName.  

I'll ask out PM's if we can determine the minimal required permissions to execute the DMV queries and add that to our documentation.

**Comment by kburtram** [comment]
Closing older issues based on previous comment.  There shouldn't be special permissions to use intellisense beyond read-only access to `sys` DMVs.
