### ISSUE TITLE
SQL in PHP String: Starting with "WITH" -> no (blue) highligh

### ISSUE THREAD

**Issue by hfhbd** [microsoft/vscode-mssql#1284]
- MSSQL Extension Version: 1.6.0
- VSCode Version: 1.37.1
- OS Version: Windows_NT x64 10.0.15063

Steps to Reproduce:

1. Create a PHP File with content:

`<?php 
$query1 = "SELECT * from test";
$query2 = "WITH d as (SELECT id from test) select id from d";
$query3 = "SELECT WITH d as (SELECT id from test) select id from d"; #invalide query
?>`

Result:
1. The first query is correctly parsed: SELECT & FROM are blue.
2. This time the WITH isn't recognized as a valid starting SQL Syntax, so the entire query isn't highlight.
3. Based on the SELECT at the start, the query is valide and correct highlight.

One possible solution (not tested):
In https://github.com/microsoft/vscode-mssql/blob/fb4dd209da56313100bab714c42aeb3929eda183/syntaxes/SQL.plist#L246 add with

**Comment by micek-petr** [comment]
Hi Philip, are you really using MSSQL extension for PHP files with all SQLs inside quotes?

**Comment by hfhbd** [comment]
@micek-petr I think I used it 2 years ago for this file, so yes. Is it not possible to reproduce this case anymore?

**Comment by micek-petr** [comment]
There were many improvements concerning syntax highlighting in MSSQL. If you are not experiencing such issue any more you may be thinking of closing it.

**Comment by hfhbd** [comment]
@micek-petr I don't use PHP anymore, so I am not experiencing this issue anymore :)
