### ISSUE TITLE
Webview doesn't set a content security policy

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1286]
It looks like VS Code is tracking extensions that open a webview and don't set a content security policy in issue https://github.com/microsoft/vscode/issues/79340.  We should fix this to follow best practices.

**Comment by abist** [comment]
@kburtram I did add a policy already, but I'll look into this,

https://github.com/microsoft/vscode-mssql/pull/1282/files#diff-8306d266d9ca46a40054bd378cc68948R5

**Comment by kburtram** [comment]
@abist thanks!  Probably VS Code team is looking at our current public release, so this should be resolved by your pending PR.  I'll take a look at the PR this evening.

**Comment by abist** [comment]
@kburtram I've verified this with them here - https://github.com/microsoft/vscode/issues/79340#issuecomment-531968074

https://github.com/microsoft/vscode/issues/79340 - MSSQL is now fixed on the list
