### ISSUE TITLE
On first connect, extension host crashes

### ISSUE THREAD

**Issue by cmeyertons** [microsoft/vscode-mssql#1289]
- MSSQL Extension Version: 1.6.0
- VSCode Version: 1.38.0
- OS Version: windows 10 1709 16299.1331

Steps to Reproduce:

1. open a SQL file -> connect
2. observe extension host crashed unexpectedly.

![image](https://user-images.githubusercontent.com/19917677/64801836-efde4f00-d54e-11e9-91ab-baf03624b759.png)

sometimes its during connect sometimes its during the first execution.

everytime I open a new VSCode window, this is the behavior (typically have multiple open).

are there any logs I can collect and send across to help investigate?

here's a screen cap of the extension host devtools:

![image](https://user-images.githubusercontent.com/19917677/64801582-6cbcf900-d54e-11e9-98ab-2e16d864c590.png)

I don't observe anything in the Output window (probably because it crashes the extension host)

**Comment by abist** [comment]
@cmeyertons Thanks for opening the issue. Could you check if there are any errors on the dev console? You can access it from `Help` -> `Toggle Developer Tools` (`Ctrl`/`Cmd+Shift+I` ) -> `Console` and paste it here if there are any?

**Comment by cmeyertons** [comment]
Forgot about this one. I ended up tracking the root cause of this to having the Live Share Chat extension installed. 

It was just coincidence me correlating it to SQL because it’s the first extension I typically end up activating. 

Will close, thank you for taking the time to reply.
