### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by rdbll7** [microsoft/vscode-mssql#1291]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.38.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
@rdbll7 Could you please elaborate more on your issue? Which part of the extension did you have an issue with?
