### ISSUE TITLE
Dragging the Results Editor Tab to a new VS Code Window does not work as expected

### ISSUE THREAD

**Issue by bobsterbob** [microsoft/vscode-mssql#1292]
- MSSQL Extension Version: 1.6.0
- VSCode Version: 1.38.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a SQL query file.
2. Run any script. Results Tab shows up.
3. Ctrl + Shift + N.
4. Close the Welcome Screen
5. Attempt to drag Results Tab from previous window to new window.

I know floating windows in Visual Studio Code is not a feature yet. Wondering if this can work instead?

**Comment by abist** [comment]
Hi @bobsterbob, thanks for opening the issue. Unfortunately, VS Code doesn't provide extensions the ability to do that yet, like you mentioned above. I'm going to close this issue for now.

**Comment by L3Home** [comment]
VS Code supports floating windows now (as of the latest version). When attempting to do so with a results window from a query, however, this plugin only creates a window that says the feature isn't yet supported by the plugin. Could this be added now?

Thank you!
