### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by jenseralmeida** [microsoft/vscode-mssql#1300]
- MSSQL Extension Version: 1.6.0
- VSCode Version: 1.38.1
- OS Version: Windows 10 Pro 1903 OS build 18980.1

Steps to Reproduce:

1. Install the extension and *do not reload* Visual Studio Code
2. Connect with a valid database
3. Run a valid query

I am getting the error below on the query results panel:

![image](https://user-images.githubusercontent.com/660075/65360816-374f8580-dbb6-11e9-93a0-bc457489a2ae.png)

If I do reload the window, the queries start to works. So, this bug is specifically related to the new installation without restarting Visual Studio Code.

**Comment by abist** [comment]
@jenseralmeida I don't see this issue any more and so I'm going to go ahead and close this. If you still notice this issue in the latest version of the extension, feel free to reopen the issue.

**Comment by begueradj** [comment]
I have the same issue with version 1.42

**Comment by blueyestar** [comment]
Same here v1.42.1

**Comment by abist** [comment]
@begueradj @blueyestar The latest version is 1.8. Please try the latest version and see if you have that issue.
