### ISSUE TITLE
SELECT 1000 and other scripting commands missing from views, sprocs, etc.

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1312]
- MSSQL Extension Version: 1.7

Steps to Reproduce:

1. Right-click on a View or SProc, etc.

Expected: SELECT 1000 and other scripting options available as appropriate.

Actual: Command are missing

**Comment by kburtram** [comment]
Let's scope this to only "SELECT 1000" on views

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/pull/1313
