### ISSUE TITLE
Toggle SQLCMD Mode opens new window

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1317]
1. Open new SQL editor window
2. Run the **Toggle SQLCMD Mode** command
3. A new blank editor window is opened up instead of the mode being toggled for the current window

**Comment by Charles-Gagnon** [comment]
This seems to be related to Untitled windows. It's hard to figure out the exact behavior here since I've had this happen for both titled & untitled editors, but it definitely always happens for Untitled editors.

**Comment by abist** [comment]
@Charles-Gagnon Could you verify is this still happens? Which build did you see this issue in?
