### ISSUE TITLE
SQLCMD Mode Status Item not visible

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1319]
1. Open existing SQL file
2. SQLCMD mode status item doesn't appear and it's not clear how to go about getting it

And then related - https://github.com/microsoft/vscode-mssql/issues/1317 makes it so even if you try to toggle the SQLCMD mode through the command it often just opens a new window. But that window also isn't set to SQLCMD mode and trying to set it results in the same behavior.

**Comment by abist** [comment]
@Charles-Gagnon Can you confirm this issue or give a repro?

**Comment by Charles-Gagnon** [comment]
I gave the repro steps, are they not clear enough? I'll see if I can still repro it later but I was hitting this consistently just playing around with SQLCMD mode. It would show up occasionally but at least half the time there would be no status item displayed.

**Comment by abist** [comment]
I'll be waiting on your update here. If you still see this happening, let me know.

**Comment by Charles-Gagnon** [comment]
Have you tried this yourself? Are you not seeing this behavior?

**Comment by abist** [comment]
Of course. I don't see any of the behavior mentioned - no new window opening or sqlcmd not shown

**Comment by abist** [comment]
@Charles-Gagnon Did you test before this PR was merged - https://github.com/microsoft/vscode-mssql/pull/1310
