### ISSUE TITLE
"Remove" command displays error

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1320]
1. Open command palette 
2. Run **MS SQL: Remove** command

This error is displayed 

![image](https://user-images.githubusercontent.com/28519865/65552653-d091db00-ded9-11e9-9f1a-63dfe0b883ff.png)

**Comment by Charles-Gagnon** [comment]
This seems to be because it's meant for usage by the OE tree. It should likely be hidden from the command palette.

**Comment by abist** [comment]
Was this before the OE contributions were removed?

**Comment by Charles-Gagnon** [comment]
Yes, so probably not an issue anymore. But you should keep this open because after OE is added back in we shouldn't be showing those commands in the palette so this is still relevant.

**Comment by abist** [comment]
> Yes, so probably not an issue anymore. But you should keep this open because after OE is added back in we shouldn't be showing those commands in the palette so this is still relevant.

Yes, I noticed this issue just with `Disconnect` as by default if you don't give a `when` clause, a command that's contributed shows up on the command palette. Fixed it by adding a when clause to the disconnect command as well.
