### ISSUE TITLE
OE doesn't show the database name in the connection node

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1329]
- MSSQL Extension Version: 1.7

Steps to Reproduce:

1. Add a connection to a database
2. Add a connection to another database on the same server

Expected: Two nodes in OE for each connection, and the nodes are clearly distinguishable

Actual: The nodes don't have sufficient details to tell them apart.  Also, the DB connections behave like Server connections, having a child node Databases folder that shows all folders.  We should review the design here since this is different than what we do in Azure Data Studio.
   
![image](https://user-images.githubusercontent.com/599935/65556482-9f6ad800-dee4-11e9-8f09-b1dd6723ec98.png)

**Comment by Charles-Gagnon** [comment]
Yup, was just going to file an issue on this. We should definitely do something like DB name + auth type like ADS has

![image](https://user-images.githubusercontent.com/28519865/65699747-63925880-e033-11e9-8946-569e3f9f3127.png)
