### ISSUE TITLE
Schema-based suggestions stop working

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1333]
- MSSQL Extension Version: 1.7

Steps to Reproduce:

1. Connect an editor to a database
2. Let the editor idle awhile

Expected: If the editor says it's connected than schema-based intellisense works

Actual: In some cases we only get the default suggestion list.  I'll continue to try to narrow down the repro.

![image](https://user-images.githubusercontent.com/599935/65626689-b3fdad80-df82-11e9-907a-6268f86903eb.png)

**Comment by kburtram** [comment]
As far as I can tell, this is the same issue discussed here https://github.com/microsoft/azuredatastudio/issues/7161.  Basically "Connected IntelliSense" schema-based suggestions on't appear to work with saved SQL files.

**Comment by mikelogaciuk** [comment]
For me it doesn't work properly either. 

It works with 1.6.0 but not with 1.7.0 and 1.7.1:

![obraz](https://user-images.githubusercontent.com/55132446/69052337-14e7b600-0a07-11ea-9dc5-c9c36d003cc3.png)
