### ISSUE TITLE
Connection password saved with "savePassword" is false

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1348]
- MSSQL Extension Version: 1.7

Steps to Reproduce:

1. Add a connection profile
2. Select "No" when asked to save password
3. Restart vs code
4. Expand save connection node in OE

Expected: Prompted to enter password

Actual: Node expand without prompting for password

![image](https://user-images.githubusercontent.com/599935/65809554-31781800-e153-11e9-8ef4-15b3ed9dc63b.png)

**Comment by kburtram** [comment]
This is still repro'ing for me on the latest build from master.

**Comment by abist** [comment]
Could you try to clear any cached extensions in `\.vscode\extensions`? I cannot repro this.
