### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Mausina** [microsoft/vscode-mssql#1354]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\Dazmyt\ms-mssql.mssql-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by kburtram** [comment]
Please attach the log file mentioned in the issue in order to facilitate investigation.  Thanks!
