### ISSUE TITLE
Command-C doesn't copy from the result grid on macOS

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1364]
- MSSQL Extension Version: 1.7
- OS Version: macOS

Steps to Reproduce:

1. Run a query
2. Try to copy from the results grid using Command-C on macOS

Expected: Cells copied

Actual: Cells not copied

Note: I haven't checked on other OS yet

**Comment by abist** [comment]
confirmed fixed with https://github.com/microsoft/vscode-mssql/pull/1369
