### ISSUE TITLE
execute queries multiple times 

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode-mssql#1385]
1.7.0

Steps to Reproduce:
1. Open a query editor
2. Use shortcut key to run the following query multiple times fast.
select * from sys.objects
go 4
select * from sys.tables

![Screen Shot 2019-10-11 at 10 35 48 AM](https://user-images.githubusercontent.com/13777222/66674018-bd3f7900-ec16-11e9-99e1-2a29796c5fb2.png)

**Comment by abist** [comment]
What OS was this? And what kind of server? I'm trying to repro this but can't

**Comment by alanrenmsft** [comment]
I am on Mac and connecting our test server

**Comment by chlafreniere** [comment]
stack trace: Error: Result set index cannot be less than 0 or greater than the number of result setsParameter name: resultSetIndex	at handleResponse (/Users/chlafren/.vscode/extensions/ms-mssql.mssql-1.7.0/node_modules/vscode-jsonrpc/lib/main.js:436:48)	at processMessageQueue (/Users/chlafren/.vscode/extensions/ms-mssql.mssql-1.7.0/node_modules/vscode-jsonrpc/lib/main.js:263:17)	at Immediate.setImmediate (/Users/chlafren/.vscode/extensions/ms-mssql.mssql-1.7.0/node_modules/vscode-jsonrpc/lib/main.js:247:13)	at runCallback (timers.js:694:18)	at tryOnImmediate (timers.js:665:5)	at processImmediate (timers.js:647:5)
