### ISSUE TITLE
Not able to select the cell in result tables

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode-mssql#1386]
1. execute the following query
select * from sys.objects
go 4
select * from sys.tables
1. when the results are rendered try select cells not in the last table

I am only able to select the cells in the last table.

**Comment by abist** [comment]
@alanrenmsft Is this when you have multiple resultsets?

**Comment by alanrenmsft** [comment]
as I mentioned in the description, I figured out that i have to click the header or scrollbar to gain focus. this is pretty bad.

**Comment by chlafreniere** [comment]
I just hit this as well, FYI
