### ISSUE TITLE
Connection does not with without optional profile name

### ISSUE THREAD

**Issue by qifahs** [microsoft/vscode-mssql#1388]
Issue Type: <b>Bug</b>

Connected to Azure SQL. Connection does not show up if I do not enter the optional profile name. Trying a second time with profile name worked.

Extension version: 1.7.0
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (45.12GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by abist** [comment]
@qifahs What kind of server was it? Was there a long time when it didn't show up before you tried to connect again?

**Comment by qifahs** [comment]
It is an Azure SQL server. I tried this again but unable to repro it.

**Comment by abist** [comment]
@qifahs I'll be trying to repro it. Please let me know if you were able to repro again!

**Comment by abist** [comment]
@qifahs  I'm going to close this issue. Feel free to re-open if you were able to repro again.
