### ISSUE TITLE
connection failed retry experience

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode-mssql#1390]
1. Try create a new connection to a server that does not exist
2.  Wait until the error notification pops up, there are 2 error notifications, one is asking whether to re-create the connection, the other one is the error message
3. Click retry and you will be prompted to type the server name

Expected: the server name I typed in earlier should be there for edit
Actual: it is showed as placeholder instead of actual input value

![Screen Shot 2019-10-11 at 12 13 44 PM](https://user-images.githubusercontent.com/13777222/66679082-32647b80-ec22-11e9-94ec-bd8715801c76.png)

 - Question: at step 2, Can we consolidate the notifications into one notification?

**Comment by abist** [comment]
This always been the behavior. I'll add it as an enhancement.

**Comment by abist** [comment]
This is now fixed. The text is now editable instead of being a placeholder.
