### ISSUE TITLE
Password prompted twice when making a connection

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode-mssql#1392]
I chose SQL Login and not save the password, I was asked to provide the password twice.

**Comment by alanrenmsft** [comment]
update: sometimes I got more than 2 prompts...

**Comment by abist** [comment]
Tracking here - https://github.com/microsoft/vscode-mssql/issues/1393

**Comment by alanrenmsft** [comment]
@abist that is a separate issue to me. same piece of code?

**Comment by abist** [comment]
@alanrenmsft Yes, all password prompting has same path.
