### ISSUE TITLE
infinite password prompt loop when making connection with profile name

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/vscode-mssql#1393]
1. connect to server with sql login and no profile name
2. connect to the same server with the same login with a profile name

expected:
a new connection established with the new profile name.

actual:
1. the existing connection is closed
2. I ran into a infinite password prompt loop

**Comment by abist** [comment]
Tracking all password issues here, including https://github.com/microsoft/vscode-mssql/issues/1392
