### ISSUE TITLE
Problems do not disappear when closing query editor

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/vscode-mssql#1398]
I had a query editor that had syntax errors in it.

After closing the editor, the problems still persisted:
![image](https://user-images.githubusercontent.com/40371649/66683489-6c3a7f80-ec2c-11e9-8fb3-ce489f3b795c.png)

**Comment by abist** [comment]
This won't make this release, reassigning the Milestone.

**Comment by abist** [comment]
This is being tracked here - https://github.com/microsoft/vscode-mssql/issues/1131
Closing as duplicate.
