### ISSUE TITLE
Add Connection: It is not clear what the last field "Profile Name" is for

### ISSUE THREAD

**Issue by qifahs** [microsoft/vscode-mssql#1412]
Issue Type: <b>Bug</b>

When adding a connection all of the input fields are self-explanatory, except for the last field "Profile Name". As a new user, I want to know the intent of this input. Maybe some text like "Profile name (used to organize connections)".

Extension version: 1.7.0
VS Code version: Code 1.39.0 (9df03c6d6ce97c6645c5846f6dfa2a6a7d276515, 2019-10-09T06:58:04.439Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (45.10GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by abist** [comment]
@yualan Do we add more info to the place holder text there?

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/commit/6887522fe50c7a38c53192beaf130d81e3308d81
