### ISSUE TITLE
Ran statement that returned multiple result sets and got error below...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/vscode-mssql#1416]
Issue Type: <b>Bug</b>

mssql: Something went wrong getting more rows: Result set index cannot be less than 0 or greater than the number of result sets
Parameter name: resultSetIndex

Extension version: 1.7.0
VS Code version: Code 1.39.1 (88f15d17dca836346e787762685a40bb5cce75a8, 2019-10-10T23:31:28.683Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by abist** [comment]
Same issue reported here - https://github.com/microsoft/vscode-mssql/issues/1385, so tracking it there.
