### ISSUE TITLE
Retrying profile creation doesn't let you select default DB

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1430]
1. Add profile, but enter in some invalid name for a database
2. Complete creation flow - error appears as expected and asks you to retry
3. Go to step asking for database name, the default is now listed as the invalid entry entered in step 2 but there isn't any way to remove that and select the default DB (the invalid DB is the value used if left blank)

**Comment by abist** [comment]
This was fixed in 1.8.
