### ISSUE TITLE
Result grid context menu disabled with multiple selected regions

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1433]
- MSSQL Extension Version: 1.7

Steps to Reproduce:

1. Run query and select multiple regions in the grid
2. Right-click on grid

Expected: Menu items enabled.

Actual: Menu items disabled, even though Ctrl-C still copies the selected cells as expected.

![image](https://user-images.githubusercontent.com/599935/66860638-6dc4ba00-ef42-11e9-860c-a9045befb026.png)

**Comment by abist** [comment]
This is the same behavior from last release. If we are fine with the order (multiple columns copied all together) in which `Ctrl + C` copies the results, I can enable it.

**Comment by kburtram** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/1415.  @abist I think the bug is that there is a different behavior with Ctrl-C then with the context menus.  They should behave consistently.  Ideally, they both should work (if that's not possible, then they both should be disabled).
