### ISSUE TITLE
Connections to a specific database shows all the server's databases

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1437]
- MSSQL Extension Version: 1.7

Steps to Reproduce:

1. Connect to a specific database on a server

Expected: Only see the contents of that database

Actual: See the content of the entire server.  If we are going to show the entire server contents why prompt for a specific database name during connection?

![image](https://user-images.githubusercontent.com/599935/67031070-a771fe00-f0c5-11e9-96bd-8fef2d9bd514.png)

**Comment by msftrncs** [comment]
This is normal for most SQL applications.  Even in an active query window that is already connected to a specific 'starting container', you can use `USE another_database` to use another database in the same server instance.
