### ISSUE TITLE
There should be an "Execute Query" run button in SQL editor toolbar

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1443]
- MSSQL Extension Version: 1.7

It would be better if there were "Run" and "Stop" buttons in the SQL editor toolbar for starting and canceling query execution.  For example, see how the Python extension uses a toolbar in .ipynb notebook files.

![image](https://user-images.githubusercontent.com/599935/67041543-b911d080-f0da-11e9-99a8-9a32d62702c3.png)

**Comment by abist** [comment]
This can't make the 1.8 milestone since VS Code doesn't give the ability to add your own commands with icons in the editor - https://github.com/microsoft/vscode/issues/41309

**Comment by kburtram** [comment]
@abist it looks like the Python extension is able to do this with .py files as show below.  They don't appear to be using a custom editor in this case, so I would suspect we can do the same for .sql files?

![image](https://user-images.githubusercontent.com/599935/71134205-2e208580-21b2-11ea-8206-f3b9ab5173f0.png)

**Comment by abist** [comment]
@kburtram I was able to confirm and add it to the extension in my testing internally. This should be easily doable.
