### ISSUE TITLE
Allow filtering of objects in Object Explorer

### ISSUE THREAD

**Issue by adisoftware** [microsoft/vscode-mssql#1445]
This is something I've wanted in SSMS for years. The Object Explorer can become a huge list. I'd like a search field which does wildcard filtering on items in the object explorer.

So keep the structure (e.g. server > Database > Database Name > Tables) etc, but filter the end nodes, the actual tables/sprocs etc, based on the filter.

**Comment by Msjronkko** [comment]
This would be a great enhancement! Maybe it could work similar to the way SSMS does filtering?

<img width="409" alt="ssms-filter" src="https://user-images.githubusercontent.com/28263831/70424658-66b8b480-1a78-11ea-875d-0600dc3045c5.PNG">

**Comment by adisoftware** [comment]
I actually really dislike the SSMS way - I think it's too cumbersome and time consuming to use so I end up just searching manually for the item most of the time. That's why I'd like a  simple text box that dynamically filters as I type - like a lot of Ajax lookup boxes on the internet. To me, that's the most elegant way of doing it (although I guess an advanced filter like the SSMS one is a nice thing to have in addition - but I wouldn't use it).

**Comment by Msjronkko** [comment]
I totally agree that for single table lookups a search field would be the most elegant way. However in cases where where we have multiple data sources that are divided into their own schemas (A.table1, A.table2, B.table1) and I'm working with just the A-data, ability to filter out all else than A based on for instance schema name, would be great.

**Comment by ceka** [comment]
is it possible to view objects by schema then, by object type?

**Comment by toferj** [comment]
@abist What does the "upstream" label mean? I'm really excited for this feature though I'm sure there are other more important features ahead of it. Even just being able to filter by schema would help me. If I even knew where to start looking at the code for this, I'd have a crack at it (no promises). I don't know what kind of committee or whatever features like this go through to determine how they'll look, function and will be implemented.

Anyway, would love to see this feature get more attention by the community... or are there really only four of us who want this feature. ;)

Thanks!

**Comment by Desmo46** [comment]
I’d like to throw my hat in and say this functionality would be very useful.  Our DBs have many tables and SPs so having an ability to quickly search and fuzzy search across all objects would save literally hours.

**Comment by aasimkhan30** [comment]
Closing as this feature is already in `main` and will be released in the next version.
