### ISSUE TITLE
`command 'extension.addObjectExplorer' not found`

### ISSUE THREAD

**Issue by puruzio** [microsoft/vscode-mssql#1447]
- MSSQL Extension Version: 1.6.0
- VSCode Version: 1.39.2
- OS Version: Windows 7

Steps to Reproduce:

1. Install mssql extension
2. Click on the SQL Server icon in the tool bar

When I click the SQL Server icon in the tool bar, I get an error message
`command 'extension.addObjectExplorer' not found`

Uninstalling the mssql extension, and restarting/reinstalling it didn't help.

I thought this might be a package build issue, but I don't see any such issue reported on github or anywhere on the internet.

**Comment by abist** [comment]
@puruzio Thanks for reporting the issue. Could you try deleting the extension cache for the previous version in `~/.vscode/extensions/mssql-(old-version)` and then installing again?

**Comment by puruzio** [comment]
Sorry it was a typo. MSSQL Extension Version is 1.7.

I deleted the extension cache as you suggested, and reinstalled it to no avail. The extension folder extensions\ms-mssql.mssql-1.7.0 includes the following files and folders:  Do they look complete?
.github\
images\
localization\
node_modules\
out\
scripts\
snippets\
sqltoolsservice\
syntaxes\
package.json
tslint.mssdl.required.json
tslint.json
ThirdPartyNotices.txt
README.md
package.nls.zh-tw.json
package.nls.zh-cn.json
package.nls.ru.json
package.nls.pt-br.json
package.nls.ko.json
package.nls.json
package.nls.ja.json
package.nls.it.json
package.nls.fr.json
package.nls.es.json
package.nls.de.json
npm-shrinkwrap.json
LICENSE.txt
KERBEROS_HELP.md
issue_template.md
install.js
gulpfile.js
coverconfig.json
CHANGELOG.md
.mention-bot
.vsixmanifest

If it's not complete, is there a way to install the extension manually using https://download.microsoft.com/download/c/2/f/c2f482e1-ceb3-4f6a-a8b7-1f8115fc0a44/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.2.zip?

**Comment by puruzio** [comment]
It was a proxy issue that caused the installation to fail (although VS Code extension indicated it was installed.) Thanks.

**Comment by iaxat** [comment]
Issue persists

**Comment by iaxat** [comment]
> It was a proxy issue that caused the installation to fail (although VS Code extension indicated it was installed.) Thanks.

How to resolve my issue?

**Comment by abist** [comment]
@iaxat Are you having issues downloading the .vsix itself or the service file as mentioned above?

**Comment by chris-schulz** [comment]
For me the installation seems fine but when i click the "+" I get the object explorer error as mentioned above. I have set the proxy settings in VSCode correctly

**Comment by abist** [comment]
@chris-schulz Can you try the suggestion here - https://github.com/microsoft/vscode-mssql/issues/1447#issuecomment-543843019

**Comment by chris-schulz** [comment]
> 
> 
> @chris-schulz Can you try the suggestion here - [#1447 (comment)](https://github.com/microsoft/vscode-mssql/issues/1447#issuecomment-543843019)

Yes already tried that. Also tried manually installing 1.80 to no avail. Seems VSCode is ignoring the proxy for the service layer install.

**Comment by abist** [comment]
> > @chris-schulz Can you try the suggestion here - [#1447 (comment)](https://github.com/microsoft/vscode-mssql/issues/1447#issuecomment-543843019)
> 
> Yes already tried that. Also tried manually installing 1.80 to no avail. Seems VSCode is ignoring the proxy for the service layer install.

Perhaps try one of the daily alpha offline builds? https://github.com/microsoft/vscode-mssql/releases

**Comment by rob99** [comment]
I had this problem occur in v1.10.1

I was able to fix it by reverting to v1.9.0

**Comment by dgkrieger** [comment]
I just ran into this with v1.10.1 on Windows 10. I resolved the same way by reverting back to v1.9.0

**Comment by necotec** [comment]
Here too,

had the issue `command 'extension.addObjectExplorer not found` with Windows 10 (20H2), VisualStudioCode and extension version 1.10.1. Installed extension version 1.10.0 and the issue is solved.

**Comment by kburtram** [comment]
@necotec there weren't any significant changes between those two builds that should cause this issue.  This issue would typically be caused by some type of installation failure, most likely with the child process that is downloaded on first launch.  You might try upgrading again and see if the issue reoccurs.

**Comment by necotec** [comment]
Hmmm...

updated to V1.10.1 and the issue is there... downgraded again to V1.10.0 and the extension is working fine.

Updated again, and the issue is there again. Downgraded again, and it's working.

Don't know why. Is it possible, that there is an issue with the Windows version (20H2)?

**Comment by kburtram** [comment]
@necotec weird, we haven't heard of any problems like this with 20H2 (which is what I'm running also).  When you upgrade did you see the sqltoolsservice zip get download and decompressed successfully in the logs?  Are there any other errors in the "Help->Developer Tools" Console output?

**Comment by art-ist** [comment]
I had the same problem on Ubuntu. The solution for me was:

1. Uninstall the extension
2. **Delete the extension files from disk (`vscode/extensions/ms-mssql.mssql-*`)**
3. Reinstall the extension

Step 2 somehow did the trick. (No idea why this was necessary.)

**Comment by liberse** [comment]
In my case, being connected to a VPN generated an error in the installation.
I add an extra step:

1. Uninstall

2. Delete the extensions ms-mssql.... in the user folder (put yours)
C:\Users\USER\.vscode\extensions

3. DISCONNECT FROM THE VPN (MY CASE)

4. Reinstall

**Comment by Justin1107-good** [comment]
**This cannot be solved. Is there any other solution？**

> 1. Uninstall
> 2. Delete the extensions ms-mssql.... in the user folder (put yours)
>    C:\Users\USER.vscode\extensions
> 3. DISCONNECT FROM THE VPN (MY CASE)
> 4. Reinstall

**Comment by ccmg-serge-kamilchu** [comment]
same issue with ms-mssql.mssql-1.18.0

**Comment by oldbuilding** [comment]
same issue.  I deleted every cached extension folder for ms-mssql* that I could find.  rebooted.  reinstalled.  rinse; repeat.

wsl --status
Default Distribution: Ubuntu
Default Version: 2

Windows Subsystem for Linux was last updated on 4/19/2022
WSL automatic updates are on.

Kernel version: 5.10.102.1

Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: linux, x86_64, name=ubuntu, version=22.04 (Ubuntu16)

Installing SQL tools service to ~/.vscode-server-insiders/extensions/ms-mssql.mssql-1.21.0/sqltoolsservice/4.9.0.37/Ubuntu16.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.9.0.37/microsoft.sqltools.servicelayer-rhel-x64-net7.0.tar.gz
failed (error code '407')
[ERROR] Error: 407

**Comment by oldbuilding** [comment]
I got it working.

> 

1. install 1.21.0 
2. > cd ~/.vscode-server-insiders/extensions/ms-mssql.mssql-1.21.0/sqltoolsservice/4.9.0.37/Ubuntu16/ 
3. > wget https://github.com/microsoft/sqltoolsservice/releases/download/4.9.0.37/Microsoft.SqlTools.ServiceLayer-rhel-x64-net7.0.tar.gz
4. > tar -xzvf Microsoft.SqlTools.ServiceLayer-rhel-x64-net7.0.tar.gz
5. > rm Microsoft.SqlTools.ServiceLayer-rhel-x64-net7.0.tar.gz
6. disable the extension
7. restart vscode-insiders
8. re-enable the extension
9. should work now

**Comment by oldbuilding** [comment]
Pin your version.  vscode update will break everything again.
