### ISSUE TITLE
SQLCMD Mode Toggle on VSCode Status Bar

### ISSUE THREAD

**Issue by Actiarn** [microsoft/vscode-mssql#1448]
- MSSQL Extension Version: 1.7.0
- VSCode Version: 1.40.0-insider
- OS Version: Windows 10
![SQLCMD Mode OnOff](https://user-images.githubusercontent.com/56735269/67112105-761c2f80-f1a4-11e9-991b-4b73bc5447dd.PNG)

Steps to Reproduce:

1. Open VS Code
2. Open .sql file with SQLCMD mode syntax
3. Connect to a SQL Server
4. Ensure SQLCMD Status shows "SQLCMD: On" on status bar
5. Script fails due to SQLCMD Mode not being enabled.
6. Click "SQLCMD: On"
7. Script runs successfully

Overview: Status Bar shows SQLCMD: Off when SQLCMD Mode is actually on. As a status bar showing what you are currently using/connected to, this should show what state SQLCMD Mode is currently in, not what the button will do. This is confusing to the user.

**Comment by abist** [comment]
@Actiarn Thanks for submitting the issue. Were you connected when you initially switched SQLCMD on?

**Comment by Actiarn** [comment]
Hello, Adyita!

I connected to SQL first, created a new query, pasted in the code below
(replace server name), and no matter which mode SQLCMD is in (On or Off),
it fails to execute. With SQLCMD On, I get a failure on :Connect. With
SQLCMD Off, I get a T-SQL style syntax error at the first colon. This works
in SSMS.

:SETVAR Pri_srv "myservername"
:SETVAR myText "Hello!"


:Connect $(pri_srv)

SELECT '$(myText)'

**Comment by abist** [comment]
@Actiarn We are trying to get the full experience of SQLCMD onto the extension, but as of now there are certain keywords that don't work right now -
:Connect
:Error
:Exit
:On Error
:Out
:Quit
:!!

This is a known issue and being tracked for the next release.

**Comment by Actiarn** [comment]
Thanks!

  As far as the status bar, I believe that was an issue on my end where I
did not close the VSCode application after the MSSQL extension update.
After I had reopened it, the issue with what was being shown (SQLCMD:
On/Off) seem to have corrected itself.

-Dale

**Comment by abist** [comment]
@Actiarn Thanks for confirming. I'm going to go ahead and close this issue. The issue I described above about missing keywords is being tracked here - https://github.com/microsoft/vscode-mssql/issues/1449, if you want to get updates on it.
