### ISSUE TITLE
Feature request: Multiple query at the same time

### ISSUE THREAD

**Issue by noppGithub** [microsoft/vscode-mssql#1452]
First of all, thank you so much for creating this vscode extension, such a great extension for anyone who needs to work with SQL databases.

If it is possible please consider allowing us to submit multiple queries. now the extension will says 
```
mssql: A query is already running for this editor session. Please cancel this query or wait for its completion.
```

Thanks

**Comment by abist** [comment]
@noppGithub You could separate multiple queries with the `GO` batch separator or run multiple queries in different tabs. I'd like to know your use case to know more about this feature request.

**Comment by SargntSprinkles** [comment]
What are the queries you're trying to run that are giving you that message? I can run multiple queries in the same request without any issue.

e.g. queries:
![image](https://user-images.githubusercontent.com/3606469/67401171-c0bef280-f57c-11e9-916a-a12b1d8a3c36.png)
results:
![image](https://user-images.githubusercontent.com/3606469/67401208-d03e3b80-f57c-11e9-8a19-f70975365c58.png)

**Comment by abist** [comment]
@noppGithub Could you clarify how you want this feature to be implemented?

**Comment by noppGithub** [comment]
> @noppGithub Could you clarify how you want this feature to be implemented?

@abist @SargntSprinkles 
Sorry for the very late reply, I was able to work without any issue after using `;` and `GO`.
Thanks a lot for considering my question.
