### ISSUE TITLE
Intellisense stops working when query is saved

### ISSUE THREAD

**Issue by HSCelahaye** [microsoft/vscode-mssql#1453]
- MSSQL Extension Version: 1.70
- VSCode Version: 1.39.2
- OS Version: Windows 10 Enterprise build version 1709

Steps to Reproduce:

1. Create New Query, do a standard select statement from DB
ex: SELECT *
FROM MEMBERS
2. Check if Intellisense works on individual columns, this should prepopulate the names
ex: SELECT MEMNAME, MEMLASTNAME
FROM MEMBERS 
3. Save the Query (this is where it breaks, the IntelliSense doesn't prepopulate anything for the DB, as if I disconnected)

I was able to roll back 1.60 and my IntelliSense works on saved queries there, but this last update broke it.

**Comment by wzlwit** [comment]
And seems Visual Studio IntelliCode is required to be 1.19 to keep MSSQL 1.60 works.

**Comment by mikelogaciuk** [comment]
I have the same issue. Intellisense isn't working...

**Comment by jkarr** [comment]
I have this same issue.  MSSQL 1. 7.0, Visual Studio IntelliCode is 1.2.0 though, and it's only change description:
Added support for MSSQL.  And a link to a blog post that redirects to  Microsoft home page (https://aka.ms/vsicsql)

**Comment by DanwithArduino** [comment]
Same issue for me, Intellisense is broken. MSSQL 1.7.1 and VSC 1.40.1

**Comment by HSCelahaye** [comment]
> Same issue for me, Intellisense is broken. MSSQL 1.7.1 and VSC 1.40.1
> Definitely has something to do with when the file is saved... Guess I'll just copy and paste between two tabs for a while...
@DanwithArduino 
I personally recommend rolling back to MSSQL 1.6.0 for the time being, the previous version works fine for me.

**Comment by DrDanRyan** [comment]
Any updates here? I have been pinned to 1.6.0 since this bug was introduced. I can't work without functioning Intellisense...

**Comment by kburtram** [comment]
@abist have we confirmed this is fixed in 1.8.0 release?

**Comment by HSCelahaye** [comment]
Thanks guys!
