### ISSUE TITLE
SELECT statement result no longer shows count of returned rows in results

### ISSUE THREAD

**Issue by alanmangalindan** [microsoft/vscode-mssql#1462]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. run any select statement 
2. in version 1.6, number of rows 'affected' was returned (first image). version 1.7 no longer shows the number of rows, just confirmation that command was executed successfully (2nd image)

![image](https://user-images.githubusercontent.com/46139665/67438116-28457280-f64f-11e9-8a0c-86209f23d16b.png)
![image](https://user-images.githubusercontent.com/46139665/67438129-2e3b5380-f64f-11e9-948d-2fc1decabfd6.png)

**Comment by abist** [comment]
@alanmangalindan We noticed this issue and will have a fix in the coming next release.
