### ISSUE TITLE
Support SQL Database Project type in VSCode

### ISSUE THREAD

**Issue by Colizobble** [microsoft/vscode-mssql#1465]
I am increasingly using VSCode for my database projects, but the disconnected experience is not as good as it could be, because of the lack of support for SSDT / SQL Database Projects. I cannot get full intellisense, or object reference checking. 
I note that Azure Data Studio now has a Schema Compare extension, but this only works with DacPac files, not project files, and while I can build a DacPac file using MSBuild on Windows, this isn't available for Mac or Linux.
It feels that nearly all the pieces are in place to support the full development experience, and I would encourage you to add the final components.

**Comment by TarekSalha** [comment]
Will this be implemented in the near future? Currently, I need to regularly switch between vs and vscode due to the lack of db projects

**Comment by Charles-Gagnon** [comment]
Closing this as the code is all merged in for this - keep an eye out for the next release for SQL Project support!
