### ISSUE TITLE
Latest update removed record count messages

### ISSUE THREAD

**Issue by ibrowne** [microsoft/vscode-mssql#1467]
- MSSQL Extension Version: 1.7.0
- VSCode Version: 1.39.2
- OS Version: Mojave 10.14.6

**Steps to Reproduce:**

1. Write a TSQL query
2. Run query on a database with data
3. Observe the Messages pane only reads "commands completed successfully".  Before the update I would see something along the lines of "1234 records affected...".

If this is due to something other than the update, please let me know.  thank you.

**Comment by abist** [comment]
Hi @ibrowne, thanks for opening this issue. We are aware of this bug and it will be fixed in the next coming update of the extension.
