### ISSUE TITLE
No affected records returned in messages

### ISSUE THREAD

**Issue by fanshaohua-fan** [microsoft/vscode-mssql#1469]
- MSSQL Extension Version: 1.7.0
- VSCode Version: 1.39.2
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. execute any query
2. see the messages returned

![image](https://user-images.githubusercontent.com/6319967/67849672-486da980-fb07-11e9-9d41-2a4ebc9286b6.png)

Remember in the previous version, there is one extra info about how many records are affected.
Like this:
![image](https://docs.microsoft.com/en-us/sql/visual-studio-code/media/sql-server-develop-use-vscode/vscode-create-database-messages.png?view=sql-server-ver15)
Now it's gone in the new version.

**Comment by abist** [comment]
Hi @fanshaohua-fan , thanks for opening this issue. We are aware of this bug and it will be fixed in the next coming update of the extension.
