### ISSUE TITLE
MSSQL extension creates confusing + to other Azure extensions.

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-mssql#1470]
- MSSQL Extension Version: 1.7.0
- VSCode Version: 1.39.2
- OS Version: Win 10 on Insiders fast

Steps to Reproduce:

1. Install the [Azure Storage](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-azurestorage) extension and note the commands in the explorer sash

![image](https://user-images.githubusercontent.com/1186948/67908253-0dd03500-fb38-11e9-8ba7-dc056b7724f7.png)

2. Install the MS SQL extension and note the commands in the explorer sash

![image](https://user-images.githubusercontent.com/1186948/67908284-33f5d500-fb38-11e9-8297-ed953f7feba7.png)

The new "+" icon in the Storage extension sash attempts to add a connect.

Discovered this during a user study in which the customer installed the Azure Tools extension pack then was confused as to why they couldn't use the "+" to create a new storage account. Note that this + icon is created on all of the Azure extensions including the ones that already have an add action:

![image](https://user-images.githubusercontent.com/1186948/67908427-b8485800-fb38-11e9-8921-5e7ccf36badd.png)

**Comment by abist** [comment]
@fiveisprime This issue is fixed in master and will be fixed in the next upcoming release of the extension.
