### ISSUE TITLE
Initialization failed due to internet 

### ISSUE THREAD

**Issue by CookieLau** [microsoft/vscode-mssql#1471]
- MSSQL Extension Version:1.6.0
- VSCode Version:1.38.1
- OS Version:ubuntu18.04

Steps to Reproduce:
1.Download the extension
2.Click to run extension

Hi there, when I launch mssql extension, the vscode can  not connect to your download url and fail to initialize:
```

Installing SQL tools service to /home/cookielau/.vscode/extensions/ms-mssql.mssql-1.7.0/sqltoolsservice/1.7.0/Ubuntu16.
Downloading https://download.microsoft.com/download/c/2/f/c2f482e1-ceb3-4f6a-a8b7-1f8115fc0a44/microsoft.sqltools.servicelayer-rhel-x64-netcoreapp2.2.tar.gz
failed (error code '503')
[ERROR] Error: 503

```

But actually I am able to connect it with browse and successfully download the .tar.gz , can you help me how to install this `microsoft.sqltools.servicelayer-rhel-x64-netcoreapp2.2.tar.gz` offline and skip the download in vscode terminal?
Thank you for your reply.

**Comment by abist** [comment]
@CookieLau Thanks for opening the issue. Could you try downloading the file mentioned above from this link - https://download.microsoft.com/download/c/2/f/c2f482e1-ceb3-4f6a-a8b7-1f8115fc0a44/microsoft.sqltools.servicelayer-rhel-x64-netcoreapp2.2.tar.gz

Please let me know if it works or not.

**Comment by CookieLau** [comment]
@abist Sorry for replying so lately, I can download the file from your link and it is 39.93MB, so what should i do next? I still can not download and install it from vscode, pity :(

**Comment by abist** [comment]
@CookieLau It seems like you have the same issue as this one - https://github.com/microsoft/vscode-mssql/issues/391. Also, we have daily offline builds (alpha) if you want to pick up offline installations of the extension here - https://github.com/microsoft/vscode-mssql/releases

**Comment by abist** [comment]
@CookieLau Feel free to reopen the issue if you face it again. I'm closing this for now.
