### ISSUE TITLE
Flip Layout view setting does not persist.

### ISSUE THREAD

**Issue by Tyler-Oreskey** [microsoft/vscode-mssql#1481]
- MSSQL Extension Version: 1.7.0
- VSCode Version: 1.40.0
- OS Version: Catalina 10.15.1

Description:
When changing the editor layout setting to "Flip Layout" in View < Editor Layout, It won't persist when disconnecting from my SQL Server, then reconnecting and creating a new SQL Query.

Steps to Reproduce:

1. Connect to a SQL Server.
2. Run a few queries.
3. Select the "Flip Layout" option in View < Editor Layout.
4. Notice your query and results are horizontally split.
5. Disconnect from your SQL Server, the reconnect.
6. Create a new query and notice that your query and results tabs are vertically split and not horizontally split.

**Comment by abist** [comment]
@Tyler-Oreskey That setting can be changed using `Workbench > Editor: Open Side By Side Direction` option in the user settings. Select `down` in case you want the results to show horizontally every time instead.

**Comment by K8-and-a-half-1000** [comment]
Can the naming of this setting be modified?
Everywhere else it's defined as **split** with  **horizontal** and **vertical** as options. 

I just spent half an hour searching, not knowing I should search on **side by side direction** with **right** and **down** as options.
