### ISSUE TITLE
Extension should bundle its dependencies per vsce warning

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1489]
When I run `vsce package` I see the below warning.  We should probably follow its suggestion to improve extension load & install performance.

```
This extension consists of 6351 separate files. For performance reasons, you should bundle your 
extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by
adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
```

**Comment by abist** [comment]
We actually use systemjs instead of webpack for Angular, but I'll look into this.

**Comment by abist** [comment]
Bundled dependencies using system-js since we use Angular too. Removed extra dependencies and now the extension size is 6 MB down from 10 MB.
