### ISSUE TITLE
Messages text can't be selected

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1493]
- MSSQL Extension Version: 1.7.1

Steps to Reproduce:

1. Run a query
2. Try to select Messages text

Expected: Text is selectable

Actual: Text is not selectable

*For reference, the below text should be selectable\copyable*

<img width="525" alt="Screen Shot 2019-11-13 at 2 51 42 PM" src="https://user-images.githubusercontent.com/599935/68811337-43d7e380-0625-11ea-8a03-a17866d87576.png">

**Comment by kburtram** [comment]
@abist I pretty sure this worked at one point.  Can you determine if this is a regression from 1.7.0?  If not, I think a fix can wait for 1.8.0.  Thanks!

**Comment by abist** [comment]
@kburtram This doesn't seem to be a regression from 1.7 but the fix is easy to take for 1.7.1, so I think we should include it.
