### ISSUE TITLE
Extension is adding second "refresh" context menu

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-mssql#1498]
similar to #1470 

Also related to: https://github.com/microsoft/vscode-azurestorage/issues/498

**Comment by abist** [comment]
@fiveisprime Thanks for opening the issue. This should be fixed in version 1.7.1 
Do you still see that issue in the latest version?

**Comment by fiveisprime** [comment]
Yeah, it's happening in the stable release today.

**Comment by abist** [comment]
@fiveisprime It was fixed in this commit - https://github.com/microsoft/vscode-mssql/pull/1456

I couldn't repro it either. Could you try clearing the old mssql extension cache and try re-installing?

**Comment by fiveisprime** [comment]
It's not reproducing on the machine I'm using right now so it may just have been something cached. Thanks!
