### ISSUE TITLE
Move to azure pipelines

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/vscode-mssql#1504]
While we are doing work here, we should do the work to move to azure pipelines.

@abist let me know if you are over extended here and I can take this.

**Comment by abist** [comment]
@anthonydresser we already are using azure pipelines - https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=46376

do you mean getting rid of appveyor totally?

**Comment by anthonydresser** [comment]
Removing appveyor and travis and instead use a public azure pipelines instance.

**Comment by anthonydresser** [comment]
Or we could use github actions if we wanted. Either is fine, but travis and appveyor are a little outdated.

**Comment by abist** [comment]
@anthonydresser I already removed Travis. Will remove AppVeyor after a bit of cleaning.
