### ISSUE TITLE
Open database objects

### ISSUE THREAD

**Issue by casraysa** [microsoft/vscode-mssql#1509]
Hi,

First of all, thank you for this superb Visual Studio Code extension. I'm writing just to make a suggestion. I'm writing just to make a suggestion. I would be nice to have the Open option when you do right-click onto one of the database objects (as stored procedures, functions, etc.) 

Kind Regards.

**Comment by abist** [comment]
@casraysa Thanks for opening this issue! When you say `Open` database objects, what exactly do you mean? Just trying to get more details on what you want to see.

**Comment by casraysa** [comment]
In the database explorer, I want to have an option to open and see or modify the code of a user-defined function or the code of stored procedure that is kept in the database. It would be great if you could have similiar functionalities to the SQL server object Explorer.

**Comment by abist** [comment]
@casraysa Do you mean adding scripting methods to create/drop/alter/execute objects?

**Comment by casraysa** [comment]
Right now, you can select a table or view and see their records. I would like to have the option to open the code that generates a view or the code of a stored procedure as you can do in SSMS object explorer.

![image](https://user-images.githubusercontent.com/14315712/69540793-dd898400-0f87-11ea-921a-093d856bf2ae.png)

**Comment by testingcan** [comment]
This is probably addressed with #1474, right? Though there is no *Modify* function, `CREATE` and `ALTER` are available and working.

**Comment by casraysa** [comment]
Hi,

That is awesome!! Thank you very much.

Kind regards,
Salva

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by abist** [comment]
@testingcan Yes, you're right. Currently, we only support `CREATE`, `DELETE`, `ALTER` right now. Feel free to open another issue for the `Modify` option.
