### ISSUE TITLE
Create Firewall rule fails to locate SQL DB in subscription

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1532]
- MSSQL Extension Version: 1.8

Setup:
- Have two Azure subscriptions, say Sub1 and Sub2
- Have a SQL DB in one of the subscriptions, say Sub2

Steps to Reproduce:

1. Sign into Sub1
2. Try to connect to SQL DB and Create Firewall Rule
3. Get error that DB is not in subscription.
4. Use "Azure Sign In" to switch to Sub2
5. Try to connect to SQL DB and Create Firewall Rule

Expected: Firewall rule created and server connected

Actual: Still get error message about not being able to locate server in subscription.  Need to restart VS Code and connect again to successfully create rule.

![image](https://user-images.githubusercontent.com/599935/70566993-ed899200-1b49-11ea-8b21-ef6604da232a.png)

**Comment by kburtram** [comment]
@abist this doesn't impact 1.8 release, but was a bug I encountered while testing the release candidate.

**Comment by cssuh** [comment]
<img width="1904" alt="Screen Shot 2020-07-22 at 12 01 14 AM" src="https://user-images.githubusercontent.com/18150417/88132858-9010f580-cbae-11ea-9f0b-be8b16295b71.png">
seeing this in the debug console when the error above (posted by Karl) is displayed
