### ISSUE TITLE
New Query fails on databases after server node "Refresh"

### ISSUE THREAD

**Issue by kenvanhyning** [microsoft/vscode-mssql#1539]
- MSSQL Extension Version: 1.8
- VSCode Version: 1.40.2 (user)
- OS Version: Windows 10

Steps to Reproduce:

1.  Connect server
2.  Expand Databases node
3. Right-click on any database, select New Query (should work fine)
4. Left-click on server to collapse
5. Right-click on server and select "Refresh"
6. Expand server (should display databases as well)
7. Right-click on any listed database and select "New Query"
8. Error pops up in toast:

Error running command mssql.objectExplorerNewQuery: Cannot read property 'connectionCredentials' of undefined. This is likely caused by the extension that contributes mssql.objectExplorerNewQuery.

Same steps above work fine if Server/Refresh is done with tree still expanded (i.e. don't left-click on server before refresh).

**Comment by abist** [comment]
Should be fixed by https://github.com/microsoft/vscode-mssql/pull/1607 and https://github.com/microsoft/vscode-mssql/pull/1602
