### ISSUE TITLE
Query execution errors aren't displayed in red is Messages

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1541]
- MSSQL Extension Version: 1.8

Steps to Reproduce:

1. Run a query that generates execution errors

Expected: Errors are displayed in red

Actual: Errors are not displayed in red in the Messages window.

*Note: see vscode-mssql SxS with ads for the same query*
![image](https://user-images.githubusercontent.com/599935/70573703-5cb9b300-1b57-11ea-9336-9f6f214715fd.png)

**Comment by ibrowne** [comment]
@abist - This is broken again in v1.25.0 that released on 10/23/2024.  Can we please re-open this or start a new issue?  The errors do not appear in red in the new Messages interface, making it very difficult to know if something went wrong in the query being run.
