### ISSUE TITLE
Multi-Query results disappear from results pane randomly

### ISSUE THREAD

**Issue by ibrowne** [microsoft/vscode-mssql#1553]
- MSSQL Extension Version: 1.8.0
- VSCode Version: 1.41.0
- OS Version: 10.14.6

Steps to Reproduce:

1. Execute a SQL cursor that contains dynamic SQL that results in several returns being displayed at the same time in the results pane. 
1. Use the mouse wheel or drag the bar on the right to scroll vertically through the results
1. notice that the display of the results is intermittent, appearing and disappearing seemingly at random.  see: https://www.screencast.com/t/07UCUWTFS

This is a big issue when the purpose of the code is to locate the queries (generated by the cursor's dynamic sql) that are returning results.

thanks.

-IAN

**Comment by kburtram** [comment]
@abist do you have any thoughts here?  I'd guess it has something to do with the optimizations we use to avoid rendering off-screen result grids.

**Comment by abist** [comment]
@kburtram Yes, I think it's because of the optimization to not load all the results. There's an existing issue about it here - https://github.com/microsoft/vscode-mssql/issues/877, which seems related.

**Comment by StarryTony** [comment]
MSSQL Extension Version: 1.22.0
VSCode Version: 1.82.2
OS Version: Windows 10 Enterprise 22H2 19045.3930

VSCODE version details:
Version: 1.82.2 (system setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

I got the same issue for multi-query results while scrolling. This appeared to be a rendering issue. Any thoughts/workaround welcome. Many thanks.

**Comment by gwduvalljr-AT** [comment]
Name: SQL Server (mssql)
Id: ms-mssql.mssql
Description: Develop Microsoft SQL Server, Azure SQL Database and SQL Data Warehouse everywhere
Version: 1.22.1
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:08:12.169Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Linux x64 6.5.0-41-generic

Same issue here. It is so bad that once I get to one of the result tables towards the bottom of the set, the results will disappear before all ten rows are visible.

Are there any workarounds at all?

**Comment by Benjin** [comment]
We're working on a new query results pane that's react-based and should be handling virtualization better.  Can you try this on the latest build with the modern features enabled?

**Comment by gwduvalljr-AT** [comment]
I have what I think is the latest, and I have the "preview features"
checked as far as I can tell, but I am not seeing any differences. I am
sure I am missing something. Can you point me to the right place?

Thanks,

[image: image.png]


Version: 1.49.1
Commit: 2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd
Date: 2024-08-13T17:56:45.095Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.8.0-47-generic


Garland Duvall

CTO

770-883-4643

***@***.***

www.activtech.com <http://activtech.com/>


Empowering Digital Supply Chains

**Comment by gwduvalljr-AT** [comment]
Let me try this again...

I realize now that you were talking about the vsix. I downloaded it and went through ADS's File->Install Extension from VSIX Package and picked the package. As far as I can tell, it did nothing. I see nothing in the developer console either.

So, I am going to need a bit of help here to upgrade ADS with the VSIX.

**Comment by Benjin** [comment]
@gwduvalljr-AT 

Just to make sure we're on the same page, this extension is intended for use with VS Code, not Azure Data Studio.  All of these features already exist in some form over in Azure Data Studio.

To install this extension in VS Code, try clicking "Install" from [this page](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) or searching for "mssql" from within VS Code's extension view.

**Comment by gwduvalljr-AT** [comment]
@Benjin 

Wow, Friday was not my best day (obviously!) I am just so used to using ADS, and its result window is so bad that I was thinking about it exclusively.

Anyway, I have loaded this in VSCode, and the results are good so far. I've got a script that produces 42 result sets that I am using for testing. Fingers crossed, the scrolling seems to be working well.

I have no idea if you know this or not, but the new pane does not seem to respect the following settings:
mssql.resultsFontFamily
mssql.resultsFontSize

Thank you for pointing me in the right direction.

**Comment by Benjin** [comment]
I didn't realize that; thanks for letting us know!  I've created #18351 to track that specific issue.  Also, I'm going to close this one since we've rewritten the entire experience since it's been filed.  If this issue is occurring in the present query pane, please file a new bug so we can have clean and recent info to work with.  Thanks!
