### ISSUE TITLE
UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by gbritton1** [microsoft/vscode-mssql#1563]
Issue Type: Bug

Install  mssql extension,
Receive an error "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
e.g. (happens with both mssql and intellicode installs)

Platform: win32, x86_64 (Windows)

Installing SQL tools service to c:\Users\BRITTG2.vscode\extensions\ms-mssql.mssql-1.8.0\sqltoolsservice\1.8.0\Windows. Downloading https://download.microsoft.com/download/e/7/8/e781cf8f-9c3f-4ad5-bd0c-f3c62b8bc6bd/microsoft.sqltools.servicelayer-win-x64-netcoreapp2.2.zip [ERROR] Error: Request error: UNABLE_TO_GET_ISSUER_CERT_LOCALLY

Note: I am behind a corp fw. FWIW I tried the suggestion here: Network Connections in Visual Studio Code

where it says, in part:

If all else fails, you can tell VS Code to ignore all certificate errors using the --ignore-certificate-errors command-line flag. Warning: This is dangerous and not recommended, since it opens the door to security issues.

However, that is an invalid flag :

> code --ignore-certificate-errors
Option 'ignore-certificate-errors' is unknown. Ignoring.
Version: 1.41.1 (system setup)
Commit: 26076a4
Date: 2019-12-18T14:58:56.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

VS Code version: Code 1.41.1 (26076a4, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18362

System Info
Item	Value
CPUs	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)
GPU Status	2d_canvas: enabled
flash_3d: enabled
flash_stage3d: enabled
flash_stage3d_baseline: enabled
gpu_compositing: enabled
metal: disabled_off
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: enabled
rasterization: enabled
skia_renderer: disabled_off
surface_control: disabled_off
surface_synchronization: enabled_on
video_decode: enabled
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off
webgl: enabled
webgl2: enabled
Load (avg)	undefined
Memory (System)	15.88GB (2.82GB free)
Process Argv	
Screen Reader	no
VM	0%
Extensions (9)
Extension	Author (truncated)	Version
githistory	don	0.4.13
gitlens	eam	10.2.0
code-runner	for	0.9.15
gc-excelviewer	Gra	2.1.32
mssql	ms-	1.8.0
python	ms-	2020.1.57204
powershell	ms-	2019.12.0
partial-diff	ryu	1.4.0
vscode-hexdump	sle	1.7.2

**Comment by abist** [comment]
Hey @gbritton1, thanks for opening this issue. It seems the same issue was reported here - https://github.com/microsoft/vscode-mssql/issues/1089 and was resolved. Could you try the solution suggested in this issue here and see if it works for you?

**Comment by gbritton1** [comment]
I'll try that. though even it it works, it's just a workaround.  WHy does this extension have this problem and no others that I use?  WHat can be done to make it conformant with others?

Also, note the the documentation I cited is incorrect.  Not at all sure what it should be though as I'm not familiar with that code.

**Comment by abist** [comment]
From what I understand you face this issue when download the IntelliCode extension as well, so it's the corpnet proxy issue, not an extension issue. You could try to add exceptions for the links where the extension downloads the service.

**Comment by gbritton1** [comment]
@abist how to add exceptions?

**Comment by abist** [comment]
@gbritton1 Set "http.proxyStrictSSL": false in user settings in VSCode, and then try using the ignore certificates flag.

**Comment by gbritton1** [comment]
The ignore certificate flag is invalid.  See the top post

**Comment by abist** [comment]
@gbritton1 Did you try changing the setting and downloading the extension?

**Comment by gbritton1** [comment]
Yes! It works.  Now how to fix it properly so the workaround is not
needed.  And how to fix the doc re that bad flag?

**Comment by abist** [comment]
@gbritton1 That's an issue you can open against `vscode`. The extension installation belongs to them, but if you see any issues with the extension itself, feel free to open an issue.
