### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Vladoni-kot** [microsoft/vscode-mssql#1569]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.8.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\я\ms-mssql.mssql-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by abist** [comment]
@Vladoni-kot Could you please attach the cpuprofile logs here?
