### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by GabrielMochi** [microsoft/vscode-mssql#1570]
- Issue Type: `Performance`
- Extension Name: `mssql`
- Extension Version: `1.8.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.41.1`

Logs:
[http://www.filedropper.com/ms-mssqlmssql-unresponsivecpuprofile](http://www.filedropper.com/ms-mssqlmssql-unresponsivecpuprofile)

**Comment by bestter** [comment]
Me too I got the same issue.

Version: 1.42.1 (user setup)
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:45:59.656Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

Extension ID: ms-mssql.mssql
Version: 1.8.0
[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-mssql/files/4283188/ms-mssql.mssql-unresponsive.cpuprofile.txt)

**Comment by bestter** [comment]
Any news? It's just append to me again. (sorry, no cpuprofile...)

**Comment by PedroArSp** [comment]
Same issue

**Comment by surajbanerjee** [comment]
I cant connect SQL to VS code!
Showingg error:-
mssql: Error: Unable to connect using the connection information provided. Retry profile creation?
mssql: Error 2: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

**Comment by eksortso** [comment]
Reminded to share this with you.
[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-mssql/files/6501895/ms-mssql.mssql-unresponsive.cpuprofile.txt)

**Comment by mattcargile** [comment]
Got this notification too. Here is my cpu profile.

[ms-mssql.mssql-unresponsive.cpuprofile_user.txt](https://github.com/microsoft/vscode-mssql/files/7628869/ms-mssql.mssql-unresponsive.cpuprofile_user.txt)

**Comment by ShakaAmilcar876** [comment]
Got the same notification. Here is my cpu profile
[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-mssql/files/8054798/ms-mssql.mssql-unresponsive.cpuprofile.txt)

**Comment by Evgenius777** [comment]
[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-mssql/files/8445618/ms-mssql.mssql-unresponsive.cpuprofile.txt)
Ubuntu 20.04.4 LTS

**Comment by hrgh74** [comment]
[ms-mssql.mssql-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-mssql/files/8915635/ms-mssql.mssql-unresponsive.cpuprofile.txt)
windows 10

**Comment by kburtram** [comment]
Closing older issue for performance on previous extension version.  Please open a new issue with updated trace files if this is still impacting the current extension.
