### ISSUE TITLE
Incorrect syntax highlight after a comment with single quote character

### ISSUE THREAD

**Issue by johanrex** [microsoft/vscode-mssql#1571]
- MSSQL Extension Version: 1.8.0
- VSCode Version: 1.41.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new sql file in VSCode. 
2. Paste this sql:

```
select 1 --Correct syntax highlight
--Here's a comment that contains single quote character. Notice how it breaks the comment coloring after the single quote character.
select 2 --Incorrect syntax highlight due to the single quote character on previous line. 

```

3. Notice that VSCode sets the wrong comment color after the single quote character. 

Example image of the incorrect syntax highlight. 
https://imgur.com/a/Onyl7k8

**Comment by johanrex** [comment]
Looks like comments in general gets highlighted wrong. Try this sql in a file to see the incorrect syntax coloring:

```
--comment without keywords displays fine.
--comment where sql keywords are present is displayed wrong (where, sql, is are keywords).

```

**Comment by abist** [comment]
This will be fixed in the coming update by https://github.com/microsoft/vscode-mssql/pull/1630

**Comment by gontadu** [comment]
It seems the issue still exists. I've commented on #1630

**Comment by johanrex** [comment]
@gontadu Works correctly for me using:
VSCode 1.43.0
mssql 1.9.0

**Comment by gontadu** [comment]
@johanrex Not sure how. I still have the issue.
