### ISSUE TITLE
Add DECLARE as a highlighted word

### ISSUE THREAD

**Issue by scottsealanddesign** [microsoft/vscode-mssql#1580]
VSCode SQL formatter uses the grammar from here. 
Please add string starting with **DECLARE** as highlighted syntax. The same as **SELECT**. This would allow highlighting for string queries such as 
```
$x = "DECLARE @id AS INT = 10; 
          SELECT  firstName
          FROM person 
          WHERE id = @id"; 
```      
Currently this would not be syntax highlighted. 
Is it as easy as updating line 246 to include declare at the beginning of a string?
https://github.com/microsoft/vscode-mssql/blob/master/syntaxes/SQL.plist

**Comment by abist** [comment]
@scottsealanddesign the `DECLARE` word does get highlighted if it's not in a string, but highlighting keywords inside the string wouldn't be possible, unless I misunderstood what you meant.

**Comment by scottsealanddesign** [comment]
My apologies, maybe this isn't for your team or maybe another team that works on VSCode?
 
When writing PHP in VSCode there is a string of SQL, there is syntax highlighting.  But the highlighting only works if words like SELECT, INSERT, DELETE, UPDATE are the first words in the string, it would be nice if the word DECLARE was also included in whatever check does that. 
![image](https://user-images.githubusercontent.com/18123576/73386341-b196c180-429c-11ea-9399-5f758af6bc8d.png)


aeschli says they use the same grammar as you (see this comment: https://github.com/Microsoft/vscode-mssql/issues/1047#issuecomment-351331517 ) 

So if you just make it somehow that DECLARE works at the start too that would be fantastic. I'm thinking if the right person saw this they would immediately know it's a simple fix, really just adding DECLARE to the same spot that SELECT, INSERT, UPDATE, DELETE are in the code that kickstarts the highlighting.

**Comment by abist** [comment]
@scottsealanddesign Thanks for the clear description of the issue. I work on this project now, and your screenshot helped me understand the issue better. I'll try to get a fix in the next coming release :)

**Comment by scottsealanddesign** [comment]
Any luck on this? I've got colleagues that still insist on breaking out the declare portion of a query and then concatenating the rest to in PHP because they want the syntax highlighting in VSCode. 

```
$query_job_details_mtls =
    "DECLARE	@COMPANY NVARCHAR(8) = ? "; 
$query_job_details_mtls .=
    "   SELECT	jm.PartNum     
                , jm.RelatedOperat...."; 
```
As opposed to: 
```
$query_job_details_mtls =
    "DECLARE	@COMPANY NVARCHAR(8) = ? 
     SELECT jm.PartNum     
                , jm.RelatedOperat.... "; 
```

**Comment by abist** [comment]
@scottsealanddesign This should be fixed in the latest release - https://github.com/microsoft/vscode-mssql/pull/1739/files
