### ISSUE TITLE
Connection string profiles display oddly in quick pick

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1583]
1. Add profile by connection string
2. Open new unconnected query window
3. Try to run query

The item is displaying some internal type information inside the brackets

![image](https://user-images.githubusercontent.com/28519865/73567704-c3eb3980-441b-11ea-885a-7b9448940ef0.png)

**Comment by cheenamalhotra** [comment]
Small display fix taken in PR #17737

**Comment by cheenamalhotra** [comment]
Fix verified
