### ISSUE TITLE
Cancel query button is always enabled

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1584]
This should be disabled when a query isn't currently running

![image](https://user-images.githubusercontent.com/28519865/73567998-5c81b980-441c-11ea-913e-2290ea7ef598.png)

Clicking on it results in this error 

`mssql: Cannot cancel query as no query is running.`

**Comment by abist** [comment]
Since this command is contributed from the `package.json` file, there's no way to show it as "disabled". I can, however, change when it appears on the editor. Would it be better to only show the `Cancel Query` icon if there's a query running?

**Comment by Charles-Gagnon** [comment]
Couldn't you have the run button switch to cancel when it's running?

**Comment by abist** [comment]
@Charles-Gagnon If we are fine with that UX, we can do that. @yualan thoughts?

**Comment by xsoheilalizadeh** [comment]
@Charles-Gagnon's suggestion has good UX, I would like to work on it. This could implement by changing the command icon in runtime, as I investigated for this change we can't do this at this time (I'm not sure), therefore I asked @jrieken, he said they are already [working on it][url]  for May iteration.

[url]:https://github.com/microsoft/vscode/issues/92791
