### ISSUE TITLE
Saving untitled editor with results disassociates results from editor

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1590]
1. Open new untitled editor
2. Run query with results
3. Save file to disk
4. Close editor

Expected : Results window closes
Actual : Results window is still visible

The results window is no longer tied to the editor in general. Re-running the query makes another results pane open and other similar effects.

**Comment by kburtram** [comment]
Closing older issues that aren't on our near-term roadmap.  This is "By Design" since the results document and query document are independently managed by VS Code.
