### ISSUE TITLE
Wiki documentation for customising keyboard shortcuts is out of date

### ISSUE THREAD

**Issue by bjkwang** [microsoft/vscode-mssql#1595]
- MSSQL Extension Version: 1.8.0
- VSCode Version: 1.42.1
- OS Version: Windows 10 1909 (18363.592)

Steps to Reproduce:

1. Follow the tutorial steps shown in https://github.com/Microsoft/vscode-mssql/wiki/customize-shortcuts

**Expected:** Pressing F5 will run a SQL query if a SQL file is open
**Actual:** either we fail to find the `extension.runQuery` entry in default keybindings, or if the snippet was copied to keybindings.json we get `command 'extension.runQuery' not found` when trying it out

All of the mssql extension commands that were previously prefixed with `extension.*` are now prefixed with `mssql.*` instead. I assume the change was intended, so it's just a matter of correcting the extension command names listed in both the tutorial and the "mssql extension commands" section.

**Comment by abist** [comment]
@bjkwang Thanks for opening this issue! I've updated the Wiki page to reflect the new changes in the commands.
