### ISSUE TITLE
Add Option on Table Right-click to Copy Table Name to Clipboard

### ISSUE THREAD

**Issue by Kenobi-the-2nd** [microsoft/vscode-mssql#1624]
Good morning,

I would find it useful if there was an option in the right-click menu of a table to copy the name of the selected table to the clipboard. Below is a screenshot of the existing options in the right-click menu for a table. 

![table_right_click_menu](https://user-images.githubusercontent.com/60623875/75796878-e97ca300-5d39-11ea-8cfb-afaeaea4ebbf.jpg)

Thank-you for your time.

**Comment by abist** [comment]
@Kenobi-the-2nd The coming release will have the ability to copy a node's name by pressing `Ctrl\Cmd + C`

**Comment by Kenobi-the-2nd** [comment]
That would work just as well. Thank-you very much.
