### ISSUE TITLE
Change Connection in an open file

### ISSUE THREAD

**Issue by pwahlmueller** [microsoft/vscode-mssql#1629]
- MSSQL Extension Version: 1.8.0
- VSCode Version: 1.42.1
- OS Version:  Windows 10.0.18362

Steps to Reproduce:

1. Open a new sql file in VSCode
2. Execute the sql - on the first time you are asked for a connection
![grafik](https://user-images.githubusercontent.com/8706955/75860763-a6373880-5dfc-11ea-80d8-1e24d50d12af.png)
3. The connection is now automagically bound to this connection for the next sql command. 

No chance to change the connection.

Suggestion:
Make it possible to see / change the connection.

**Comment by abist** [comment]
@pwahlmueller Thanks for opening this issue. that's a good suggestion. Currently, you can see the connection in the bottom right of the screen on the Status Bar. Clicking it also allows you to change the database of the current connection.

**Comment by pwahlmueller** [comment]
Ok, thought it is only possible to choose the default database there - did not recognize the disconnect in the bottom. So seems there is everything I need. 
Only want to add, that I do not understand to ask "are you  sure you want to disconnect?" - since nothing can happen. But I can handle that.
Thank you!

**Comment by abist** [comment]
@pwahlmueller That button is useful when a user is running a large query but wants to disconnect in the middle of a running query, for example :)
