### ISSUE TITLE
Switch tabs between results windows adds error entry to query history

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1631]
- MSSQL Extension Version: 1.9

Steps to Reproduce:

1. Run several queries
2. Switch back and forth between results windows

Actual: Several error entries get added to query history list even though no queries are being rerun and all the queries were successful.

*All the errors in the below screenshot shouldn't be there*
<img width="1341" alt="Screen Shot 2020-03-05 at 7 34 20 AM" src="https://user-images.githubusercontent.com/599935/75997285-fae9ba80-5eb3-11ea-8654-f37ac13629ab.png">

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/pull/1632
