### ISSUE TITLE
Results slow to render

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#1634]
- MSSQL Extension Version: 1.9.0

This doesn't seem to be a regression, but this still seems unacceptably slow. At the very least it seems like we should try to display a loading icon or something while it's loading. 

![Capture](https://user-images.githubusercontent.com/28519865/76032332-808a5c00-5eee-11ea-9927-301d234c5847.gif)

**Comment by kburtram** [comment]
Closing older issues.  We are refactoring the results grid and will focus on load time optimization as part of that process.
