### ISSUE TITLE
Incorrect SQL Syntax Begin/End Single Quote Textmate Scope

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-mssql#1638]
From @prayforwinter in https://github.com/microsoft/vscode/issues/92112

- MSSQL Extension Version: VSCode built in grammar
VSCode Version: 1.43.0-insider
OS Version: Windows 10 Enterprise 1903

1. Create a SQL syntax document. 
2. Enter SQL syntax containing single quotes: 
```SQL
SELECT * FROM dbo.Person
WHERE firstname = 'Ashleigh'
-- example: in the Nord theme the above opening quote is white, closing is green
ORDER BY birthdate DESC
```
3. Launch Developer: Inspect Editor Tokens and Scopes from the Command Palette.
4. Navigate cursor to left side of either single quote.
5. Note incorrect/missing begin/end single quote textmate scope.

**Actual:** 
Opening single quote scope reads _punctuation.definition.string.end.sql_ and the closing single quote *does not* have a textmate scope.

**Expected:**
Opening single quote textmate scope reads _punctuation.definition.string.begin.sql_ and closing single quote textmate scope reads _punctuation.definition.string.end.sql_

**Screenshot:**
https://i.imgur.com/RUjU07W.png

Does this issue occur when all extensions are disabled?: Yes

**Comment by abist** [comment]
This will now be fixed in the coming update by https://github.com/microsoft/vscode-mssql/pull/1630
