### ISSUE TITLE
Add script as context menu entries for triggers

### ISSUE THREAD

**Issue by LeonarddeR** [microsoft/vscode-mssql#1652]
- MSSQL Extension Version: 1.9
- VSCode Version: 1.43.0
- OS Version: Windows 10 1909

## Steps to Reproduce

1. In the SQL Server tree view, select a table trigger
2. Perform a right mouse click

## Expected
Script as options to create, alter, drop the trigger

## Actual
Only the refresh option is available.

**Comment by kburtram** [comment]
This has been added in the current version of the extension.

![image](https://github.com/user-attachments/assets/ebaeddd8-2488-4856-8d52-634127676b32)
