### ISSUE TITLE
'\' causes Syntax highlighting to fail

### ISSUE THREAD

**Issue by nmunday** [microsoft/vscode-mssql#1653]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.43.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create new SQL file and enter:
DECLARE @i INT = CHARINDEX('\\', 'Foo');
DECLARE @another INT = 0;

**Comment by abist** [comment]
This should be fixed in the coming release.
