### ISSUE TITLE
Nested SQL block comments not tokenized correctly

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-mssql#1654]
From @Conbhair in https://github.com/microsoft/vscode/issues/92078

Issue Type: <b>Bug</b>

Open a new tab, change the language to SQL and paste the following:
```sql
/*
    /*
        SELECT 'hello1'
    */
    SELECT 'hello2'
*/

SELECT 'hello3'
```
If the formatting was correct, the hello2 line would also be green however it is displaying as if it's uncommented (when it's not). The only uncommented (non green) line here should be the last one with 'hello3'

If you copy and paste the code I provided into SSMS, the formatting is different to how it is being displayed. If you also execute the code in SSMS, the only result you get back is 'hello3'. The issue i've raised isn't about the code being correct, it's the formatting display for SQL language which clearly shows SELECT 'hello2', and the second `*/`, as being not being commented whereas they are actually commented.

In SSMS (with results):
![Issue 92078 example](https://user-images.githubusercontent.com/5824259/75987546-ffc86180-5ee7-11ea-9928-39c6ebd11d27.PNG)

In Visual Studio Code:
![Issue 92078 example 2](https://user-images.githubusercontent.com/5824259/75987610-18387c00-5ee8-11ea-9eb2-1a50cf13c3f9.PNG)

VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:45:59.656Z)
OS version: Windows_NT x64 10.0.18362

**Comment by alexr00** [comment]
Looks like the grammar GitHub uses has the same issue.

**Comment by abist** [comment]
@alexr00 Hey, thanks for opening the issue! We have this problem being tracked here - https://github.com/microsoft/vscode-mssql/issues/1014. I'm going to go ahead and close this issue as duplicate.
