### ISSUE TITLE
Ctrl+Shift+E does not work

### ISSUE THREAD

**Issue by async84** [microsoft/vscode-mssql#1655]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.43.1
- OS Version: Linux Mint 19.3 x64
- SQL Server 2019

Steps to Reproduce:

1. Write any code, then write GO
2. press Ctrl+Shift+E

The code does not execute, it simply prints the letter 'e' to the screen.

Possible solution: change the shortcut.

**Comment by abist** [comment]
@async84 Thanks for reporting this issue. Could you open your Developer Console and see if there are any errors there? You can go to `Help` -> `Toggle Developer Tools`or `Ctrl + Shift + I` -> `Console` tab to see if there are any errors there. If there are, could you please copy paste them here?

**Comment by async84** [comment]
I have also noticed the Ctrl + Shift + I does'nt work, this may be a vs code issue not an extension issue. Error list below:

abstractExtensionService.ts:400 [ms-vscode.powershell]: Command `workbench.action.debug.start` appears multiple times in the `commands` section.
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///snap/code/27/usr/share/code/resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///home/darren/.vscode/extensions/ms-mssql.mssql-1.9.0/syntaxes/SQL.plist
register @ TMScopeRegistry.ts:45
console.ts:137 [Extension Host] Git installation not found.
t.log @ console.ts:137
extensionHost.ts:211 Extension Host
extensionHost.ts:212 Debugger attached.
log.ts:191  WARN UNRESPONSIVE extension host, 'ms-mssql.mssql' took 99% of 824.371ms, saved PROFILE here: '/tmp/exthost-191588.cpuprofile' Array(3)
console.ts:137 [Extension Host] logFile for SqlToolsResourceProviderService is /home/darren/.config/Code/logs/20200324T141738/exthost1/ms-mssql.mssql/resourceprovider.log
console.ts:137 [Extension Host] This process (ui Extenstion Host) is pid: 15128
console.ts:137 [Extension Host] Old log files deletion report: {}
console.ts:137 [Extension Host] [vscode-icons] v10.0.0 activated!
console.ts:137 [Extension Host] Event[file] 1 - /home/darren/.config/Code/User/settings.json
console.ts:137 [Extension Host] Event[file] 1 - /home/darren/.config/Code/User/settings.json
DevTools failed to parse SourceMap: https://ticino.blob.core.windows.net/sourcemaps/fe22a9645b44368865c0ba92e2fb881ff1afce94/core/vs/loader.js.map

**Comment by abist** [comment]
@async84 You're right, that's a vscode issue. From the logs, I don't see any errors regarding this.
