### ISSUE TITLE
Double backslash in string messes up syntax highlighting

### ISSUE THREAD

**Issue by atorres76** [microsoft/vscode-mssql#1657]
Issue Type: <b>Bug</b>

The following Transact-SQL is highlighted incorrectly in Visual Studio Code.

declare @path varchar(10) = '\\server\path\'
select @path
select 1
select 2
select 3

Everything after the final backslash is colored as if it were all a string. The backslashes and the character immediately following them are yellow. The entire string should be one color and end at the final single quote. It seems that the interpreter is treating the backslash as an escape character. The backslash is not an escape character in Transact-SQL.

Extension version: 1.9.0
VS Code version: Code 1.43.1 (fe22a9645b44368865c0ba92e2fb881ff1afce94, 2020-03-18T07:01:20.184Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.84GB free)|
|Screen Reader|no|
|VM|40%|
</details>

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/pull/1701
