### ISSUE TITLE
Cascade comments breaks highlighting

### ISSUE THREAD

**Issue by micek-petr** [microsoft/vscode-mssql#1658]
Issue Type: <b>Bug</b>

Code example:
-- all the following code is inside a top-level comment --
/*   -- top-level comment begin --
  SELECT object_id
  FROM sys.objects
  WHERE (name LIKE N'sysmail%')
      /* AND (name != N'sysmail_allitems')*/      -- << -- this inner comment breaks the highlighting --
  ;
  -- following code should be part of the comment but is highlighted as out-of-comment code --
  SELECT state = N'succeeded';

*/  -- top-level comment end --

Extension version: 1.9.0
VS Code version: Code 1.43.2 (0ba0ca52957102ca3527cf479571617f0de6ed50, 2020-03-24T07:38:38.248Z)
OS version: Windows_NT x64 10.0.18363

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/pull/1701

**Comment by micek-petr** [comment]
Anyone there?
