### ISSUE TITLE
Error connecting to server "localhost:1433"

### ISSUE THREAD

**Issue by yalamandarao** [microsoft/vscode-mssql#1661]
Error connecting to server "localhost:1433". Details: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)

Using Mac OS and Visual Studio Code.

**Comment by abist** [comment]
@yalamandarao Thanks for opening this issue. Were you trying to select to a local SQL Server? What version of macOS is it? How do you try to connect to your server? It would be great if you added some details to help us track this down.

**Comment by KrishnaPravin** [comment]
@yalamandarao don't use `localhost:1433`. Use `localhost,1433`
