### ISSUE TITLE
Data rows in the tables (output result) is empty when the number of tables (output) is huge.

### ISSUE THREAD

**Issue by smshafa** [microsoft/vscode-mssql#1664]
Issue Type: <b>Bug</b>

I run a SQL command with approximately 40 result tables in the output window. When I scroll down the Results window, the last tables' data are not shown.
![Last table results](https://user-images.githubusercontent.com/24754063/78869405-cd1b0700-7a59-11ea-8001-754fffddd9c0.JPG)

Extension version: 1.9.0
VS Code version: Code 1.44.0 (2aae1f26c72891c399f860409176fe435a154b13, 2020-04-07T23:31:18.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by abist** [comment]
@smshafa This is an issue which is caused when there are a lot of results. If you click on a certain result or hover over it, they should appear. However, this is a valid issue.

**Comment by ReeceGoding** [comment]
I can confirm that this bug still exists. The fix of clicking on certain results doesn't work because this bug causes no results to show. Although you can see the columns, clicking on them does not make the rows appear.
