### ISSUE TITLE
[Feature Request] Results pane opening behavior

### ISSUE THREAD

**Issue by jfcarr** [microsoft/vscode-mssql#1665]
When you execute a query, the results window opens to the right of the SQL editor (by default).  This is controlled by the "Open Side By Side" setting under Workbench > Editor Management.  This is a global setting.  It controls how all side-by-side editors are opened.  I find the default behavior of opening to the right to be preferable for most file types, but for SQL, the results are more readable if they open down, instead of right.

It would be nice to have a mssql-vscode specific setting to control the default placement of the results window.

Steps to Reproduce:

1.  Open SQL text in the editor.
2.  Execute it.
3.  Results appear to the right.

**Comment by SP-SuperPoney** [comment]
Currently a show stopper for me.
Every tools I know whcih execute SQL queries display theresult at the bottom !

**Comment by systematical** [comment]
Unless I am misunderstanding you guys, you can do this. View > Editor Layout > Split Down. I agree... I run one monitor vertically so opening to the side would be a no-go for me as well. Once I saved a workspace with this option it always opens like this 100%, I haven't had to mess with it since I installed mssql.

**Comment by simon-curtis** [comment]
I don't the OP wants every pane to split down, just the MSSQL one.

Horizonal split isn't too bad for low column count queries but here's an example of 16 columns , VSCode (MSSQL Extension) vs SSMS

![image](https://user-images.githubusercontent.com/43214378/89530270-2287da80-d7e6-11ea-8f29-f4ceaf2a8ebb.png)

![image](https://user-images.githubusercontent.com/43214378/89530697-d8532900-d7e6-11ea-8daf-d1c735f8e936.png)

**Comment by systematical** [comment]
> I don't the OP wants every pane to split down, just the MSSQL one.
> 
> Horizonal split isn't too bad for low column count queries but here's an example of 16 columns , VSCode (MSSQL Extension) vs SSMS
> 
> ![image](https://user-images.githubusercontent.com/43214378/89530270-2287da80-d7e6-11ea-8f29-f4ceaf2a8ebb.png)
> 
> ![image](https://user-images.githubusercontent.com/43214378/89530697-d8532900-d7e6-11ea-8daf-d1c735f8e936.png)

All of my results do show up vertically just like SSMS. I updated my comment with a picture of what mine looks like. I think VS Code can already do what they are asking for (unless I'm not getting what they are asking).

**Comment by simon-curtis** [comment]
@systematical that's fine for when you are using the MSSQL extension. But we don't want this to be the default behaviour for  the whole IDE

**Comment by systematical** [comment]
Alright that makes sense, and I agree with you guys in that case. I do also use it for Python and it puts the output at the bottom as well so I guess I haven't seen it put results anywhere other than vertically and on the bottom after I changed that setting.

**Comment by abist** [comment]
I looked into this issue and looks like it's upstream. VSCode doesn't give extensions the ability to split the editor in it's own way, and we need to follow the VSCode setting for it.

**Comment by Matthew-Hiebing** [comment]
Any update on this?

**Comment by landkid15** [comment]
> ![15967212340167110399535977800971](https://user-images.githubusercontent.com/65402632/89538837-aa5aee00-d7c0-11ea-8d52-95b649f17f1a.jpg)
> Unless I am misunderstanding you guys, you can do this. View > Editor Layout > Split Down. I agree... I run one monitor vertically so opening to the side would be a no-go for me as well. Once I saved a workspace with this option it always opens like this 100%, I haven't had to mess with it since I installed mssql.

does postgreSQL works with that?  It begins to display in a new window after the first time.

**Comment by Benjin** [comment]
We've introduced a new query results pane at the bottom of the window in 1.25.  Please give it a go!
