### ISSUE TITLE
problem with single quote

### ISSUE THREAD

**Issue by ccarlos12** [microsoft/vscode-mssql#1666]
Issue Type: <b>Bug</b>

I have a problem with the color of the text when I use '
if i white a text with \\ in single quotes the color is desconfigured in the text. i use it in sql lenguajes 

for example  select * from table where col1='\\asd' and col2=2
fron the and word, the color change like a text in single quote 

Extension version: 1.9.0
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
@abist This has been reported in ADS as well https://github.com/microsoft/azuredatastudio/issues/10208

and is also currently broken in VS Code insiders.

Are you investigating this?

![image](https://user-images.githubusercontent.com/28519865/81001388-7f957e00-8dfc-11ea-85da-a88726b8293c.png)

**Comment by abist** [comment]
@Charles-Gagnon Yes, I'm looking at it right now
