### ISSUE TITLE
Command to flip connection within the file

### ISSUE THREAD

**Issue by flogger007** [microsoft/vscode-mssql#1669]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.43.2
- OS Version: Win10 enterprise 1903

This is an enhancement request similar to #1629. Not sure if this is supported already. Could not find it in documents. 
When we are connected to any connection, this works for the full file unless we hit the button at the bottom. We should have a command line to change the connection using the saved profile name within the same file.

Thanks
Ashish

**Comment by abist** [comment]
@flogger007 You can use the command `MS SQL: Use Database` command from the command palette to do this.
