### ISSUE TITLE
Cannot add a new connection on Mac

### ISSUE THREAD

**Issue by garrypas** [microsoft/vscode-mssql#1670]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.44
- OS Version: Mac Catalina

Steps to Reproduce:

1. Install SQL Server (mssql) in VS Code
2. Click the "Add connection" button (top right corner, see attachment).
3. Nothing happens, no feedback, no error, nothing.

![Screenshot 2020-04-29 at 09 56 11](https://user-images.githubusercontent.com/5046018/80579816-8c802f00-8a02-11ea-99cc-fde654117b21.png)

Also note my MS SQL instance is running in a docker container. Can connect from terminal with sqlcmd.

**Comment by garrypas** [comment]
This is what I get when toggling developer tools...

![image](https://user-images.githubusercontent.com/5046018/80580775-0369f780-8a04-11ea-8913-a19691577089.png)

**Comment by abist** [comment]
@garrypas Thanks for opening the issue. This seems like an error because of your bash file. Could you try this suggested solution here - https://unix.stackexchange.com/questions/544837/bash-uname-command-not-found
Make sure you have all the dependencies installed properly.

**Comment by garrypas** [comment]
`sh -c uname` and `bash -c uname` both work as expected.

I ran ls -l /usr/bin/uname and got this:

`-rwxr-xr-x  1 root  wheel  31552  6 Apr 21:46 /usr/bin/uname`

When you say dependencies, do you mean tools I'm missing on my OS? Is there anything in particular I should be looking for?

**Comment by garrypas** [comment]
Interestingly when I `ls ~/.vscode/extensions/` I see no extension being installed after removing/installing it through the extensions plugin of VSCode.

**Comment by garrypas** [comment]
CMD + P -> Add Connection gives this:

(command 'mssql.addObjectExplorer' not found)

**Comment by garrypas** [comment]
Issue on my machine. For anyone who sees similar I found that something else unrelated had messed around with my PATH variables, which meant /usr/bin was not in there. Hence the error message.

**Comment by abist** [comment]
@garrypas Glad you could work it out!

**Comment by mrkskwsnck** [comment]
I'm experiencing the same issue on my machine.

- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.51
- OS Version: Linux Mint 20

The error message says:

> Command 'MS SQL: Add Connection' resulted in an error
> (command 'mssql.addObjectExplorer' not found)

What exactly was the fix?
