### ISSUE TITLE
Syntax Colorizations misread CHARINDEX('\')

### ISSUE THREAD

**Issue by aaronostlund** [microsoft/vscode-mssql#1680]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.45.0
- OS Version: Windows 10 Version	10.0.17134 Build 17134

Steps to Reproduce:

1. Create text/code block to demonstrate syntax colorization
2. Insert CHARINDEX('\') before or in the middle of the block
3. Note that the colorizations to not consider the '\' string closed.

CHARINDEX('\') returns the correct character identifier when run but does not color accordingly in mssql.

**Comment by aaronostlund** [comment]
The text editor shows how tricky this issue is by sabotaging my text. Everywhere that it shows CHARINDEX('') should have a backslash enclosed by the single quotes.

**Comment by SJMakin** [comment]
This issue is driving me nuts.  Stopping me using the extension.  See fix was attempted in #1630 and rolled back.  Going to see if I can crack it! @abist have you made any progress on it since rollback?

**Comment by abist** [comment]
@SJMakin Like you rightly pointed out, the fix was rolled out because it broke other key scenarios. I haven't worked on this since yet, but I'll make it a priority.

**Comment by SJMakin** [comment]
@abist Thanks.  It is a suprisingly common occurance due to the `charindex` use - parsing user names for exmaple.  Debugging now.  Looks like your original commit wasnt far off at all.  Hoping I can contribute/help :)

**Comment by SJMakin** [comment]
@abist Please can you review #1701?

**Comment by abist** [comment]
@SJMakin Thanks for opening the PR! I'm going to look at it tonight and do some testing and hopefully get this shipped if it all looks good!

**Comment by jeffhebrank** [comment]
What happened to this? Its still breaking for me and I see there hasn't been any activity on the PR for a month....
