### ISSUE TITLE
A11y_mssql for VSCode_ Select top 1000 Results window_Screenreader:  After pressing Ctrl+Alt+R key for expand and collapse result menu, NVDA announce wrong status.(Reads R R R R)

### ISSUE THREAD

**Issue by harshgangrade111** [microsoft/vscode-mssql#1685]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 
 
**GitHubTags**: #A11y_mssql for VSCode Object Explorer;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp; #MAS1.3.1;#Narrator;#Win10;#Visual Studio Code;#mssql for VSCode;#NVDA;#JAWS;#FTP; #SH_OBjectExplorer_MAY2020;#Benchmark; #STP;

**Environment Details:**
Application Name: mssql for VSCode Object Explorer
Windows Version: Windows10
Screen Reader: NVDA, JAWS 2020

**Repro Steps:** 

1. Open Visual studio code 
2. Click on extension button and search for "mssql"
3. Click on install and move to the SQL Server button
4. Click on Add Connection Button and insert the valid credentials
5. after adding the server move to database expand it -->System database expand-->Master expand-->Tables expand -->System table expand and right click on it and select top 1000 option
6. Select top 1000 window will open navigate to Resluts window
7. Start NVDA and press Ctrl+Al+R  key.

**Actual:**

After pressing Ctrl+Alt+R key for expand and collapse result menu, NVDA announce wrong status. (Reads R R R R)

**Same issue is also observed with Message Window.**
**Same Issue is also observed with JAWS.**

**Expected:**

After pressing Ctrl+Alt+R key for expand and collapse result menu, NVDA should announce expand result and collapse result. It should not announce wrong content.

**User Impact:**

Screen reader user will not receive correct status of the expand and collapse result menu.

**Attachment link for Reference:**
[1685_A11y_mssql for VSCode Object Explorer_ Select top 1000 Results window_Screenreader.zip](https://github.com/microsoft/vscode-mssql/files/4686666/1685_A11y_mssql.for.VSCode.Object.Explorer_.Select.top.1000.Results.window_Screenreader.zip)

**Comment by abist** [comment]
Please use the following build to verify - https://mssqltools.visualstudio.com/_apis/resources/Containers/2339179/drop?itemPath=drop%2Fmssql-1.9.0.vsix

**Comment by Roopesh-T** [comment]
@abist the above issue is still repro in the latest environment. 
![image](https://user-images.githubusercontent.com/86601127/218411287-7ca58946-fb00-4897-9e36-40aec71ba970.png)
and the link of vsix you provided is not working.
please reopen the bug.

![1685_Repro](https://user-images.githubusercontent.com/86601127/218411994-50c9ed88-a962-4368-b091-8ad43129f568.gif)

**Comment by BhanuPrakashGit** [comment]
@abist Could you please reopen the bug as it is not fixed.
Verified the bug in the environment: 
Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Bug is not fixed and still repro'ing.
PFA for reference

[1685_Reopened.zip](https://github.com/microsoft/vscode-mssql/files/10722185/1685_Reopened.zip)

**Comment by alanrenmsft** [comment]
@BhanuPrakashGit I have fixed the issue, now when using the shortcut keys, the state change will be announced by NVDA. please verify the fix using this build: https://microsoft-my.sharepoint.com/:u:/p/alanren/EYrDnf2Aj7dPvpMAaKi8MxwBZQsvPMCsO144WRb8wEwwbA?e=IauKx9

**Comment by alanrenmsft** [comment]
@BhanuPrakashGit  ping...

**Comment by fsteffi** [comment]
verified in 
Version: 1.77.0-insider (user setup)
Commit: bbc87d8ec2453f12c0066e1c30b41cd5bd2aa021
Date: 2023-03-07T05:23:49.023Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.25300
Sandboxed: Yes

states are read only for the first time
[Video 3-07 at 17.00.webm](https://user-images.githubusercontent.com/24580570/223410409-eed146d9-0f8c-49ea-b3d2-8df5cdad4b51.webm)

**Comment by alanrenmsft** [comment]
@fsteffi 
I tried with latest vscode-mssql extension and below is the screen reader recording, as you can see, when I use the shortcut keys to expand/collapse the section, the state change events are getting announced properly. please retry.

![mssql-keyboard](https://github.com/microsoft/vscode-mssql/assets/13777222/936a33ca-6c9e-4ba8-8312-49374d221f35)

**Comment by Roopesh-T** [comment]
Issue not repro in Version: 1.79.0-insider (user setup) so closing the bug.

**GitHubTags** : #Closed;#Regressed:05-18-23
![1685_no repro](https://github.com/microsoft/vscode-mssql/assets/86601127/56d3a044-55af-41f7-9e31-e7c7e8a12e2b)

**Comment by alanrenmsft** [comment]
close issue as requested by the accessibility team.
