### ISSUE TITLE
A11y_mssql for VSCode_ Message Window_Keyboard: Message window does not expand and collapse with the help of keyboard and shortcut key(Ctrl+alt+Y).

### ISSUE THREAD

**Issue by harshgangrade111** [microsoft/vscode-mssql#1687]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 

**GitHubTags:**#A11y_mssql for VSCode; #A11ySev2; #A11yTCS; #A11yMAS; #DesktopApp;#MAS2.1.1;#Win10;#mssql for VSCode;#Keyboard;  #FTP; #BM_MSSQL_MAY2020; #Benchmark;
 
**Environment Details:**
Application Name: mssql for VSCode

Screen Reader: NVDA, JAWS 2020

**Repro Steps:** 

1. Open Visual studio code 
2. Click on extension button and search for "mssql"
3. Click on install and move to the SQL Server  button
4. Click on Add Connection Button and insert the valid credentials
5. Right click on the server/database node you want to run the new query on.
6. Click on “New Query” write any valid query and click on "Execute query button"
7. Message Window will open
8. Press enter for expand and collapse the message window or use shortcut key (Ctrl+Alt+y).

**Actual:**

Message window does not expand and collapse with the help of keyboard and shortcut key (Ctrl+alt+Y).

**Same issue is not observed when “Select top 1000 Results window” Window Open.**

**Expected:**

Message window should be accessible with the help of keyboard and when we performing action on it ,it will be expand or collapse also with the help of Shortcut key it will also expand or collapse. 

**User Impact:**

Keyboard users will face problem when they want to expand or collapse the message window.

**Attachment link for Reference:**

[1687_A11y_mssql for VSCode_ Message Window_Keyboard.zip](https://github.com/microsoft/vscode-mssql/files/4687324/1687_A11y_mssql.for.VSCode_.Message.Window_Keyboard.zip)

**Comment by abist** [comment]
Please use the following build to verify - https://mssqltools.visualstudio.com/_apis/resources/Containers/2339179/drop?itemPath=drop%2Fmssql-1.9.0.vsix

**Comment by BhanuPrakashGit** [comment]
@abist Please reopened this bug as it should be verified and closed by Trusted Tester only.
Tried to verify this issue but getting below error. Could you please share the latest build so that we can verify and take action accordingly.
GithubTags: #Regressed:03-02-23;

![image](https://user-images.githubusercontent.com/104351566/216572274-6c8c21da-7fef-4c4f-8e24-6060cbb814e7.png)

**Comment by Charles-Gagnon** [comment]
@kburtram FYI Alan and I are following up separately with the a11y team to help them resolve these connection issues.

**Comment by BhanuPrakashGit** [comment]
**GithubTag:**#Closed;
Verified the bug in the environment: Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

Bug is fixed and does not repro. Hence Closing the bug.
PFA for reference
[1687_Closed.zip](https://github.com/microsoft/vscode-mssql/files/10719287/1687_Closed.zip)
