### ISSUE TITLE
A11y_mssql for VSCode_ Query History_Keyboard: After expand the “More Action” Button and press ”Esc” key for collapse the more action button keyboard focus is not in logical order.

### ISSUE THREAD

**Issue by harshgangrade111** [microsoft/vscode-mssql#1689]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 

GitHubTags:#A11y_mssql for VSCode Object Explorer; #A11ySev2; #A11yTCS; #A11yMAS; #DesktopApp; #MAS2.4.3; #Win10; #mssql for VSCode; #FocusOrder;#keyboard; #FTP; #Benchmark;
 
**Environment Details:**
Application Name: mssql for VSCode

Screen Reader: NVDA, JAWS 2020

**Repro Steps:** 

1. Open Visual studio code 
2. Click on extension button and search for "mssql"
3. Click on install and move to the SQL Server  button
4. Click on Add Connection Button and insert the valid credentials
5. Right click on the server/database node you want to run the new query on.
6. Click on “New Query” wirte any valid query and click on "Execute query button"
7. in the left panel Query History window will appears
8. Navigate to "More Action" button and perform action.

**Actual:**

After expand the “More Action” Button and press ”Esc” key for collapse the more action button keyboard focus is not in logical order.

**Expected:**

Keyboard focus should remain constant om the “More Action” button from where have started to perform action.Keyboard focus should move back on the ‘More action” button after pressing “Esc” key.

**User Impact:**

Keyboard user will get confused because keyboard focus is not in logical order.

**Attachment link for Reference:**

[1689_A11y_mssql for VSCode_ Query History_Keyboard.zip](https://github.com/microsoft/vscode-mssql/files/4687450/1689_A11y_mssql.for.VSCode_.Query.History_Keyboard.zip)

**Comment by abist** [comment]
The focus stays if the actions is taken via the keyboard, but isn't present when it's performed by clicking it, by design. This is also an upstream issue.

**Comment by harshgangrade111** [comment]
@abist Please assign bugs for validation to the tester who has created this bug after that only bug should be close

**Comment by hannahqin** [comment]
Updated in conformance doc

**Comment by Roopesh-T** [comment]
**GitHub Tag**:#Closed;
Above issue is not repro in environment, so closing the bug.
![image](https://user-images.githubusercontent.com/86601127/218417661-fc88be78-ffb2-4358-9162-0dbbf2e0d4d8.png)
![1689_Closed](https://user-images.githubusercontent.com/86601127/218417725-12e1927b-a564-401e-96db-629ab5cb4308.gif)

**Comment by BhanuPrakashGit** [comment]
**GithubTags:**#Closed;

PFA for reference
[1689_Closed.zip](https://github.com/microsoft/vscode-mssql/files/10722363/1689_Closed.zip)
