### ISSUE TITLE
Can't connect to 'localhost' server

### ISSUE THREAD

**Issue by Pomidorka1234** [microsoft/vscode-mssql#16915]
- MSSQL Extension Version: 1.10.0
- VSCode Version: 1.52.1
- OS Version: Windows 10 Pro 2004 (64 bit)

Steps to Reproduce:

1. I've followed this tutorials & issues: https://docs.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver15
https://github.com/microsoft/vscode-mssql/issues/1069
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-troubleshooting-guide?view=sql-server-ver15

Though I don't have Linux.
I don't have MSSQL from https://www.microsoft.com/en-us/sql-server/sql-server-2019 either.
Is that the problem?
 
2. I have followed the tutorial (in the first link) with 'localhost' name, but id didn't work out.
Then I searched for similar issues [here.](https://github.com/microsoft/vscode-mssql/issues)
And found that if I write (localhost:1401) or (localhost:5500) as a server name id does add a new connection 
![image](https://user-images.githubusercontent.com/72037282/102699185-85d15100-424b-11eb-9460-e5152f08d499.png)
![image](https://user-images.githubusercontent.com/72037282/102699205-a5687980-424b-11eb-8219-1e43fdc0c2db.png)

So that the following error comes out...
![image](https://user-images.githubusercontent.com/72037282/102699210-b87b4980-424b-11eb-9000-79fd31570cc2.png)

**Comment by Pomidorka1234** [comment]
If you need more details, I can give them right away

**Comment by cssuh** [comment]
Hi, please try setting your `"trustServerCertificate": true` under `options` as referenced by this issue: https://github.com/microsoft/vscode-mssql/issues/1806

**Comment by Pomidorka1234** [comment]
Thanks, I tried that and I got pretty much the same result
![image](https://user-images.githubusercontent.com/72037282/102838176-3edb8b00-4406-11eb-8496-c8dfaffbffda.png)
![image](https://user-images.githubusercontent.com/72037282/102838193-4864f300-4406-11eb-806d-414fc1477966.png)
Inside settings.json

**Comment by Pomidorka1234** [comment]
![image](https://user-images.githubusercontent.com/72037282/102838217-54e94b80-4406-11eb-8f1c-3b8a51f58e2a.png)

**Comment by Pomidorka1234** [comment]
Should I be using MSSQL installed on my pc?
Because I don't have MySQL nor MSSQL or anything like that

**Comment by cssuh** [comment]
Hi, can you check to see if you can connect to your server using SSMS?

**Comment by Pomidorka1234** [comment]
Do I need SSMS?
I installed it...

**Comment by cssuh** [comment]
You don't need it the vscode-mssql extension will function without it - this is just a troubleshooting step to see whether you are able to connect to your SQL Server using other means.

**Comment by Pomidorka1234** [comment]
Thanks, though I don't have enough memory for installation, and clearing it won't help either...

**Comment by Pomidorka1234** [comment]
![image](https://user-images.githubusercontent.com/72037282/102918063-f2885d80-448e-11eb-8873-006e4013d9fa.png)
This is what I tried to do
I clicked 'refresh' on reconnect and that's what I got
![image](https://user-images.githubusercontent.com/72037282/102918121-07fd8780-448f-11eb-8df2-479d03a3c09e.png)

**Comment by dzsquared** [comment]
Hi @Pomidorka1234 - it sounds like you don't have mssql/SQL Server installed - the server engine that this extension for VS Code connects to.
One way to get setup on Windows 10 is to install Docker Desktop and run SQL in a container: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-powershell

**Comment by Pomidorka1234** [comment]
shit doesn't work

**Comment by kburtram** [comment]
@Pomidorka1234 did you install SQL Server on Docker or as a Windows Service?   If you installed as a Windows Service then the default port would be 1433.  On Docker the port will be whatever was exposed in the `docker run` command with -p parameter.

Based on previous comments it appears you may be using docker with port 5500?  In this case, it is likely that you don't have Windows Active Directory authentication enabled between your Windows localhost and the Docker guest Linux OS.  In this case, it is likely that you want to try to use SqlLogin with the username `sa` and whatever password you provided when launching the Docker container.  Hope that helps point you in the right direction.

**Comment by Pomidorka1234** [comment]
@kburtram, I don't have SQL Server, no Docker, nor do I have Linux OS.
And I got the idea to write the 5500 port from 'Live Server' extension in Visual Studio Code, it was also connecting via 127.0.0.1,5500 port form 'Live Server'.

**Comment by IlCallo** [comment]
Experiencing the same problem here on Linux, receiving this error even after having added `trustServerCertificate` option:

```
mssql: Connection error : A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```

**Comment by kburtram** [comment]
@Pomidorka1234 thanks for the additional context.  I'm not sure about the vscode Live Server but it appears to be a mechanism for running an HTTP server during web development.  This extension is for connecting to SQL Server databases, so a connection to an HTTP port won't work due to protocol mismatch.  Please let us know if you are having difficulty working with a SQL Server database.  Otherwise, I would recommend following up on the Live Server repo if you believe there is an issue with that extension https://github.com/ritwickdey/vscode-live-server.

**Comment by Pomidorka1234** [comment]
@kburtram Thanks, I will try to continue...
I don't have too much memory btw, though that's a big problem I think there should be a solution to my problem I just might be lazy or can't figure it out.
