### ISSUE TITLE
Object Explorer hangs when clicking open a server

### ISSUE THREAD

**Issue by columbaspexit** [microsoft/vscode-mssql#16914]
- MSSQL Extension Version: 1.10
- VSCode Version: 1.52.1
- OS Version: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open Object/Server Explorer pane
2. Click on the down arrow for an integrated-authentication v15.0.20000.5 server 
3.  Observe infinite spinnng dot-dot-dot circle thingy instead of the usually-expected Database/Security/Server Objects folders

This is a new issue for me after the 1.10 upgrade. If I revert to 1.9, the issue goes away. I can have a SQL file open and connected to the server just fine, scripts run, I just can't see it in object explorer. Also, I only have three servers I connect to, so not many opportunities to test it, but the issue only happened with the above specific server; both an older integrated-auth server (v11.0.6260.1) & a SQL-auth server (v11.0.6020.0) show up just fine in object explorer. 

ETA: Neither deleting/recreating the connection profile, nor adding  `"trustServerCertificate": true` to the profile as referenced in issue [#1806](https://github.com/microsoft/vscode-mssql/issues/1806), makes a difference.

![spinningDOOM](https://user-images.githubusercontent.com/8880052/102573618-6fdd5800-40b4-11eb-84a3-828ad51c8571.png)

**Comment by cssuh** [comment]
Hi, if you open the developer tools (using `Control + Shift + P`), do you see any error messages?  Does this happen after you've left the window open for some time or immediately after opening mssql?

**Comment by columbaspexit** [comment]
G'morning! So today after reinstalling the 1.10 version of mssql...

Just after opening up vscode, the first error below comes up in developer tools. 
After waiting a few minutes, trying to connect via clicking on the profile in Object Explorer still only results in the infinitely-spinning circle, no errors. However, the second error below comes up when trying to connect via `Ctrl + Shift + C` to the problematic profile (chervil). Also noticed that old/deleted connection profiles for chervil appear in the profile list from `Ctrl + Shift + C` and clicking on THOSE profiles connect successfully. However, these profiles do not show up in either Object Explorer, or in setting.json.


First error after opening VSCode:
> console.ts:137 [Extension Host] (node:16616) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> t.log @ console.ts:112
> $logExtensionHostMessage @ remoteConsoleUtil.ts:11
> _doInvokeHandler @ rpcProtocol.ts:396
> _invokeHandler @ rpcProtocol.ts:330
> _receiveRequest @ rpcProtocol.ts:269
> _receiveOneMessage @ rpcProtocol.ts:208
> (anonymous) @ rpcProtocol.ts:90
> fire @ event.ts:525
> fire @ ipc.net.ts:449
> _receiveMessage @ ipc.net.ts:785
> (anonymous) @ ipc.net.ts:642
> fire @ event.ts:525
> acceptChunk @ ipc.net.ts:191
> (anonymous) @ ipc.net.ts:191
> t @ ipc.net.ts:925
> emit @ events.js:223
> addChunk @ _stream_readable.js:309
> readableAddChunk @ _stream_readable.js:290
> Readable.push @ _stream_readable.js:224
> onStreamRead @ internal/stream_base_commons.js:181


Second error, comes up when trying to connect to a server via `Ctrl + Shift + C`:
> notificationsAlerts.ts:40 mssql: Failed to connect: System.InvalidOperationException: Cannot set the AccessToken property if the 'Integrated Security' connection string keyword has been set to 'true' or 'SSPI'.    at Microsoft.Data.SqlClient.SqlConnection.CheckAndThrowOnInvalidCombinationOfConnectionOptionAndAccessToken(SqlConnectionString connectionOptions)    at Microsoft.Data.SqlClient.SqlConnection.set_AccessToken(String value)    at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection..ctor(String connectionString, RetryPolicy connectionRetryPolicy, RetryPolicy commandRetryPolicy, String azureAccountToken) in D:\a\1\s\src\Microsoft.SqlTools.ManagedBatchParser\ReliableConnection\ReliableSqlConnection.cs:line 77    at Microsoft.SqlTools.ServiceLayer.Connection.SqlConnectionFactory.CreateSqlConnection(String connectionString, String azureAccountToken) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\SqlConnectionFactory.cs:line 25    at Microsoft.SqlTools.ServiceL...
> onDidChangeNotification @ notificationsAlerts.ts:36
> (anonymous) @ breadcrumbsModel.ts:294
> fire @ event.ts:525
> addNotification @ notifications.ts:171
> notify @ notificationService.ts:68
> (anonymous) @ mainThreadLogService.ts:16
> _showMessage @ mainThreadLogService.ts:16
> $showMessage @ mainThreadLogService.ts:16
> _doInvokeHandler @ rpcProtocol.ts:396
> _invokeHandler @ rpcProtocol.ts:330
> _receiveRequest @ rpcProtocol.ts:269
> _receiveOneMessage @ rpcProtocol.ts:208
> (anonymous) @ rpcProtocol.ts:90
> fire @ event.ts:525
> fire @ ipc.net.ts:449
> _receiveMessage @ ipc.net.ts:785
> (anonymous) @ ipc.net.ts:642
> fire @ event.ts:525
> acceptChunk @ ipc.net.ts:191
> (anonymous) @ ipc.net.ts:191
> t @ ipc.net.ts:925
> emit @ events.js:223
> addChunk @ _stream_readable.js:309
> readableAddChunk @ _stream_readable.js:290
> Readable.push @ _stream_readable.js:224
> onStreamRead @ internal/stream_base_commons.js:181

**Comment by 8888alex** [comment]
I had the same problem. 
and this is a new issue for me after the 1.10 upgrade. If I revert to 1.9, the issue goes away. 

MSSQL Extension Version: 1.10
VSCode Version: 1.52.1
OS Version: Windows 10 x64 1909

![image](https://user-images.githubusercontent.com/5001484/103091259-91978b80-462e-11eb-947e-a8fd01c1dd18.png)

**Comment by cssuh** [comment]
Please try following the instructions on [this comment](https://github.com/microsoft/vscode-mssql/issues/16930#issuecomment-759711399) to see if the new build fixes this issue for you.

**Comment by cssuh** [comment]
This has been fixed in the new 1.10.1 release (released today).
