### ISSUE TITLE
A11y_mssql for VSCode_New Query Window_Keyboard: When we are in “New Query Window’ and press shortcut key(Ctrl+Shift+D) for Open Run options , we  are unable to move Run Command window.

### ISSUE THREAD

**Issue by harshgangrade111** [microsoft/vscode-mssql#1691]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.” 
 
**GitHubTags**:#A11y_mssql for VSCode; #A11ySev2; #A11yTCS; #A11yMAS; #DesktopApp; #MAS2.1.1; #Win10; #mssql for VSCode; #keyboard; #FTP; #Benchmark;

**Environment Details:**
Application Name: mssql for VSCode

Screen Reader: NVDA, JAWS 2020

**Repro Steps:** 

1. Open Visual studio code 
2. Click on extension button and search for "mssql"
3. Click on install and move to the SQL Server  button
4. Click on Add Connection Button and insert the valid credentials
5. Right click on the server/database node you want to run the new query on.
6. Click on “New Query”
7. Navigate to new query window and press “Ctrl+Shift+D” key for Open SQL Server View.

**Actual:**

When we are in “New Query Window’ and press shortcut key(Ctrl+Shift+D) for Open Run options , we  are unable to move Run Command window.

**Same issue is also observed with “Select top 1000” window.**

**Expected:**

After pressing Ctrl+Shift+D to navigate Run Command window, Keyboard focus should move to that window.

**User Impact:**

Keyboard user will be facing problems after pressing Shortcut key.

**Attachment link for Reference:**
[1691_A11y_mssql for VSCode_New Query Window_Keyboard.zip](https://github.com/microsoft/vscode-mssql/files/4693676/1691_A11y_mssql.for.VSCode_New.Query.Window_Keyboard.zip)

**Comment by abist** [comment]
The shortcut for `Open SQL Server View` is not `Ctrl+Shift+D`, but `Ctrl+Alt+D`. To open the context menu, you can press `Shift+F10` on Windows and `Fn+Shift+F10` on Mac if the`F10`is bound to the volume key by default.

**Comment by abist** [comment]
@harshgangrade111 The issue is that the shortcut `Ctrl + Shift + D` conflicts with `Disconnect` command. The user is suggested to change the keyboard shortcut for either `Disconnect` or `Show: Debug View` from VS Code settings.

**Comment by abist** [comment]
Please use the following build to verify - https://mssqltools.visualstudio.com/_apis/resources/Containers/2339179/drop?itemPath=drop%2Fmssql-1.9.0.vsix

**Comment by BhanuPrakashGit** [comment]
**GithubTag:**#Closed;
[1691_Closed.zip](https://github.com/microsoft/vscode-mssql/files/10719089/1691_Closed.zip)
