### ISSUE TITLE
Question about where the connection is made

### ISSUE THREAD

**Issue by alferpal** [microsoft/vscode-mssql#16924]
Hello, everyone.

More a question rather than an issue.

I'm trying to solve a problem unrelated to this extension at all: the problem being we can't connect to a heimdall data proxy from node with the tedious client but this extension can.

So, I've been trying to find exactly where in the code is the connection made, but I'm not having luck finding that.

Could someone point me in which file or files is the actual connection to MSSQL opened?

Thank you

- MSSQL Extension Version: v1.10.0
- VSCode Version: 1.52.1
- OS Version: Windows 10 enterprise 10.0.19042

**Comment by abist** [comment]
@alferpal Thanks for the question. The extension has a `ConnectionManager` - https://github.com/microsoft/vscode-mssql/blob/main/src/controllers/connectionManager.ts which talks to the C# backend here - https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/Connection/ConnectionService.cs
