### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by octaviogarciav** [microsoft/vscode-mssql#1692]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.45.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by octaviogarciav** [comment]
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 14571,
		"activateCallTime": 1,
		"activateResolvedTime": 5431,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.mssql",
				"_lower": "ms-mssql.mssql"
			},
			"activationEvent": "onLanguage:sql"
		}
	},
	"runtimeErrors": []
}
```

**Comment by abist** [comment]
@octaviogarciav Thanks for opening the issue. Could you describe the problem you're facing a little more?
