### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Ashu-7310** [microsoft/vscode-mssql#16920]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.10.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.52.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
hi @Ashu-7310, could you please elaborate the issue you're facing?

**Comment by cssuh** [comment]
Closing this issue as no further info was provided
