### ISSUE TITLE
 Reopening #1786 - Bug not resolved. Cannot set AccessToken property error connecting with Integrated Auth 

### ISSUE THREAD

**Issue by pvspain** [microsoft/vscode-mssql#16933]
- MSSQL Extension Version: v1.10.0
- VSCode Version: 1.52.1
- OS Version: Windows 10 Enterprise, Version 1909, OS Build 18363.1257

Steps to Reproduce:

1.
2.

**Comment by cssuh** [comment]
This has been fixed in the 1.10.1 release (released today).

**Comment by pvspain** [comment]
Thanks a bunch!
Cheers, Paul
