### ISSUE TITLE
Cancel Query Button Doesn't Stop Query Execution

### ISSUE THREAD

**Issue by sivan-koren** [microsoft/vscode-mssql#16939]
- MSSQL Extension Version: 1.10.0
- VSCode Version: 1.52.1
- OS Version: Windows 10 20H2 (build 19042.746)

Steps to Reproduce:

1. Start a query.
2. Click the Cancel Query button.

A message appears to state that no query is running. However, a query is in fact running.

**Comment by smartguest** [comment]
Running an infinite query: 
````
declare @i int
while (1=1)
set @i = 1
````
shows that it can be cancelled easily without any issue, this is probably related to the new version of STS that was added since this bug was filed. This was fixed by https://github.com/microsoft/sqltoolsservice/pull/1246
