### ISSUE TITLE
SQL Syntax Highlight Bug with \' 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-mssql#16934]
- MSSQL Extension Version: built in to VS Code
- VSCode Version: Code - Insiders 1.53.0-insider (76436a4, 2020-12-11T17:56:17.606Z)
- OS Version: Windows_NT x64 10.0.19041

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/20490672/103794127-a61f4f00-5044-11eb-80af-e9a31cbb1d02.png)
```sql
INSERT INTO test (test1,test2,test3) VALUES
('test','test\'s', 'test')
```

Originally from @DaniGTA in https://github.com/microsoft/vscode/issues/113087

**Comment by micek-petr** [comment]
Hi Alex, this behaviour is perfectly correct according to MSSQL syntax. The backslash character has no meaning in MSSQL. The highlighting engine closed the string after \' correctly as it should be in MSSQL syntax.
