### ISSUE TITLE
Compatibility Level Mismatch

### ISSUE THREAD

**Issue by 1nsomniac** [microsoft/vscode-mssql#16952]
- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.52.1
- OS Version: 20H2 Build 19042.685

Steps to Reproduce:

1. Access server (not using VS Code)
2. Run `SELECT compatibility_level
  FROM sys.databases d WHERE d.database_id = DB_ID();`
3. Note the response of 140
4. Connect to the server via VSCode
5. Run `SELECT compatibility_level
  FROM sys.databases d WHERE d.database_id = DB_ID();`
Note the response of 100

This may very well be user error, or me not understanding how to configure the extension, but I was unable to find the right setting to do that. I also tried refreshing the connection.

**Comment by kburtram** [comment]
I wasn't able to repro this behavior comparing extension output with SSMS output.  The compatibility level is a per-DB setting and is not set by the extension.  It could be possible that you connected to different databases on the same server and getting different compat levels.  Closing as "No repro".  Please let us know if you're still impacted by this issue.
