### ISSUE TITLE
mssql: Error: Unable to connect using the connection information provided. Retry profile creation?

### ISSUE THREAD

**Issue by zihad18** [microsoft/vscode-mssql#16951]
- MSSQL Extension Version:v1.10.1

- VSCode Version:1.52.1
- OS Version:Ubuntu 20.04

I am trying to connect sql in vscode but every time when I fill all the things such as,server as localhost then database mane and other things.then it send me this message.

"mssql: Error: Unable to connect using the connection information provided. Retry profile creation?"

How can I solve this problem.

**Comment by cssuh** [comment]
Hi, if you open the developer tools (using `Control + Shift + P`), do you see any error messages?

**Comment by zihad18** [comment]
No acually when I finish al procedure then on the right bottom side some error message come.

**Comment by Benjin** [comment]
Are you still encountering this issue?  I'm going to close it now, but please re-open it if you're still hitting it.
