### ISSUE TITLE
Add an ability to set trustServerCertificate from Connection Wizard

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#16959]
- MSSQL Extension Version: 1.10

The driver change to more strictly enforce SQL Server certificate validation is causing connections to fail that worked with previous driver versions.  The UI doesn't make the error and the resolution very intuitive.  There should be an ability in the connection UX to set this property and perhaps other advanced connection options.

See discussion here for more context https://github.com/microsoft/vscode-mssql/issues/1806.

**Comment by cheenamalhotra** [comment]
Closing since we now support setting Trust Server Certificate from main connection dialog.
