### ISSUE TITLE
Extension Installed and Activated but No Commands Are Available

### ISSUE THREAD

**Issue by eksortso** [microsoft/vscode-mssql#16961]
Even though I have the `mssql` extension and it's activated globally, any attempt to execute any of its commands results in an error message saying the command is not found.

I reloaded VSCode. I tried uninstalling and reinstalling the extension, reloading or restarting between each transition. Logged out and rebooted my computer. No matter what I try, VSCode can't find the `mssql` commands that it is listing.

This is the first time that something like this has happened, and it was working just fine yesterday. No other extension was installed, disabled, enabled, or uninstalled. (I can't tell how to see if VSCode performed any extension updates.) No other extension that I have installed & activated is experiencing similar problems.

I use this extension a lot, and I much prefer it over SSMS for the work that I do. So any help that you can provide would be greatly appreciated!

- MSSQL Extension Version: v1.10.1
- VSCode Version: 1.53.2 (user setup)
- OS Version: Windows NT x64 10.0.18363

Steps to Reproduce:

1. Start from an editor containing a SQL file.
2. Press `Ctrl+Shift+P`, then type "mssql". You will see the commands that the mssql extension installs.
3. Select "MS SQL: Connect". A notification opens saying that the command is not found.
4. The same thing happens for any of the `mssql` commands.
5. Use keyboard shortcuts to run any of the `mssql` commands, A shorter message will appear, but the error is the same: the command is not found.

![image](https://user-images.githubusercontent.com/1184444/109178418-d5a22c00-7756-11eb-9c02-4dae2392cdc0.png)

**Comment by kburtram** [comment]
@eksortso we haven't pushed any extension updates recently.  Have you tried uninstalling and reinstalling the extension?

@abist any ideas what's happening here?

**Comment by eksortso** [comment]
> @eksortso we haven't pushed any extension updates recently.  Have you tried uninstalling and reinstalling the extension?

Yes, I did that. Even closed and reopened VSCode between uninstalling and reinstalling. It didn't help.

**Comment by kburtram** [comment]
@eksortso could you please check in the "Help->Developer Tools" Console to see if there an exception stack trace available?

**Comment by eksortso** [comment]
Here's what I found. I don't know how to open the Issues panel, but here's the Console log.
[-1614271860049.log](https://github.com/microsoft/vscode-mssql/files/6044555/-1614271860049.log)

**Comment by kburtram** [comment]
@eksortso I suspect this is the relevant line in the log `workbench.desktop.main.js:1734 Activating extension 'ms-mssql.mssql' failed: Unable to write into user settings. Please open the user settings to correct errors/warnings in it and try again..`

Could you please try opening your settings file with the `Open Settings (JSON)` command and looking for any errors in there?  You may copy/paste the JSON into an online JSON editor to see if there are any syntax issue in the file (missing `}`, quotes, etc.).  

We'll take a look why this error is causing the extension to fail to load.  But the workaround is likely to resolve any issues in the settings file.

**Comment by eksortso** [comment]
@kburtram Ah yes, that's exactly what happened. A missing comma. That's a little embarrassing, especially since I try to keep my error counts down to zero. I put in the missing comma and saved the settings, then reloaded the window. After the extensions loaded, `mssql` commands worked perfectly. Thank you!
![image](https://user-images.githubusercontent.com/1184444/109202675-3d657080-7771-11eb-848b-047396699ee0.png)

I'll keep this open so you can track the loading failure, but from my perspective, you can close it at any time.

**Comment by kburtram** [comment]
@eksortso glad to hear you're unblocked!  it seems strange the extension fails to load in this case so we'll take a look to see if we can avoid that somehow.

**Comment by aligature** [comment]
I had exactly the same issue that ended up being a parsing error in my json settings file. In my case, the updated json parser (or whatever caused the difference) didn't like `//` comments I had in my settings.

**Comment by kburtram** [comment]
Closing this issue since the initial report is resolved.
