### ISSUE TITLE
Connection issues with Azure SQL

### ISSUE THREAD

**Issue by Sti2nd** [microsoft/vscode-mssql#16964]
When pasting in the connection string the first time using the command `MS SQL: Add Connection` everything works nearly perfectly. All times after that, though, almost nothing works. Error messages include:

> mssql: Execution failed: Cannot connect to the database due to invalid OwnerUri (Parameter 'OwnerUri')

> mssql: Failed to connect: System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0. at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue) at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey) at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms, Boolean useOdbcRules) at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value) at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.CreateConnectionStringBuilder(ConnectionDetails connectionDetails) in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1096 at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionSer...

and several others the last weeks.

- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.53.2
- OS Version: Win 10

Steps to Reproduce:

1. Add connection to an Azure SQL database by copying a connection string. Like `Server=URL,1433;Initial Catalog=CONN_NAME;Persist Security Info=False;User ID=USER_NAME;Password=USER_PASSWORD;Connection Timeout=600;`
2. Close VS Code
3. Start VS Code again and try to open the existing connection to the db. Errors!

Other things to consider fixing:

- Connecting always takes more than 30 seconds.
- The moving loading line in the Connections tab never stop moving, but it quickly starts from the beginning again, like it is spamming the database with requests many times each second.

**Comment by kburtram** [comment]
@Sti2nd thanks for reporting this bug!  I was able to reproduce on my local env.  As a workaround you should be able to add the connection using the Connection Wizard prompts (i.e. not using connection string, but filling out the various components directly in wizard).  We'll schedule this for the next release.

**Comment by kburtram** [comment]
Fix ported to release/1.12.
