### ISSUE TITLE
I cannot alter or view a trigger script on my database connections

### ISSUE THREAD

**Issue by omarsd03** [microsoft/vscode-mssql#16962]
- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.53.2
- OS Version: Windows 10 Enterprise 1809

Steps to Reproduce:

1. Open Visual Studio Code
2. Click on SQL Server icon
3. Right click on a existing connection and choose New query
4. Write a query for create a new trigger for a table
5. Right click on the active connection and choose Refresh
6. Navigate on the connection panel to find the table with the new trigger.
7. Right click on the new trigger for choose some option to alter or drop.
8. Only appears "Refresh"

It would be very useful that as well as it is possible to edit or eliminate stored procedures, it would be possible to edit triggers or even eliminate them.

I hope this can be a good suggestion to be contemplated in a next version as an improvement.

If I am doing the process wrong and it is possible to alter triggers or at least view the current script of the triggers, I hope someone can help me how to do it.

**Comment by mrchao-SP** [comment]
Freundliche Grüße


Servillano Pantillo
IT-Systemadministrator


__________________________________

[cid:ESGLogo_2_f21c3edb-19dc-4b8e-9e1d-f36936e437a4.png]

Für Sie immer unter Strom!

+ Freiburg
Basler Straße 111-113
79115 Freiburg i.Br.
(Postadresse)

+ Offenburg
Kinzigtalstraße 5
77799 Ortenberg

+ Donaueschingen
Josefstraße 17
78166 Donaueschingen


Fon: +49 (0) 761 1371770
Fax: +49 (0) 761 13717710

Öffnungszeiten:
Mo - Do 08:00 - 12:00 Uhr, 13:00 - 16:30 Uhr,
Fr 08:00 - 13:00 Uhr
.
www.esg-gmeiner.de<http://www.esg-gmeiner.de>

[cid:SocialLink_Facebook_32x32_c08803ec-a29c-4da8-a907-368748ac32ec.png]<https://www.facebook.com/gmeinergmbh/?modal=admin_todo_tour>[cid:SocialLink_Youtube_32x32_2ce64da5-656c-41c5-887f-a5230f1ec5ae.png]<https://www.youtube.com/watch?v=rfOweS7g5l0>

Geschäftsführer: Wolfgang Gmeiner & Markus Götz
Sitz: 79115 Freiburg im Breisgau
Handelsregister: Freiburg HRB 706139
Umsatzsteuer-Identifikations-Nr: DE274884868

Diese Nachricht und alle mit gesendeten Dateien enthalten vertrauliche und rechtlich geschützte Informationen.
Wenn Sie nicht der richtige Adressat sind oder diese Email irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Nachricht.
Das unerlaubte Drucken, Kopieren, Behalten sowie die unbefugte Weitergabe an Dritte dieser Nachricht ist nicht gestattet.

Ps: Bitte denken Sie an die Umwelt, bevor Sie diese Email ausdrucken.

Am 26.02.2021 um 20:00 schrieb Omar Salgado Diaz <notifications@github.com>:

﻿

 *   MSSQL Extension Version: 1.10.1
 *   VSCode Version: 1.53.2
 *   OS Version: Windows 10 Enterprise 1809

Steps to Reproduce:

 1.  Open Visual Studio Code
 2.  Click on SQL Server icon
 3.  Right click on a existing connection and choose New query
 4.  Write a query for create a new trigger for a table
 5.  Right click on the active connection and choose Refresh
 6.  Navigate on the connection panel to find the table with the new trigger.
 7.  Right click on the new trigger for choose some option to alter or drop.
 8.  Only appears "Refresh"

It would be very useful that as well as it is possible to edit or eliminate stored procedures, it would be possible to edit triggers or even eliminate them.

I hope this can be a good suggestion to be contemplated in a next version as an improvement.

If I am doing the process wrong and it is possible to alter triggers or at least view the current script of the triggers, I hope someone can help me how to do it.
