### ISSUE TITLE
Extension issue - slow loading times

### ISSUE THREAD

**Issue by DaveBarx** [microsoft/vscode-mssql#16960]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.10.1`
- OS Version: `Windows_NT x64 10.0.21313`
- VSCode version: `1.53.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 25597,
		"activateCallTime": 2,
		"activateResolvedTime": 10879,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.mssql",
				"_lower": "ms-mssql.mssql"
			},
			"activationEvent": "onLanguage:sql"
		}
	},
	"runtimeErrors": []
}
```

**Comment by kburtram** [comment]
@DaveBarx was there any CPU profiling information available?  or other info to help determine why the load time was slow in this case?  These load times look bad, but unfortunately there isn't sufficient detail above to understand what's going on.

**Comment by kburtram** [comment]
Closing since the issue lacks adequate information for further investigation.
