### ISSUE TITLE
Native VScode on M1 (Apple Silicon) breaks extension 

### ISSUE THREAD

**Issue by roelrens** [microsoft/vscode-mssql#16967]
- MSSQL Extension Version:v1.10.1
- VSCode Version: 1.55.0-insider (Universal)
- OS Version: 11.2.3 (20D91)

Steps to Reproduce:

1. use the universal binary of VSCode
2. extension support broken.

**Comment by davemcdermid** [comment]
Looks like this is can be fixed with a small change to platform mapping, I've created a PR: https://github.com/microsoft/vscode-mssql/pull/16969

**Comment by leighghunt** [comment]
I've just run into this whilst setting up a new M1 Air - can help test if required

**Comment by dzsquared** [comment]
There is now a preview release available here: https://github.com/microsoft/vscode-mssql/releases/tag/v1.10.2

Next stable release is planned for end of October

**Comment by brunovieira97** [comment]
Any news on this?

**Comment by leighghunt** [comment]
> Any news on this?

I'm not on the team or anything, but I'm successfully using v1.13.0, just downloaded from the marketplace if I recall correctly - and i can see the change that was made is in the v1.13.0 code branch - https://github.com/microsoft/vscode-mssql/blob/v1.13.0/src/models/platform.ts#L292

**Comment by brunovieira97** [comment]
@leighghunt I see. Thanks for the heads up. I was checking up on this because it seems to be a dependency for Azure Data Studio to be properly ported to Apple Silicon. Glad to know this is taken care of.

**Comment by nick-gibb** [comment]
+1, would be great if we could get this to run using ARM64.

**Comment by Nova-Logic** [comment]
+1 waiting m1 version
