### ISSUE TITLE
I can't connect to a local MySQL server

### ISSUE THREAD

**Issue by Denoic** [microsoft/vscode-mssql#16977]
- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.55
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Adding a connection profile
2. Typing localhost,3306
3. Leaving it blank
4. Choosing SQL login
5. Name: root Pass: (my own password. Typing it without errors, or typos)
6. Saving the password
7. Display Name: Local

And it gives me the following error:

> mssql: Failed to connect: System.InvalidOperationException: Internal connection fatal error. at Microsoft.Data.SqlClient.TdsParserStateObject.TryProcessHeader() at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired) at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, Boolean encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean withFailover, SqlAuthenticationMethod authType) at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover) at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePass...

I saw this issue. And tried it out. But it still doesn't work.  #1806

**Comment by dzsquared** [comment]
The mssql extension for VS Code does not support MySQL at this time.

**Comment by Denoic** [comment]
oh ok, thanks for letting me know. I didn't know.

**Comment by DanaCoding** [comment]
> The mssql extension for VS Code does not support MySQL at this time.

I don't understand why the databases that are so popular all over the world are not supported. Is there a xx between Microsoft and MySQL? :)
