### ISSUE TITLE
[Feature Request] Have query results use VSCode's new table widget

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-mssql#16974]
- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.55
Would be nice if this extension displayed results with the table widget. They've updated their keyboard shortcuts UI to use it:

![image](https://user-images.githubusercontent.com/41576511/113221649-5fc14100-927d-11eb-9da3-6e6ce10e6695.png)

 I've always found the default results pane a little jarring when used with a dark theme.

**Comment by kburtram** [comment]
The result grid control has been highly customized for this extension and the unfortunately the VS Code Table is not a comparable replacement.  Closing as "Won't Fix".  Thanks for opening this suggestion!
