### ISSUE TITLE
SQL TOOL SERVICE

### ISSUE THREAD

**Issue by Collinsago** [microsoft/vscode-mssql#16973]
- MSSQL Extension Version:
- VSCode Version: V8
- OS Version: WINDOWS 7
![Capture](https://user-images.githubusercontent.com/71197307/112784805-73d12c80-904a-11eb-9a9d-df7a5dc9b929.PNG)

Steps to Reproduce:

1.
2.

Failed to load the dll from [C:\Users\ENGR COLLINS\.vscode\extensions\ms-mssql.mssql-1.7.0\sqltoolsservice\1.7.0\Windows\hostfxr.dll], HRESULT: 0x80070057
The library hostfxr.dll was found, but loading it from C:\Users\ENGR COLLINS\.vscode\extensions\ms-mssql.mssql-1.7.0\sqltoolsservice\1.7.0\Windows\hostfxr.dll failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
[Error - 4:39:37 AM] Connection to server got closed. Server will not be restarted.

**Comment by kburtram** [comment]
Closing older issues without recent repro.  Please try with latest extension and let us know if you're still encountering this issue.  Thanks!
