### ISSUE TITLE
Adding connection to workspace settings, copies to settings.json

### ISSUE THREAD

**Issue by dustyghost** [microsoft/vscode-mssql#16983]
- MSSQL Extension Version: v1.10.1
- VSCode Version:
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

- OS Version: Windows 10 - 20H2

Steps to Reproduce:

1. Add the following to the Workspace setting file:

```
		"mssql.connections": [
			{
				"connectionString": "Server=(localdb)\\LocalDevDB;Database=MainDB;Trusted_Connection=True;ConnectRetryCount=0",
				"profileName": "LocalLogs",
				"password": ""
			},
```

2. When you save, then load the extension in the left panel and look at Settings.Json. The settings for the SQL has been copied there. 

This is frustrating is it's not needed in my other workspaces, yet the connection appears as it's in the 
`C:\Users\<user>\AppData\Roaming\Code\User\settings.json`

**Comment by gsimardnet** [comment]
I agree it is very frustrating because adding this setting in the workspace settings overwrites mssql.connections in user settings.
