### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Bijaelo** [microsoft/vscode-mssql#16987]
This is an issue that has been asked at least once before #1022 in a similar fashion. There the problem was solved (it seems) for most users in by either

1. Restarting VScode
2. Uninstall the extension, restarting VScode and reinstalling
3. Uninstalling, deleting the associated extension folder in .vscode/extensions, restarting and reinstalling
4. Removing other extensions and reinstalling the specific extension. 

After trying all of these (and also trying to remove **all** extensions and their associated folder before only installing the mssql extension), I am now hoping for other solution suggestion.  The issue has not changed. Installing the mssql vscode extension, **no** functions/commands are located. Both in the SQL SERVER pane (where it fails to find "add connection") and when trying to execute any command through using ctrl+shift+P. 

System information:
```
Version: 1.56.0 (user setup)
Commit: cfa2e218100323074ac1948c885448fdf4de2a7f
Date: 2021-05-04T22:09:06.405Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.18363
```
Image of the SQL SERVER page (missing "add connection")

![connection-screenshot](https://user-images.githubusercontent.com/38879206/117462498-08368500-af4f-11eb-9875-1f58c0464b8a.png)

Image of errors thrown whenever any command from mssql is used:

![command-not-found](https://user-images.githubusercontent.com/38879206/117462634-22706300-af4f-11eb-9d96-df475577534a.png)

**Comment by Bijaelo** [comment]
Tried something new: 
Added vscode - insiders (1.57) to test the installation. The extension works fine in insiders, but does not work in vscode itself, even after completely obliterating it from my system and reinstalling vscode. Guess insiders is the way to go.

**Comment by abist** [comment]
@Bijaelo Can you try removing the cached extension in your home directory? It should be under `“~\.vscode\extensions\ms-mssql.mssql-{version}”` or similar path in your home directory

**Comment by Bijaelo** [comment]
Hi @abist Please refere to the checklist of what I have already tried doing in the question itself. What you're asking is tried in point number 2, 3 and 4.

**Comment by kburtram** [comment]
Closing older issues without recent repros.  This error indicates the extension failed to load, so the basic commands didn't get registered.  If this is still a problem, please create a new issue and provide any exception details from the Developer Tools Console available from the Help menu. Thanks!
