### ISSUE TITLE
Failing to install mssql sql tools 

### ISSUE THREAD

**Issue by mhmtsoydam** [microsoft/vscode-mssql#16989]
- MSSQL Extension Version:1.10.1
- VSCode Version:1.56
- OS Version: W10

Steps to Reproduce:

Hi, I'm trying to install mssql extension for my heavy database use however I'm getting the following error:

Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

_Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to c:\Users\mehmet.soydam\.vscode\extensions\ms-mssql.mssql-1.10.1\sqltoolsservice\1.10.0\Windows.
Downloading https://download.microsoft.com/download/9/6/7/96792b35-04b8-4ef0-8d38-c634ef975e3b/microsoft.sqltools.servicelayer-win-x64-netcoreapp3.1.zip
failed (error code '407')
[ERROR] Error: 407
_

I have followed solution steps mentioned in #568 but it didn't help. I'd appreciate a solution.

**Comment by ls-ita** [comment]
Following up on this open issue (Failing to install mssql sql tools #16989) to see if there is any update. I'm experiencing the same problem as originally reported by [mhmtsoydam](https://github.com/mhmtsoydam).

**Comment by bjonen** [comment]
For us same (similar) issue. Installing the extension from market place works fine. But then installing sql tools fails

```
Installing SQL tools service to /mnt/fineng/workspaces/jonb/vscode/.vscode-server/extensions/ms-mssql.mssql-1.15.0/sqltoolsservice/4.0.1.1/RHEL.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.0.1.1/microsoft.sqltools.servicelayer-rhel-x64-net6.0.tar.gz
[ERROR] Error: Request error: NONE
```

**Comment by daniel-woodhead** [comment]
@bjonen My workaround for now is to manually download it:

```
cd /home/node/.vscode-server/extensions/ms-mssql.mssql-1.15.0/sqltoolsservice/4.0.1.1/Debian
wget -c https://github.com/Microsoft/sqltoolsservice/releases/download/4.0.1.1/microsoft.sqltools.servicelayer-rhel-x64-net6.0.tar.gz -O - | tar -xz
```

And then Ctrl + Shift + P -> Reload Window

**Comment by strategic-learner** [comment]
@DevTeam: the fix may be something simple:  It appears the GitHub path changed for accessing release items; from "download" to "tag".  But the installer is still looking for the old path:

OLD: github.com/microsoft/sqltoolsservice/releases/ **download/** 4.4.1.5/
NEW: github.com/microsoft/sqltoolsservice/releases/ **tag/** 4.4.1.5/

**Comment by kburtram** [comment]
The extension downloads an out-of-proc component on initial launch after install/update.  Sometimes this download can fail due to network reliability or other intermittent issue.  Please try to reinstall to see if that helps or try to manually download the component as suggested above.  Thanks!
