### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by mhhc-bi** [microsoft/vscode-mssql#16999]
Issue Type: <b>Bug</b>

I cannot reproduce this error on any other system.  This seems to be a system issue which only affect this specific process.

With Microsoft SQL Plugin running a query I get the error below. The Query does not run and there is no other response (No data returned)

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

When using the Microsoft SQL Server Plugin.  It seems to  be related to something out side of VS code, possibly with chrome.  I have other install with the exact same setup and it works fine.  One day to the next without any known update or change this error pops up 100% of the time when running a query in the app.  Reinstall of the VSCode and complete cleaning out settings and plugins causes the same error.

Extension version: 1.10.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:13:13.157Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (2.25GB free)|
|Process Argv|--crash-reporter-id 06880155-dbd6-4292-9ec5-070e40b659f0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt678:30270856
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551:30311712
vspre833:30267464
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158cf:30286554
vscgsv2ct:30307505
vscorehov:30309549
vscod805:30301674
binariesv517cf:30312826

```

</details>

**Comment by abist** [comment]
Where do you see the webview error? Also, could you try pasting the errors in the Developer Tools -> Console? (Ctrl+Shift+I or Help -> Toggle Developer Tools)

**Comment by MattConroy** [comment]
I'm having the same issue, here are the errors in the Developer Tools

`Webview fatal error: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
(anonymous) @ main.js:782
async function (async)
(anonymous) @ main.js:780
channel.port1.onmessage @ main.js:283`

`notificationsAlerts.ts:42 Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
onDidChangeNotification	@	notificationsAlerts.ts:42
(anonymous)	@	notificationsAlerts.ts:28
fire	@	event.ts:628
addNotification	@	notifications.ts:206
error	@	notificationService.ts:92
(anonymous)	@	webviewElement.ts:264
(anonymous)	@	webviewElement.ts:205
messagePort.onmessage	@	webviewElement.ts:205`

**Comment by kburtram** [comment]
Closing older issue without recent repro reports.  Please let us know if this is still occurring on current version of extension and VS Code.  Thanks!
