### ISSUE TITLE
Feature Request: Grouping tables by schema

### ISSUE THREAD

**Issue by Bijaelo** [microsoft/vscode-mssql#16990]
This is related to a feature available in some other GUI's such as [DBeaver](https://dbeaver.io/) and apparently [Visual Studio Server Explorer](https://stackoverflow.com/q/24425888/10782538), grouping tables by their schema parent. 

As a database grows (especially if there are hundreds or even thousands of tables and/or schemas) it becomes increasingly difficult to navigate to specifically desired tables. In the SQL Server tools such as this one and SSMS the standard has been that each DB has a table folder which contains all tables with their schema extensions. However, this can often lead to time spent scrolling through tables, as you have misspelled some vaguely named table.

This wasted time could be reduced drastically if one had option to group tables by schema. For example lets say we had database with 3 tables, all under the same schema `extract`. Then these 3 tables would be grouped under the same sub-folder within "tables" called `extract`. 

| Database 
| - tables
| - - `extract`
| - - - table1
| - - - table2
| - - - table3

**Comment by kburtram** [comment]
This is supported in the current extension release by clicking the "Enable/Disable Group by Schema" toggle button in the Connections view.

![image](https://github.com/user-attachments/assets/507af909-62c1-4789-82d7-35449b24262f)
