### ISSUE TITLE
Azure Data Studio for Mac - connection failure if .sql script longer than X lines

### ISSUE THREAD

**Issue by scottfagg** [microsoft/vscode-mssql#16996]
- MSSQL Extension Version: unknown
- VSCode Version: 1.20.0
- OS Version: MacOS 10.15.7

Steps to Reproduce:

1. connect to any supported ms-sql db ( was using Azure SQL Database )
2. attempt to run a script longer than X lines
3. receive :

Msg 0, Level 20, State 0, Line 0
A transport-level error has occurred when sending the request to the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
Total execution time: 00:00:00.045

.. and ..

SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.

--

Testing i was able to run 200 lines of insert statement but not 400 lines of insert statements. I haven't yet pin-pointed the precise threshold of failure.

Same scripts run ok when using Azure Data Studio for Windows.

**Comment by kburtram** [comment]
Closing as this is a bug for Azure Data Studio, but this repository is for MSSQL for VS Code extension.  Please open a bug at https://github.com/microsoft/azuredatastudio if you are still impacted by this issue.

**Comment by scottfagg** [comment]
This is actually got resolved some time ago. I think it got logged here because this is were VS Code took me when i used the 'report an issue'.
