### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by yanonymous** [microsoft/vscode-mssql#16993]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.10.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.56.2`

it shows unresponsive behavior and has very long profile time.
Any idea what might be the issue?

**Comment by kburtram** [comment]
@yanonymous were you able to capture any profile traces during the slow behavior?  without additional info it's hard to determine why their may be perf issues in a particular environment.

**Comment by yanonymous** [comment]
@kburtram no it just shows up in notification tab so was not able to capture profile traces
