### ISSUE TITLE
How to add or edit snippets?

### ISSUE THREAD

**Issue by OfirD1** [microsoft/vscode-mssql#17003]
Using the extension, typing `sql` displays a list of code snippets. 

Is it possible to add or edit snippets inside VS Code? if so, how? I see that snippets are defined inside [mssql.json](https://github.com/microsoft/vscode-mssql/blob/main/snippets/mssql.json), but is it reachable for editing inside VS Code?

**Comment by dzsquared** [comment]
https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

You can absolutely add/edit snippets for use with VS Code!  The above link is a guide to all things snippets, including starting your custom snippets file and the syntax.
