### ISSUE TITLE
Corrupt ZIP

### ISSUE THREAD

**Issue by dhireng** [microsoft/vscode-mssql#17006]
- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.57.1
- OS Version: Windows  10 - version 1909

Steps to Reproduce:

installation of 1.10.1 throws Corrupt ZIP: end of central directory record signature not found: validating: Corrupt ZIP: end of central directory record signature not found
All other versions work okay
Issue seen for several months now

**Comment by kburtram** [comment]
Closing older issue without recent repro reports.  Please let us know if this issue is still occurring on current release of extension.  Thanks!
