### ISSUE TITLE
Extension is not installed correctly on Linux

### ISSUE THREAD

**Issue by Xinayder** [microsoft/vscode-mssql#1702]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.46.0
- OS Version: Arch Linux, kernel 5.7.5-zen1-1-zen

Steps to Reproduce:

1. Install the `mssql` extension from Marketplace
2. Open Developer Tools 
3. There will be a message saying the extension couldn't be activated:
```
/usr/share/vscodium-bin/resources/app/out/vs/workbench/workbench.desktop.main.js:4071 Activating extension 'ms-mssql.mssql' failed: Cannot find module '/home/alex/.vscode-oss/extensions/ms-mssql.mssql-1.9.0/out/src/extension'
Require stack:
- /usr/share/vscodium-bin/resources/app/out/vs/loader.js
- /usr/share/vscodium-bin/resources/app/out/bootstrap-amd.js
- /usr/share/vscodium-bin/resources/app/out/bootstrap-fork.js.
```

**Comment by Esperadoce** [comment]
I have the same problem any solution ?

**Comment by mrkskwsnck** [comment]
I'm experiencing the same issue with VSCodium v1.51.1 and mssq l1.9.0. However, I don't think this is a GNU/Linux related issue.

As I have a dual boot system I tried VSCodium with mssql on Windows 10 with the same result, a.k.a. not working (with the error message mentioned above). Then I gave MS VSCode a try and… the extension mssql seems to work just fine.

So, for me the question is: Why does the extension mssql work with VSCode but not with VSCodium. Where shall we address this issue?

**Comment by kburtram** [comment]
I'm not able to reproduce this on the latest version of the extension/vscode on CentOS.  Please let us know if this is still a problem.  Unfortunately, we are not able to investigate issues that are specific to VSCodium that don't reproduce on VS Code, but there shouldn't be any implementation details specific to VS Code that I'm aware of.
