### ISSUE TITLE
Default isolation level is set to `read uncommitted`

### ISSUE THREAD

**Issue by sjp363** [microsoft/vscode-mssql#17044]
- MSSQL Extension Version:  1.7+
- VSCode Version: 1.59.1
- OS Version: windows 10 21H1

Steps to Reproduce:

1. version mssql 1.6;   execute dbcc useroptions; isolation level = "read committed" 
2. version mssql 1.7+; execute dbcc useroptions; isolation level = "read UNcommitted" 
not able to permanently change or set default using statement "set transaction isolation level read committed"

**Comment by sjp363** [comment]
@kburtram you are the man 💯 !! thanks so much, that fixed it. 😄

**Comment by kburtram** [comment]
@sjp363 happy to hear that resolved the problem!  I'll leave this open to track adding the settings into the vscode settings UI and possibly changing the default isolation mode.  Thanks!
