### ISSUE TITLE
Apple silicon Not Supported Issue

### ISSUE THREAD

**Issue by xkalf** [microsoft/vscode-mssql#17048]
- MSSQL Extension Version: 1.10.1
- VSCode Version: 1.59.1
- OS Version: macOS Big sur 11.5.2

Steps to Reproduce:

1. Pls support M1 mac version 
2.

**Comment by kburtram** [comment]
We're tracking this request with issue https://github.com/microsoft/vscode-mssql/issues/16967.  Please add any comments to that issue if there is any additional context you'd like to add.  Thanks!
