### ISSUE TITLE
MSSQL appears to be executing a query - but when attempt to stop "mssql: Cannot cancel query as no query is running."

### ISSUE THREAD

**Issue by BenGardiner123** [microsoft/vscode-mssql#1705]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Connected to Azure DB
2. Execute a query to create tables that already exist.
3.  Get  error mssql: Execution failed: SQL Execution error: A fatal error occurred. Incorrect syntax was encountered while /* CREATE TABLE
4. Now i am unable to execute any queries. If i try to i get 
![image](https://user-images.githubusercontent.com/61527372/87614994-efa57600-c754-11ea-9488-1f360df9ec14.png)

n.b ive tried restarting vscode and my PC
tried deleting and restarting my DB in azure

**Comment by abist** [comment]
@BenGardiner123 Thanks for opening the issue. Does restarting not help? Could you expand the error and paste the whole message here?

**Comment by BenGardiner123** [comment]
The rest of the error was simply a copy of my query being spat back at me. There was no other information.  I deleted VScode and the extensions folder, resinstalled and the same error came up. 
I then opened a new file in a new repo, pasted the query in there and the error disappeared. So the error was caused by something associated with the previous file.
