### ISSUE TITLE
SQLCMD Scripting Variables are reported as errors.

### ISSUE THREAD

**Issue by cnash** [microsoft/vscode-mssql#17071]
- MSSQL Extension Version: v1.10.1
- VSCode Version: Version: 1.61.0 (system setup)
  - Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
  - Date: 2021-10-07T18:13:09.652Z
  - Electron: 13.5.1
  - Chrome: 91.0.4472.164
  - Node.js: 14.16.0
  - V8: 9.1.269.39-electron.0
  - OS: Windows_NT x64 10.0.19042

- OS Version: Windows 10 v20H2 (19042.1237)

I'm working on a set of SQL scripts that are run as part of our deployment process. They are executed by from a CMD.COM script using SQLCMD.EXE, and passing in **scripting variables** like this:

```
SET SOURCEDB=MySourceDb
SET TARGETDB=MyTargetDb
SET _SQLCMD=sqlcmd -V11 -m1 -v destination="%TARGETDB%" -v source="%SOURCEDB%"
%_SQLCMD% -i "%REPOPATH%\scripts\Script1.sql"
%_SQLCMD% -i "%REPOPATH%\scripts\Script2.sql"
```
Then, inside the SQL scripts, such as `Script1.sql` I have code like this:

```
INSERT INTO $(destination).dbo.SomeTable(Field1, Field2)
     SELECT  Field1, Field2 FROM $(source).AnotherTable
```

The mssql extension reports the scripting variables as errors with red squiggly underlines, and entries in the 'Problems' window.

It would be better for me as a sql script developer if these were not reported as syntax errors.

**Comment by alanrenmsft** [comment]
@cnash the issue will be fixed in the next release, please remember to turn of the sqlcmd mode if you need to work with it:

![image](https://user-images.githubusercontent.com/13777222/144345771-6c4dd22f-1d3d-434b-a1b5-f00b45caf09d.png)
