### ISSUE TITLE
Extension startup time is slow

### ISSUE THREAD

**Issue by AmentBRT** [microsoft/vscode-mssql#17087]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.11.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.61.2`
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 7891,
		"activateCallTime": 1,
		"activateResolvedTime": 3702,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "ms-mssql.data-workspace-vscode",
				"_lower": "ms-mssql.data-workspace-vscode"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": 1
}
```

**Comment by cssuh** [comment]
Hi @AmentBRT, can you please specify and give a description of what the issue is? Also, are there any logs or error messages you are seeing?

**Comment by kburtram** [comment]
@Charles-Gagnon @Benjin this looks like a perf issue with the Data Workspace extension.  The report says ~8 sec to load the extension code and ~3.5 sec for activate.  It's worth checking if there's anything we can do to improve this.

**Comment by kburtram** [comment]
Hmm, on a re-read of the issue I think this is saying mssql extension is slow being loaded because of the data-workspace extension.

**Comment by Charles-Gagnon** [comment]
Ack

@Benjin @kisantia we should look and see if we can improve this. The code loading taking so long is pretty weird, it isn't a large extension...

**Comment by Charles-Gagnon** [comment]
@AmentBRT Does this happen every time you start VS Code or was this a one-time thing?

**Comment by Benjin** [comment]
Hmm... my first guess was that it was the scan for projects, but that's happening asynchronously.  We'll have to add some profiling.

@AmentBRT Do you see the same slow startup with an empty workspace as one with a larger folder (plenty of files for the extension to search for projects)?

**Comment by mrchao-SP** [comment]
is that code open source?

**Comment by Charles-Gagnon** [comment]
@mrchao-SP Yup, 

https://github.com/microsoft/azuredatastudio/tree/main/extensions/data-workspace
There's also https://github.com/microsoft/azuredatastudio/tree/main/extensions/sql-database-projects which interacts with the data-workspace extension so it's possible something is going wrong there as well.

**Comment by Charles-Gagnon** [comment]
For anyone having this issue - could you provide the following information.

- Does this happen every time you open VS Code or just the first time
- Approximate size of the folder/workspace in number of files/folders
- Max folder depth
- Whether there's any SQL project files in the folder/workspace
- Whether you still see these perf issues when opening an empty VS Code (no folder/workspace)

**Comment by kburtram** [comment]
Cleaning up older issues.  Please let us know if this performance issue is still present on current extension release.
