### ISSUE TITLE
Disable SQLTools Service

### ISSUE THREAD

**Issue by LawrenceL-QHR** [microsoft/vscode-mssql#17090]
- MSSQL Extension Version: 1.11.0
- VSCode Version: 1.61.2
- OS Version: Windows 10 Enterprise 20H2

I would like to use the MSSQL extension ONLY for the T-SQL formatter.

Can I disable the SQL Tools Service and any other unnecessary functionality, especially anything that would try to connect to a database?

**Comment by kburtram** [comment]
The SQL formatter is implemented within SQL Tools Service, as is the majority of the other features of this extension.  We don't  a setting to disable the child process as that would disable most everything beyond simple features like colorization.  Closing as out of scope.  Thanks for opening the issue.

**Comment by kburtram** [comment]
...for what it's worth, SQL Tools Service will not try to connect to a database unless you explicitly run the Connect command and fill out connection parameters.

**Comment by LawrenceL-QHR** [comment]
Thank you very much for answering kburtram!
