### ISSUE TITLE
Please install .NET Core SDK version 3.1 and include a global.json in the project folder specifying the SDK version to use.

### ISSUE THREAD

**Issue by cgsthtm** [microsoft/vscode-mssql#17110]
- MSSQL Extension Version: v1.11.0
- VSCode Version:Version: 1.62.2 
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. install mssql on the vscode extensions
2. then the output window : installing sql tools service to .... downloading... done! 766 files unpacked.
3. pop-up in the lower right corner of vscode : installed .NET SDK version 6.0.100 is newer than the currently supported versions. Project build will not work. Please install .NET Core SDK version 3.1 and include a global.json in the project folder specifying the SDK version to use. More Information. Source: SQL Database Projects(Extension)

I installed .net core sdk 3.1.415, but that still doesn't solve the problem.
my english is very not good, please help me, thanks a lot!

**Comment by Charles-Gagnon** [comment]
@cgsthtm Did you add a global.json file specifying the SDK version to use in the root of your project?

https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x

So the contents should look like this 

```json
{
  "sdk": {
    "version": "3.1.415"
  }
}
```

**Comment by Charles-Gagnon** [comment]
And just to confirm - are you trying to work with a sqlproj? Or are you seeing this when working on other project types (such as csproj)?

There's an issue we identified that is making this warning show up for non-sqlproj types which shouldn't be happening since it only applies to sqlproj. So if you're not working on sqlproj projects then you can click the "Don't show again" button (or just dismiss it) - adding the global.json isn't necessary.

**Comment by cgsthtm** [comment]
> And just to confirm - are you trying to work with a sqlproj? Or are you seeing this when working on other project types (such as csproj)?
> 
> There's an issue we identified that is making this warning show up for non-sqlproj types which shouldn't be happening since it only applies to sqlproj. So if you're not working on sqlproj projects then you can click the "Don't show again" button (or just dismiss it) - adding the global.json isn't necessary.

Thank you for answering my questions.
