### ISSUE TITLE
Enable vscode-mssql grammar to be available for VS Code on the Web

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-mssql#17132]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure vscode-mssql is available in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

I checked your extension and I see there are quite some node dependencies, so this transition to web might not be trivial or possible. However it would be cool if you could at least contribute `grammars` for web, and using `when` clauses disable all other contributions which can not work on the web.

We are also open to helping here. Let us know what you think. Thanks!

@aeschli

**Comment by Charles-Gagnon** [comment]
@abist @kburtram FYI

Thanks for reaching out @isidorn! I believe that VS Code already pulls in the T-SQL grammar as part of the built-in language support - https://github.com/microsoft/vscode/blob/main/extensions/sql/syntaxes/sql.tmLanguage.json (pulled from https://github.com/microsoft/vscode-mssql/blob/main/syntaxes/SQL.plist)

@alexr00 can you confirm this?

**Comment by isidorn** [comment]
I can confirm that VS Code has built-in sql coloring, thus a grammar is present. Though @alexr00 can confirm where we are pulling the grammar from.

However I still wanted to create this issue for discussion if there are other parts of the extension that might make sense in the web context. If there are none feel free to close this issue. Thank you

**Comment by alexr00** [comment]
Yes, this is where we pull the grammar from.

**Comment by lewis-sanchez** [comment]
Hi @isidorn, the vscode-mssql extension can't run in the web context because it depends on the SQL Tools Service and that service needs a child process for the extension to work. Without the service the extension is missing a lot of its functionality and isn't useful in the web context. I've reviewed the grammar and found that the T-SQL grammar being pulled into VS Code is up to date with the grammar in vscode-mssql. Since the extension can't work without it's required service and the T-SQL grammar is up to date I'm closing this issue.

**Comment by isidorn** [comment]
Sounds good. Thank you for the analysis.
