### ISSUE TITLE
Token retrieval failed with an error.

### ISSUE THREAD

**Issue by Shaul-Z** [microsoft/vscode-mssql#17174]
- MSSQL Extension Version: 1.12.0
- VSCode Version: 1.63.1
- OS Version: Ubuntu 18.04.4 LTS

Steps to Reproduce:
I am not sure how to reproduce this error but when I try to connect to a DB I get the error:
1. "Token retrieval failed with an error. Open developer tools to view the error."
2. Then prompt to Refresh My Credentials - I did it and everthing works fine although it ask me:
"Are you trying to sign in to Azure Data Studio? "
and it is the only option I get so I am force to press continue.
3. Finaly, I get back to VSCODE and get the same error: "Token retrieval failed with an error. Open developer tools to view the error."
4. Until 12-12-2021 everything worked perfect!

settings.json:

> {
>     "remote.SSH.remotePlatform": {
>         "12.34.56.7": "linux"
>     }, 
>     "editor.fontSize": 18,
>     "terminal.integrated.fontSize": 18,
>     "mssql.connections": [
>         {
>             "server": "my.server.url",
>             "database": "MyDataBaseName",
>             "authenticationType": "AzureMFA",
>             "profileName": "MyProfileName",
>             "email": "my@email.com",
>             "accountId": "MyAccountId",
>             "password": ""
>         }
>     ],
>     "workbench.editor.enablePreview": false,
>     "workbench.editor.openSideBySideDirection": "down",
>     "gitlens.codeLens.enabled": false,
>     "python.defaultInterpreterPath": "\\usr\\local\\bin\\python3",
>     "mssql.query.implicitTransactions": true,
>     "mssql.showBatchTime": true,
>     "mssql.enableQueryHistoryCapture": false,
>     "files.autoSave": "afterDelay",
>     "mssql.azureActiveDirectory": "DeviceCode"
> }

**Comment by Shaul-Z** [comment]
Today I tried to connect using the newer version = 1.12.0 but still no luck :(

**Comment by kburtram** [comment]
We've made significant refactors/improvements to the AAD token management code since this issue was last updated.  Please let us know if you're still impacted by this issue on the current extension version.
