### ISSUE TITLE
OOM Errors when in large JS/TS Repo

### ISSUE THREAD

**Issue by vincent-eb** [microsoft/vscode-mssql#17175]
Issue Type: <b>Bug</b>

When extension enabled in a large workspace (thousands of files) primarily `.js` `.ts` and some `json` and `md` processing power consistently spikes and eventually causes an OOM error where the extension host crashes.

Often switching between workspaces where some require `.sql` tools and others do not so leave it enabled in general.

Extension version: 1.11.1
VS Code version: Code 1.63.0 (7db1a2b88f7557e0a43fec75b6ba7e50b3e9f77e, 2021-12-07T05:15:48.091Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 6, 6|
|Memory (System)|32.00GB (2.06GB free)|
|Process Argv|--crash-reporter-id 6859d24c-cfc6-43a1-9d5e-efbb7bb083ce --crash-reporter-id 6859d24c-cfc6-43a1-9d5e-efbb7bb083ce|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30384385
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
vscop804:30404766
vscop341:30404997
vsrem710cf:30405999
vscexrecpromp3t2:30407763
vscop841cf:30413486
vscop927cf:30413487
vscop436cf:30413488

```

</details>

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if you're still impacted by this issue.
