### ISSUE TITLE
Error: File entry unexpectedly large: nnnnnn (max: 4096)

### ISSUE THREAD

**Issue by morningtundra** [microsoft/vscode-mssql#17181]
- MSSQL Extension Version: ms-mssql.mssql-1.12.0\sqltoolsservice\3.0.0-release.174
- VSCode Version: November 2021 (version 1.63.2)
- OS Version: Win 10

Steps to Reproduce:

1. Launch VSCode
2. Install mssql extsnion OR allow existing install to update

Error:

```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to c:\Users\cwhite2\.vscode\extensions\ms-mssql.mssql-1.12.0\sqltoolsservice\3.0.0-release.174\Windows.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.174/microsoft.sqltools.servicelayer-win-x64-net5.0.zip
(59671 KB) .................... Done!
Installing ...
[ERROR] Error: File entry unexpectedly large: 28229 (max: 4096)
```

The large file size (`28229`) varies each time I try to reproduce this issue.

**Comment by kburtram** [comment]
@morningtundra the first time vscode-mssql launches after update it will try to download an out-of-proc tools service binary, which provides the actual database interaction implementation.  For some reason this download is failing, though we use a pretty standard node module to do the actual downloading (i.e. the extension doesn't actually implement the file transfer functionality, but uses a common API).

As a workaround you could try manually downloading https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.174/microsoft.sqltools.servicelayer-win-x64-net5.0.zip and extracting the contents into c:\Users\cwhite2\.vscode\extensions\ms-mssql.mssql-1.12.0\sqltoolsservice\3.0.0-release.174\Windows to avoid having the extension trying to do this.

We can investigate where the `File entry unexpectedly large` error message is originating from.

**Comment by morningtundra** [comment]
This is the first file it fails on and then errors on every subsequent file in the zip archive...

![image](https://user-images.githubusercontent.com/49348167/146586502-d9d10747-cf75-4d9c-b721-b67cdddab3d4.png)

**Comment by kburtram** [comment]
@morningtundra it appears as if something is holding a lock on these files.  You could try (1) delete all the files from c:\Users\cwhite2.vscode\extensions\ms-mssql.mssql-1.12.0\sqltoolsservice\3.0.0-release.174\Window then decompress the ZIP into a different new folder.  Then copy the decompressed files into the above directory.

Typical reasons for locking are that an application in the directory is running, antivirus scans, etc.  You may ensure all instances of vscode are closed, and check the task manager to ensure no programs are running from the target directory.  Rebooting often frees locks held by OS system tasks.  Please let me know if that doesn't help workaround this issue.

**Comment by morningtundra** [comment]
@kburtram, thanks for looking at this issue. I'm unable to Unpack this zip file in any directory at all, even after rebooting and disabling anti-virus. Can you confirm this Unpacks ok for you (and not a transitory build anomaly)?

https://github.com/microsoft/sqltoolsservice/releases/download/v3.0.0-release.174/Microsoft.SqlTools.ServiceLayer-win-x64-net5.0.zip

If so, then it's my local problem and not something I should be bothering you with :-)

![image](https://user-images.githubusercontent.com/49348167/146608805-a4cda843-20f1-4079-b231-02e0e58c6ee2.png)

**Comment by kburtram** [comment]
@morningtundra I double-checked that the ZIP extracts fine for me manually (screenshot below).  All users of the extension will download and extract this file, so if there was a file corruption issue then it would have wide-spread impact.  Unfortunately the error code is "Unspecified Error", which doesn't provide a lot to go on.  Perhaps a different compression tool such as 7zip would give a better error message at least.  Please let us know if there's anything else we can assist with.

![image](https://user-images.githubusercontent.com/599935/146609807-1f82bcaa-04b4-4287-a4cc-29c8632f872e.png)

**Comment by morningtundra** [comment]
@kburtram thank you for taking the time to look at this but 7Zip didn't like it either. I'll take it up with corporate IT. Go ahead and mark this as closed.

![image](https://user-images.githubusercontent.com/49348167/146610851-3bbc0529-d90a-4dfd-847b-41ce28207a61.png)

**Comment by morningtundra** [comment]
Manual, offline install procedure works.

**Comment by kburtram** [comment]
Closing based on previous comment.  Thanks!
