### ISSUE TITLE
Notebook support enhancement

### ISSUE THREAD

**Issue by tomgross** [microsoft/vscode-mssql#17185]
- MSSQL Extension Version: 1.12.0
- VSCode Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open SQL file
2. Allow combining SQL statements and markdown documentation via notebook extension of VSCode.

**Comment by Charles-Gagnon** [comment]
@chlafreniere FYI

@tomgross VS Code has native support for Notebooks now - https://code.visualstudio.com/blogs/2021/08/05/notebooks

SQL support can be added via the [.NET Interactive](https://devblogs.microsoft.com/dotnet/net-interactive-with-sql-net-notebooks-in-visual-studio-code/) extension 

Let us know if these don't support your use case!
