### ISSUE TITLE
Latest version crashes and does not start correctly

### ISSUE THREAD

**Issue by gdvallance** [microsoft/vscode-mssql#17180]
- MSSQL Extension Version: v1.12.0 (Last updated 15/12/2021)
- VSCode Version: 1.63.2
- OS Version: Windows 10

Steps to Reproduce:

1. Uninstall `mssql`
2. Reinstall `mssql`

This occurred after a recent update? So I uninstalled and reinstalled the extension which is why the above is the steps I had to reproduce.

Get following messages:
"The AzureResourceProvider server crashed 5 times in the last 3 minute ..."
"mssql:SQL Tools Service component could not start."

Output from the console:
```text
Error:
   An assemly specifed in the application dependencies maifest (SqlToolsResourceProviderServie.deps.json) was not found:
     package: 'Microsoft.Azure.Management.Sql', version: '1.41.0-preview'
     path: 'lib/netstandard2.0/Microsoft.Azure.Management.Sql.dll'
[Info -  <time> Connection to server got closed. Server will restart

[Repeated a further 4 times.]
```

The extension (and for the second time recently) has apparently lost ALL the connection strings to the MSSQL servers I talk too. **This is very frustrating**.

The connection section (if you open up the side-bar) just hangs ...

Anything else you want/need?

What can I do to further help debug and support sorting this issue? Up until now this has been a stellar extension.

**Comment by cmooring** [comment]
I'm also now experiencing this issue. What can we supply to help investigate this?

MSSQL Extension Version: v1.13.0
VSCode Version: 1.65.2
OS Version: Windows 10
DotNet Version: 5.0.15 (SDK 5.0.406)
```
.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

I get a similar error reported as @gdvallance;
"The AzureResourceProvider server crashed 5 times in the last 3 minutes. The server will not be restarted."

In my console window, I get;

```
Failed to create CoreCLR, HRESULT: 0x80004005
[Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
[Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
[Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
[Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
Failed to create CoreCLR, HRESULT: 0x80004005
```

**Comment by cmooring** [comment]
> I get a similar error reported as @gdvallance; "The AzureResourceProvider server crashed 5 times in the last 3 minutes. The server will not be restarted."
> 
> In my console window, I get;
> 
> ```
> Failed to create CoreCLR, HRESULT: 0x80004005
> [Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
> Failed to create CoreCLR, HRESULT: 0x80004005
> [Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
> Failed to create CoreCLR, HRESULT: 0x80004005
> [Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
> Failed to create CoreCLR, HRESULT: 0x80004005
> [Info  - 11:07:06 pm] Connection to server got closed. Server will restart.
> Failed to create CoreCLR, HRESULT: 0x80004005
> ```

After messing with this for a while, I found that installing a previous version. I went back to 1.11.0, and then through all versions to see where it stopped working. However, by the time I got back to 1.13.0, it seemed to install, and now VSCode starts without the crash messages. This doesn't help diagnose what the issue was, but if anyone else faces this, it could be a work around.

**Comment by gnpar** [comment]
I was experiencing the same problem, fixed it by:

- Uninstalling mssql extension
- Removing all related files from `~/.vscode/extensions` (on linux):

```
rm -fr ms-mssql.data-workspace-vscode-0.2.1 ms-mssql.mssql-1.15.0 ms-mssql.sql-bindings-vscode-0.2.0 ms-mssql.sql-database-projects-vscode-0.17.1
```

- Reinstalling the extension

**Comment by kburtram** [comment]
Cleaning up older issues for previous extension versions.  Please let us know if you're still impacted by this problem.  These appear to be assembly load issues, which could be related to the .Net runtime configuration in a particular environment.
