### ISSUE TITLE
Latest version for offline installation

### ISSUE THREAD

**Issue by WolfgangKluge** [microsoft/vscode-mssql#17184]
I've to use the offline installation the first time but I fail already at the simple task finding the latest version.

Currently, the latest release is v1.12.0
- on the [overview page](https://github.com/microsoft/vscode-mssql)  there's a link to "v1.6.0"
- if I [follow this link](https://github.com/microsoft/vscode-mssql/releases/tag/v1.5.0-alpha.14) I'm in tag `v1.5.0-alpha.14` (but the downloads are `v1.6.0` (at least confusing to me)
- newer alpha releases have more recent versions - but the [newest `v1.5.0-alpha.397`](https://github.com/microsoft/vscode-mssql/releases/tag/v1.5.0-alpha.397) is on `v1.10.1`
- there's a `Preview Release 1.10.2` but every other entry seems older - and I'm not able to find `v1.12.0` in there

What I'm doing wrong here?

**Comment by WolfgangKluge** [comment]
Ok. I can download the latest version from the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql). Since I'm still curious, I'll leave this question open anyway (hope, that's ok).

**Comment by Charles-Gagnon** [comment]
We don't currently upload platform-specific versions of the extension (the Github releases are very out of date, I'll work on at least making that updated with the latest release).

Could you explain your situation a bit more about why you need to have an offline installation option for the extension?

**Comment by WolfgangKluge** [comment]
I've never managed to get the installation working behind the company proxy (so #779 and others are still open for me)

**Comment by waltiam** [comment]
My corporate development server is behind a firewall and it does not allow direct access to GitHub.  So when I manually install the extension and attempt to run it, the first thing it does attempt to connect to github to install components.  How come there is no well documented way to install the components manually?

**Comment by kzhui125** [comment]
any updates @Charles-Gagnon  ?
we need offline installation

**Comment by Charles-Gagnon** [comment]
I've updated the release page with platform-specific packaged versions of the VSIX. 

https://github.com/microsoft/vscode-mssql/releases/tag/v1.13.0

You can download this separately and then transfer it to the firewalled machines as needed.

1. Download the VSIX appropriate to your platform/architecture
2. Transfer to the machine you wish to install the extension on
3. Run the `Extensions: Install from VSIX` command in VS Code and select the VSIX OR use the `--install-extension <path-to-vsix>` command line parameter and select the VSIX that was downloaded/transferred

This should then install the extension with the appropriate SqlToolsService already installed, which means it shouldn't try to download the service upon startup. Let us know if you have any issues with this!
