### ISSUE TITLE
A11y_mssql for VSCode_Message Window_Keyboard:After pressing tab key(Ctrl+M) from "More actions" keyboard focus is going to bottom status bar instead of going to the "messages" dropdown.

### ISSUE THREAD

**Issue by Roopesh-T** [microsoft/vscode-mssql#17192]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yMAS;#A11yTCS;#BM_mssql for VSCode_Jan2022;#mssql for VSCode;#Win32;#FTP;#DesktopApp;#A11ySev2;#Keyboard;#AINotInScope;#FocusOrder;#WCAG2.4.3;#Regressed:03-02-2023;

## Environment Details:
Application Name: mssql for VSCode
Windows Version: Win11

## Repro Steps:

1. Open Visual studio code 
2. Tab till extension button and search for "mssql"
3. Tab till install and move to the SQL Server  button
4. Tab till Add Connection Button and insert the valid credentials
5. Right click on the server/database node you want to run the new query on.
6. Press enter “New Query” write any valid query and click on "Execute query button"
7. Message Window will open and check if the focus order is correct in message window.

## Actual:
After pressing tab key(Ctrl+M) from "More actions" keyboard focus is going to bottom status bar instead of going to the "messages" dropdown.

**Similar issue is also observed in Select top 1000 Results window_focus order is coming from bottom to top.**

## Expected:
After pressing tab key(Ctrl+M) from "More actions" keyboard focus should go to "messages" dropdown bottom instead of going to the status bar.

## User Impact:
Keyboard users will face difficulty in navigating the Message Window
## Attachments
![17192_A11y_mssql for VSCode_Message Window_Keyboard](https://user-images.githubusercontent.com/86601127/149113178-15376054-04c4-43fe-a40e-74da26950f16.gif)

**Comment by smartguest** [comment]
This issue appears to be caused either by the way dividers are arranged in the extension or how vscode handles elements in windows. This may be fixed by changing the way elements are arranged in vscode-mssql (need to know how vscode determines what element to tab next)

**Comment by smartguest** [comment]
Closing as this is standard vscode behavior with webview based windows. This is demonstrated as when you open an IPYNB notebook in vscode, the same tab behavior is seen there as well.

**Comment by Roopesh-T** [comment]
@smartguest **Please reopen this bug** and visit the OH: [C&AI Accessibility Team (office365.com)](https://outlook.office365.com/owa/calendar/microsoft2779007@microsoft.onmicrosoft.com/bookings/)
book a slot, for discussing this bug with SMEs

**Comment by Roopesh-T** [comment]
The issue is still repro in the latest env
![216575569-acdc8f4a-0d0c-4911-8672-31a37b6a4167](https://user-images.githubusercontent.com/86601127/216596079-9d5ee802-dd3c-4f06-a2e6-127233b61bf0.png)
please reopen the bug.
![17192_repro](https://user-images.githubusercontent.com/86601127/216596136-0366e268-006a-4aa3-adfd-214628884db5.gif)

**Comment by Roopesh-T** [comment]
Closing the bug, as the bug https://github.com/microsoft/vscode/issues/166768 is the exact same issue. and the team is following up on that bug.
**Git Hub Tag**: #closed;
