### ISSUE TITLE
A11y_mssql for VSCode_Select top 1000 Results window_Usability:When using Ctrl+Alt+arrow keys to navigate between cells, to column 1 and row 1 screen reader is not announcing any data in the cell, since there is no data in the cell.

### ISSUE THREAD

**Issue by Roopesh-T** [microsoft/vscode-mssql#17208]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yUsable;#A11yTCS;#BM_mssql for VSCode_Jan2022;#mssql for VSCode;#Win32;#FTP;#DesktopApp;#A11ySev4;#AINotInScope;

## Environment Details:
Application Name: mssql for VSCode
Windows Version: Win11

## Repro Steps:

1. Open Visual studio code 
2. Tab till extension button and search for "mssql"
3. Tab till install and move to the SQL Server  button
4. Tab till Add Connection Button and insert the valid credentials
5. After adding the server move to database expand it -->System database expand-->Master expand-->Tables expand -->System table expand and right click on it and select top 1000 option
6. Select top 1000 window will open tab to Results window 
7. Run NVDA 
8. Tab to the table use Ctrl+Alt+arrow keys to navigate between cells to column 1 and row 1 and check if the screen reader is announcing any data in the cell.

## Actual:
When using Ctrl+Alt+arrow keys to navigate between cells, to column 1 and row 1 screen reader is not announcing any data in the cell, since there is no data in the cell.

**Similar issue is also observed in JAWS**

## Expected:
When usis Ctrl+Alt+arrow keys to navigate between cells, to column 1 and row 1 screen reader should announce data in the in the cell as "S.No"

## User Impact:
Screen reader users will face difficulty if no data is present in the cell.
## Attachment
![17208](https://user-images.githubusercontent.com/86601127/149321727-7578381d-f1ee-416d-afa4-0076eb9b3634.gif)
![17208 1](https://user-images.githubusercontent.com/86601127/149324786-51271ea0-8e89-47d8-b2da-314b4e5390de.gif)

**Comment by smartguest** [comment]
There is literally no value there for the screen reader to read from, it's going to be annoying when a user navigates to the space, there should be a very small description for that small cell block indicating it's the row number column, that can be implemented within the query tables if possible, having something like, "Line number" in the row might help make it more descriptive for users.

**Comment by smartguest** [comment]
Closing as this is mainly an upstream issue related to the grid library and is already closed for exclusion in ADS (for similar issues), issue is non-blocking:

https://github.com/microsoft/azuredatastudio/issues/6662
https://github.com/microsoft/azuredatastudio/issues/6688
