### ISSUE TITLE
扩展意外终止

### ISSUE THREAD

**Issue by BluesVN** [microsoft/vscode-mssql#17211]
所需的数据太大，无法直接发送。我们已经将其写入剪贴板，请粘贴。
Issue Type: <b>Bug</b>

升级新版vscode 该扩展会大量占用CPU
最终导致扩展程序意外终止

Extension version: 1.12.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (3.90GB free)|
|Process Argv|--crash-reporter-id 88fcc0c0-5e99-4190-84b4-1c6da78fc0af|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dsc:30421290
pythonvs932:30410667
vscop804cf:30404767
vscop940:30404999
vsrem710cf:30416617
vsccppwtstudy:30421978

```

</details>

**Comment by kburtram** [comment]
Thanks for filing this issue.  Unfortunately we're only able to track issues written in English.  This is important so that everyone on the development team is able to follow conversations on the repo.  Please file the issue in English if possible.
