### ISSUE TITLE
from  flask_mysqldb import MySQL

### ISSUE THREAD

**Issue by Nourfaress** [microsoft/vscode-mssql#17228]
Which is library should I get on macos to fix this issue

**Comment by Nourfaress** [comment]
macs-MacBook-Pro:~ mac$ /usr/local/bin/python3 /Users/mac/Flask-app.py
Traceback (most recent call last):
  File "/Users/mac/Flask-app.py", line 3, in <module>
    from flask_mysqldb import MySQL
ModuleNotFoundError: No module named 'flask_mysqldb'

**Comment by kburtram** [comment]
@Nourfaress thanks for opening this issue.  This repo is for the MSSQL for VSCode extension and isn't related to MySQL database.  I'm not sure the answer to your question, but I can confirm it's unrelated to this project.  You may try asking here https://github.com/cyberdelia/flask-mysql/.
