### ISSUE TITLE
Should be able to view connection information without going to settings.json

### ISSUE THREAD

**Issue by davidpcaldwell** [microsoft/vscode-mssql#17220]
I successfully created a connection profile using integrated authentication and gave it a friendly name, but later I went back to try to remember exactly what it represented and couldn't figure it out.

I wanted to right-click on the connection in the Connections tab and look at the underlying data. But there's no option for that; there are only options for querying, disconnecting, etc.

Even searching through the settings in the VSCode settings UI I couldn't find much. Eventually I did see the UI option to look in settings.json and was able to look there to find what I needed.

But this seemed like a lot for what's a pretty basic function -- a UI for connection profiles should, in my view, be a CRUD UI, where connections can not just be created and deleted but also examined and updated.

**Comment by Benjin** [comment]
As of a couple releases ago, you now can!  Update to the latest version, and enable the `Enable Modern Experiences` config flag:

![Image](https://github.com/user-attachments/assets/e8398022-658f-4072-9fca-2fa677e6259b)

You can read more about the connection dialog we added (and other new features) [here](https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#connection-dialog).
