### ISSUE TITLE
mssql: Execution failed: Could not find the resource "Microsoft.SqlTools.ManagedBatchParser.Localization.SR.resources" among the resources "Microsoft.SqlTools.ManagedBatchParser.SR.resources" embedded in the assembly "Microsoft.SqlTools.ManagedBatchParser", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.

### ISSUE THREAD

**Issue by vaqxai** [microsoft/vscode-mssql#17221]
- MSSQL Extension Version: 1.12.0
- VSCode Version: 1.63
- OS Version: 20H2

Steps to Reproduce:

1.open a .tsql extension file
2.use "execute query" on a query

**Comment by smartguest** [comment]
The localization resources haven't been updated in a while due to the localization process no longer functioning as of late, for now a manual fix is necessary

**Comment by vaqxai** [comment]
It only happens when executing a query that contains the 'GO' statement.

**Comment by smartguest** [comment]
@vaqxai to clarify, there is no fix for the user side. It's something that will have to be looked at by our team.

**Comment by smartguest** [comment]
Same issue was found here: https://github.com/microsoft/azuredatastudio/issues/17967
