### ISSUE TITLE
A sql editor must have focus

### ISSUE THREAD

**Issue by kharigardner** [microsoft/vscode-mssql#17261]
Issue Type: <b>Bug</b>

trying to run a sql create table script but everytime I try to run I get the focus error. 

Extension version: 1.12.0
VS Code version: Code 1.64.2 (f80445acd5a3dadef24aa209168452a3d97cc326, 2022-02-09T22:02:28.252Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.82GB free)|
|Process Argv|--crash-reporter-id d3a979cd-5ed1-40c2-a951-fe44840d0000|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30425749
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30438340
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrt:30437039
vsrem710:30416614
vscop841cf:30438916
pythonvsnew555:30436484
vsbas813:30436447
vscscmwlcmc:30438804
helix:30438806

```

</details>

**Comment by alexdaguplo** [comment]
I have the same problem when opening  large sql file. I already set the language to SQL but still gives me the same error

**Comment by kburtram** [comment]
I am unable to repro this with the provided description.  Could you please let us know if you're still impacted by this issue, and if so please provide additional details on the steps required to reproduce and the observed behavior?  Thanks!
