### ISSUE TITLE
Update readme for Feb release

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#17263]
- MSSQL Extension Version: `1.12.0`

We need to update README.md file and package.json version, and port to release branch for Feb release.

**Comment by Charles-Gagnon** [comment]
The version is already updated FYI 

https://github.com/microsoft/vscode-mssql/pull/17259

**Comment by kburtram** [comment]
@Charles-Gagnon thanks!  I'll use this issue to track getting the readme packaged in the VSIX updated.

**Comment by erpett** [comment]
Readme has been updated as of https://github.com/microsoft/vscode-mssql/pull/17274
