### ISSUE TITLE
add SQL binding when functions project is within a folder asks to create a new project

### ISSUE THREAD

**Issue by dzsquared** [microsoft/vscode-mssql#17269]
not a ship blocker

- MSSQL Extension Version: RC 1.13
Version: 1.64.2 (Universal)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:00:58.347Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

Steps to Reproduce:

1. open an empty folder
2. add a folder, we'll call it "functions"
3. create a functions project within "functions"
4. open object explorer and try to add a sql binding to a table

![2022-02-18_17-20-10 (1)](https://user-images.githubusercontent.com/12227241/154780321-beb00ded-ae95-465f-8934-ac00e9a185fa.gif)

**Comment by VasuBhog** [comment]
Hmm, interesting catch. An azure function project folder inside another folder isn't caught. I will test and address this.

**Comment by VasuBhog** [comment]
Another interesting thing I saw was that the `Azure Functions: Create Project` does ask which folder it should create the folder in. So if I wanted to create a function in a specific folder it would just use the parent instead.
