### ISSUE TITLE
No icon on the sidebar to open the Object Explorer

### ISSUE THREAD

**Issue by Fedefirewall** [microsoft/vscode-mssql#17279]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. install the extension

Simpli the icon is missing, tried to reinstall the extension and vs code too
![image](https://user-images.githubusercontent.com/61513937/155984428-a8d600fd-467c-4a8a-8148-cdbcf3e8ef9b.png)

**Comment by dzsquared** [comment]
@Fedefirewall if you right-click on the sidebar, is there an option for "SQL Server" to select?

**Comment by Fedefirewall** [comment]
> @Fedefirewall if you right-click on the sidebar, is there an option for "SQL Server" to select?

No, the issue persists on another PC

**Comment by Charles-Gagnon** [comment]
And could you also verify that your user settings.json is valid? We've seen issues with invalid settings causing the extension to crash.

(You can view it by running the `Preferences: Open Settings (JSON)` command)

**Comment by Fedefirewall** [comment]
![image](https://user-images.githubusercontent.com/61513937/156071330-ab9c5ea2-dd91-4db9-8230-5c7b4119dbb5.png)
Erorrs seem ok, and settings.json too, no errors

**Comment by chlafreniere** [comment]
@Fedefirewall can you confirm the following:
- VS Code version
- MSSQL Extension version

**Comment by Fedefirewall** [comment]
**VS CODE**
Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**EXTENSION**
![image](https://user-images.githubusercontent.com/61513937/156159081-7b99d6c8-1ef3-4fe1-9b6d-345946518122.png)

**Comment by Fedefirewall** [comment]
These are all the extensions i have installed, note that i intsallted SQLTools and SQLTools Microsoft  SQL Server/Azure only after the problem, so i dont think they are causing it 
![image](https://user-images.githubusercontent.com/61513937/156159459-4663949c-fc48-4809-aa07-939fcd7ea024.png)
![image](https://user-images.githubusercontent.com/61513937/156159461-eda44bc6-666e-4711-8668-5a0bd8d65fdb.png)

**Comment by Fedefirewall** [comment]
Ok i solved.
I uninstalled completely visual studio code and all files under different folders.
Then when i reinstalled vs code and installed right after the extension, all worked, but as soon i logged in and turned on setting sync, the icon disappeared.
so i manually copied the settings.json that was on the cloud and pasted in my local settings.json (that contained only the mssql settings at that point), then i manually reinstalled all the other extensions that i had. 
now everything seems to work. 
should i close the issue?

**Comment by Charles-Gagnon** [comment]
Interesting that the settings sync broke this, it does seem to point to an issue with the settings file though.

If you're not seeing the issue and are back where you were before then you can close this issue, but if you have any more information or see the issue again definitely let us know and we can try to find out more information about what's going on!

**Comment by mattspeterson** [comment]
I can confirm this issue as well. In @Fedefirewall's suggested solution above, if you replace step 3 with simply turning settings sync back on, you can watch the mssql side bar icon disappear. The mssql extension itself seems to still work (I can connect to a SQL database and run queries, for example).

**Comment by Fedefirewall** [comment]
> Ok i solved. I uninstalled completely visual studio code and all files under different folders. Then when i reinstalled vs code and installed right after the extension, all worked, but as soon i logged in and turned on setting sync, the icon disappeared. so i manually copied the settings.json that was on the cloud and pasted in my local settings.json (that contained only the mssql settings at that point), then i manually reinstalled all the other extensions that i had. now everything seems to work.
> 
> So to solve this,
> 
> 1. basicaly uninstall and delete every file related to vscode (https://debug.to/1074/how-to-uninstall-vs-code-completely)
> 2. reinstall vs code and before doing anything else install the msqql extension
> 3. Try to return to the previous state of your vs code by copying and pasting all lines in settings.json
> 4. reinstall all extension
>    should i close the issue?

**Comment by imsomdev** [comment]
Facing same issue. And don't want to uninstall vs code
