### ISSUE TITLE
Add support for Rocky Linux

### ISSUE THREAD

**Issue by AtomBaf** [microsoft/vscode-mssql#17294]
- MSSQL Extension Version: 1.13.0
- VSCode Version: 1.63.0
- OS Version: Rocky Linux 8

Steps to Reproduce:

1.Install the extension from a Rocky Linux distribution
2.The second step of installation will download a microsoft.sqltools.servicelayer-rhel-x64-net6.0.tar.gz file a untar it under `~//.local/share/code-server/extensions/ms-mssql.mssql-1.13.0/sqltoolsservice/3.0.0-release.205/CentOS` directory
3.After that, the plugin is trying to access the `~//.local/share/code-server/extensions/ms-mssql.mssql-1.13.0/sqltoolsservice/3.0.0-release.205/Ubuntu16` directory instead, which does not exist
4. I solved the problem by making a symlink from Ubuntu16 to CentOS

So, apparently in the `platform.ts` file there is no case for Rocky Linux. Should this be added in [`getRuntimeIdHelper`](https://github.com/microsoft/vscode-mssql/blob/main/src/models/platform.ts#L333) and below?

**Comment by AtomBaf** [comment]
Fyi, here is the content of the `/etc/os-release` file:
```
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

**Comment by kburtram** [comment]
Closing as "out-of-scope".  We currently build generic Linux .Net binaries that should work on most distos, but we only officially test on Redhat and Debian variants.

**Comment by AtomBaf** [comment]
Too bad. It's seems that even arch, elementary, oracle linux and [a lot more](https://github.com/microsoft/vscode-mssql/blob/main/src/models/platform.ts#L347) are taken into account. Rocky is probably one of the most popular distro today. Having to manually symlink after installation is just a pain, but I'll stay like this as of today.

For ref: https://linuxiac.com/rocky-linux-is-the-most-preferred-enterprise-linux-distribution/

**Comment by kburtram** [comment]
@AtomBaf I reopen to investigate.  It sounds like there may be a bug in downloader, as the same directory such be used at download time and runtime.

**Comment by kburtram** [comment]
I wasn't able to repro this issue with the latest Rocky, VS Code and MSSQL extension.  I see that the sqltoolsservice files are going into a folder named Ubuntu16, but they seem to get extracted and run fine from there (see screenshot below).  There is only one version of the .Net binaries for all Linux distros, so the path name is a bit of an implementation detail, though we do plan to change to something like "Linux" in a future release.

Please let me know if you're still experiencing this issue with the latest extension version, and if so what error messages you're encountering during the sqltoolsservice archive extraction.  Thanks!

![image](https://github.com/user-attachments/assets/e341892a-1e51-4a4b-8507-52c254873faf)

**Comment by kburtram** [comment]
Closing based on above comment.  The extension appears to be working with latest versions of various products.  Please let us know if you're still impacted by this issue.  Thanks!
