### ISSUE TITLE
Connect windows authentication on other session??

### ISSUE THREAD

**Issue by aliduyar** [microsoft/vscode-mssql#17329]
- MSSQL Extension Version:1.14.1
- VSCode Version:1.66
- OS Version: Win 11

I want to log in with my windows authentication on a different computer.  I can connect using integrated on my own computer, but how should I connect in a different session?

**Comment by cheenamalhotra** [comment]
@aliduyar you'd need to establish trust between the two machines by joining them to same domain/network by joining them to an Active Directory or create a Windows Domain Controller and connect second machine with it.

Basically, your machines should be in the same domain to be able to establish domain trust. You will then be able to login with a "domain" user account from one machine to another.

**Comment by kburtram** [comment]
Closing based on the previous comment.  We are unable to support arbitrary Windows domain accounts in the connection experience due to limitations in SQL client driver dependency.
