### ISSUE TITLE
Windows 10 ARM64 Support

### ISSUE THREAD

**Issue by dtarachan-tlg** [microsoft/vscode-mssql#1733]
- MSSQL Extension Version: 1.9
- VSCode Version: 1.47.3
- OS Version: Windows 10, 2004, ARM64

Steps to Reproduce:

Since both Visual Studio Code and Microsoft SQL Tools Service (as of v2.0.0-release.63) have Windows 10 ARM64 builds, it would be great it this extension could add support for ARM64. I have a Surface Pro X and can help test, if required.

**Comment by openindustryorg** [comment]
+1 Currently fails on ARM64. Another Surface Pro X user here.

**Comment by alanrenmsft** [comment]
arm64 support for windows and mac will be available in the upcoming release.

**Comment by mkurz** [comment]
@alanrenmsft Awesome! Can you please make sure that it works also with Kernels that do not use 4k page sizes? For example I use Asahi Linux which uses a page size of 16k:
* https://asahilinux.org/
* Also see https://asahilinux.org/2022/03/asahi-linux-alpha-release/#known-broken-applications:
> The Asahi Linux kernel is compiled to use 16K pages.

Would be really nice if you consider that, thanks!

**Comment by mkurz** [comment]
@alanrenmsft I opened #17640

**Comment by alanrenmsft** [comment]
@mkurz Does VSCode work with Asahi Linux? if so, please install the attached mssql extension installer and give it a try.  If VSCode doesn't work, then you should open an issue in VSCode repo, this is the repo for the mssql extension.

1. Uninstall the mssql extension if it is already installed
2. Unzip the attached file.
3. Use the `Install from VSIX...` command in VSCode to install the preview version of mssql extension
![image](https://user-images.githubusercontent.com/13777222/227038666-b78eb76a-76ec-412c-82d9-78cf2b9e3c25.png)

[mssql-1.19.0.zip](https://github.com/microsoft/vscode-mssql/files/11044780/mssql-1.19.0.zip)
