### ISSUE TITLE
mssql module crashes upon startup / connection to on prem SQL server

### ISSUE THREAD

**Issue by umwireless** [microsoft/vscode-mssql#17333]
Version: 1.36.1
Commit: e56e1d931bbb110fe8f24751423c4e184bb8f22d
Date: 2022-04-21T21:19:26.480Z
VS Code: 1.59.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 4.18.0-383.el8.x86_64

Steps to Reproduce:

1. Install Azure Data Studio 1.36.1 (as recommended by 1.32)
2. Attempt to connect to saved SQL Server connection imported from Azure Data Studio 1.32
3. Fail.

**Comment by cheenamalhotra** [comment]
_Related issue: https://github.com/microsoft/azuredatastudio/issues/18844_

@umwireless This issue has been addressed with PR https://github.com/microsoft/vscode-mssql/pull/17425, I will proceed to close the issue as fixed in upcoming release.

Thanks!
