### ISSUE TITLE
Cannot expand connection node 

### ISSUE THREAD

**Issue by abist** [microsoft/vscode-mssql#1734]
Branch: main

Steps to Reproduce:

1. Make a connection to a Azure SQL Database.

Expected - It connects and expands in the Object Explorer 
Actual - Nothing happens and the connection is stuck.

When trying to remove the node, we get this error -
![Screen Shot 2020-08-10 at 1 20 03 PM](https://user-images.githubusercontent.com/6411451/89827312-5592dc80-db0c-11ea-925b-6fcece917b37.png)

**Comment by cssuh** [comment]
I am not able to repro, do you have any more details?

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/pull/1735
