### ISSUE TITLE
The MS SQL Extension stopped working and all connections setup got lost.

### ISSUE THREAD

**Issue by tarekahf** [microsoft/vscode-mssql#17344]
Today I noticed there was an update to MS SQL and looks like the update failed. Now, I see that the MS SQL Extension is not working, and all the connections that were set up are lost.

```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to c:\Users\fodler\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice\3.0.0-release.238\Windows.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.238/microsoft.sqltools.servicelayer-win-x64-net6.0.zip
(65826 KB) ..[ERROR] Error: Request error: ECONNRESET
```

Version Details:
```
Name: SQL Server (mssql)
Id: ms-mssql.mssql
Description: Develop Microsoft SQL Server, Azure SQL Database and SQL Data Warehouse everywhere
Version: 1.14.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

OS: Windows 10 Enterprise
VS Code Version: 1.67.2
```

I also installed yesterday SQLServer Tools extension and thought that this might have caused the issue. So, I removed it but it did not solve the problem.

I was able to download the ZIP file referenced in the error above, but didn't know what to do with it.

Please help.
Tarek

**Comment by Charles-Gagnon** [comment]
The error makes it seem like there was an issue downloading the SQL Tools Service (a separate executable that the MSSQL extension uses). If you restart VS Code do you still see that same error? It should retry the download again if you do this.

If you enter https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.238/microsoft.sqltools.servicelayer-win-x64-net6.0.zip into your browser URL bar can you download the zip directly?

If you still see the error in VS Code but can download the zip then you can follow these steps to manually place the service files : 

1. Close all instances of VS Code
2. Unzip the contents of the zip into a folder
3. Copy the contents of that folder into `%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice` (creating the `sqltoolsservice` folder if necessary). If done correctly this should be a valid path `%LOCALAPPDATA%\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice\3.0.0-release.238\Windows\MicrosoftSqlToolsServiceLayer.exe`
4. Start VS Code

Now the extension should be able to start.

**Comment by tarekahf** [comment]
Thank you, @Charles-Gagnon 

I am able to download the ZIP file. It seems there is some policy blocking the file initially, but I was able to resume. Tech support provided me proxy config but not sure where to apply the proxy config in vs code and not sure if this will solve the problem.

I unzipped the file mentioned, but I didn't find the file `%LOCALAPPDATA%\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice\3.0.0-release.238\Windows\MicrosoftSqlToolsServiceLayer.exe`.

I found the file `MicrosoftSqlToolsServiceLayer.exe` under `%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice` instead. I did follow the instructions you provided but when I restart VS code, it will try to download the file again, and I will get the same errors I reported earlier. See the screenshot for more details.

```
mssql: Failed to load Sql Tools Service
```
![vscode error mssql extension](https://user-images.githubusercontent.com/20842027/170118272-7ffa8ab0-bbd1-4364-9e4b-f771be00b163.PNG)

Could you please review the steps you mentioned? It seems there is something missing or I am doing something wrong.

Regards,
Tarek

**Comment by tarekahf** [comment]
I copied the unzipped folder into `%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice\3.0.0-release.238\Windows` and it worked. Thank you so much!

Can you tell me where to set up the proxy details in vscode for the future?

Tarek

**Comment by Charles-Gagnon** [comment]
My apologies, I did indeed put the wrong path in the instructions! I've updated it to be correct now. Glad it worked for you!

I'll have to look into the proxy settings, I don't believe we have that documented anywhere (if it's even supported for this case)

**Comment by tarekahf** [comment]
Thank you. I'm almost 100% sure that I came across such setting but I can't remember where I found it. I'll take it up with our tech team.

**Comment by Charles-Gagnon** [comment]
It looks like this code should be using the proxy settings from ADS 

![image](https://user-images.githubusercontent.com/28519865/170139114-878d94c8-22a5-47b0-8d1e-83c6bebec84c.png)

So you could try those out to see if they work
