### ISSUE TITLE
can not run in .txt

### ISSUE THREAD

**Issue by lanweipeng** [microsoft/vscode-mssql#1736]
- MSSQL Extension Version:1.9.0
- VSCode Version:1.47
- OS Version:win10

Steps to Reproduce:

1.write some sql code in .txt,but not find button to run
2.write some sql code in .sql,can find button to run
I want to .txt can show run button too.

**Comment by dzsquared** [comment]
@lanweipeng 
The editor needs to be in SQL "language mode" for the extension to work - but this can be done for txt files!


In the lower right where VS Code shows "Plain Text" for your txt file, click and VS Code will open a language mode drop down.  If you select "SQL" the extension will activate in that text editor.
![image](https://user-images.githubusercontent.com/12227241/90027149-0f08c380-dc6d-11ea-8ca4-44a08007287a.png)


For more info:
https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file
