### ISSUE TITLE
Problem reconnecting to Database

### ISSUE THREAD

**Issue by blogcraft** [microsoft/vscode-mssql#1737]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.48.0
- OS Version: Windows 10

Steps to Reproduce:

1. Create Database connection saving password
2. Close VS Code
3. Open VS Code
4. Try to connect to the database
5. mssql: Connection error : Error de inicio de sesión del usuario 'sa'.
6. Retry profile creation? Yes
7. All values are the same but the Password that is filled has different number of chars (is it saving it wrong??)

**Comment by abist** [comment]
@blogcraft Can you try recreating the connection? You can remove the connection from your user settings manually if deleting the connection doesn't work. If there was an incorrect password, that should get rid of it.

**Comment by kburtram** [comment]
Closing older issues without recent repro.  Please let us know if you're still impacting by this issue.  Regarding the question of password length on connection retry, the display string should be something like '******', where the number of * characters is fixed and not based on the content of the actual password.
