### ISSUE TITLE
Sql Server extension errors

### ISSUE THREAD

**Issue by Smartens-Larson** [microsoft/vscode-mssql#17383]
I just installed SQL Server v1.15.0...and I can't seem to get anything to work.

If I try any of the f1 (command pallate) commands it fails.

MS SQL: Connect -> gives error command 'mssql.connect' not found.

MS SQL: Add Connection -> gives error 'mssql.addObjectExplorer' not found.

MS SQL: Manage Connection Profiles -> gives error 'mssql.manageProfiles' not found.

i have tried uninstalling and reinstalling the Extension.  I have tried removing all other SQL extensions...then again uninstalling/reinstalling the MS SQL extension.  I have tried restarted VS Code...and I have tried restarting my computer.

Is there any other log file or way to see what is going on...and why it is failing?

Thanks

**Comment by Charles-Gagnon** [comment]
You can try these to see if there's anything indicating what the problem is. 

1. Command palette -> `Developer: Show Logs...` -> `Extension Host`
2. `Help` menu-> `Toggle Developer Tools` -> `Console` tab

**Comment by Smartens-Larson** [comment]
And from the Show Logs -> Extension Host.  It shows the following:

[2022-06-30 17:47:36.955] [exthost] [error] Activating extension ms-mssql.mssql failed due to an error:
[2022-06-30 17:47:36.955] [exthost] [error] Error: Request error: CERT_SIGNATURE_FAILURE
	at ClientRequest.<anonymous> (c:\Users\smartens\.vscode\extensions\ms-mssql.mssql-1.15.0\out\src\languageservice\httpClient.js:46:24)
	at ClientRequest.emit (node:events:402:35)
	at TLSSocket.socketErrorListener (node:_http_client:447:9)
	at TLSSocket.emit (node:events:390:28)
	at emitErrorNT (node:internal/streams/destroy:157:8)
	at emitErrorCloseNT (node:internal/streams/destroy:122:3)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Charles-Gagnon** [comment]
Looks like there's an issue downloading the tools service, which is required to run the extension. Are you behind a firewall/proxy or something that would be causing these kinds of issues? 

You can try these steps as a potential workaround : 

1. Download https://github.com/microsoft/sqltoolsservice/releases/download/4.0.1.1/Microsoft.SqlTools.ServiceLayer-win-x64-net6.0.zip
2. Extract the zip
3. Copy the contents of the extracted folder (should be a bunch of folders and DLLs) into `%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.15.0\sqltoolsservice\4.0.1.1\Windows`
4. Restart VS Code and try to activate the extension again

**Comment by Smartens-Larson** [comment]
Yes. Behind a company proxy and firewall.  I will try to download at home and bring in on thumb drive.

Thanks.  I will let you know next week when back in the office.

From: Charles Gagnon ***@***.***>
Sent: Thursday, June 30, 2022 6:05 PM
To: microsoft/vscode-mssql ***@***.***>
Cc: Sam Martens ***@***.***>; Author ***@***.***>
Subject: [Ext] Re: [microsoft/vscode-mssql] Sql Server extension errors (Issue #17383)

CAUTION: This email originated from outside of the organization! Do not click links, open attachments or reply unless you recognize the sender's email address and know the content is safe!

Looks like there's an issue downloading the tools service, which is required to run the extension. Are you behind a firewall/proxy or something that would be causing these kinds of issues?

You can try these steps as a potential workaround :

  1.  Download https://github.com/microsoft/sqltoolsservice/releases/download/4.0.1.1/Microsoft.SqlTools.ServiceLayer-win-x64-net6.0.zip [github.com]<https://urldefense.com/v3/__https:/github.com/microsoft/sqltoolsservice/releases/download/4.0.1.1/Microsoft.SqlTools.ServiceLayer-win-x64-net6.0.zip__;!!CxzxHa7kK4Z_RA4!NMsUUo7zogqMOkCXIocO_-EDWx6HHxd6my1Bk-46Vo8WVyuGJkj3YSECJj50SMBLebAFSCDlYqliQZv8L5UMim_E9dk$>
  2.  Extract the zip
  3.  Copy the contents of the extracted folder (should be a bunch of folders and DLLs) into %USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.15.0\sqltoolsservice\4.0.1.1\Windows
  4.  Restart VS Code and try to activate the extension again

**Comment by Smartens-Larson** [comment]
Downloading the VSIX from Github on my home network. Then, bringing it into work on a thumbdrive and opening manually worked.

Now, the extension is working properly!  

Thanks for the help.
