### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Jerson-Lourenco** [microsoft/vscode-mssql#1738]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.10586`
- VSCode version: `1.48.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
@Jerson-Lourenco Thanks for opening this issue. Could you please elaborate on the problem you're facing and how we can repro this issue?
