### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by SSahiner** [microsoft/vscode-mssql#17381]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.15.0`
- OS Version: `Windows_NT x64 10.0.14393`
- VS Code version: `1.68.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Charles-Gagnon** [comment]
Closing this as there isn't any actionable information - please let us know if you can explain what the issue that you're experiencing is!
