### ISSUE TITLE
Improve documentation for testing the extension

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode-mssql#17394]
After https://github.com/microsoft/vscode-mssql/pull/17392 users would be able to do:
1. `gulp watch` in a terminal
2. Add breakpoint to a test file
3. Run gulp test in a separate terminal or run `gulp ext test`. 

This should either be documented or update an exiting launch task so that users can easily debug tests quickly.

**Comment by kburtram** [comment]
Cleaning up issue backlog.  Let's track this "engineering task" in the ADO if still needed.
