### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by saurabh-191** [microsoft/vscode-mssql#17390]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.15.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Charles-Gagnon** [comment]
Consolidating into https://github.com/microsoft/vscode-mssql/issues/17403
