### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Mahim-Sama** [microsoft/vscode-mssql#17403]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.15.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 19061,
		"activateCallTime": 2,
		"activateResolvedTime": 13636,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.data-workspace-vscode",
				"_lower": "ms-mssql.data-workspace-vscode"
			},
			"activationEvent": "api"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by Charles-Gagnon** [comment]
@kisantia @Benjin We've gotten a number of extension load issues at this point, with 2 of them specifically calling out data-workspace (and the other two not having the information on the extension causing the issue). 

Could you work on adding some logging so we can figure out what's getting stuck here? 13 seconds is a very long time for this to be activated. (I'd suggest using telemetry to alert us when something takes a long time to run)

**Comment by kisantia** [comment]
The extension was updated in the latest version (0.5.0) to no longer activate on *, so it should only activate if the workspace has a .sqlproj file or if the sql projects extension is used
