### ISSUE TITLE
When changing the password, it still tries to use the old cached tokens

### ISSUE THREAD

**Issue by Katzmann1983** [microsoft/vscode-mssql#17409]
MSSQL Extension Version: 1.15.0
    VSCode Version: 1.68.1
    OS Version: Windows 10 Enterprise 19042.1706

Steps to Reproduce:

1. Change password
2. The cached token will still be used

**Comment by cheenamalhotra** [comment]
Do you mean Change Password or Refresh access token?

**Comment by kburtram** [comment]
Closing based on non-response to previous clarification question.  Please let us know if you're still impacted by this issue.  Thanks!
