### ISSUE TITLE
SSL error even when encrypt is set to false

### ISSUE THREAD

**Issue by mohd-akram** [microsoft/vscode-mssql#17405]
I'm trying to connect to an SQL server that only accepts unencrypted connections. I've specified a connection in `mssql.connections` in settings and have set `encrypt` to false and yet I continue to get an SSL error:

```
mssql: Connection error : A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
```

- MSSQL Extension Version: 1.15.0
- VSCode Version: 1.69.2
- OS Version: Fedora 36

Steps to Reproduce:

1. Add a connection with `"encrypt": false`

**Comment by cheenamalhotra** [comment]
Hi @mohd-akram 

Pre-Login handshake is always encrypted no matter the encrypt setting, as it is to identify TLS protocol to use.
You may need to verify your target SQL Server and client OS (Fedora) can communicate, BOTH are updated to support TLS 1.2.

For further troubleshooting, you can read this doc: https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-troubleshooting-guide?view=sql-server-ver16#possible-reasons-and-solutions

**Comment by mohd-akram** [comment]
I cannot update the server, and it, AFAICT, does not support TLS. I have been able to connect to the server from client code (using typeorm, which uses the mssql npm library), but not from the VS Code extension. Surely if there's an "encrypt" option it should disable TLS? What is it supposed to do?

**Comment by cheenamalhotra** [comment]
What's the SQL Server version in use - if I may ask?

**Comment by cheenamalhotra** [comment]
You might be facing an issue with .NET 5.0+ and cipher suites on Linux distributions as we use .NET 6 to build extension. 
Could you try updating your system-wide crypto policies as recommended from link below?

https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux#recommended-action

I'm also keeping a close eye on issue https://github.com/dotnet/SqlClient/issues/1561 as its related.

**Comment by mohd-akram** [comment]
The SQL Server version:

```
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64) 
	Sep  7 2018 01:37:51 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
```

> Could you try updating your system-wide crypto policies as recommended from link below?

That actually worked! Thanks. I ran:

```
sudo update-crypto-policies --set LEGACY
```

I wonder if there's a way to make it work without changing the system policy, or perhaps by doing something on the server.

**Comment by cheenamalhotra** [comment]
Glad to know you're able to connect! ❤️ 

This is, as you can see documentation, a known issue since .NET 5.. and many applications are affected.
Let me know if you have any other query, or feel free to close the issue.
