### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by artjamnagar** [microsoft/vscode-mssql#17406]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.15.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 16083,
		"activateCallTime": 2,
		"activateResolvedTime": 12575,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.data-workspace-vscode",
				"_lower": "ms-mssql.data-workspace-vscode"
			},
			"activationEvent": "api"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by kburtram** [comment]
Cleaning up issues for previous extension versions.  Please let us know if this performance issue is still occurring on current version.  Thanks!
