### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by thuproofy** [microsoft/vscode-mssql#17408]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.15.0`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Charles-Gagnon** [comment]
Closing this since there's no actionable information, please reopen a new issue with the content copied to your clipboard or a description of the problem and we can help figure it out.
