### ISSUE TITLE
Connection does not update after being asked to re-enter information

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode-mssql#17419]
- MSSQL Extension Version: 1.16 (dev)
- VSCode Version: v1.70
- OS Version: MacOS 12.5

Steps to Reproduce:

1. Try to connect to a database that is saved in the connections viewlet (it should have incorrect login credentials)
2. Upon getting to the retry prompt that asks users to retry: 
<img width="396" alt="image" src="https://user-images.githubusercontent.com/23587151/184262316-2e86c36a-e5d9-4900-b18a-63c7b5e81274.png">

3. I enter the correct login info (password for example) and asks me to save (select yes):

<img width="499" alt="image" src="https://user-images.githubusercontent.com/23587151/184262369-2f9dd15b-16ac-4a6d-bac1-0805da78bd55.png">

4. It connects
5. Restart VScode and retry connecting

Current: It fails as it does not save the information user entered to correct the connection
Expectation: It should save the new information the user entered so that when they try again they don't have to enter it again

**Comment by Benjin** [comment]
Working with the [new connection dialog](https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#connection-dialog), released in 1.25
