### ISSUE TITLE
No edit connection option for existing connections

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/vscode-mssql#17420]
MSSQL Extension Version: 1.16 (dev)
VSCode Version: v1.70
OS Version: MacOS 12.5

There is currently no way to edit a saved connection (that I know of - possibly command palette) via right-clicking the connection in Object Explorer.  
![image](https://user-images.githubusercontent.com/23587151/184246882-b198bef3-2769-4e84-a37a-b558daace513.png)

There should be a way to prompt users to edit information and update it to the connection they selected.

**Comment by Benjin** [comment]
The new connection dialog went to public preview in 1.25, including the ability to edit existing connections!

https://github.com/microsoft/vscode-mssql/blob/main/FEATURES.md#connection-dialog
