### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by QuantumBoy1010** [microsoft/vscode-mssql#17436]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.16.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 20375,
		"activateCallTime": 3,
		"activateResolvedTime": 10805,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-mssql.data-workspace-vscode",
				"_lower": "ms-mssql.data-workspace-vscode"
			},
			"activationEvent": "api"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by kisantia** [comment]
@QuantumBoy1010 if you restart vscode a few times, is the data workspace start time consistently this slow? If you execute "F1 > Developer: Show Running Extensions" is data workspace the extension with the slowest startup activation time?

**Comment by kburtram** [comment]
Cleaning up perf issues for previous extension versions.  Please let us know if this is still impacting the current version.  Thanks!
