### ISSUE TITLE
Russian language in SQL give not readble string in result

### ISSUE THREAD

**Issue by MetaAbstract** [microsoft/vscode-mssql#1744]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 
- OS Version:
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:56:10.074Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.0-10-amd64
Steps to Reproduce:

1. SELECT 'Привет'
2. run
3. result in view as in JSON 
[
  {
    "(No column name)": "??????"
  }
]

**Comment by MetaAbstract** [comment]
English strings run ok.

**Comment by zombba** [comment]
@MetaAbstract 
Hello. It is usual result for varchar string.
You should use nvarchar string.
For example, SELECT N'Привет'

**Comment by MetaAbstract** [comment]
@zombba  thx!

**Comment by zombba** [comment]
@MetaAbstract please, close issue, if your problem is solved
