### ISSUE TITLE
MicrosoftSqlToolsServiceLayer.dll does not exist error

### ISSUE THREAD

**Issue by sudheer82** [microsoft/vscode-mssql#17454]
the extension load is failing with following error. this issue has surfaced recently

![image](https://user-images.githubusercontent.com/3577158/192697890-fe66709f-15b3-485d-a348-d5d69716999a.png)

`The application to execute does not exist: 'c:\Users\<user>\.vscode\extensions\ms-mssql.mssql-1.16.0\sqltoolsservice\4.2.1.5\Windows\MicrosoftSqlToolsServiceLayer.dll'.
[Error - 11:11:00 AM] Connection to server got closed. Server will not be restarted.`

if i roll back to v1.15.0, this issue is no longer seen

**Comment by Charles-Gagnon** [comment]
Does this path exist?

`c:\Users\<user>\.vscode\extensions\ms-mssql.mssql-1.16.0\sqltoolsservice\4.2.1.5\Windows\` 

If it does is there anything in it? If not then please try deleting the `4.2.1.5` folder and restarting VS Code to force it to redownload the tools service.

**Comment by kburtram** [comment]
Closing older issue without recent repro reports.  Please try to install the latest extension if you're still impacted by this issue.
