### ISSUE TITLE
Result windows disappear # VS Code

### ISSUE THREAD

**Issue by venuavasarala** [microsoft/vscode-mssql#17467]
Hi,
I am trying to run a SQL query in visual studio code but couldn't see result window and Messages windows. There is not error in query and data is fetching from database.

<img width="949" alt="image" src="https://user-images.githubusercontent.com/116671124/197843179-3a553964-789f-43f4-b931-6ca34973220f.png">

Your help is really appreciated..
Thanks,
Venu.

**Comment by Benjin** [comment]
@venuavasarala, can you check to see if you're still encountering this issue in the latest version of MSSQL?  I'm going to close this issue because there hasn't been any activity in a while, but please re-open it if the bug is still occurring in the latest release.
