### ISSUE TITLE
Refresh Credential Error: 

### ISSUE THREAD

**Issue by CoryKennedy** [microsoft/vscode-mssql#17468]
- MSSQL Extension Version: 1.16.0
- VSCode Version: 1.17.2
- OS Version: Windows_NT x64 10.0.19044

## Steps to Reproduce:

1. Add a connection to SQL Server in VS Code
2. Follow prompts to add a new connection, I am using Azure SQL Database with Azure AD - Multifactor Authentication
3. **Error**: mssql: Credential Error: Account credentials have expired. Please re-authenticate. 
4. Select option to _Refresh Credentials_
5. Follow prompts in browser to sign in with Azure AD account. 
6. **Error**:  **errorcode: this.stringLookup.getInteractionRequiredString is not a function**

## Things I have tried

-  Removed and add the MSSQL extension back
-  Rolled back to previous version of MSSQL extension
-  Cleared browser data 
-  Cleared credential manager data
-  Removed the MSSQL credential located in JSON editor
-  Manually created the MSSQL credential in JSON editor
-  Checked for updates to VS Code and All Extensions 

## Screen Shots

![Succesful Authentication in Browser](https://user-images.githubusercontent.com/58702938/197880154-d563b059-39e5-4887-8839-1f43b4d59c95.png)
![VSCode Error Message](https://user-images.githubusercontent.com/58702938/197880847-f4c7f719-42fc-4c45-a082-42fcbd2e4be5.png)

**Comment by pedroangelini** [comment]
I'm having the same problem here. 
I deleted the credentials in the Windows credential manager and the AAD folder in my AppData folder as explained here: https://stackoverflow.com/questions/72224416/why-cant-i-re-authenticate-mfa-with-mssql-extension-for-vs-code and it worked, but this should be happening automatically when the extension detects an expired token.

**Comment by ThomasHornschuh** [comment]
I have the same problem. I haven't seen the errorcode mentioned in step 6 of initial post:
"Error: errorcode: this.stringLookup.getInteractionRequiredString is not a function"
For me simply the mssql Credential Error Popup Window just appears every time again. The problem does not appear in Azure Data Studio. 

My VSCode Workspace runs in WSL Linux (WSL2.0), Ubuntu 18.04 LTS. 

Deleting the connection, Exit and Restart VSCode (Reload is not sufficient) and then recreate the connection solves the problem, until the next expiration.
