### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by roopak751** [microsoft/vscode-mssql#17472]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.16.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cheenamalhotra** [comment]
Hi @roopak751 

What is the issue?

**Comment by cheenamalhotra** [comment]
Closing as no-op
