### ISSUE TITLE
Support Central Management Servers

### ISSUE THREAD

**Issue by lostsole** [microsoft/vscode-mssql#17493]
Can you make this Extension (extensions/cms/) (Microsoft Central Management Servers) work Visual Studio's  2017/2019.

Can the Extensions be more universal,  So that they can be used across MS products
Visual Studio Code
Azure Data Studio
and 
Visual Studio Pro/Enterprise 2017/2019.

**Comment by alanrenmsft** [comment]
updated the title and transferred to the correct repository.

**Comment by kburtram** [comment]
Closing older issues that aren't on the planned medium-term roadmap.  Thanks for taking the time to file this suggestion.

**Comment by LarnuUK** [comment]
@kburtram  with the deprecation of ADS, this is now a must, and can't be a not-planned.
