### ISSUE TITLE
"SqlToolsService Initialization" steals focus on start up

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-mssql#17499]
I decided to not open this as a bug, as I wasn't able to definitively find where this bit of code is. However, since this is part of the SQL Server extension I figured this would be a good place to start.

Whenever I open a project with this extension, the bottom pane is forced to the output section, specifically with "SqlToolsService Initialization" selected. This is very frustrating because the only way to switch back is to leave the keyboard (where my hands are most of the time), move my mouse around to find the cursor, then select the terminal window to go back to where I was. I simply don't care what happens with this service unless something goes wrong, which has not happened. This happens with a few other extensions, and I'll be submitting issues like this with them as well.

If this is not the correct repo, please let me know which repo is.

**Comment by kburtram** [comment]
I'm not able to reproduce this issue.  Are you running VS Code under a debugger?  This can cause diagnostic messages to get displayed in Output window as described.
