### ISSUE TITLE
x86 vscode-mssql extension can't establish connection to server

### ISSUE THREAD

**Issue by lewis-sanchez** [microsoft/vscode-mssql#17494]
- MSSQL Extension Version: 1.17.0
- VSCode Version: 1.73.1
- OS Version: Windows 11 Enterprise

Steps to Reproduce:

1. Install the x86 version of the x86 vscode-mssql extension
2. Attempt to connect to a SQL Server instance from VSCode using the extension

In dev tools the following error will appear:
![image](https://user-images.githubusercontent.com/87730006/205160460-cd22e6cf-0831-42fa-9b61-9a251f203f35.png)

VS Code will output the following: 
![image](https://user-images.githubusercontent.com/87730006/205160781-4f7f7114-f806-4ac1-b870-572af1bd48f4.png)

**Comment by Charles-Gagnon** [comment]
@lewis-sanchez Are you seeing this on an x86 machine? It's very possible this is something specific to trying to run the x86 version of the extension on an x64 machine (which should in general work, but is also not something that's directly supported). 

I was able to repro this on my x64 machine but I don't have an x86 one to test with handy...

**Comment by lewis-sanchez** [comment]
@Charles-Gagnon, I don't have an x86 machine either to confirm.

**Comment by kburtram** [comment]
x86 version is no longer officially supported at this time.
