### ISSUE TITLE
https://www.facebook.com/jenny.a.howes?mibextid=ZbWKwL

### ISSUE THREAD

**Issue by Justmi03** [microsoft/vscode-mssql#17502]
**Problem Summary**

    MSSQL Extension Version:
    VSCode Version:
    OS Version:

**Formatter Settings**
```
datatypeCasing: "none" / "uppercase" / "lowercase",
keywordCasing: "none" / "uppercase" / "lowercase",
alignColumnDefinitionsInColumns: false,
placeCommasBeforeNextStatement: false,
placeSelectStatementReferencesOnNewLine" false,
```

**Input Text** - place unformatted SQL below
```sql

```

**Actual Output** - place formatted SQL (that doesn't work as expected) below
```sql

```

**Expected Output** - place formatted SQL as you'd expect it to look below
```sql

```

**Comment by cheenamalhotra** [comment]
@Justmi03 

What is the issue?

**Comment by kburtram** [comment]
Closing as there is not enough context to investigate.  Please additional context and reactive if you're still experiencing this problem.  Thanks!

**Comment by lfeeman** [comment]
> **Problem Summary**
> 
> ```
> MSSQL Extension Version:
> VSCode Version:
> OS Version:
> ```
> 
> **Formatter Settings**
> 
> ```
> datatypeCasing: "none" / "uppercase" / "lowercase",
> keywordCasing: "none" / "uppercase" / "lowercase",
> alignColumnDefinitionsInColumns: false,
> placeCommasBeforeNextStatement: false,
> placeSelectStatementReferencesOnNewLine" false,
> ```
> 
> **Input Text** - place unformatted SQL below
> 
> **Actual Output** - place formatted SQL (that doesn't work as expected) below
> 
> **Expected Output** - place formatted SQL as you'd expect it to look below

Www.facebook.com Jenny a howel
