### ISSUE TITLE
Cannot cancel running query.

### ISSUE THREAD

**Issue by mfusigh** [microsoft/vscode-mssql#17506]
While running a query that takes a long time, clicking on the tiny square "cancel" button in the tab strip does nothing.  The only way to stop the query is to stop the vscode process or kill the query on sqlserver.

Also, the UI for this extension is awful. HAving a tiny 12x12 pixel icon for running/canceling queries and hiding it in the tabstrip of open files is a poor ux/ui choice.

**Comment by kburtram** [comment]
@alanrenmsft I thought we did some work related to improving query cancelation in ADS?  Does that need to be ported to the VS Code extension?

@mfusigh the UI for this extension is following the recommended toolbar layout from the VS Code team.  It wouldn't be our preferred choice but is meant to be consistent with the rest of the product.  Sorry for the frustration.

**Comment by alanrenmsft** [comment]
I was able to cancel the query below while it is running on the wideworldimporters sample databas. @mfusigh do you see any error in the console?

``` T-SQL
SELECT *
FROM [Sales].[InvoiceLines] il
INNER JOIN [Sales].[Invoices] i ON i.InvoiceID = il.InvoiceID
INNER JOIN [Sales].[OrderLines] ol ON ol.OrderID = i.OrderID
INNER JOIN [Sales].[Orders] o ON o.OrderID = ol.OrderID
```

**Comment by kburtram** [comment]
Closing older issue as no repro.  We've done some fixes in this area since this issue was opened.  Please let us know if you're still experiencing this issue on the current extension.

**Comment by AMurtagh** [comment]
I'm definitely still experiencing this behaviour; whether the root cause is identical to the OP I'm not sure. I have the behaviour in a fashion that is incredibly reproduceable, consistently about 50% of the time.

**Comment by karlb-dev** [comment]
> [@kburtram](https://github.com/kburtram) I wonder if you would be kind enough to re-open this issue? You've asked for us to let you know if the issue continues and yet we don't have permissions to re-open the issue.

If you're still experiencing issues with query execution, please open a new issue with repro steps so that we can investigate.
