### ISSUE TITLE
T-SQL color coding gets messed up if a there is a backslash followed by a single quote

### ISSUE THREAD

**Issue by MarkIannucci** [microsoft/vscode-mssql#1751]
- MSSQL Extension Version: v. 1.9.0
- VSCode Version: 1.49.1
- OS Version: Windows 10 Enterprise 1809 build 17763.1217

Steps to Reproduce:

VS-Code interprets a `\` in a t-sql literal string as an escape character when rendering t-sql.  Unfortunately, if a you have a trailing backslash at the end of a literal string, the color coding gets messed up.  Code that can cause this follows

`'by that I mean a string in single quotes\'`

Actual screenshot:

![image](https://user-images.githubusercontent.com/16762974/94033663-6dea4e00-fd7e-11ea-901a-9fd308267f84.png)

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/vscode-mssql/pull/1701
