### ISSUE TITLE
Select Top 1000 option returns blank query

### ISSUE THREAD

**Issue by jennkeum** [microsoft/vscode-mssql#17511]
- MSSQL Extension Version: v1.16.0
- VSCode Version: 1.74.2 (user setup)
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Connect to SQL Server database 
2. Right click on a table
3. Select "Select Top 1000" option

Expected: Query created with list of columns within the selected table. 
Actual: Query is blank

![image](https://user-images.githubusercontent.com/96705173/210667047-fa2d1dc4-6c1f-4620-acdc-f9d0f1dc5f89.png)

**Comment by kburtram** [comment]
@jennkeum if this happens again, could you please check the "Help->Developer Tools" Console and see if any errors were logged there?  Does this repo consistently?

**Comment by kburtram** [comment]
I am unable to repro and there isn't enough info in the bug to determine what could be happening.  If you are still impacted by this bug please see if there are any error messages in the log that may help us determine what is causing this problem.  Thanks!
