### ISSUE TITLE
SQL-Server 2014 seems not to work after upgrade to v1.17.1

### ISSUE THREAD

**Issue by jeansagi** [microsoft/vscode-mssql#17537]
- MSSQL Extension Version:
         v1.17.1
- VSCode Version:
         Version: 1.74.3 (system setup)
         Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
         Date: 2023-01-09T16:59:02.252Z
         Electron: 19.1.8
         Chromium: 102.0.5005.167
         Node.js: 16.14.2
         V8: 10.2.154.15-electron.0
         Sandboxed: No
- OS Version:
         OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. MSSQL upgraded automatically to v1.17.1 and all my 3 connections got lost (Not nice BTW).
2. Got the message https://user-images.githubusercontent.com/13396919/205182717-917ff892-4ba2-4dfc-bd7d-fa74ee1846a9.png
   and as said effectively my connections refused to work.
   BTW: https://learn.microsoft.com/es-mx/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver16#encrypt-and-trust-server-certificate did not say anything related to new Encryption settings nor the way to restore them.
3. Trying to retore the first 2 connections was successful: https://user-images.githubusercontent.com/13396919/205173028-5529e32c-fa42-4c09-9840-9fdba60e1aed.png appeared and after choosing the option "Enable Trust Server Certificate" the connections were restored.
4. The last connection has not been possible to restore. It does not show the option to choose "Enable Trust Server Certificate".
    The difference with the previous two connections is that the third one is a Sql-Server 2014 database.
    So, I edited settings.json and give the same options to the third connection:

        // This connection is working correctly
        {
            "server": "tcp:DEV01,2323",
            "database": "C_m_QA",
            "authenticationType": "SqlLogin",
            "user": "SxxCxMxxXX",
            "password": "",
            "emptyPasswordInput": false,
            "savePassword": true,
            "profileName": "FVLCdeM - QAS",
            "encrypt": "Mandatory",
            "trustServerCertificate": true,
            "connectTimeout": 15,
            "applicationName": "vscode-mssql"
        },
        // This connection is NOT working anymore
        {
            "server": "tcp:DEV_OLD,1433",
            "database": "bx_xxx",
            "authenticationType": "SqlLogin",
            "user": "cXYZdb",
            "password": "",
            "emptyPasswordInput": false,
            "savePassword": true,
            "profileName": "FVLCdeM - QAS",
            "encrypt": "Mandatory",
            "trustServerCertificate": true,
            "connectTimeout": 15,
            "applicationName": "vscode-mssql"
        }

        Other variations have not worked either:
        // This connection is NOT working anymore
        {
            "server": "tcp:DEV_OLD,1433",
            "database": "bx_xxx",
            "authenticationType": "SqlLogin",
            "user": "cXYZdb",
            "password": "",
            "emptyPasswordInput": false,
            "savePassword": true,
            "profileName": "FVLCdeM - QAS",
            "encrypt": "Optional",
            "trustServerCertificate": false,
            "connectTimeout": 15,
            "applicationName": "vscode-mssql"
        }

        // This connection is NOT working neither
        {
            "server": "tcp:DEV_OLD,1433",
            "database": "bx_xxx",
            "authenticationType": "SqlLogin",
            "user": "cXYZdb",
            "password": "",
            "emptyPasswordInput": false,
            "savePassword": true,
            "profileName": "FVLCdeM - QAS"
        }

So as the first two connections are to SQL-Server 2019 and the last one is SQl-Server 2014 is there a bug in that?
Maybe is there a connection type "SqlLogin" is not supported anymore? (All the example I saw were with "Integrated").
Is there any other variations I could try to restore the connections? (Sorry: Haven't found any more documentation on the net).

Obviously: All the 3 connections were working perfectly before the upgrade to v1.17.1 so I really think there is some kind of feature not supported in Sql-Server 2014.

Any help/hint/clue will be very appreciated.

J.

PS: Really don't want to downgrade to a previous version.

**Comment by cheenamalhotra** [comment]
Hi @jeansagi 

Apologies for inconvenience, can you paste version string of SQL Server 2014 you're connecting to?
I was able to verify connectivity with SQL Password auth with a SQL 2014, and my version string looks like this:

_Microsoft SQL Server 2014 (SP3-GDR) (KB4508234) - 12.0.6174.6 (X64) 	
Nov 23 2022 23:42:21 	
Copyright (c) Microsoft Corporation	
Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 20348: ) (Hypervisor)_

Also please let us know the error you get when you try to connect with "encrypt": "Optional".

**Comment by jeansagi** [comment]
Hi Cheena,

Actually, **I DO APOLOGIZE** myself!.

The real problem here seems to be in the connection properties I'm defining to access the database.
I know for sure that the DB I'm trying to connect is up and running but after several attempts to connect from other tools (including SQL Server Management Studio), none has been successful.

In fact, using the **vscode-mssql** plugin I successfully created a connection to a SQL Server 2012 database without any issue and indeed the message "Enable Trust Server Certificate" appeared as expected.

So, this is **MY BAD**!.

As such this issue can be closed.


J.

**Comment by cheenamalhotra** [comment]
No worries, will close the issue.

**Comment by jeansagi** [comment]
Just for the record (If anyone in need):

Check your **FIREWALL** too!

In my case all the connection properties were right but new firewall rules, applied so long ago, prevented access from outside the server.


J.
