### ISSUE TITLE
SQL Messages need to persist and be accurate

### ISSUE THREAD

**Issue by cdchild** [microsoft/vscode-mssql#1753]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.49.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open two SQL Scripts
2. Execute both SQL Scripts and note: the Messages section with the Total Row Count, any other message output, & Total Execution Time in the results window after each one is executed.
3. Switch between the results tabs of the two scripts.
Notice that the messages disappear (the Total Rows, statistics, Print output, etc.) disappears and the Total Execution Time increases by the original amount of time each time tabs are switched.

**Comment by cdchild** [comment]
![image](https://user-images.githubusercontent.com/8571711/94712179-57a43b00-0306-11eb-8f90-39e4b75ba8dc.png)
First Results

![image](https://user-images.githubusercontent.com/8571711/94712249-73a7dc80-0306-11eb-91bc-19845ff26634.png)
Looks good so far

![image](https://user-images.githubusercontent.com/8571711/94712358-a05bf400-0306-11eb-8838-3d58b84f839e.png)
Original execution time was 00:00:00.021, now it's 00:00:00.042.
Row affected disappeared.

![image](https://user-images.githubusercontent.com/8571711/94712497-cb464800-0306-11eb-8cce-3973967c6a4e.png)
Original execution time was 00:00:00.018, now it's 00:00:00.036...
Row affected is no longer there either.

![image](https://user-images.githubusercontent.com/8571711/94713792-80c5cb00-0308-11eb-96a8-bdd34e4c59f9.png)
It'll keep going the more times you switch.

For simplicity in reporting/recreating I've omitted examples where the number of rows affected is helpful.  However, it is helpful especially when multi-tasking, waiting for longer/larger queries, etc.  We'll need to be able to switch between multiple results without worrying about the stats changing.  I have another request coming on statistics...

**Comment by cdchild** [comment]
This also affects other statistics like the output from SET STATISTICS IO (https://docs.microsoft.com/en-us/sql/t-sql/statements/set-statistics-io-transact-sql).
Now you see it:
![image](https://user-images.githubusercontent.com/8571711/94715055-32193080-030a-11eb-9156-7b4a1227dc47.png)

Now you don't (after switching between tabs):
![image](https://user-images.githubusercontent.com/8571711/94715300-83292480-030a-11eb-872f-6a877d071b21.png)

**Comment by RandomGHUser** [comment]
It seem like tabbing to a different result tab (or, say, closing the active result tab which makes another one active) actually re-executes the underlying query of the newly active result tab.  This seems like very dangerous behavior to be happening by default.  Can anybody confirm this, and/or a way to resolve this related issue?  When any result tab becomes active, it should show the last queried data and messages, not re-execute the query.

**Comment by Brian-Keith** [comment]
Just want to add my support to this issue since it has been open for over 2 years. It's very frustrating that the message history is not retained when switching between windows, which is not behavior that happens in SSMS.

This is especially frustrating as the author mentioned when executing multiple queries since any debugging information will be lost. Would really appreciate a fix for this issue.

**Comment by simonsabin** [comment]
Just came across this, can't quite believe messages aren't maintained between tab switching
