### ISSUE TITLE
1.17.1 Doesnt Work Unless Restarting VS Code

### ISSUE THREAD

**Issue by l-j-g** [microsoft/vscode-mssql#17538]
- MSSQL Extension Version: 1.17.1
- VSCode Version: 1.73.1
- OS Version: Windows_NT x64 10.0.22000

Please advise how to provide a more detailed log... Nothing is working with the latest update of the extension. 

Errors are all command not found : 
 "Command MS SQL: Use Database' result in an error (command 'mssql.chooseDatabase' not found or similar .e.g "mssql.addObjectExplorer not found. 
 

Steps to Reproduce:

1. Install 1.17.0 - Works fine
2. Install 1.17.1 - Nothing work.s 

Update :: Close VS Code will install the necessary tools after updating. Suggest a user prompt that a restart is required after updating.

**Comment by kburtram** [comment]
@l-j-g thanks for opening this issue.  When updating the extension VS Code will show a prompt in the Extension Manager saying "Reload Required".  But as this may happen automatically in the background it's understandable that this may not be obvious.  We'll see if there's anything we can do to improve this experience.

![image](https://user-images.githubusercontent.com/599935/217902008-75d73f14-d3a6-4f05-8913-8b95ea3bcaea.png)
