### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by DerlanRodr** [microsoft/vscode-mssql#17533]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.17.0`
- OS Version: `Windows_NT x64 10.0.18362`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by cheenamalhotra** [comment]
Hi @DerlanRodr 

Can you please paste the issue details?
