### ISSUE TITLE
Connections with same account but different tenant overwrites existing connections

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#17598]
1.18.0

1. Have an existing connection with Azure MFA auth type connected with an account that belongs to multiple tenants
2. Create a new connection to the same server with the same account but choose a different tenant

Expected : A new connection is created with the same options but a different tenant

Actual : The existing connection is overwritten with the new connection and tenant

**Comment by cheenamalhotra** [comment]
@Charles-Gagnon 

A server belongs to only 1 tenant/subscription, unless I'm missing some advanced multi-tenant setting on Azure SQL. 
Is that something that works with ADS?

**Comment by Charles-Gagnon** [comment]
That's one thing I was very confused about - I seemingly was able to connect to a server with multiple tenants (despite one being just a test one I made myself and the other being on our test subscriptions)

So possibly something wrong here with using the wrong access token. Doesn't seem like a regression though so we can dig into it further post release, although if you think there's something concerning here glad to sit down and go over it together this week.

**Comment by Charles-Gagnon** [comment]
Alright, not sure what was going on here but I can't repro it anymore. I correctly get a login error when trying to login with a different tenant. (and verified ADS behaves in the same way)
