### ISSUE TITLE
Inconsistent sizing in group by schema icons

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/vscode-mssql#17594]
Doesn't look very polished like this, the icon itself should stay the same size with only the x being added/removed.

![SchemaIconResize](https://user-images.githubusercontent.com/28519865/223589484-7dcaf5f0-32ea-403a-9390-a4bc2efd01ea.gif)

**Comment by Charles-Gagnon** [comment]
Confirmed fixed in latest version of 1.18.0 VSIX
