### ISSUE TITLE
Device Code prompt asks to log in to ADS

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#17599]
1.18.0

1. Change Azure auth method to "DeviceCode"
2. Create new connection with AzureMFA and add new account
3. Enter in code and click OK

Expected : Form is shown asking the user to log in to VS Code MSSQL Extension

Actual : Form asks to log in to ADS

![image](https://user-images.githubusercontent.com/28519865/223867563-2b7c58b9-c5f6-43e2-adcb-fb1af8a3e97b.png)

**Comment by cheenamalhotra** [comment]
I did capture that in https://github.com/microsoft/vscode-mssql/issues/17559, but app isn't updated.
Thanks for logging again..

**Comment by cssuh** [comment]
This is by design - I chatted with Karl and we don't want to create separate app IDs for these two tools.
