### ISSUE TITLE
User is prompted to select tenant when SQL Auth Provider is enabled

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#17609]
- MSSQL Extension Version: 1.18.0

According to https://github.com/microsoft/azuredatastudio/issues/22298#issuecomment-1464313921 this isn't supposed to prompt the user for the tenant, but I'm still seeing the prompt. 

It does seem to correctly ignore the selection though (I can connect to a server no matter the tenant I select) but the tenant ID is still saved in the settings. That's probably the behavior I was seeing that made me file https://github.com/microsoft/vscode-mssql/issues/17598 - but for that it feels like the "correct" thing here is to not prompt for the tenant ID at all (which means tenantId would be undefined in the settings)

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra FYI

**Comment by cheenamalhotra** [comment]
I seem to have missed that change, thanks for catching! :)
