### ISSUE TITLE
New connections can end up with wrong node label

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/vscode-mssql#17600]
- MSSQL Extension Version: 1.18.0

1. Create two connections to the same server, but with different auth types (e.g. SQL Login & AzureMFA)
2. Reload VS Code (this part seems to matter, I wasn't able to repro it without reloading first)
3. Delete one of the connections - the order here seems to matter as sometimes I wasn't able to repro this depending on which one I deleted
4. Try to re-add the connection

Expected : Node shows up with the information entered

Actual : Node shows up, but it has the incorrect information (seems to match the existing node to the same server). A reload of VS Code MSSQL fixes the issue and the settings seem correct so likely just an issue with updating the node text.

![DuplicateNodes](https://user-images.githubusercontent.com/28519865/223876063-c3428d0a-4742-4627-8423-e00eb30a047a.gif)

**Comment by Charles-Gagnon** [comment]
I take it back - looks like something else gets screwed up with the nodes. Reloading fixes the display issue but then when I try to expand a node it expands the wrong one and then seems to get stuck in a loop somewhere (the loading indicator at the top is flashing constantly)

No errors in the console or anywhere else that I see

![NodeExpansion](https://user-images.githubusercontent.com/28519865/223878836-dfc6bbc8-4da0-4095-8201-c2d7eb816871.gif)

**Comment by cheenamalhotra** [comment]
Related to https://github.com/microsoft/vscode-mssql/issues/17558 ?
