### ISSUE TITLE
Linux aarch64 Support

### ISSUE THREAD

**Issue by mkurz** [microsoft/vscode-mssql#17640]
Please make sure that it also works with Kernels that do not use 4k page sizes. For example I use Asahi Linux which uses a page size of 16k:
* https://asahilinux.org/
* Also see https://asahilinux.org/2022/03/asahi-linux-alpha-release/#known-broken-applications:
> The Asahi Linux kernel is compiled to use 16K pages.

Would be really nice if you consider that, thanks!

**Comment by alanrenmsft** [comment]
@mkurz as I mentioned in this comment: https://github.com/microsoft/vscode-mssql/issues/1733#issuecomment-1480262915. could you please give it a try?

**Comment by mkurz** [comment]
@alanrenmsft I can successfully install the extension:

```
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: linux, aarch64, name=archarm, version=unknown (Linux)

Installing SQL tools service to /home/mkurz/.vscode/extensions/ms-mssql.mssql-1.19.0/sqltoolsservice/4.6.0.14/Linux.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.6.0.14/microsoft.sqltools.servicelayer-linux-arm64-net7.0.tar.gz
(65251 KB) .................... Done!
Installing ...
Done! 843 files unpacked.
```
Also can see the commands:
<kbd><img width="400" src="https://user-images.githubusercontent.com/644927/227321710-824aead6-aa06-4b21-96ba-2f8bce432fad.png" /></kbd>

However I do not have access to a SQL server instance right now and running SQL Edge via docker doesn't work currently.
So I can test running queries etc.
I will update when I can connect to a server.

**Comment by mkurz** [comment]
@alanrenmsft I run into another problem when trying to run [Azure SQL Edge](https://hub.docker.com/_/microsoft-azure-sql-edge) via docker on my ARM64 Linux system (aarch64). The docker image does actually support ARM64 Linux, however it seems only systems with a kernal page size of 8kb (which most Linux distributions use by default). However my Asahi Linux installation has a page size of 16kb:
```
$ getconf PAGESIZE
16384
```
So when running the Azure SQL Edge image on my system I end up with:
```sh
$ docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e 'MSSQL_SA_PASSWORD=abcdefghi' -p 1433:1433 --name azuresqledge -d mcr.microsoft.com/azure-sql-edge
098abcdb28957b302b11440f237168cb5c7051a920a65d5f3b38a7a4ce09b529

$ docker logs azuresqledge
Azure SQL Edge will run as non-root by default.
This container is running as user mssql.
To learn more visit https://go.microsoft.com/fwlink/?linkid=2140520.
2023/04/04 16:36:57 [launchpadd] INFO: Extensibility Log Header: <timestamp> <process> <sandboxId> <sessionId> <message>
2023/04/04 16:36:57 [launchpadd] WARNING: Failed to load /var/opt/mssql/mssql.conf ini file with error open /var/opt/mssql/mssql.conf: no such file or directory
2023/04/04 16:36:57 [launchpadd] INFO: DataDirectories =  /bin:/etc:/lib:/lib32:/lib64:/sbin:/usr/bin:/usr/include:/usr/lib:/usr/lib32:/usr/lib64:/usr/libexec/gcc:/usr/sbin:/usr/share:/var/lib:/opt/microsoft:/opt/mssql-extensibility:/opt/mssql/mlservices:/opt/mssql/lib/zulu-jre-11:/opt/mssql-tools
2023/04/04 16:36:57 Drop permitted effective capabilities.
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
# ...
# same message round 500 times
# ...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Error in GnuTLS initialization: ASN1 parser: Element was not found.
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
Out of memory allocating bitmask: Cannot allocate memory
```

It seems this can be fixed by building jemalloc with `--with-lg-page=16`, like done here:
* https://gitlab.com/gitlab-org/omnibus-gitlab/-/merge_requests/4800/diffs

More details and comments:
* https://github.com/rust-lang/rust/issues/100180#issuecomment-1207207445
* https://github.com/jemalloc/jemalloc/pull/769/files
* https://github.com/archlinuxarm/PKGBUILDs/pull/1914#issuecomment-1214376524
* https://github.com/archlinuxarm/PKGBUILDs/commit/4efd481729babaa8fc96a9f6dfc82e90a06ec636#diff-5501c9c3b5ba0d0607184fd35e6eba1a9bb5c8ff0d2c17a108e91b496c9ad846R31-R35
* https://bugzilla.redhat.com/show_bug.cgi?id=1545539

I know this is the bug tracker for vscode-mssql, however do you know where to report this bug and it's solution to the sql server team where actually someone looks at it and doesn't get lost? Do you know someone from the sql server team you can ping here on GitHub or to forward my issue to?

I think this could easily be solved if someone who is in charge takes a look at.

Thanks!

**Comment by alanrenmsft** [comment]
@dzsquared do you know where to report the Azure SQL Edge image issues?

**Comment by dzsquared** [comment]
All container image issues go to https://github.com/microsoft/mssql-docker, I believe.  @kendalvandyke, fyi

**Comment by alanrenmsft** [comment]
@mkurz Did you get a chance to verify the mssql extension by connecting to another server?

**Comment by mkurz** [comment]
@alanrenmsft Sorry not yet, I switched machines an didn't set up everthing yet (including necessary VPN). However I will try to do that until tomorrow. Will come back asap.

**Comment by mkurz** [comment]
FYI: Posted here: https://github.com/microsoft/mssql-docker/issues/824

**Comment by mkurz** [comment]
@alanrenmsft I finally could try the extenstion you provided me. Works fine! I can connect to the server, can run select and update queries. Results shown in nice tables. The servers view shows me the servers I created. Looking forward to the release!
Here is a screenshot
![Untitled](https://user-images.githubusercontent.com/644927/231423504-a3afadeb-1655-437d-b907-e393aa46ef6f.png)

**Comment by alanrenmsft** [comment]
@mkurz thanks for confirming.

**Comment by kirichenec** [comment]
@mkurz, hello!
I'm trying to run 1.0.7 on my raspberry pi 5 with 64 bit OS and have same problem with 16384 page size. How can I compile (or anything else) and run Azure SQL Edge same way as you?)

**Comment by mkurz** [comment]
@kirichenec Sorry I don't fully understand your question. The extension worked for me to connect to a sql server instanz that is running remote.

**Comment by richieieie** [comment]
@mkurz Did you run your Azure SQL Edge on your asahi linux? I've tried for many days and still stuck. If you could run sql server on your ashahi linux machine, please help me to fix it. Thank you very much

**Comment by mkurz** [comment]
@richieieie sorry I do not work with Azure SQL Edge anymore currently (or any MS SQL Server product). Maybe in like 2 month I will need it again, but not now and I didn't try meanwhile. Sorry.

**Comment by richieieie** [comment]
I appreciate it, thank u for replying me.

**Comment by mkurz** [comment]
No, I never had success.

**Comment by mkurz** [comment]
Regarding sql server edge this this comment: https://github.com/microsoft/mssql-docker/issues/824#issuecomment-4242904824
(its dead)
