### ISSUE TITLE
SQL Server BUG

### ISSUE THREAD

**Issue by iurych** [microsoft/vscode-mssql#17651]
Type: <b>Bug</b>

trying to pass the command CREATE TABLE IF NOT EXISTS chocolates... And IF, EXISTS and others command showin syntax erros only in my vscode.

Extension version: 1.18.0
VS Code version: Code 1.77.2 (e344f1f539a80912a0e9357cec841f36ce97a4e2, 2023-04-06T10:08:05.978Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.09GB free)|
|Process Argv|C:\\Users\\iuryv\\OneDrive\\Área de Trabalho\\kenzie\\M4\\sprint-3\\relations-postgres-dotenv --crash-reporter-id b02237c5-13f3-46fe-8e6c-fb8904922d88|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
vsctsb:30705553
vscodedisable:30660115
pythonb192:30669360
functionswalk:30687959
pythonms35:30701012
pythonfmttextcf:30710682

```

</details>

**Comment by Charles-Gagnon** [comment]
Is this still for a Postgres server?

https://github.com/microsoft/vscode-mssql/issues/1243#issuecomment-1505839599

**Comment by Yashar8991** [comment]
IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'chocolates')
BEGIN
    CREATE TABLE chocolates (
        id INT PRIMARY KEY,
        name VARCHAR(50),
        price MONEY
    )
END
