### ISSUE TITLE
SQL Tools extension won't load

### ISSUE THREAD

**Issue by mattmcnabb** [microsoft/vscode-mssql#17653]
Here's an error I recently started getting when attempting to connect:

![image](https://user-images.githubusercontent.com/6998507/231800137-8dceff52-d780-485e-828d-1dd44849a435.png)

OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393
VS Code Version: 1.77.3
MSSQL Extension Version: 1.18.0

I see this in the output pane during initialization:

```Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: win32, x86_64 (Windows)

Installing SQL tools service to c:\Users\matt\.vscode\extensions\ms-mssql.mssql-1.18.0\sqltoolsservice\4.5.1.6\Windows.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.5.1.6/microsoft.sqltools.servicelayer-win-x64-net7.0.zip
[ERROR] Error: Request error: ECONNREFUSED
```

**Comment by EdCallahan** [comment]
Looks related to the continuing issue: https://github.com/microsoft/vscode-mssql/issues/17772

**Comment by kburtram** [comment]
Closing based on previous discussion.  Please confirm proxy configuration for the particular environment, and let us know if you require further assistance to troubleshoot this.
