### ISSUE TITLE
SqlCmdVariables are not getting populated at publish time

### ISSUE THREAD

**Issue by Benjin** [microsoft/vscode-mssql#17682]
VSCode duplicate of https://github.com/microsoft/azuredatastudio/issues/23079

Same issue is causing SqlCmdVariables to not get saved to publish profiles.

**Comment by kisantia** [comment]
Generate script is now failing with this error in the console after this was checked in: 
![image](https://github.com/microsoft/vscode-mssql/assets/31145923/fd14fedd-faa0-475d-bddb-6c8273868111)

**Comment by Benjin** [comment]
Verified in release build
