### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by samyukhthamurthy** [microsoft/vscode-mssql#1770]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.50.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
@samyukhthamurthy Could you please elaborate on what the issue is?

**Comment by samyukhthamurthy** [comment]
> 
> 
> @samyukhthamurthy Could you please elaborate on what the issue is?

Hey, I resolved the issue. I'm sorry for taking your time.
