### ISSUE TITLE
A11y_mssql for VSCode_Results Tab_Screen Reader: NVDA/JAWS is not reading the total number of columns and rows correctly 

### ISSUE THREAD

**Issue by fsteffi** [microsoft/vscode-mssql#17713]
**GitHubTags**: #A11yTCS; #A11yMAS; #DesktopApp; #Win11; #A11y_mssqlforVSCode; #WCAG1.3.1; #C+E-H; #mssqlforVSCode; #ScreenReader; #NVDA; #JAWS;#A11ysev2;

## Environment Details:
Visual Studio Code – Insider
Version: 1.79.0-insider (user setup)
Commit: fa8eefda18bf099d82b58453f8fe5d3010196fa0
Date: 2023-05-31T03:06:45.096Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25370
Screen reader: NVDA, JAWS

## Repro Steps:

1. Open Visual Studio Code in your system--
2. Navigate to "Extensions" and install "SQl Server (mssql)" extension
3. Press F1 and select MS SqL : Connect and connect to any sql server
4. Write code (SELECT * FROM sys.objects;) in the new document and press F1 and select ""MS SQL : Execute Query"" "
5. Start NVDA/JAWS
6. Tab till “more options” button and press down arrow in scan mode to read the non-text content
7. Verify if NVDA/JAWS is reading the total number of columns and rows correctly

## Actual Result:
When user presses down arrow while navigating to the grid, NVDA/JAWS is reading as table with 26 rows and 13 columns

## Expected Result:
Screen reader should read the total number of rows and columns correctly as “Table with 104 rows and 13 columns”

## User Impact:
Screen Reader users will not be aware of the total number of rows and columns that are present in the table

## Attachment
![image](https://github.com/microsoft/vscode-mssql/assets/24580570/b6a70764-5955-418f-b613-9f608c31c97c)

**Comment by fsteffi** [comment]
logged in ref to https://github.com/Microsoft/vscode-mssql/issues/1227

**Comment by ShaileshChudawkar** [comment]
#closed; #Regressed:10-17-23;
verified the issue in below environment: Version: 1.840-insider (user setup)
