### ISSUE TITLE
A11y_mssql for VSCode_Results Tab_Screen Reader: NVDA/JAWS is reading the column value and header name incorrectly.

### ISSUE THREAD

**Issue by fsteffi** [microsoft/vscode-mssql#17712]
**GitHubTags**: #A11yTCS; #A11yMAS; #DesktopApp; #Win11; #A11ymssqlforVSCode; #WCAG1.3.1; #C+E-H; #mssqlforVSCode; #ScreenReader; #NVDA; #JAWS;#A11ysev2;#BM_MSSQL_MAY2020;

## Environment Details:
Visual Studio Code – Insider
Version: 1.79.0-insider (user setup)
Commit: fa8eefda18bf099d82b58453f8fe5d3010196fa0
Date: 2023-05-31T03:06:45.096Z
Electron: 22.5.4
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.25370
OS Version: Microsoft Windows 10 Enterprise (10.0.18362 Build 18362)
Screen reader: NVDA, JAWS

## Repro Steps:

1. Open Visual Studio Code in your system
2. Navigate to "Extensions" and install "SQl Server (mssql)" extension
3. Press F1 and select MS SqL : Connect and connect to any sql server
4. Write code (SELECT * FROM sys.objects;) in the new document and press F1 and select ""MS SQL : Execute Query"" "
5. Start NVDA/JAWS
6. Navigate to results table grid with the help of mouse
7. Verify if NVDA/JAWS is reading the table elements correctly

## Actual Result:
NVDA/JAWS is reading the column value and header name incorrectly.

## Expected Result:
Screen reader should read the related column names and column number properly when focus is on the table elements

## User Impact:
Screen Reader users will be provided with faulty data if the screen readers will read column header name and column values wrongly

## Attachment
[Video 6-01 at 10.35.webm](https://github.com/microsoft/vscode-mssql/assets/24580570/aa0759db-d7f6-4be1-b3f1-41f18520ef77)

**Comment by fsteffi** [comment]
logged for https://github.com/microsoft/vscode-mssql/issues/1226

**Comment by ShaileshChudawkar** [comment]
#closed; #Regressed:10-17-23;
verified the issue in below environment:
Version: 1.83.1 (user setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621
 
issue is fixed. So, closing the bug. Attachment is added for reference.
https://github.com/microsoft/vscode-mssql/assets/143179527/e70bb0ce-4a37-43a9-be9a-c6f75749a70b
