### ISSUE TITLE
getProxyAgentOptions error

### ISSUE THREAD

**Issue by EdCallahan** [microsoft/vscode-mssql#17755]
- MSSQL Extension Version: 1.20.0
- VSCode Version: 1.80.1
- OS Version: Win11

Steps to Reproduce:

1. Upgrade mssql vscode module version from v 1.19.1 to 1.20.0
2. Try to connect to a SQL server

The following getProxyAgentOptions error is found in the output window

Downgrading to 1.19.1 fixes the problem.

I do have a proxy defined on my workstation (via environmental variables, Internet Connection configuration and settings.json)

> Initializing SQL tools service for the mssql extension.
> Note: mssql commands will be available after installing the service.
> 
> Platform: win32, x86_64 (Windows)
> 
> Installing SQL tools service to c:\Users\EVCallahan\.vscode\extensions\ms-mssql.mssql-1.20.0\sqltoolsservice\4.8.1.2\Windows.
> Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.8.1.2/microsoft.sqltools.servicelayer-win-x64-net7.0.zip
> [ERROR] TypeError: Cannot read properties of undefined (reading 'getProxyAgentOptions')

**Comment by cheenamalhotra** [comment]
Issue has been addressed in https://github.com/microsoft/vscode-mssql/pull/17757. 

However, it doesn't seem a recent issue, it likely happened in an earlier release.
You can try to download STS manually from URL above and unzip it in below location, in the meantime:
`C:\Users\~\.vscode\extensions\ms-mssql.mssql-1.20.0\sqltoolsservice\4.8.1.2\Windows\`
_(follow path as v1.19)_

**Comment by harrisadni** [comment]
> Issue has been addressed in #17757.
> 
> However, it doesn't seem a recent issue, it likely happened in an earlier release. You can try to download STS manually from URL above and unzip it in below location, in the meantime: `C:\Users\~\.vscode\extensions\ms-mssql.mssql-1.20.0\sqltoolsservice\4.8.1.2\Windows\` _(follow path as v1.19)_

This helps.

**Comment by cheenamalhotra** [comment]
Re-opening issue for July Hotfix consideration, as it may also be contributing to https://github.com/microsoft/vscode-mssql/issues/17739

**Comment by cheenamalhotra** [comment]
Closing as fix has been merged to release branch.
