### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by kobiecrowder** [microsoft/vscode-mssql#1776]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
@kobiecrowder Thanks for opening the issue. Could you please elaborate on the problem you're facing?
