### ISSUE TITLE
SQL: Incorrect syntax highlighting with square brackets ("[ ]") in string

### ISSUE THREAD

**Issue by Ujifman** [microsoft/vscode-mssql#17779]
- MSSQL Extension Version:
- VSCode Version: 
    Version: 1.81.1 (system setup), Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
    Date: 2023-08-09T22:22:42.175Z
    Electron: 22.3.18
    ElectronBuildId: 22689846
    Chromium: 108.0.5359.215
    Node.js: 16.17.1
    V8: 10.8.168.25-electron.0
    OS: Windows_NT x64 10.0.19045

- OS Version: Windows 11 (19045.3324)
- Code for Postgresql

I have table, which stores columns-names and columns types of some other tables. 
Insert commands in sql file have wrong syntax highlighting. 
Some of types of columns are arrays, that cause syntax breaking

**Wrong script example**

```sql
INSERT INTO some_table(id, table_name, columns_names, columns_types)
VALUES (
    1,
    'points',
    ARRAY['id',      'name', 'airport_id', 'geom'    , 'uuid'   ],
    ARRAY['integer', 'text', 'integer[]',  'geometry', 'varchar']
);


INSERT INTO some_table(id, table_name, columns_names, columns_types)
VALUES (
    2,
    'patterns',
    ARRAY['id',      'type', 'geom'    , 'uuid'   ],
    ARRAY['integer', 'text', 'geometry', 'varchar']
);
```

looks like this
![image](https://github.com/microsoft/vscode-mssql/assets/34909951/5807b708-d21b-44df-ac60-9b4e775fa78b)

**Ok script example**

```sql
INSERT INTO some_table(id, table_name, columns_names, columns_types)
VALUES (
    1,
    'points',
    ARRAY['id',      'name', 'airport_id', 'geom'    , 'uuid'   ],
    ARRAY['integer', 'text', 'integer',  'geometry', 'varchar']
);


INSERT INTO some_table(id, table_name, columns_names, columns_types)
VALUES (
    2,
    'patterns',
    ARRAY['id',      'type', 'geom'    , 'uuid'   ],
    ARRAY['integer', 'text', 'geometry', 'varchar']
);
```

Looks like this
![image](https://github.com/microsoft/vscode-mssql/assets/34909951/41195122-9855-476f-a0ef-0f34ef7d5b1c)

Steps to Reproduce:

1. Type sql code with insert of aray of strings, with one string contained `[]` symbols

**Comment by Charles-Gagnon** [comment]
The grammar in this repo is only meant to support T-SQL, so closing this since supporting Postgresql is out of scope.

Have you tried a PG-specific extension, such as https://github.com/Borvik/vscode-postgres?
