### ISSUE TITLE
Can't login via VS Code

### ISSUE THREAD

**Issue by merdz21snchz** [microsoft/vscode-mssql#17775]
Hi Everyone,

After updating to the latest version of VS Code, I am now unable to login to my local server, here's the error message:

_mssql: Error -2146893022: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)_

Any help or assistance would be appreciated!

Thanks & Regards!

**Comment by cheenamalhotra** [comment]
Hi @merdz21snchz 

Have you tried below things:
- Enabling 'Trust Server Certificate' on connection string
- Setting 'Host Name In Certificate' to server hostname that matches Subject name in certificate.

For additional info and possible reasons, refer to:
https://learn.microsoft.com/en-us/sql/connect/ado-net/sqlclient-troubleshooting-guide?view=sql-server-ver16#login-phase-errors

**Comment by merdz21snchz** [comment]
Hi @cheenamalhotra,

Thank you for the tips above, tip #1 did the trick!
Though I really don't have an idea on how to do it, but after searching about it, found an article in SO that shows how to do it in the VS Code settings.json file.


![image](https://github.com/microsoft/vscode-mssql/assets/69063993/92f614b9-eda0-4c7e-a00f-08c368e75bb0)



Thank you & Regards!
