### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by IT-bd-dev** [microsoft/vscode-mssql#1777]
- Issue Type: `Bug`
- Extension Name: `mssql`
- Extension Version: `1.9.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.50.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by abist** [comment]
@IT-bd-dev Thanks for reporting this issue. Could you please elaborate on the problem you're facing?
