### ISSUE TITLE
Cannot Filter SQL ObJect (Tables, Views etc) Search in SQL Server Explorer

### ISSUE THREAD

**Issue by nivek7** [microsoft/vscode-mssql#17783]
Type: <b>Bug</b>

(Example for searching/filtering for Stored Procedures)
Open SQL Server Explorer
Expand desired SQL Server
Expand Progammability
Expand Stored Procedures
CTRL-F to Open Search
Type in Search Term (matches are highlighted)
Click the Filter button (nothing happens)

In other Explorer listings, SQL Files for example, clicking the Filter button will show only matched results.

Extension version: 1.20.1
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11300H @ 3.10GHz (8 x 3110)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.91GB free)|
|Process Argv|--crash-reporter-id f84d3fb6-6571-4e25-9dae-d8a9a9501d09|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
2e4cg342:30602488
f6dab269:30613381
2i9eh265:30646982
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572

```

</details>

**Comment by kburtram** [comment]
@aasimkhan30 do you know why Ctrl-F doesn't work in OE?  I guess this is something that can be enabled/disabled for the VS Code Tree extension point?  In any case, if we can't enable this directly in OE Tree, I think the Filter dialog you're working on will be the suggested workaround/resolution for this request.

**Comment by mickeyperlstein** [comment]
very important for us we have over 200 tables .. (i know :/ )
i must filter to make use of this amazing extension. uninstalling for now

**Comment by aasimkhan30** [comment]
Closing this issue as filtering has been added to the object explorer. A node with many children can be filtered with the inline filter option shown below. 
![Image](https://github.com/user-attachments/assets/94d1a1d2-a99f-4851-b8aa-7e1b9de6d8b0)

**Comment by dstewartLAG** [comment]
Filtering is not the same as searching. It's also limited to a per schema basis. Please see below this basic functionality in Azure Data Studio:

![Image](https://github.com/user-attachments/assets/93bda672-61ff-48fb-90ed-5c4279d2b14a)
