### ISSUE TITLE
Square brackets don't escape comments

### ISSUE THREAD

**Issue by Subinfinity** [microsoft/vscode-mssql#1778]
- MSSQL Extension Version: v1.9.0
- VSCode Version: 1.51.0-insider
- OS Version: Windows 10 2004

Steps to Reproduce:

1. type []
2. put either -- or /* inside 

VSCode:
![image](https://user-images.githubusercontent.com/16784928/97060397-2e6f7700-1561-11eb-8f2f-aa5a79b9fb07.png)
SSMS:
![image](https://user-images.githubusercontent.com/16784928/97060414-3b8c6600-1561-11eb-8afd-142346b54730.png)

**Comment by Charles-Gagnon** [comment]
I'm not seeing this behavior with the current version of the extension, so closing as resolved

![image](https://user-images.githubusercontent.com/28519865/222787380-6f314539-6cad-48ef-a48b-fb0c5366f7b7.png)
