### ISSUE TITLE
Plugin applies intellisense to every sql document

### ISSUE THREAD

**Issue by ericbrian** [microsoft/vscode-mssql#17780]
Every sql file I open, Tsql intellisense is used to show errors and such. However, not all of my sql files are for Sqlserver. I switch it over to none for those documents. But the next time I open the document, it tries to use Tsql again.

**Comment by Charles-Gagnon** [comment]
Just to confirm - you're talking about this quickpick?

![image](https://github.com/microsoft/vscode-mssql/assets/28519865/17264533-8ad7-4a4a-82c7-5f67216a5800)

(vs the "Language Mode" quickpick)

**Comment by kburtram** [comment]
This looks like a duplicate of https://github.com/microsoft/vscode-mssql/issues/801
