### ISSUE TITLE
SQL Server (mssql) extension in Visual Studio Code has lots of bugs, can't even work

### ISSUE THREAD

**Issue by sumngh** [microsoft/vscode-mssql#17784]
1. Not able to connect the server second time or after closing window when at the first it was able to connect normally.
2. Weird errors of webview, OwnerURI etc, even if we are not trying to connect, it just start throwing errors.
3. Keep showing a message "Testing connection profile..."
4. Query execution time is way longer then in Normal SSMS window.
5. Worst ever UI for SQL results, no proper controls like in SSMS, all basics functions are gone.
6. At least need to test this before release. Basic functions shortcuts like F5 to run query, Ctrl+R to change result panel, etc should work.
7. No settings to set results panel to bottom side, it always appears in Right side.
8. 
![Extension Error](https://github.com/microsoft/vscode-mssql/assets/54373676/23fdaec8-605e-47e2-ae11-969e223e4f98)

**Comment by cheenamalhotra** [comment]
Hi @sumngh 

Please gather logs with setting: `"mssql.tracingLevel": "Verbose"` and fetch them by running command: `Developer: Open Logs Folder` and zip logs from latest `windowXX` folder, where errors are captured.

**Comment by ntkeefer** [comment]
I just ran into this same issue. Any updates on this?

**Comment by kburtram** [comment]
Closing due to lack of logs needed for further investigation.  Thanks for opening this issue.  Please let us know if you're still experiencing problems with this extension.

**Comment by sumngh** [comment]
Hi Team,We have stopped using this extension as it has lots of bugs.Thanks & Regards•••••••••••••••••••••••••••••••••••••••••••••••Sumer Singh+91-8287014644| Deal with the world the way it is, not the way you wish it was. |••• From Mobile (Outlook)On 21 Aug 2024, at 4:09 AM, Karl Burtram ***@***.***> wrote:﻿
Closing due to lack of logs needed for further investigation.  Thanks for opening this issue.  Please let us know if you're still experiencing problems with this extension.
