### ISSUE TITLE
Azure authentication issues

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/vscode-mssql#17791]
- MSSQL Extension Version: main
- VSCode Version: Latest
- OS Version: Windows 11

Azure authentication is failing with below errors:

Silent auth failure:
```log
[Error]: Failed to acquireTokenSilent - [{"errorCode":"no_account_in_silent_request","errorMessage":"Please pass an account object, silent flow is not supported without account information","subError":"","name":"ClientAuthError"}]
[Verbose]: [ClientAuthError] Failed to silently acquire token - []
[Error]: Failed to silently acquire token, not InteractionRequiredAuthError: no_account_in_silent_request: Please pass an account object, silent flow is not supported without account information - []
[Verbose]: Starting login - []
```

Account refresh failure:
<img src="https://github.com/microsoft/vscode-mssql/assets/13396919/7e6e5ef5-44ef-487b-940b-769534b1a080" width=600 />

They seem to have started occurring post changes made in ADAL removal PR #17749

**Comment by cssuh** [comment]
Fixed in #17797

**Comment by cssuh** [comment]
Fixed in #17797

**Comment by cheenamalhotra** [comment]
I would still keep it open, so we can close this once fix is merged in release branch and validated.

**Comment by kisantia** [comment]
Port PR is merged. @cssuh please verify this is fixed when the build is finished and close the issue after validating

**Comment by cheenamalhotra** [comment]
Fix verified in latest updates.
