### ISSUE TITLE
write to CSV programmatically

### ISSUE THREAD

**Issue by Lincoln-Hannah** [microsoft/vscode-mssql#17799]
Would be great if the extension could write to CSV programmatically . Something like:
```
SELECT * 
INTO   CSV( "folder\filename.csv")
FROM  my_table
```
I'm a Julia user (VS Code is the default editor). The Julia ODBC package is good but doesn't do SQL syntax highlighting or auto-completion.

If the mssql extension could write to CSV as above, I could call a  .SQL from Julia then read the CSV file outputs into Julia DataFrames.

**Comment by kburtram** [comment]
Thanks for opening this issue.  The extension only supported T-SQL syntax, so I'm closing as "out of scope" for our current roadmap.  There is an option to export a CSV file from the results grid after executing a query, in case that's helpful.
