### ISSUE TITLE
Executing mssql commands does not work from code-server

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-mssql#1780]
MSSQL Extension Version: 1.10.0
code-server: v3.6.1
VS Code: v1.50.0
OS Version: Debian Stretch

Steps to Reproduce:

1. Install mssql extension on code-server
2. Execute any MSSQL extension command, either from the toolbar or keyboard shortcut

This command fails with the following error message:

    command 'mssql.runQuery' not found

It similarly fails for running the current statement:

    command 'mssql.runCurrentStatement' not found

I have not been able to execute any MSSQL extension commands successfully from code-server.

Based on comments in a related issue, I checked to ensure there are no duplicate keyboard shortcuts set up, and there are not. Have also tried deleting the extension folder in ~/.vscode/extensions/ and re-installing the extension, but the error persists. I have also tried installing the 1.15.0 alpha from the vsix file, but this similarly does not fix the issue.

**Comment by dzsquared** [comment]
Hi @fonnesbeck - keep in mind that code-server is not an supported implementation of VS Code. (project URL for reference: https://github.com/cdr/code-server)

If you need a web instance of VS Code and the mssql extension, I recommend GitHub Codespaces: https://github.com/features/codespaces

**Comment by fonnesbeck** [comment]
OK, thanks. The extension is available on the code-serer marketplace, so I had assumed it was supported.

Codespaces probably won't cut it, as I am primarily building and running models, so I need heftier computing hardware than I would if I were just coding.
