### ISSUE TITLE
Extension cannot create a connection to localhost, with localdb instances

### ISSUE THREAD

**Issue by Anthony-Breneliere** [microsoft/vscode-mssql#17813]
- MSSQL Extension Version: 1.20.1
- VSCode Version: 1.82.2
- OS Version: Windows 10

Steps to Reproduce:

1. Install extension
2. Add connection
3. Server name : localhost, Authentification type: Integrated

I have the following error messages : 

mssql: Error 2: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

With Visual Studio 2022, I had no issue connecting to (localdb)\MSSQLLocalDB (SQL Server 15), so I discocovered in Visual Studio the connection string of the localdb instance.
Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False

So I added this connectionstring as parameter to the "Add connection" command and it worked.

But is there a way to connect to local database with the extention without to have a Visual Studio to get local connection strings ?  I did not find one with the documentation https://github.com/Microsoft/vscode-mssql/wiki/manage-connection-profiles.

**Comment by cheenamalhotra** [comment]
Server name "localhost" is not the same as "(localdb)\MSSQLLocalDB".
Hence the error.

You need to provide the correct host name in order to connect.

**Comment by Anthony-Breneliere** [comment]
(localdb)\MSSQLLocalDB is not a hostname, and a hostname is demanded.

In Visual Studio local instances are discovered automatically.

It may differ if it is a local dB, a SQL express, there may be the computer name or not.

With this extension what is the way to know what string is demanded in order to succeed establishing the connection to the local database ?

**Comment by cheenamalhotra** [comment]
`(LocalDb)\MSSQLLocalDB` corresponds to default local db instance and is a valid and accepted server/host name format. You'll need to use the same if you're connecting to Local DB installed on your machine with Visual Studio or with SQL Server Express Local DB. 

You'd use `localhost` when you install a standalone SQL Server instance in your local machine that is running on port 1433 (default port) and you are trying to connect to it from local machine.

Local DB comes with Visual Studio SSDT components, I believe that's what you may be using. 
[More info here](https://learn.microsoft.com/en-us/sql/database-engine/configure-windows/sql-server-express-localdb?view=sql-server-ver16#installation-media).

**Comment by cheenamalhotra** [comment]
I will close the issue as answered.
