### ISSUE TITLE
Ability to login using domain account other than the current one

### ISSUE THREAD

**Issue by Mrugendra27** [microsoft/vscode-mssql#17820]
Type: <b>Feature Request</b>

We would like to have the ability to connect to SQL database using a domain account other than the account we are logged in as.
Something similar to what we do with the MSSQL JDBC when we use the paramters domin=<SOMEOTHERDOMAIN.COM>, authenticationScheme=ntlm with integratedSecurity=true in the connection string.

Extension version: 1.21.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Remote OS version: Linux x64 4.18.0-477.21.1.el8_8.x86_64

**Comment by cheenamalhotra** [comment]
The underlying .NET driver doesn't support the same as of now.
Also a similar issue exists: https://github.com/microsoft/vscode-mssql/issues/826 I will close this as duplicate request. You may upvote the same.
