### ISSUE TITLE
Can't show the definition of Views

### ISSUE THREAD

**Issue by stevennson** [microsoft/vscode-mssql#17831]
When press F2 or Alt+F12 button,the definition of Views doesn't show as Tables.

![attachment](https://github.com/microsoft/vscode-mssql/assets/5284123/c349b820-a035-40c9-a9d0-114a02926bdd)

**Comment by kburtram** [comment]
I was able to repro this with the outlined steps.  Have you confirmed that the editor window has an active connection to a DB containing this view?  You should be able to see the connection details for the editor in the bottom-right of the status bar (example below).

![image](https://github.com/user-attachments/assets/551edcda-b36b-469c-8499-37dbf9bf213a)

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if you're still impacted by this issue.  Thanks for reporting.
