### ISSUE TITLE
加载 Web 视图时出错: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by HaoDong108** [microsoft/vscode-mssql#17860]
- MSSQL Extension Version:  <= v1.22.0 
- VSCode Version:  1.79.0 -(insider)
- OS Version:  Windows 10 专业工作站版   19042.1766

The following error occurred while executing SQL.:
 ERROR:  加载 Web 视图时出错: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

![image](https://github.com/microsoft/vscode-mssql/assets/60975172/16c6dd42-c43a-4c00-a3d8-160981c54feb)

The SQL statement can be executed normally, but the execution result cannot be displayed, and the above error appears. I tried to reduce the version and reinstall the extension program, but it didn't work.

**Comment by HaoDong108** [comment]
Well, I tried to restart Vscode, and it finally worked.😅

**Comment by Charles-Gagnon** [comment]
This generally occurs when you have both VS Code and VS Code Insiders running at the same time, perhaps that was the issue?
