### ISSUE TITLE
Cannot set AccessToken property error connecting with Integrated Auth

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#1786]
- Azure Data Studio Version:

Steps to Reproduce:

1. Add a connection using Integrated Auth
2. Close and reopen vscode
3. Expand Connection in OE

Expected: Connection expands sucessfully

Actual: Error about not being able to set AccessToken

![image](https://user-images.githubusercontent.com/599935/98070646-5d65d280-1e16-11eb-9fc5-a61f0eeca437.png)

**Comment by HikariPL** [comment]
Hi, same problem here with 1.10 version (and the problem was closed on 7 Nov). What can I do to solve it?

**Comment by SonOfLentz** [comment]
Same issue here with 1.10.0 on 12/17/2020.

**Comment by SonOfLentz** [comment]
Interestingly, I can partially get around the issue by either

- creating a new connection in a new file (that connection will work until the new file is closed), or
- bringing up the SQL Server sidebar, clicking the entry for a previously created connection, clicking "connect," then right-clicking on the entry for that connection and selecting "new query."

**Comment by SonOfLentz** [comment]
Update: reddit user Samiro05 found a solution here: https://www.reddit.com/r/SQL/comments/kib5vt/vs_code_mssql_extension_my_connection_string/

**Comment by HikariPL** [comment]
Have you found the file with azureAccountToken statement?

**Comment by HikariPL** [comment]
Guys, any solutions that worked for you? I am asking as this bug is really killing me when using VSC with SQL.

**Comment by dbreese-keystone** [comment]
As described in that Reddit link from @SonOfLentz , I notice the following gets created in my Settings.json file (Extensions -> SQL Server (mssql) -> Manage -> Extension Settings -> MSSQL: Connections -> Edit in settings.json):

        {
            "server": "my-server-name",
            "database": "my_database",
            "authenticationType": "SqlLogin",
            "user": "my_username",
            "password": "",
            "emptyPasswordInput": false,
            "savePassword": false,
            "profileName": "MyProfileName",
            "connectTimeout": 15,
            "encrypt": false,
            "applicationName": "vscode-mssql",
            "azureAccountToken": ""
        }

Again as described in that link, my workaround has been to delete the line saying "azureAccountToken", and save the file.  After doing so, the connection seems to work normally.

This "fix" gets lost/reset after I restart VS Code though.  Every time I restart VS Code, I have to go into the Settings.json and delete the line again.

Was planning to submit my own bug report, but this seems like the same thing I've got.

Hoping the devs can fix soon.  Happy to test or provide more info, or submit a separate report, if it would help.

**Comment by dbreese-keystone** [comment]
Just realized the issue may be a bit different, plus forgot this bug report is closed.

I'll plan to submit my own issue for what I'm seeing, when I get a chance to reproduce this again (next time I restart VS Code and try to run a query).

**Comment by pvspain** [comment]
I've re-opened trhis issue as [#16933][1] as its unresolved in mssql extension version 1.10. Please add new reports on the [new bug report][1]

[1]: https://github.com/microsoft/vscode-mssql/issues/16933
