### ISSUE TITLE
mssql: Failed to load Sql Tools Service

### ISSUE THREAD

**Issue by Miao-Bukeyan** [microsoft/vscode-mssql#17868]
- MSSQL Extension Version: 1.22.1
- VSCode Version: 1.85.2 (system setup)
- OS Version:  Windows 11 家庭中文版 22H2 22621.3007

Steps to Reproduce:

1. 安装SQL Server(mssql) 插件
2. 点击左侧侧边栏Sql Server
3. 等待一会儿后提示 mssql: Failed to load Sql Tools Service
4. 点击面板添加按钮，无法添加连接  并且提示：“运行命令 mssql.addObjectExplorer 错误: command 'mssql.addObjectExplorer' not found。这可能是由提交 mssql.addObjectExplorer 的扩展引起的。”
![image](https://github.com/microsoft/vscode-mssql/assets/19161045/f1103f24-c186-466d-a650-1b85161bdf83)

**Comment by shrijanRegmi** [comment]
Having same issue
!

**Comment by kburtram** [comment]
Unfortunately we are only able to support issues filed in English on this repo.  From the screenshot it appears the out-of-proc SQL Tools Service component timed out during download.  Possible mitigations could be (1) retry launching the extension if the network issue is intermittent (2) download the zip file using a different tool and extract to the noted destination directory.  Please let us know if you're still impacted by this issue.  Thanks!
