### ISSUE TITLE
error loading extension, hostfxr.dll does not contain the expected entry point

### ISSUE THREAD

**Issue by MitchellR2** [microsoft/vscode-mssql#17886]
- MSSQL Extension Version: 1.22.1
- VSCode Version: 1.87.2
- OS Version: Win11 (10.0.22631)

I am trying to troubleshoot the installation of this extension for users in my environment. these are fresh Win11 devices. Initially the extension was being blocked by application control software, however i believe it is now whitelisted. i have uninstalled and reinstalled VScode and the extension but the error persists. 

Steps to Reproduce:

1. Download the extension via the extension browser
2. error occurs while loading the DLL after setup

**Comment by kburtram** [comment]
The extension is running a .Net Core application to handle most database interactions.  It's hard to tell what's going on from the error, but possibly something is wrong with the .Net Core runtime on this machine.  You could try running SQL Tools Service EXE directly to see if it generates a more helpful error message.  It should be in a location similar to `[USERDIRECTORY]\.vscode\extensions\ms-mssql.mssql-1.23.0\sqltoolsservice\5.0.20240724.1\Windows\MicrosoftSqlToolsServiceLayer.exe"

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if you're still impacted by this issue.  Thanks!
