### ISSUE TITLE
scape character and apostrophe not recognised for .sql file text colouring

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode-mssql#17894]
- MSSQL Extension Version: 
- VSCode Version: 1.88, 1.89
- OS Version: N/A

Steps to Reproduce:

1.

```sql
SELECT
	name_string LIKE '%\'%' as has_perc,
FROM
	business_details
;
```
Changing `'%\'%'` to `'%''%'` fixes the issue.

![image](https://github.com/microsoft/vscode-mssql/assets/38270282/0e0b875e-0874-42c9-b9ff-bd613327db51)

Originally from @DamianChimes  in https://github.com/microsoft/vscode/issues/210616

**Comment by Charles-Gagnon** [comment]
Hey @alexr00 / @DamianChimes - the grammar in this repo is specifically for T-SQL, which doesn't support backslash as an escape character. So this is intended behavior.
