### ISSUE TITLE
Multi Cursor Memory Leak

### ISSUE THREAD

**Issue by aviralgoyal** [microsoft/vscode-mssql#17892]
- MSSQL Extension Version: v1.22.1
- VSCode Version: Insider 1.89.0 - insider (Also stable 1.88.0)
- OS Version: Windows 11

Steps to Reproduce:
1. When you start typing and deleting and manipulating a thounsand entries using multi cursor, the memory leakage goes upto 97-99% and will not come down unless I close down that particular instance running sql queries.
2. There are other VS code instances also open, but the only one that causes memory leak is the one where I create sql queries with multi-cursor. And I have tried reproducing without  mssql extension, but it does not happen in that situtation no matter how many cursors.

**Comment by kburtram** [comment]
I wasn't able to reproduce this behavior using the provided steps.  It's not clear what the MSSQL extension would be contributing to memory usage in this scenario, as the editor memory is controlled by VS Code with little direct influence from the extension.  Could you please take a screenshot of the VS Code memory usage per-process, such as shown below?  If it's the MSSQL extension consuming memory we should see it attributed to one of the SQL-release processes.

![image](https://github.com/user-attachments/assets/70eb1fa8-6dda-481b-872d-59ffc431efa0)

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if you're still impacted by this issue.  Thanks!
