### ISSUE TITLE
Sql Server - Add Connection Errors

### ISSUE THREAD

**Issue by Max-Scialabba** [microsoft/vscode-mssql#17895]
- MSSQL Extension Version: v1.19.1
- VSCode Version: 1.70.2 (Universal)
- OS Version: macOS 14.4.1 (23E224)

After downloading SQL Server v1.19.1, I ran into the same initial error messages as this issue: [https://github.com/microsoft/vscode-mssql/issues/17383](https://github.com/microsoft/vscode-mssql/issues/17383). 

Namely, when opening up the command palette, and inputting "MS SQL: Add Connection", I got the following error: "Command 'MS SQL: Add Connection' resulted in an error (command 'mssql.addObjectExplorer' not found)"

However, upon checking the Extension Host and Command Palette, I was unable to replicate the errors they found. In addition, I was unable to implement their fix, because '%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.19.1' had no corresponding directory 'sqltoolsservice'.

How should I resolve this issue? Is there any more information I can provide?

**Comment by kburtram** [comment]
@Max-Scialabba the extension will download the sqltoolsservice binaries on first launch and unzip them into the extension's directory.  If there is no sqltoolsservice  directory that means this download/extraction is failing for some reason.  Are you seeing any errors in the Output window regarding wat error is occurring?

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if you're still impacted by this issue.
