### ISSUE TITLE
Misleading Input Prompts for Database Connection Information at Status Bar

### ISSUE THREAD

**Issue by ywh555hhh** [microsoft/vscode-mssql#17902]
As a beginner, I find the input prompts for database connection information to be quite misleading. The prompt suggests the following formats: `hostname/instance`, `.database.windows.net`, or `ADO.NET connection string`. 

This kind of prompt can lead beginners like me to misunderstand the correct format for entering the information. For instance, I might be misled into thinking that the port should be written in front, like `3443/rm-myinstance-xxxx112`, which is obviously incorrect.

For newcomers who are not familiar with the specific formats, this could be a significant source of confusion. I suggest that the prompts should be more explicit and beginner-friendly, perhaps with more detailed examples for each case.

**Comment by kburtram** [comment]
@Benjin fyi, something to think about with the new connection UI.  It may be good to have some watermark text in the input controls or the info tooltip that helps explain the expected input format.

**Comment by Benjin** [comment]
@ywh555hhh we're working on some big changes to the connection experience, the first batch of which has already released in September, with even more coming in our next release.

To try out the September changes, update to version 1.24 and enable experimental features.  You can do this either in the settings UI (`MSSQL: Enable Experimental Features`) or by editing the user settings JSON directly (`"mssql.enableExperimentalFeatures": true`).

Let us know what you think in this issue, and look forward to even more refinement to the connections UI coming soon.
