### ISSUE TITLE
not able to build your vscode-mssql successfully by running npm i

### ISSUE THREAD

**Issue by brendahon** [microsoft/vscode-mssql#17911]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

I am not able to build your vscode-mssql successfully with the screen capture of the command & error below. May I ask for your advice how to fix it?
![image](https://github.com/joyceerhl/vscode-mssql-chat/assets/30277820/ab359832-c65d-4a01-975f-502e1065e7ed)

**Comment by kburtram** [comment]
The commands I typically use to build are below.  `npm i` doesn't appear to work, but `yarn install` should.  I'll keep this open to track updating the extension documentation.

```
yarn install
yarn build
```

**Comment by Benjin** [comment]
Our [contribution docs](https://github.com/microsoft/vscode-mssql/wiki/contributing) say to use `yarn`, but they definitely do need updates and clean-up in general.  This is a good reminder for that.

@brendahon, did you happen to see that page when trying to build the extension?
