### ISSUE TITLE
Failure starting client on Windows 10

### ISSUE THREAD

**Issue by fonnesbeck** [microsoft/vscode-mssql#1791]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.51.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Install SQL Server extension
2. Click on SQL Server extension in side bar

When the extension is run for the first time, it fails. The SQLToolsService output contains the following error:

```
[Error - 9:40:56 AM] Starting client failed
Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at Object.spawn (child_process.js:549:9)
    at c:\Users\fonne\.vscode\extensions\ms-mssql.mssql-1.9.0\node_modules\vscode-languageclient\lib\main.js:354:40
```

![image](https://user-images.githubusercontent.com/81476/98609856-e87e1700-22b3-11eb-9037-c72f5f30a1e9.png)

**Comment by fonnesbeck** [comment]
Is there any reason 1.10.0 should not be available to me? I am at 1.9.0, but there is no update available, yet the README says 1.10.0 is the most recent version.

**Comment by abist** [comment]
@fonnesbeck 1.10.0 will be releasing today or tomorrow.

**Comment by fonnesbeck** [comment]
Thanks. Will this address the issue above?

**Comment by abist** [comment]
@fonnesbeck You shouldn't be seeing this issue. Could you Toggle Developer Tools from the Help Menu button and click on Console and see if there are any errors there?

**Comment by fonnesbeck** [comment]
I see the following, in addition to the error reported above:

```
Couldn't start client AzureResourceProvider
onDidChangeNotification @ breadcrumbsModel.ts:39

Couldn't start client SQLToolsService
onDidChangeNotification @ breadcrumbsModel.ts:39

notificationsAlerts.ts:40 mssql: Failed to load Sql Tools Service
onDidChangeNotification @ breadcrumbsModel.ts:39

Activating extension 'ms-mssql.mssql' failed: spawn UNKNOWN.
_logMessageInConsole @ abstractExtensionService.ts:663

rejected promise not handled within 1 second: Error: spawn UNKNOWN
t.log @ console.ts:140

```

**Comment by DCAL12** [comment]
I'm having the same issue and same error output, also on version 1.9.0 with a fresh WIndows 10 install and VS Code version 1.51.1. When is version 1.10.0 expected to be available?

**Comment by fonnesbeck** [comment]
In my case I am running on Windows ARM64 (Surface Pro X 2020), which I am guessing is the issue? Is there any reason the extension should not work on ARM?

**Comment by stewday** [comment]
Same issue here.
Windows 10 Enterprise (10.0.19042.985)
VS Code 1.64.1
mssql v1.14.1

Had problems installing mssql directly from Marketplace (timeout on download) but was able to download the vsix and install without any errors. Restarted VS Code.

I have an SQL db on a network share that I want to connect to so, following the instructions [here](https://docs.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver15), I created a new SQL file to initiate the mssql commands. As soon as I set the language type I get the following: 
![errors](https://user-images.githubusercontent.com/4748335/167730950-58275ecc-e5d1-460e-9993-21a83643b7b7.png)

![output](https://user-images.githubusercontent.com/4748335/167731014-30c26d1e-3629-4edd-8ae3-513d9c1d6c63.png)

Noting the comment for @abist above I opened Developer Tools - there are a number of errors showing:

![dev tools](https://user-images.githubusercontent.com/4748335/167731829-65f7418e-4e12-4c27-a2d7-17dcd7c4f10d.png)

Wondering if this has something to do with permissions/restrictions locked down by our IT dept (state government employee)?

**Comment by Charles-Gagnon** [comment]
@stewday Does the following folder exist for you and contain a bunch of files (DLLs/exes)?

`%USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.14.1\sqltoolsservice\3.0.0-release.238\Windows`

**Comment by stewday** [comment]
Hi @Charles-Gagnon. Yes, that location has 300+ files (DLL/exe etc) and 30+ subfolders.

**Comment by Johanaxa** [comment]
Has anyone found a solution to this? has had exactly the same problem.

**Comment by lundeen-bryan** [comment]
I think I have the same issue but to add something when i open a sql file and press the shortcut to run sql, it gives me the following error:
`command 'mssql.runQuery' not found
`
This only started today luckily after I wrote some queries I can run on SSMS, but I'd love to use vscode for sql again.

**Comment by stewday** [comment]
OK ... take 2 on this issue for me.

My corporate laptop has been replaced due to a hardware issue so I have a fresh install of VSCode (1.67.1) on a new machine and have attempted to install the SQL Server (mssql) extension from the marketplace.

Everything appeared to install correctly this time (didn't have to resort to downloading the vsix) but when I open an sql file I get the message:
`Installing SQL tools service to c:\Users\slday\.vscode\extensions\ms-mssql.mssql-1.14.2\sqltoolsservice\3.0.0-release.238\Windows.
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.238/microsoft.sqltools.servicelayer-win-x64-net6.0.zip
failed (error code '407')
[ERROR] Error: 407`

Referring back to the earlier question from @Charles-Gagnon:

> @stewday Does the following folder exist for you and contain a bunch of files (DLLs/exes)?
> 
> %USERPROFILE%\.vscode\extensions\ms-mssql.mssql-1.14.1\sqltoolsservice\3.0.0-release.238\Windows

That folder/path exists but there are no files in it.
