### ISSUE TITLE
Unable to see the mssql updated version on open-vsx.org

### ISSUE THREAD

**Issue by aakash1862** [microsoft/vscode-mssql#17926]
Hi Team,

I am using "open-vsx.org" registry as my golden source for all the extensions in my VSCode IDE.
However, I got to know that there is a difference in version of mssql on [open-vsx.org](https://open-vsx.org/) from the mssql version on [VisualStudio Marketplace](https://marketplace.visualstudio.com/). 

Question is why the extension is not updated in open-vsx.org and how long will it take to update the same on open-vsx.org?

For reference, I have attached the screenshots from both the registries.
![Extension on marketplace visualstudio com](https://github.com/microsoft/vscode-mssql/assets/10572530/0513ccfb-08a1-4c0b-8957-8560b1157b51)
![Extension on open-vsx org](https://github.com/microsoft/vscode-mssql/assets/10572530/0d2218fd-1ded-4b3f-8ad8-62b1fb3de1d6)

**Comment by kburtram** [comment]
@aakash1862 I'm not aware of how extensions appear on open-vsx or the process for updates getting published there.  Please try following up with the account that originally published the extension to that marketplace for updates.  Currently this extension is only officially being released through the VS Code Marketplace, though I'll note the suggestion to support additional marketplaces to the product PM.  Thanks for opening this suggestion!  

@croblesm FYI
