### ISSUE TITLE
Feature Request: Drag Objects from Left Pane to Query Window

### ISSUE THREAD

**Issue by NicholasTuttle** [microsoft/vscode-mssql#1792]
As you can in MSSMS, I would like to be able to drag the name of objects (table names, column names, etc.) from the left pane into the query window.

**Comment by kburtram** [comment]
@aasimkhan30 do you know if drag-n-drop is supported from extension contributed tree views and the editor window?

**Comment by Benjin** [comment]
Added in https://github.com/microsoft/vscode-mssql/pull/18439
