### ISSUE TITLE
STS component could not start

### ISSUE THREAD

**Issue by cssuh** [microsoft/vscode-mssql#17930]
- MSSQL Extension Version: main
- VSCode Version: 1.91.1
- OS Version: 14.5 (23F79) (M3 Macbook)

Steps to Reproduce:

1. Run yarn & yarn run watch to build extension
2. Launch extension using VSCode Run & Debug
3. STS fails to start:

<img width="425" alt="Screenshot 2024-07-15 at 3 53 30 PM" src="https://github.com/user-attachments/assets/a01d1f17-b9d1-4abd-b240-fa4dfc6dda3b">

**Comment by kburtram** [comment]
I see this on my mac as well.  When I download the STS binaries directly I get the following error, so perhaps something isn't working with the new signing infra?

<img width="298" alt="Screenshot 2024-07-16 at 4 20 56 PM" src="https://github.com/user-attachments/assets/00636d24-4dc0-4a76-86f5-c2d4d9b9c140">

**Comment by kburtram** [comment]
This is fixed in the current build
