### ISSUE TITLE
Data provider no longer found after latest update

### ISSUE THREAD

**Issue by Kjartanl** [microsoft/vscode-mssql#17961]
Type: <b>Bug</b>

1. Upgrade to version v1.23.0
2. Open the "Sql Server" icon; instead of any connections, the following error shows up: "There is no data provider registered that can provide view data".

Note: I tried installing the previous version instead ("Install specific version" and selected "1.22.1"). After restarting extensions, my previously existing connections show up again, like before.

Extension version: 1.23.0
VS Code version: Code 1.92.0 (b1c0a14de1414fcdaa400695b4db1c0799bc3124, 2024-07-31T23:26:45.634Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.68GB (12.42GB free)|
|Process Argv|--crash-reporter-id 62c699ed-ba1d-4e0d-97af-730642c6f89b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
724cj586:31013169
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
ccplt:31103426
pythonrstrctxtcf:31103194

```

</details>

**Comment by kburtram** [comment]
@Kjartanl this can sometimes happen on first usage after installing an upgraded extension while the out-of-proc SQL Tools Service component is downloading & installing.  This process can take a variable amount of time depending on network speed at the time of download (should normally be around 30 seconds).  Output such as below should be visible in the console while SQL Tools Service is installing.  You might try to upgrade again and confirm that the download completes successfully.

![image](https://github.com/user-attachments/assets/d0328761-c5e4-4459-9171-52e2080a77a3)

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if you're still impacted by this issue.
