### ISSUE TITLE
Unable to connect to Azure SQL Database - Forced to reinstall extension

### ISSUE THREAD

**Issue by AV25242** [microsoft/vscode-mssql#17963]
- MSSQL Extension Version: 1.23.0
- VSCode Version:
- 
![image](https://github.com/user-attachments/assets/41e030a7-7420-494a-921f-43c953c3b734)

- OS Version: Windows 11 Enterprise Edition
   OS build : 22631.3880

Steps to Reproduce:

1. Installed vs code extension
2. Clicked on the "+" icon
3.Connection screen shows up.
       I entered Azure SQL Data connection string in the connection string tab. (copied over ADO.NET connection string)
       The connection never established (don't know the reason) the wheel kept spinning.
       
**Problem statement: ** 
After performing steps 1-3, I closed the "connection screen" window and after that I was never able to get back to the connection screen.
All I see is a button named "Connect" which has no action. 
I also see an error below 
**_"TypeError: Cannot read properties of undefined" may be related to that  ??_**

![image](https://github.com/user-attachments/assets/75991906-8a5b-4968-8d7e-d89fa14f31d3)

The only way I was able to get around this was to un-install and reinstall the extension.

**Comment by kburtram** [comment]
@aasimkhan30 could you please follow up on what is happening here?

**Comment by Benjin** [comment]
@AV25242 if you use the connection form in the latest version, are you able to successfully connect?  We still want to fix the connection string path, but this can help us to narrow down problematic area.

**Comment by Benjin** [comment]
Closing due to no user response.
