### ISSUE TITLE
Connection MRU can contain entries that don't have any label

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#17968]
Steps to Reproduce:

1. Add some connections using the connection dialog

Expected:  All connections have a description similar to in Object Explorer.

Actual: Some entries do not have a description level.  These appear to be connections created with connection string, though I haven't confirmed that is necessary for repro.

![image](https://github.com/user-attachments/assets/8d74693e-b279-417d-8df5-d9025071f987)

**Comment by Benjin** [comment]
This should have been fixed as part of https://github.com/microsoft/vscode-mssql/pull/18030
