### ISSUE TITLE
Cannot set ApplicationIntent=ReadOnly in connection string causing Msg 978

### ISSUE THREAD

**Issue by TencentSZ** [microsoft/vscode-mssql#1797]
- MSSQL Extension Version: 1.9

I have access to a SQL Server database, and I need to add 'ApplicationIntent=ReadOnly' to connection string following the instruction of the server admin.

When I use vscode-mssql to connect to this server and run any query on it, it raise an error
'The target database ('DatabaseName') is in an availability group and is currently accessible for connections when the application intent is set to read only. '

I think it is caused by the connection string without 'ApplicationIntent=ReadOnly' . But I cannot find the place to add this in vscode-mssql extension.

**Comment by cheenamalhotra** [comment]
Closing as issue no longer occurs.
