### ISSUE TITLE
Time saving update to support filtering query results

### ISSUE THREAD

**Issue by Femi-0** [microsoft/vscode-mssql#17978]
As a data analyst, it would save countless work-hours if I am able to filter the results of queries in the results screen, as opposed to exporting it to a spreadsheet for this single purpose. Please see screenshot attached, thank you.

![image](https://github.com/user-attachments/assets/24f81b7d-c33e-42de-8cec-db2f708503e1)

**Comment by kburtram** [comment]
Thanks for the suggestion!  We are actually currently working on adding this functionality.  The planned experience will be similar to what we offer in Azure Data Studio, specifically the below pop-up dialog in the results grid.

![image](https://github.com/user-attachments/assets/46cd3db6-93e6-412f-9f17-e2ec35252c7d)

**Comment by Femi-0** [comment]
Fantastic! This is exactly what is needed. 
Thank you for making the world a better place in your own little way 🥳

**Comment by Benjin** [comment]
We're using https://github.com/microsoft/vscode-mssql/issues/18063 to track this issue; look for it in the next release!
