### ISSUE TITLE
Canceling query connect prompt leaves results view in invalid state

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#17980]
Steps to Reproduce:

1. Open a SQL file, don't connect, type some statements
2. Click the Execute button
3. Cancel the Select Connection prompt

Expected: Query execution canceled

Actual: Results document is display but fails since there is no active connection for the document

![image](https://github.com/user-attachments/assets/c9025c28-f01d-4584-96bb-e5eee8ba1f2d)

**Comment by caohai** [comment]
This is no longer an issue with the new query result pane. @kburtram Do you think this is a good enough to close the issue? Not sure if we want to go back and fix the angular implementation any more.
![Image](https://github.com/user-attachments/assets/a230aa62-286f-4efb-b3dc-be70dc61672c)

**Comment by Benjin** [comment]
Moving to November, when we can decide whether we want to fix the old behavior.  It may depend on initial feedback on the new UX (i.e. how close we are to GAing the new UX and removing the old)
