### ISSUE TITLE
Query failed: Conversion overflows on select from table with numeric(38,0) column

### ISSUE THREAD

**Issue by mvolovich** [microsoft/vscode-mssql#1798]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.52
- OS Version: Windows 10

Steps to Reproduce:

1. Run query to select data from table with numeric(38,0) column
2. Error returned: "Query failed: Conversion overflows"

**Comment by kburtram** [comment]
This appears to be working in current build.  I tried the below test case.

```SQL
CREATE TABLE TT1
(id int,
val numeric(38,0))

INSERT INTO TT1 VALUES(1, 2)
INSERT INTO TT1 VALUES(3, 4)
INSERT INTO TT1 VALUES(5, 6.6)

SELECT *
FROM TT1
```

Results
```
id	val
1	2
3	4
5	7
```
