### ISSUE TITLE
Intellisense use a bad escape character '\'

### ISSUE THREAD

**Issue by pontos3** [microsoft/vscode-mssql#1799]
- MSSQL Extension Version: 1.9.0
- VSCode Version: 1.51.1
- OS Version: Linux x64 4.9.0-14-amd64 Debian

Steps to Reproduce:

1. Create a sql script with this 2 lines 
```sql
select '\'
select 'some text'
```
2. the syntax coloring for the second line is not the good one like in markdown syntax above

**Comment by alanrenmsft** [comment]
It seems the issue has been fixed, I checked with version 1.11.1 of MSSQL extension.

![image](https://user-images.githubusercontent.com/13777222/144659356-7d459d0d-5060-4907-b5d7-2fc61180142d.png)
