### ISSUE TITLE
SQLPLAN custom editor stuck in Loading

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18002]
Steps to Reproduce:

1. Using latest 1.24.0 VSIX build from ADO pipeline, open a SQLPLAN file

Expected: SQL execution plan graph

Actual: Document stuck in loading.

![image](https://github.com/user-attachments/assets/5da21a8d-2ad0-44ef-8aef-662c560bb268)

**Comment by laurennat** [comment]
fixed by this pr: https://github.com/microsoft/vscode-mssql/pull/18005

**Comment by kburtram** [comment]
Unfortunately, https://github.com/microsoft/vscode-mssql/pull/18005 isn't resolving the issue in my environment.

**Comment by kburtram** [comment]
I'm able to load now with the latest ADO build.
