### ISSUE TITLE
"Open snapshot in new tab" doesn't do anything

### ISSUE THREAD

**Issue by Benjin** [microsoft/vscode-mssql#18112]
Repro:
1. Connect and run a query
2. Click "open snapshot in new tab" button
![image](https://github.com/user-attachments/assets/e3d941ac-b72a-4573-99eb-0949c18e835e)

Expected:
resultset opens in a full tab view

Reality:
nothing happens (well, a "todo" is logged to the console).

----

Two notes:
* We should hide this button until it is hooked up.
* "snapshot" is a bit confusing to me; it sounds like the result set is incomplete or out-of-date in some way.  What does it mean?

**Comment by Benjin** [comment]
@caohai can you link the PR that this issue was fixed in?

**Comment by caohai** [comment]
> [@caohai](https://github.com/caohai) can you link the PR that this issue was fixed in?

Updated in the original comment.
