### ISSUE TITLE
"Browse Azure" not apparent in the connection dialog

### ISSUE THREAD

**Issue by caohai** [microsoft/vscode-mssql#18115]
It took me a few minutes to find the "Browser Azure" option in the connection dialog, partly due to the bug back doc showing the Azure icon among the extension list.

I'd suggest we add an Azure icon to "Browse Azure" option and make it more obvious.
<img width="273" alt="Screenshot 2024-10-01 at 11 40 02" src="https://github.com/user-attachments/assets/6a572b8d-0a32-46ef-ad59-6024d65ef351">

**Comment by Benjin** [comment]
@croblesm @jdesai-24

**Comment by jdesai-24** [comment]
We can add a small icon in the beginning of "Browse Azure"

**Comment by Benjin** [comment]
@jdesai-24 can you send me an svg to use or find an appropriate icon in the fluent icon library, please?
