### ISSUE TITLE
Connect Button sometimes gets cut off when connecting to Azure SQL DB

### ISSUE THREAD

**Issue by caohai** [microsoft/vscode-mssql#18123]
The connect button is cutoff and there's no way to scroll down if the UX is zoomed in. The only solution is to zoom out.
<img width="559" alt="Screenshot 2024-10-01 at 12 30 20" src="https://github.com/user-attachments/assets/c6bf05e0-c959-40cd-9b52-4254f034a146">

**Comment by Benjin** [comment]
Add a sticky footer
