### ISSUE TITLE
Database name is empty when editing saved connection

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18149]
The Database name text box is empty when editing a previously saved connection:

 ![image](https://github.com/user-attachments/assets/3a850861-b525-47b4-a9da-8bcf53b33c87)

~~It would be great to show a drop-down list with all possible databases I can select. Instead of leaving this parameter as a user input (regular text box).~~ Tracking as #18209

**Comment by Benjin** [comment]
Splitting the second request (dropdown list with databases on the specified server) into a different issue: #18209

**Comment by Benjin** [comment]
@croblesm I wasn't able to reproduce this bug on the latest internal build.  Can you confirm if it's still happening, and if so, add some more specific repro steps?

https://github.com/user-attachments/assets/6756d842-801a-43f9-be2c-e2f1b5175117

**Comment by croblesm** [comment]
> [@croblesm](https://github.com/croblesm) I wasn't able to reproduce this bug on the latest internal build. Can you confirm if it's still happening, and if so, add some more specific repro steps?
> 20241017-1634-45.7901864.mp4

Nice! I will confirm later today.
