### ISSUE TITLE
Update Browse Azure dropdown lists

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18154]
Consider displaying the elements of each dropdown list below the text box. The text box can be repurposed to perform text-based filters. The current design forces the user to scroll down the whole list (or type the initial letter of what the user is looking for).

Moving the dropdown list will be very helpful when the user has many subscriptions, RGs, locations, servers. Also make all the values required, not just ```Server```.

![image](https://github.com/user-attachments/assets/f9056f9c-ec58-4dd2-a63f-3cb1fcf20751)

Tagging @jdesai-24 for visibility

**Comment by Benjin** [comment]
Auto select first server in list.  Come up with placeholder text for empty dropdowns
