### ISSUE TITLE
Add a refresh button in all levels

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18158]
Consider adding a refresh button to each node and level in the Object Explorer list. This would provide convenience for developers by removing the need to ```right-click``` and select ```refresh``` at database level, as is currently required in the extension.

**Comment by aasimkhan30** [comment]
There is no requirement to perform refreshes at the database level. We currently have a refresh button available at all levels. Were you unable to find it at any level?

Few examples: 
![Image](https://github.com/user-attachments/assets/0c807d53-9bd5-4f0b-9aa5-93a06bcc45f5)
![Image](https://github.com/user-attachments/assets/7986948f-36b8-4e9e-b11e-c8a8d7861767)

**Comment by croblesm** [comment]
> There is no requirement to perform refreshes at the database level. We currently have a refresh button available at all levels. Were you unable to find it at any level?
Yes, this is required. When creating a new database, the database node will not get updated by default

What you have on the screenshot is not a button, that is a context menu. I'm referring to the icons that appear on the right-hand side as new table or filter

![Image](https://github.com/user-attachments/assets/a51ea137-bb47-44ff-ba3b-17227ad6b908)

The refresh button is missing in all levels.

**Comment by aasimkhan30** [comment]
I see. So you are requesting inline refresh icons. Got a little confused by the wording of the issue.
