### ISSUE TITLE
Changes to Column Name in Column Properties Not Reflected in Column List or SQL Script

### ISSUE THREAD

**Issue by croblesm** [microsoft/vscode-mssql#18162]
Column name changes made in the ```Column Properties``` are not being reflected in the column list or SQL script.
![image](https://github.com/user-attachments/assets/0ee57ef5-26ba-43a7-988a-1b59e911013a)

**It appears to only work for data type updates.**

**Comment by aasimkhan30** [comment]
@croblesm , it seems to be working on my end

https://github.com/user-attachments/assets/771228e0-ebcf-48f1-982e-0a250bcb4612

Can you please open devtools console: Help> Toggle Developer tools > Console and paste any error you see there when you try to make the edit?

**Comment by croblesm** [comment]
Interesting! I don't get any errors, and it is working now. It was probably a local problem with VS Code.
Let's close this issue @aasimkhan30.
