### ISSUE TITLE
Multiple result sets in a batch don't work correctly

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18213]
Steps to Reproduce:

1. Run multiple queries in a batch, such as:

```SQL
 SELECT 1

 SELECT 2

 SELECT 3
```

Expected: Three resultsets with 1, 2, 3

Actual: Only the final result set.  If we add GO between the statements everything works as expected.

![Image](https://github.com/user-attachments/assets/6f2d6a56-1502-47bb-abd1-a05dd7fdc219)

**Comment by kburtram** [comment]
@caohai this one looks pretty impactful too.  Could you please take a look when you have a chance?

**Comment by caohai** [comment]
@kburtram Sure this is a bug I missed, will send out a fix this afternoon
