### ISSUE TITLE
Too many notifications on first launch after update

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18210]
Ideally we should only have one notification, but we have two.  I would suggest removing release notes prompt, but since the notes will have details on the new features, we probably do want that prompt.  Maybe the "Learn More" link can substitute for what we want to accomplish with the Release Notes prompt.  

Also, for wording the prompt, I like the more casual tone, but I might rephrase from "GUI-features" to like "The MSSQL for VS Code extension is introducing new modern data development features!  Would you like to enable them?"  I guess the "GUI" part seems more incidental to me.

![Image](https://github.com/user-attachments/assets/c4b73e83-50df-428b-b38d-e51b9cd40c46)

**Comment by kburtram** [comment]
The other area to consider is it I click "Learn More" then the notification goes away.  Then if I want to "Enable Rich Experiences" the notification is already gone.  I wonder if a link in the text that doesn't dismiss the prompt makes more sense for the Learn More?

**Comment by kburtram** [comment]
Oh, and I finally, clicked the Enable button and then I see the below?  Can the enable button be something like "Enable Experiences & Reload"?  I mean, it's probably fine, but seems like unnecessary to split the set & reload steps, unless I'm missing something here?

![Image](https://github.com/user-attachments/assets/9427f514-7272-46ef-bdf5-12ed78bf591e)

**Comment by Benjin** [comment]
@kburtram 
> Oh, and I finally, clicked the Enable button and then I see the below? Can the enable button be something like "Enable Experiences & Reload"? I mean, it's probably fine, but seems like unnecessary to split the set & reload steps, unless I'm missing something here? (edit: or maybe this prompt is coming from VS and we can't control/consolidate it?)

The prompt to reload is coming from our extension, but via a vscode-emitted event that fires any time a config option changes.

I can just execute the reload immediately after the user clicks "enable features and reload"; this will still pop up _very_ briefly before the window reloads, which I think is okay since it's a one-time thing.  The other option is to not display the reload prompt for this config flag, but that risks confusing users if they enable it manually via the settings UI or json.

**Comment by Benjin** [comment]
> Ideally we should only have one notification, but we have two. I would suggest removing release notes prompt, but since the notes will have details on the new features, we probably do want that prompt. Maybe the "Learn More" link can substitute for what we want to accomplish with the Release Notes prompt.

They're a little different (different triggers, different target content), but I think we could display the "we have new features!" prompt if it's relevant (disabled and not hidden) and the regular release notes prompt if it isn't (ux flag is enabled already or do-not-show-ed).
