### ISSUE TITLE
Cannot see the selected rows clearly in new result grid

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18211]
Steps to Reproduce:

1. Run a query with new results grid

Expected: Selected regions are clear

Actual:  They are not.  Can we use the previous styling for this?

![Image](https://github.com/user-attachments/assets/4a5c5dc0-9c17-4caf-9dab-db25dd3c1496)

**Comment by kburtram** [comment]
@caohai @cssuh do we know if a fix is coming for this?  It seems like "baseline functionality" we need here, right?

**Comment by caohai** [comment]
@kburtram This should be fixed in this PR, the gif in the PR shows the region selection styling.
https://github.com/microsoft/vscode-mssql/pull/18206

**Comment by kburtram** [comment]
thanks @caohai!  I figured a fix was coming but wanted to open "just in case".  I couldn't find an existing issue.

**Comment by cssuh** [comment]
> [@kburtram](https://github.com/kburtram) This should be fixed in this PR, the gif in the PR shows the region selection styling. [#18206](https://github.com/microsoft/vscode-mssql/pull/18206)

That PR linked doesn't change much around region selection styling, but I can address it in a future PR.

**Comment by caohai** [comment]
@cssuh This issue is fixed, right
