### ISSUE TITLE
JSON cells in results grid don't link to new editor with JSON content

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18216]
Steps to Reproduce:

1. Run a query that produces a JSON cell.  Such as:

```SQL
WITH RecursiveCTE AS (
    SELECT 1 AS Level, CAST('Start' AS NVARCHAR(MAX)) AS Data
    UNION ALL
    SELECT Level + 1, CAST(CONCAT(Data, N' -> Level ', CAST(Level + 1 AS NVARCHAR(10))) AS NVARCHAR(MAX))
    FROM RecursiveCTE
    WHERE Level < 50
)
SELECT Level, Data
FROM RecursiveCTE
FOR JSON PATH, ROOT('NestedMadness')
```

Expected: JSON cell is a link to a new JSON file editor with the content from the cell.

Actual: The cell looks like a link but nothing happens when I click

![Image](https://github.com/user-attachments/assets/fc4bad30-45e9-4283-b6a0-e1f7e422e44c)

**Comment by Benjin** [comment]
Also was unable to copy the json out of the cell

**Comment by Benjin** [comment]
Similar to #18339
