### ISSUE TITLE
Run a query with a loop is painfully slow to execute

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18246]
Steps to Reproduce:

1. Run a query with a loop, like below.

```SQL
-- Query that prints tons of messages
DECLARE @j INT = 0;
WHILE @j < 10000 -- Adjust this number to control how many messages are printed
BEGIN
    PRINT 'Message ' + CAST(@j AS NVARCHAR(10)) + ': ' + CAST(NEWID() AS NVARCHAR(36));
    SET @j = @j + 1;
END
```

Expected: The query runs and renders quickly.

Actual: It does not.  Compare the execution of this snippet between vscode & SSMS.  It takes a like 100x as long in my env.

**Comment by Benjin** [comment]
Pri 1 for investigation; if complex, defer to Nov/Dec

**Comment by caohai** [comment]
I did some quick investigation yesterday and I believe the main issue comes from the way we handle message event, each call to the event handler triggers a call to the webview, which can get slow with a large number of msg event. Rendering all the messages once takes a few seconds, which is not super quick but is not the bottleneck for now.

I'll move this issue to Nov and continue the investigation/fix.
