### ISSUE TITLE
Result grid client-side sort popup has a Cancel option

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18250]
Steps to Reproduce:

1. Run a query and sort one of the columns client-side

Expected: Sort Ascending/Sort Descending and maybe like "Reset"

Actual: Cancel item, that doesn't appear to do anything

![Image](https://github.com/user-attachments/assets/c9baf5c6-1c01-43b0-9c38-22e06706932e)

**Comment by Benjin** [comment]
Does cancel the context menu or cancel the sort?  unclear
