### ISSUE TITLE
add link handling for Query Plan in query results pane

### ISSUE THREAD

**Issue by laurennat** [microsoft/vscode-mssql#18263]
Don't forget to address the second part of bug #18254:
> Results pane shows the XML **with a link that opens the plan in its own tab**

When I check out this branch, Looks like the link still isn't able to be opened.

_Originally posted by @Benjin in https://github.com/microsoft/vscode-mssql/pull/18258#pullrequestreview-2375912917_

**Comment by caohai** [comment]
@laurennat I'll ping you once I finish implementing https://github.com/microsoft/vscode-mssql/issues/18216
I might add a `console.log("xml cell")` to the xml link handler and you can modify the hander behavior after that.

**Comment by Benjin** [comment]
Similar to #18339
