### ISSUE TITLE
Handle long error messages correctly

### ISSUE THREAD

**Issue by cssuh** [microsoft/vscode-mssql#18280]
- MSSQL Extension Version: 1.25

Steps to Reproduce:

1. Connect to a server that requires a firewall rule update

There are two issues:

1. The error message is too big for the container
2. The error message should be focused on the screen when it appears (I didn't see it until I scrolled up in the connection dialog)

 
![Image](https://github.com/user-attachments/assets/911b3744-d647-4aa9-90d5-e43036715d5e)

**Comment by Benjin** [comment]
@cssuh can you confirm that you're still seeing this on the latest build from main?  I just went to repro it, and the error box appears to be already resizing correctly:

![Image](https://github.com/user-attachments/assets/7987f8e9-d9c0-4a91-a85f-3646c1eb060d)
