### ISSUE TITLE
Context menu in results grid doesn't appear correctly themed on Light mode

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18293]
OS: macos
Steps to Reproduce:

1. RIght click on result grid in light mode,

Expected: Correct theme of menu

Actual: Dark themed menu in Light mode

![Image](https://github.com/user-attachments/assets/e48c1239-5f06-40c3-afaf-a28ba4f23854)

**Comment by Benjin** [comment]
If it's something that we control the rendering of, let's use [the Fluent Menu](https://react.fluentui.dev/?path=/docs/components-menu-menu--docs)
