### ISSUE TITLE
Query Results Grid can no longer be viewed separately of editor selection

### ISSUE THREAD

**Issue by munawes** [microsoft/vscode-mssql#18316]
- MSSQL Extension Version:
- VSCode Version: 1.94.2
- OS Version: Win 11

In the past I was able to run queries side by side and have both result sets open at the same time. With the new update this is no longer possible which impedes workflow due to a lack of being able to quickly reference multiple data sets at once. 

Steps to Reproduce:

1. Open 2 editor tabs
2. Run a query in each tab
3. Switching between tabs also switches between results

**Comment by AlertedCoffee** [comment]
I have the same problem.
I would like to return to the old type of output, it was more convenient.
Maybe there is some kind of setting for this

**Comment by D1lsh0d** [comment]
same shit

> I have the same problem. I would like to return to the old type of output, it was more convenient. Maybe there is some kind of setting for this?

**Comment by nbarnwell** [comment]
Yes unfortunately this is very accurate. I'll be going back to the old experience until this is improved.

**Comment by benmcf** [comment]
I have disabled the new features because of this, too. It's essential for me to be able to view the query results while working in a tab other than the tab that produced the results.

**Comment by Benjin** [comment]
Thank you for trying out the new UI features we introduced in this extension! ❤️
 
We're hearing you, and we agree with you that viewing query result sets side-by-side is critical!  Please note that this is an early public preview release, and the new features (including this one) are still actively in development. If the current functionality is disrupting your workflow, you can disable these preview features using the configuration setting below. We appreciate your patience as we continue refining these features.
 
👉 Good news: we’re already planning to introduce the ability to view result sets side-by-side in our next release! This will allow you to move a point-in-time snapshot of result sets from the docked pane into a separate document window, enabling you to keep multiple result sets visible simultaneously, or view them even when the SQL query window isn’t open.  We’ll post some UX design concepts in this issue thread later this week in case you'd like to share some early feedback on our design for how this will work.

Thanks again for testing these features and sharing your insights. We hope you’ll continue to explore them as we make progress toward the next release. Please let us know if there’s anything else we can do to improve your experience!

----

Here’s the setting to disable the new features if the current experience is disruptive. Thank you for your support!

![Image](https://github.com/user-attachments/assets/02254539-4647-4a21-bd74-f2e3e1f9391e)

or add `"mssql.enableRichExperiences": false` in your user settings JSON

**Comment by ThomasGrammer** [comment]
Thank you for your work, and for considering our feedback!
I read your comment as "default will be output area, but you can move it to a tab". That is great, but for me that would still be disruptive.
Could we have an option, to get the rich experience output per default in a tab, instead of the console area? So the output of a code window always goes to the same tab?
I like the rich experience output, but want to keep having my outputs on a different monitor than my code. Without having to drag them there every time. With tabs that was easy.

**Comment by Benjin** [comment]
What does everything think about this experience?

* Queries be popped out into a separate tab and dragged around or split like any other tab.  As before, they're live views that will update when the associated query is re-run.
* Query results still default to the pane below the query, like it is in Azure Data Studio and SSMS, but the first time you pop it out, you're asked if you'd like to make that the default behavior going forward.

https://github.com/user-attachments/assets/a6bb579d-011a-4513-b37d-ba48c7a10472

**Comment by NHCC-IRE-DEV** [comment]
This would work.

**Comment by ThomasGrammer** [comment]
yes, sounds good!

**Comment by munawes** [comment]
I think this is a much better experience for both types of users, those who prefer a more "pinned results" layout, and those who would like to have their layout be more custom. Thank you for listening to the community!
