### ISSUE TITLE
CTRL + C not working for cells returned from SELECT queries in Enhanced MSSQL Extension for Visual Studio Code

### ISSUE THREAD

**Issue by Crhistake** [microsoft/vscode-mssql#18315]
- MSSQL Extension Version: 1.25.0
- VSCode Version: 1.94.2
- OS Version: 10.0.22621

Steps to Reproduce:

1. Run any SELECT query
2. Try to copy cell result with CTRL + C

**Comment by kburtram** [comment]
@Crhistake thanks for reporting and testing out the new UX!  The keyboard shortcuts didn't make it for Oct, but will be in Nov.  Please use the context menu for copying results in the meantime.  Sorry for not having this basic functionality in the initial preview release.

**Comment by Crhistake** [comment]
Thank you for giving us a swift return! I've been enjoying the features so far, so it's great to see such an active community! Loved the New Table creator!

**Comment by NHCC-IRE-DEV** [comment]
The copying doesn't work in v.  1.25.0 at all for me, even using the context menu. I had to downgrade to v. 1.24.0.
