### ISSUE TITLE
[Rich Experience] Blank Result Pane After SELECT

### ISSUE THREAD

**Issue by EdCallahan** [microsoft/vscode-mssql#18329]
- MSSQL Extension Version: 1.25.0
- VSCode Version: 1.94.2
- OS Version: Win 11

Running some combinations of multiple SQL commands in the same Execute seems to cause an empty Results pane. I've notice that running two SELECT statements in the same Execute seems to work, but combing a USE or DROP TABLE along with the SELECT in the same execute causes the Results page to be blank.

For example:

1. "SELECT count(*) from dbo.Numbers"returns a result
2. "Use Utilities; GO; SELECT count(*) from dbo.Numbers" causes a blank Results pane

https://github.com/user-attachments/assets/729963a0-5a55-4c84-9cdd-a632979b8cfe

**Comment by EdCallahan** [comment]
The problem may just be with executing multiple commands at the same time, in the same Execute. 

Steps to Reproduce:

1. Run: "SELECT count(*) from dbo.Numbers" and Result pane works OK
2. Run: "Use Utilities; GO; SELECT count(*) from dbo.Numbers" and Result pane is blank

https://github.com/user-attachments/assets/fb607c93-dce1-4fff-8df4-b922746182fe

**Comment by caohai** [comment]
Thanks for creating the issue! I can confirm the repro, will take a look.
