### ISSUE TITLE
Connection Dialog broken

### ISSUE THREAD

**Issue by gbrueckl** [microsoft/vscode-mssql#18321]
Please add "Area" label and repro steps before submitting --> does not seem like I could do this?!

---
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22621

SQL Server (mssql): v1.25.0

Steps to Reproduce:

1. add a new connection
2. Connection Dialog is empty or incomplete
 an error message in VSCode is shown: `Cannot read properties of undefined (reading 'displayName')`

![Image](https://github.com/user-attachments/assets/3d24164b-0f22-4200-8706-c0572dfec8c6)
![Image](https://github.com/user-attachments/assets/8c65d04f-8b65-4442-96c4-76e062862c57)

**Comment by Benjin** [comment]
@gbrueckl is this continuing to happen for you after you restart all instances of VS Code?  When it does occur, do you see any messages in the VS Code Output pane named "SqlToolsService Initialization"?  It appears that STS didn't start properly, which is what this dialog uses for getting all the available connection options.

**Comment by schwabmi** [comment]
Hello,
We are facing the same issue.

Are there any updates?

**Comment by Benjin** [comment]
It appears that the connection dialog initialization code isn't correctly reading your saved connections from your user settings JSON.  If you open that file (command palette: `Preferences: Open User Settings (JSON)` and find the `mssql.connections` config entry, do you spy anything in that array appears anomalous?

If you're willing to block out all identifying information (emails, GUIDs, server names, passwords, usernames) from that entry and paste it here, I can identify the specific issue.

**Comment by gbrueckl** [comment]
actually no, in fact i also renamed all `mssql.connections` to `mssql123.connections` but the issue is still the same

**Comment by DMoschou** [comment]
Same issue here...any update?

**Comment by Benjin** [comment]
The issue we were able to identify is related to the Entra accounts stored in the MSSQL's cache.  In this instance, we were able to resolve the issue by removing the existing Entra accounts from MSSQL by running these two commands:

1. "MSSQL: Clear Microsoft Entra account token cache"
2. "MSSQL: Remove Microsoft Entra Account" for each account that shows up

Can others hitting this issue see if this gets the Connection Dialog back into a functioning state?

**Comment by gbrueckl** [comment]
for me this worked - thanks @Benjin

**Comment by Benjin** [comment]
Excellent to hear!  I'm going to leave this issue open to track adding in additional error handling and in this area so we can hopefully get a more complete fix in place.

**Comment by airazores** [comment]
Hi! Have same issue, but deleting  Entra accounts stored in the MSSQL's cache did now work. Any alternative?

Thanks

**Comment by Benjin** [comment]
@airazores you're seeing this error in the console, correct? `Cannot read properties of undefined (reading 'displayName')`

Can you reproduce the issue after changing the extension's logging level to verbose to see if anything stands out in the logs?  `    "mssql.tracingLevel": "Verbose"`.  I'm particularly interested in any entries related to the Connection Dialog or Azure accounts/authentication.

Make sure to scrub personal info from any log excerpts before you post them.

**Comment by airazores** [comment]
@Benjin no error in the console.

**Comment by airazores** [comment]
In the meantinme, deleted settings.json, restarted VS Code and is now working fine.

Thanks
