### ISSUE TITLE
[Rich Experience] Query results can no longer be opened in another window

### ISSUE THREAD

**Issue by danhogan** [microsoft/vscode-mssql#18335]
- VSCode Version: 1.94.2
- OS Version: Win 11

Prior to enabling the new rich experience, I was able to put the query results in a separate window and easily put it where I want (like another monitor). This newer version seems to lock it to the same window/tab in a new way. Is there still a way to put it in another window similar to the terminal? If not, could that be added?

**Comment by kburtram** [comment]
Thanks for evaluating and leaving feedback for these new preview experiences!  We're tracking this with issue https://github.com/microsoft/vscode-mssql/issues/18316.  Please add any additional comments there.  Please note the current experience is still in development and we're going to add functionality to address this limitation in the next release.
