### ISSUE TITLE
[Rich Experiences] Export Results Buttons will cover by scroll bar when zoom level bellow 0

### ISSUE THREAD

**Issue by wilson97183** [microsoft/vscode-mssql#18334]
- MSSQL Extension Version: 1.25.0
- VSCode Version: 1.95.0
- OS Version: Windows 11 10.0.22631 

Steps to Reproduce:

1. Enable in settings.json "mssql.enableRichExperiences": true
2. Execute any query
3.  `Ctrl + -` to shirink zoom level (zoom out )

Buttons for export results will be cover by scroll bar like this
![Image](https://github.com/user-attachments/assets/1a2efe8b-9dba-4226-b2ad-cbe4b9aab18f)

 This also happen when zoom level set to 3 or higher, even though I don't think anyone will do that in daily use.

**Comment by Benjin** [comment]
I think this was fixed for 1.26.0 (November's release).  If you're still seeing this bug on the latest version, please re-open this issue.

Zoomed in:
![Image](https://github.com/user-attachments/assets/6d95b1d3-6f9f-48e0-a977-d7b2f08bf887)

Zoomed out:
![Image](https://github.com/user-attachments/assets/637de8c9-40c7-4e63-acf7-3f16ca03f856)
