### ISSUE TITLE
Enhanced MSSQL Extension 1.25.0 - missing XML cell preview in a new pane

### ISSUE THREAD

**Issue by htrzewik** [microsoft/vscode-mssql#18339]
Old **Query Results Pane** had possibility to open XML document from cell in new pane (same feature as in SQL Studio). In new **Query Results Pane** this feature is missing - there is no link in XML cell. Please, do :)

**Comment by Benjin** [comment]
"Bug" label because this is missing functionality over the old Query Results UX, even though it's technically an enhancement.
