### ISSUE TITLE
[Rich Experience] Bad Query Result header readability on some themes

### ISSUE THREAD

**Issue by atbraz** [microsoft/vscode-mssql#18340]
- MSSQL Extension Version: 1.25.0
- VSCode Version: 1.95.0-insider
- OS Version: Win 11 Pro 23H2

Steps to Reproduce:

1. Use **some** non-default themes
1. Enable in settings.json "mssql.enableRichExperiences": true
2. Execute any query

On some themes (light and dark) the result header background and foreground colors make for some unreadable combinations.

#### Dark (Visual Studio)
![Image](https://github.com/user-attachments/assets/470de1f8-d7b2-40ee-84f5-68fcb16a632e)

#### Light (Visual Studio)
![Image](https://github.com/user-attachments/assets/6470deb1-88d8-4fe3-bd5b-83d093d70f58)

#### Github Dark
![Image](https://github.com/user-attachments/assets/6b23ce97-589d-467d-bce0-d9dfd0f66493)

#### Github Light
![Image](https://github.com/user-attachments/assets/46c3b95b-f21e-42ee-bc27-cdc733a6d5c8)

#### Red
![Image](https://github.com/user-attachments/assets/0a4c6fe5-cf29-4487-a335-f408b34f7731)

#### Solarized Dark
![Image](https://github.com/user-attachments/assets/9ce72c5f-fb0c-42c6-9f32-7180268213e6)

#### Monokai Pro (Filter Machine) - or almost any Monokai
![Image](https://github.com/user-attachments/assets/11cff800-9e80-4ddd-8005-b92d0708976c)

#### Tomorrow Night Blue
![Image](https://github.com/user-attachments/assets/e8dd418c-7cbc-4615-bf61-3e8e2cd32be5)

#### Light High Contrast
![Image](https://github.com/user-attachments/assets/6a82ce17-35e9-432a-93b2-06c131e0fd5c)

#### Ayu Dark
![Image](https://github.com/user-attachments/assets/9c5e8722-aa8a-4f8b-99c0-d20c5811a3c4)

**Comment by Benjin** [comment]
Thanks for bringing this to our attention!

@cssuh, do you think you'll be able to fix this for November, at least for the Light High Contrast theme?  Seems we'll have to delve deeper into the many theme color options to make sure we're using combinations that are visible.

**Comment by Benjin** [comment]
We've fixed many theming issues across the extension with https://github.com/microsoft/vscode-mssql/pull/18347, which will be in our next release.  Please open more issues if you find any other places where we have low contrast on some themes!

Monokai Pro (Filter Machine):
![Image](https://github.com/user-attachments/assets/60769dc3-0f19-49c0-b461-3c6a15e1364a)

Tomorrow Night Blue:
![Image](https://github.com/user-attachments/assets/0a28169f-9b1a-4af6-8a55-3c7f38fd4d48)

Light High Constrast:
![Image](https://github.com/user-attachments/assets/7cb1b3e6-6493-4f82-b586-a1c9b2619f73)

Ayu Dark:
![Image](https://github.com/user-attachments/assets/8c6d45c9-22bb-4df4-b6e1-26b80a0d3c2c)
