### ISSUE TITLE
Query Result, Result grid does not show

### ISSUE THREAD

**Issue by DanielPieterSmit** [microsoft/vscode-mssql#18350]
- MSSQL Extension Version: v1.25.0
- VSCode Version: 1.94.2
- OS Version: Windows 10 Enterprise, 10.0.19045 Build 19045

Steps to Reproduce:

1. Using SQL Server extension, open new *.sql file 
2. Connect to server
3. Execute SQL Query
4. View Results tab
5. Messages will display correctly
6. Result does not display anything

**Comment by EdCallahan** [comment]
Could this be a dup issue with: https://github.com/microsoft/vscode-mssql/issues/18329? Are there multiple commands in the SQL file?

**Comment by caa212** [comment]
I am seeing this same behavior with a single connection and single query command.  I also renamed my settings.json file and reinstalled the extension, however the issue persists.  VS Code 1.95.2 and mssql 1.25.0

**Comment by Benjin** [comment]
Are you hitting this on the new or old query results grid?  (what are your settings for `mssql.enableRichExperiences` and `mssql.enableNewQueryResultFeature`?)

We've made a bunch of stabilizing fixes to the new query results grid with v1.26.

**Comment by caa212** [comment]
@Benjin - it looks like both of those settings are enabled.  And a quick test using v1.26 appears to be working thus far.  I ran into an issue when saving to Excel, but I will need to restart my system and try again.  Thanks for the updates.

**Comment by Benjin** [comment]
Excellent to hear!  If you're still hitting the issue when saving to Excel, definitely file another issue so we can get that fixed.
