### ISSUE TITLE
Query execution message text isn't positioned properly

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18405]
1. Run a query and look at the message

Expected: Text more in the left of the visible pane.

Actual: Text is way too far to the right.

![Image](https://github.com/user-attachments/assets/5a9f4446-0130-4300-9ef1-6836760cea2c)

For reference here's what it looks like in ADS:

![Image](https://github.com/user-attachments/assets/486e13bd-bdd1-401b-82f9-9e9af1e58fc0)

**Comment by laurennat** [comment]
also, if there are multiple lines in the message, it ends up not spacing properly

![Image](https://github.com/user-attachments/assets/fdce0f0d-a1c4-4922-a78a-2f9a9d9e4a00)

**Comment by caohai** [comment]
> also, if there are multiple lines in the message, it ends up not spacing properly
> 
> ![Image](https://github.com/user-attachments/assets/fdce0f0d-a1c4-4922-a78a-2f9a9d9e4a00)

@laurennat Can you share the repro query for this?

**Comment by laurennat** [comment]
select 2
for json auto

**Comment by croblesm** [comment]
@caohai 
Same issue. This is the query I used:

```sql
INSERT INTO authors (id, first_name, middle_name, last_name) VALUES
(6, 'Frank', 'Patrick', 'Herbert'), 
(7, 'Orson', 'Scott', 'Card'), 
(8, 'Suzanne', NULL, 'Collins'),
(9, 'Andy', NULL, 'Weir'), 
(10, 'Yuval', 'Noah', 'Harari');
```

Result:
![Image](https://github.com/user-attachments/assets/efa60b34-f62b-430a-8c66-6e5331d18ee8)
