### ISSUE TITLE
Unable to add new connection on Windsurf Editor

### ISSUE THREAD

**Issue by iml885203** [microsoft/vscode-mssql#18436]
Type: <b>Bug</b>

show 'extension.addObjectExplorer' not found when click 'Add Connection' button

Extension version: 1.9.0
Windsurf version: Windsurf 1.94.0 (8700dafefa2ae56df8cf3f66b96d4d03815405fa, 2024-11-18T23:15:04.974Z)
OS version: Darwin arm64 24.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|24.00GB (0.04GB free)|
|Process Argv|carina.casino|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Benjin** [comment]
We aren't providing support for VS Code derivatives, but we invite you to fork this repo, follow the [contribution instructions](https://github.com/microsoft/vscode-mssql/wiki/contributing), and send a PR for any compatibility fixes you come up with.  If you find any issues when running this extension in VS Code, please continue to file issues here.  Thanks!
