### ISSUE TITLE
[Rich Experience] Message pane empty after running command

### ISSUE THREAD

**Issue by EdCallahan** [microsoft/vscode-mssql#18447]
- MSSQL Extension Version: 1.26.0
- VSCode Version: 1.95.3
- OS Version: Win11

Steps to Reproduce:

1.  Close any open Query Results (Preview) panes
2.  Run a command such as USE MASTER or an ALTER SCHEMA. Message pane is not populated with messages
3.  Run a SELECT. Now Message pane contains messages
4.  At this point, USE MASTER or ALTER SCHEMA, etc, generate messages on the Message pane

Thanks for your work on this project, VSCode is a nice place to so SQL work.

https://github.com/user-attachments/assets/6ae73ef5-36c3-409a-b439-6c97365d58a8

**Comment by Fred-Wu** [comment]
I was about to report the same.  

If `enableNewQueryResultFeature` is set as true,  it shows nothing even when a query is being executed. 
It should behaviour like the old one, telling you

![Image](https://github.com/user-attachments/assets/fadf872d-6e4a-43ce-986d-4203c016cf47)


Also for an empty table gets queried and written to a temporary table, the message pane also shows nothing, which could not tell what's wrong with the table in the first place.

**Comment by caohai** [comment]
@EdCallahan @Fred-Wu Thanks for reporting the bug. I can confirm the repro. I'll take a look at the issue.

**Comment by Fred-Wu** [comment]
> [@EdCallahan](https://github.com/EdCallahan) [@Fred-Wu](https://github.com/Fred-Wu) Thanks for reporting the bug. I can confirm the repro. I'll take a look at the issue.
> 
> > for an empty table gets queried and written to a temporary table
> 
> [@Fred-Wu](https://github.com/Fred-Wu) Are you talking about something like this with source table being an empty table?
> 
> ```
> SELECT *  
> INTO #TempDestinationTable
> FROM Source_Table
> WHERE ...
> ```

Yes.  In the old interface, the message would show how many rows affected. But nothing appears in the new interface.
