### ISSUE TITLE
Message issues

### ISSUE THREAD

**Issue by dotvihar** [microsoft/vscode-mssql#18452]
# Technical info

## MSSQL Extension Version:
> Name: SQL Server (mssql)
> Id: ms-mssql.mssql
> Version: 1.26.0

## VSCode Version:
> Version: 1.95.3 (user setup)
> Commit: f1a4fb101478ce6ec82fe9627c43efbf9e98c813
> Date: 2024-11-13T14:50:04.152Z
> Electron: 32.2.1
> ElectronBuildId: 10427718
> Chromium: 128.0.6613.186
> Node.js: 20.18.0
> V8: 12.8.374.38-electron.0
> OS: Windows_NT x64 10.0.22631

## OS Version:
> Edition: Windows 11 Enterprise
> Version: 23H2
> OS build: 22631.4460
> Experience: Windows Feature Experience Pack 1000.22700.1047.

---
# Message BUGs
## 1. Do not receive any messages during executions
I have a query that runs for about an hour. There are print statements in the code to help me track its execution, but I do not receive any messages during the execution.
```sql
-- code example
print @msg_body + ' finished. (' + convert(varchar, @current_dttm) + ')'
print 'Time elapsed: '
print '_ millisecond: ' + convert(varchar, (datediff(ms, @start_dttm, @current_dttm)))  + ', '
print '_ second: '      + convert(varchar, (datediff(s, @start_dttm, @current_dttm)))   + ', '
print '_ minute: '      + convert(varchar, (datediff(mi, @start_dttm, @current_dttm)));
```

## 2. The lines overlap in Messages pane
![Image](https://github.com/user-attachments/assets/cf57a8ec-d885-489c-b8e4-ade095f6e93c)

**Comment by caohai** [comment]
Thanks @dotvihar for creating the issue!
We are aware of these two bugs (no msg && rendering issue) and we are actively working on a fix. 
For the no msg bug, you can track the progress of the fix at https://github.com/microsoft/vscode-mssql/issues/18447

**Comment by sistefi** [comment]
## Hola el mismo problema, sin mensajes.
### No se da en todos los casos pero es muy largo el proseso de tener que verificar en la base de datos, para ver si todo quedo bien.

> Me acomode muy bien con la APP Grecias.
