### ISSUE TITLE
[Rich Experience] Query Results Messages unreadable

### ISSUE THREAD

**Issue by gaj104** [microsoft/vscode-mssql#18486]
When viewing Messages the 'grid' is not auto sizing and instead showing fixed width and height resulting in unreadable messages.

Actual

![Image](https://github.com/user-attachments/assets/fbd5f12c-693e-4970-a2a4-79b422655f4e)

Expected (e.g. as per Azure data studio)

![Image](https://github.com/user-attachments/assets/8bbe9902-64fe-42a6-8d4f-c7e3ce82fb20)

This was not an issue beforehand and maybe the result of a updated release.

**Comment by Benjin** [comment]
@caohai is this resolved by https://github.com/microsoft/vscode-mssql/pull/18483?

**Comment by caohai** [comment]
@gaj104 Thanks for creating the issue. This issue has been fixed in `main` and will be released soon.
@Benjin Yes, #18483 fixed this issue, here's the screenshot I just took with the latest `main`
![Image](https://github.com/user-attachments/assets/34139358-5461-4850-86ba-48b2a20cec48)

**Comment by gaj104** [comment]
Thanks @caohai for resolving - much appreciated.
