### ISSUE TITLE
Messages don't render sometimes when the query contains an error

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#18482]
Steps to Reproduce:

1. Run a query with an error

Expected: Messages are rendered with the error message

Actual: Message pane is blank

![Image](https://github.com/user-attachments/assets/93e10163-61ed-4c27-a323-98db3e65429b)

**Comment by caohai** [comment]
Dup of https://github.com/microsoft/vscode-mssql/issues/18447
This issue should be fixed with https://github.com/microsoft/vscode-mssql/pull/18483
