### ISSUE TITLE
Messages in QUERY RESULTS (PREVIEW) are not displayed

### ISSUE THREAD

**Issue by tomasz-paluch-sh** [microsoft/vscode-mssql#18493]
- MSSQL Extension Version: 1.26
- VSCode Version: 1.95.3
- OS Version: Windows 11

Steps to Reproduce:

1. Execute correct/incorrect query (in previous version result and message are displayed in separate tab, now nothing is shown)
2. Check Query Results (Preview) in the Panel
3. Screenshot:
![Image](https://github.com/user-attachments/assets/0586876a-8292-43be-b332-44d91327be44)
4. It should be something like this:
![Image](https://github.com/user-attachments/assets/053f2627-e154-4cbd-a160-4ab364748de7)

**Comment by caohai** [comment]
@tomasz-paluch-sh Thanks for reporting the issue. We've merged a fix for this and it should come out with next release soon.
<img width="1162" alt="Image" src="https://github.com/user-attachments/assets/25e59f76-88d4-4c85-954e-7de550b6d689" />
