### ISSUE TITLE
Zero records produces 'Start row cannot be less than 0 or greater than the number of rows in the result set (Parameter 'startRow')'

### ISSUE THREAD

**Issue by gaj104** [microsoft/vscode-mssql#18531]
- MSSQL Extension Version:v1.27.0
- VSCode Version:1.96.2
- OS Version:Windows 

Steps to Reproduce:

1.Run a query with 0 records  e.g. 

select top 10 *
from sys.objects
where 1 = 0

When this is run the error:

"mssql: Something went wrong getting more rows: Start row cannot be less than 0 or greater than the number of rows in the result set (Parameter 'startRow')" is returned

![Image](https://github.com/user-attachments/assets/bac25424-fd44-4778-97f4-e17129bdf77d)

Expected outcome:

No error reported. Zero records are legitimate.

**Comment by caohai** [comment]
Thanks for creating the issue! We can confirm the repro and are working on a fix and that will be included in the next release.
