### ISSUE TITLE
Data grid scalability issues with large data sets

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#259]
The data grid hits some scalability issues with large data sets.  Specifically there are some cell border rendering issues on rows much over 500000, and selection operations don't seem to work.

**Environment**
MacOS Sierra (though I've seen similar issueso on other OS)

**Repro**
1. Select large dataset.  The below query should generate ~1000000 rows

SELECT *
FROM sys.all_objects a
CROSS JOIN sys.all_objects b;

2. Scroll toward the end of the result set and try to select cells

Expected: Renders and selection work correctly

Actual: Cells border doesn't draw consistently and selecting cells doesn't seem to work

**Comment by anthonydresser** [comment]
After some experimentation it seems it might be a problem in the slick grid lib as I was able to recreate some of the issues on in one of their tests. It seems to be an issue when you are getting 2.7 million + rows. There are no performance problems, only rendering problems.
