### ISSUE TITLE
Edit window loses focus after executing query

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#261]
The editor window loses focus when executing a query.  The experience seems better if the focus isn't lost so that the query can easily be edited and re-executed if needed.  This is consistent with SSMS behavior.

**Comment by fcatae** [comment]
+1. This is an odd experience from a DBA experience - when you're troubleshooting perf, you keep running manually the same query, so you dont want to lose the windows focus.

**Comment by ransagy** [comment]
+1 Yup, it seemed odd for me as well. I definitely figured this as a bug when i first encountered it.

**Comment by kburtram** [comment]
I've started a PR to try to improve this scenario #585.
