### ISSUE TITLE
Detect when workspace service is in bad state and handle appropriately

### ISSUE THREAD

**Issue by MitchellSternke** [Microsoft/vscode-mssql#272]
It is possible for the workspace service's in-memory model for a text document to become out of sync with the actual file's contents.

When this happens, we either need to recover (reload the file) or request that the user close and reopen the editor, otherwise there will be strange behavior with the language service/query execution.

**Comment by MitchellSternke** [comment]
For anyone looking into this, an example location where the service could be in a bad state is in WorkspaceService.cs, in the HandleDidChangeTextDocumentNotification(). The catch block there has a description.

Another example is the error returned from query execution when the Query object is null internally. This should never happen normally, so this would be another case where the service is likely in a bad state and needs to recover.

**Comment by kevcunnane** [comment]
Closing due to lack of customer reports.
