### ISSUE TITLE
Recently used connections shows duplicate entries

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#276]
OS: Windows.

Steps to reproduce:

1. Create a connection profile to a server. Leave database name blank 
2.  In the query window, execute "USE msdb" and then "USE master" to switch databases multiple times
3. Execute the Connect command again to show the list of connections

Expected:

- Only 1 entry for master

Actual:

- 2 entries for master are shown in the connection list

![image](https://cloud.githubusercontent.com/assets/10819925/20027500/c3c7fdfa-a2d2-11e6-8830-f258f8d0e352.png)

**Comment by Raymondd** [comment]
Have not been able to reproduce the issue.
