### ISSUE TITLE
Adding quote at end of word incorrect adds 2 quote marks

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#277]
For other file types (e.g. JSON, JS, C#) if you have a word like test, and you add a quote at the start (e.g. "test or 'test), then typing in a quote at the end of the word "test" or 'test' will only add the single " or ' character.
For .sql files, if you type his it adds 2 characters, e.g. "test"" or 'test''. 

- What makes this more annoying is hitting delete removes both characters - to succeed in adding the end quote you have to hit the right key then delete the 2nd quote

- This is an inconsistency with other editor types and quite annoying. We are basically failing to correctly detect we're at the end of a word and handle appropriately

**Comment by kburtram** [comment]
Fix with commit https://github.com/Microsoft/sqltoolsservice/commit/84eb164d8733521f688a6f1b7a613bd0a32beb21
