### ISSUE TITLE
Results view should adhere to the zoom in VScode

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#280]
Feedback from the Private Preview users. This appears to be a VSCode issue (see [VSCode Issue 5745](https://github.com/Microsoft/vscode/issues/5745)). It also affects the Markdown Preview viewer, but raising here for tracking.

- "Works pretty well. Only suggestion I have so far is adhering to the zoom in Vcode. Have a lot of dead space when you zoom on with the results pane. For those that present it could be an issue. I'm on Windows 10, VCode 1.7.1"

Steps to reproduce:

- Connect & execute a query in VSCode, which brings up the results view
- Select View -> Zoom in

**Expected**:
- Results view fonts etc. zoom in but the view takes up all the space

**Actual**:
- fonts are updated but the view takes up only a fraction of the space available. This makes zoom in / out essentially useless.

![image](https://cloud.githubusercontent.com/assets/10819925/20027861/0072059c-a2de-11e6-8038-61d4230fe695.png)

**Comment by kburtram** [comment]
@kevcunnane I think this is fixed in the latest VS Code.  I'll verify as part of the GA sign-off.

**Comment by abist** [comment]
@kburtram I can still reproduce this

**Comment by kburtram** [comment]
@abist great, then I'll remove this from the GA milestone since the fix needs to come from the VS Code side when they update to an electron version that has the chromium fix.

**Comment by anthonydresser** [comment]
Looks like this is still an open issue for electron, electron/electron#7375

**Comment by kevcunnane** [comment]
This has finally been fixed by the latest VSCode update, 1.13. I am closing and can happily report that zoom now works as expected.
