### ISSUE TITLE
Home + end keys in results view don't do anything

### ISSUE THREAD

**Issue by MitchellSternke** [Microsoft/vscode-mssql#329]
- MSSQL Extension Version: latest dev
- VSCode Version: 1.7.x
- OS Version: Windows

Steps to Reproduce:

1. Use home and end keys while the results grid is active

Expected: Home key goes to first column, end key goes to last column (like SSMS)
Actual: Home/end keys do nothing

**Comment by kevcunnane** [comment]
PR is out in the slickgrid repo: https://github.com/Microsoft/angular2-slickgrid/pull/1. This will resolve this issue once it's checked in. I'll close at that point since we automatically pull in updated version of this on build.

**Comment by kevcunnane** [comment]
Fixed by https://github.com/Microsoft/angular2-slickgrid/pull/1
