### ISSUE TITLE
Results grid doesn't refresh cells sometimes

### ISSUE THREAD

**Issue by kburtram** [microsoft/vscode-mssql#331]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7+ 
- OS Version: All
 
![capture](https://cloud.githubusercontent.com/assets/599935/20206175/81aade5e-a793-11e6-8a7a-cb5e135f901d.png)

Steps to Reproduce:

1. Run a query with a lot of rows and columns

2. Scroll up and down/left and right in the result grid

Expected: Results always render correctly

Actual: Sometime results don't render.  Often scrolling down then back up will cause the results to reappear.

**Comment by anthonydresser** [comment]
I can't seem to repro on latest dev.

**Comment by kburtram** [comment]
I've still seen this periodically, even with 0.2.0 release.  We should keep trying to locate the repro.

**Comment by ransagy** [comment]
Happened to me once with a single digit number of rows when playing around with the 0.2.0 release on vscode 1.8.2, Windows 10 x64 (Insider builds though).

Didn't seem to be anything specific and couldn't repro it more than once.
