### ISSUE TITLE
Password is not saved when connection created from user settings file with savePasswortrue 

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#353]
- MSSQL Extension Version: 1.5
- VSCode Version: 1.7.1
- OS Version: macOS

Steps to Reproduce:

1. Hit F1 -> Manage Connection Profiles -> Edit to open the connection list
2. Copy & Paste and existing connection with password, or add one (see below)
3. Set password as blank but have `"savePassword": true`
4. Save, open a .sql file and connect to the database. Enter your password when prompted
5. Disconnect, then reconnect to that DB

Expected:
- Password is saved and you are not prompted to re-enter every time

Actual:
- Password is not saved. Every time you reconnect you must enter it

```
"mssql.connections": [
        {
            "authenticationType": "SqlLogin",
            "server": "myserver",
            "database": "",
            "user": "test",
            "password": "",
            "savePassword": true
        }
    ]
```

**Comment by Raymondd** [comment]
Just to clarify, the password should not be saved in plain text in the connection profile. This seems like an issue with the Credential Store not saving the password for the next time you connect?

**Comment by kevcunnane** [comment]
Correct. If you leave the password field blank but have savePassword=true, this should mean:

- If password is already saved in the credential store, use it to connect
- If password is not saved (or password is incorrect and connection fails), prompt user for password when connecting and if successful, save the password

This makes creating a connection via the settings file much easier/safer - you can define a new profile using copy&paste while having it managed securely and not risking it being checked into Git.
