### ISSUE TITLE
Executing Begin Transaction on its own returns "A transaction that was started in a MARS batch is still active at the end of the batch"

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#354]
- MSSQL Extension Version: 1.5
- VSCode Version: 1.7.1
- OS Version: macOS

Steps to Reproduce:

1. Create a table T1 and write a script with `BEGIN TRANSACTION` and `END TRANSACTION` statements
```sql
-- Create a new table called 'T1' in schema 'dbo'
-- Drop the table if it already exists
IF OBJECT_ID('dbo.T1', 'U') IS NOT NULL
DROP TABLE dbo.T1
GO
-- Create the table in the specified schema
CREATE TABLE dbo.T1
(
    T1Id INT NOT NULL PRIMARY KEY, -- primary key column
    Column1 [NVARCHAR](50) NOT NULL,
    Column2 [NVARCHAR](50) NOT NULL
   -- specify more columns here
);
GO

BEGIN TRANSACTION
INSERT INTO T1 VALUES (1, '1', '2')
ROLLBACK TRANSACTION
```

2. Select the `BEGIN TRANSACTION` command and execute just this

Expected:
- Get result `Command(s) completed successfully` as you would in SSMS/SSDT

Actual:
- Get result `A transaction that was started in a MARS batch is still active at the end of the batch. The transaction is rolled back.`. 
- This indicates that we are using Multiple Active Result Sets for query execution which is incorrect. 
- We also need to keep connection open during a query execution session, so that when you execute the `BEGIN`, `INSERT INTO`, and `ROLLBACK` commands in sequence (not all at once), we handle this the same way SSMS/SSDT does.

**Comment by kburtram** [comment]
This is fixed with https://github.com/Microsoft/sqltoolsservice/commit/84eb164d8733521f688a6f1b7a613bd0a32beb21.  It looks like the change to disable MARS didn't make it to master for CTP1 release.
