### ISSUE TITLE
Azure SQL connection - invalid cert error

### ISSUE THREAD

**Issue by justinschuldt** [Microsoft/vscode-mssql#358]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. Use the configuration wizard to set up a connection to an Azure sql server
2. Connect

I'm not sure if this is a problem with my machine or a legitimate bug. I am able to connect to my Azure sql server with other software. Here is the error:

`mssql: Failed to connect: System.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught) ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`

Here is my `mssql.connections` array:
``` 
       {
            "authenticationType": "SqlLogin",
            "server": "myserver.database.windows.net",
            "database": "",
            "user": "someusername",
            "password": "",
            "savePassword": true,
            "profileName": "azureconnection"
        }
```

Do I need an `encrypt: true` or something?

Thank you! Cant wait to start using your plugin!

**Comment by kburtram** [comment]
@justinschuldt I haven't seen this specific error before when connecting to Azure DB.  Could you try verifying OpenSSL is installed with symlinks as mentioned in https://github.com/Microsoft/vscode-mssql/wiki/OpenSSL-Configuration?

**encrypt: true** should get auto-set when connecting to Azure DB instance.  We'll try to get a repro and let you know.

**Comment by justinschuldt** [comment]
Thanks for the quick reply @kburtram !

The brew method did not work for me, so I installed the latest openssl with a different method ([http://bytefish.de/blog/net_core_mac_os/](http://bytefish.de/blog/net_core_mac_os/)).

Openssl seems to be working, when I run `openssl version -a` the result is:
```
OpenSSL 1.0.2j  26 Sep 2016
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: cc -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/ssl/macos-x86_64"
```

Hope that helps, Thanks!
Justin

**Comment by kburtram** [comment]
@justinschuldt thanks for checking!  @llali mentioned this could be related to this .Net Core issue https://github.com/dotnet/corefx/issues/5173.  

That thread mentions that adding TrustServerCertificate=True, which would be **"trustServerCertificate": true**, should avoid this issue.  

Obviously that has some security concerns when connecting to a Azure DB instance.  We'll try to get a repro and a better recommended fix for this.

**Comment by erickangMSFT** [comment]
@kburtram @justinschuldt typically connection string for Azure SQL DB defines two properties with following values

 "trustServerCertificate": false,
 "encrypt": true

**Comment by kburtram** [comment]
@erickangMSFT thanks Eric.  Yes, those are the default values, which apparently aren't working correctly in this case.  "trustServerCertificate": true should avoid this issue, but makes connection vulnerable to man-in-middle attacks.

**Comment by kevcunnane** [comment]
@justinschuldt - have you been able to try the workaround for this issue? Does this solve the problem? It would help us diagnose whether this is an issue in the SqlClient implementation in .Net Core or our extension. Thanks.

**Comment by justinschuldt** [comment]
@kevcunnane Yes, the work around was successful. Thanks!

**Comment by kevcunnane** [comment]
@justinschuldt thanks for confirming and glad you're now able to test things out. I'm going to close this issue out for now - if there is a problem it's likely in SqlClient's implementation on macOS, so the right place to create an issue would be https://github.com/dotnet/corefx. That'll ensure the right people look at it.
