### ISSUE TITLE
Wiki - Minor Improvements to getting started example

### ISSUE THREAD

**Issue by carlsonad** [Microsoft/vscode-mssql#359]
- MSSQL Extension Version: none
- VSCode Version: none
- OS Version: none

Steps to Reproduce:

1. Walk through the Getting started example on the wiki
2. The sql in the [Create a table](https://github.com/Microsoft/vscode-mssql/wiki/getting-started#create-a-table) section is inconsistent with the [Insert and query](https://github.com/Microsoft/vscode-mssql/wiki/getting-started#insert-and-query) section and will result in an exception.

I created a [PR](https://github.com/carlsonad/vscode-mssql_wiki/pull/1) in my own account with some suggested improvements.

**Comment by kburtram** [comment]
@erickangMSFT Could you please merge these corrections into the wiki and to the replica on MSDN docs?

**Comment by erickangMSFT** [comment]
the fix is merged to master. Thanks.
