### ISSUE TITLE
Error mssql: Failed to load Sql Tools Service

### ISSUE THREAD

**Issue by grairdon88** [Microsoft/vscode-mssql#360]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Windows 8.1 Enterprise

Steps to Reproduce:

1. Install the extension
2. Reload VS Code
3. Message dialog is displayed saying "Failed to load Sql Tools Service".

**Comment by kburtram** [comment]
@grairdon88 Could you please verify the latest C runtime is installed following instructions at https://github.com/Microsoft/vscode-mssql/wiki/windows10-universal-c-runtime-requirement.

**Comment by grairdon88** [comment]
Sorry, didn't see that part of the instructions. My work pc must have a policy that doesn't let me install that anyway. Thanks for looking into this though!

**Comment by erickangMSFT** [comment]
Can you install .Net core for your Windows itself? or is it not allowed by the policy? if you can install .net core itself the same issue will be resolved since it is a part of .net core setup chain.  It is a one time reqirement for any .net core app on a pre-windows 10 machine.
