### ISSUE TITLE
Does not work on recent insider build

### ISSUE THREAD

**Issue by akharsh-tr** [Microsoft/vscode-mssql#361]
- MSSQL Extension Version: 0.1.5
- VSCode Version: pic
- OS Version: Windows 7 

Steps to Reproduce:
![image](https://cloud.githubusercontent.com/assets/22811492/20377538/3a175fbe-ac88-11e6-95e8-f37640879c18.png)

1.Select SQL to execute
2.Execute.

No result shown on results windows (tab)

**Comment by kburtram** [comment]
@akharsh-tr I think this may be an issue with today's Insiders build.  I'm hitting the same issue using the Markdown Preview feature (create .md file and click Preview button), so I think the html pane may be broken on Windows.  I'll follow-up to get an issue created for VS Code.

**Comment by peterblazejewicz** [comment]
The same on Windows 10 Enterprise, so @kburtram can be correct:

Version 1.8.0-insider
Commit 1b95a2f7a7e8858c5612807522a6f8cd8e03c1dc
Date 2016-11-17T00:36:45.332Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by kburtram** [comment]
Upstream issue was closed with https://github.com/Microsoft/vscode/commit/07e605ea7f24f66ac2ffb6a9ffa7d54c2eed21aa so I'll close this issue.
