### ISSUE TITLE
[FR] Empty password (SQL Login) 

### ISSUE THREAD

**Issue by buzzzzer** [microsoft/vscode-mssql#363]
I would like the option to not require a password please

**Comment by kevcunnane** [comment]
Thanks for this feedback. For clarification: are you asking for support for Windows Authentication, or do you have a SQL Login which does not require a password configured on your SQL Server?

- Windows Authentication is supported on Windows. Support on Mac/Linux is tracked by https://github.com/Microsoft/vscode-mssql/issues/356.

**Comment by buzzzzer** [comment]
Yes. sql login like "sa" with no password.

**Comment by erickangMSFT** [comment]
This would require a bit more of consideration since it is also linked with the sql security best practice. One thing that we want to avoid is to unintentionally promote a habbit against the security best practice. Let me dig in a bit more about that aspect to be on the safe side. :)

**Comment by buzzzzer** [comment]
@erickangMSFT 
We use "login with no password" config only on develop test servers in an isolated network.
Keep passwords in workspace settings also not safe.

**Comment by kburtram** [comment]
We'll take this in the first post-GA release since it's not currently signed-off, tested and merged into dev.
