### ISSUE TITLE
Unable to execute the command while the extension is initializing

### ISSUE THREAD

**Issue by Verrickt** [Microsoft/vscode-mssql#365]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04.1 LTS

Steps to Reproduce:

1.Install MSSQL extension
2.Restart VSCode
3.Open a .sql file
4.Run MSSQL:Conenct

Three pop ups show:

<del>mssql: Failed to load Sql Tools Service</del>

<del>Errormssql: Unable to execute the command while the extension is initializing. Please try again later.</del>

<del>ErrorRunning the contributed command:'extension.connect' failed</del>

After waiting for about 1 hour , running MSSQL:Connect works

**Comment by RickyLin** [comment]
I have the same issue, will have a look 1 hour later.

**Comment by spsanderson** [comment]
I am having this issue and it has been over an hour
