### ISSUE TITLE
Intellisense on MSSQL extension for vscode should support [bracket].[syntax] 

### ISSUE THREAD

**Issue by wpostma** [Microsoft/vscode-mssql#366]
- MSSQL Extension Version: 0.0.5
- VSCode Version: 1.7.1
- OS Version: windows 10

Steps to Reproduce:

1.  Open a query with .sql file extension.
2.  Type a value like `select * from [dbo].[C`

Expected:
  Expect code completion, finding symbols that begin with C, 
Actual:
 No code completion/language-service integration in a query that uses square brackets to escape things.  

While many people consider creating symbols that require this syntax is invalid, many DBAs/devs are used to doing this, and it's valid. This works in SSMS.  Screenshot from SSMS included

![ssms-intellisense](https://cloud.githubusercontent.com/assets/1833470/20398648/3677b0f0-acbc-11e6-9a46-f65aa90bdb5e.png)

**Comment by kevcunnane** [comment]
Eric - this is a valid request. There is additional bracket support that we should look at so please help scope how support should work and we'll assign to an engineer

**Comment by wpostma** [comment]
Fixed title to remove the old name of the deprecated extension.

**Comment by erickangMSFT** [comment]
I consider two aspects in this case. 

1. auto-complete or suggestion fails when user type [. - I consider this behavior as a bug. 

2. auto-complete always escape a schema object name with []. - Currently when a schema object name contains a special characters, the extension automatically detects it and escape it with []. This can be enabled and we can add an option to set user preference. 

If we enable #2 then it can effectively cover #1 case but it will require change of user's habbit of not typing [ and always use suggestion and auto-complete to escape with []. this can be a UX friction. any thought?

**Comment by erickangMSFT** [comment]
@wpostma This feature is being implemented by @llali I will unassign myself.

**Comment by wpostma** [comment]
Hooray! 👍

**Comment by kevcunnane** [comment]
This is fixed by https://github.com/Microsoft/sqltoolsservice/pull/164, closing this as it'll be in the next release.
