### ISSUE TITLE
Add support to copy with Headers in the result grid.

### ISSUE THREAD

**Issue by PavelPawlowski** [Microsoft/vscode-mssql#368]
- MSSQL Extension Version: 1.7.1
- VSCode Version: 0.1.5
- OS Version: Win 10

Currently when copying resuts from result grid with Ctrl+C, only the data area copied.
It would be good to have the possibility to copy the results with column haders for exampe throuhg context menu. This is possible in SSMS but not possible in the vscode-mssql.

**Comment by anthonydresser** [comment]
@PavelPawlowski Thanks for the feature suggestion. We'll definitely be looking to implementing this in a future extension update.

**Comment by erickangMSFT** [comment]
Design note:

1. Addition of Copy with Header context menu on result grid. 
2. Optionally, addition of an option to switch the default behavior of CTRL+C between copy w/ header and copy with header.

**Comment by kevcunnane** [comment]
@erickangMSFT - Beta implementation is in branch https://github.com/Microsoft/vscode-mssql/tree/feature/copyShouldIncludeHeaders. Questions:

- Do we need the context menu options? Current implementation just reads from a config value.

- I've defaulted the option to false to match SSMS behavior. Can you confirm this is what we should match?

**Comment by erickangMSFT** [comment]
@kevcunnane 

RE:#1 - We can add another issue item 'Add Copy and Copy with Header context menus'. When the extension starts supporting Copy with Header functionality, it should consider user groups with different preferences. For example: 
- User group 1 - frequent need to copy w/o header but also need infrequent copy w/ header
- User group 2 - frequent need to copy w/ header but also need infrequent copy w/o header
Context menu is more intuitive, discoverable and efficient to support above scenarios while user can set the default behavior of CTRL+C using the extension option.

RE:#2 - Agreed and confirmed.

**Comment by kevcunnane** [comment]
@erickangMSFT - turns out it was trivial to add the context menu items. I updated the branch with context menu support. Will need to add tests for this case, but can address separately.

The end result matches SSMS behavior - copy always respects the user setting (defaulting to not include headers). Copy with Headers always includes headers.

![image](https://cloud.githubusercontent.com/assets/10819925/20469879/39751308-af58-11e6-82e2-58f31920c504.png)

**Comment by erickangMSFT** [comment]
Awesome. Thanks Kevin
