### ISSUE TITLE
mssql: SQL Tools Service component could not start

### ISSUE THREAD

**Issue by mirao** [Microsoft/vscode-mssql#370]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.10

Steps to Reproduce:

1. Run the preview version of mssql from docker image - the service is running and I'm able to connect using _sqlcmd_
2. Install the mssql extension and reload vscode

Expected result:

- no issue

Actual result:
The extension fails to start, output shows this:

[Error - 8:41:44 PM] Connection to server is erroring. Shutting down server.
[Error - 8:41:44 PM] Connection to server is erroring. Shutting down server.
[Error - 8:41:44 PM] Connection to server is erroring. Shutting down server.
Failed to initialize CoreCLR, HRESULT: 0x80131500

Reload of vscode doesn't help

**Comment by kevcunnane** [comment]
Hi Mirao, this looks to be an issue loading the .Net Core-based service process we use in our application. There is a similar issue discussed at https://github.com/dotnet/cli/issues/2018. Could you try calling the following to install some required dependencies for Ubuntu? There are a number of options mentioned on that thread, but this seems like an up to date one:

```
wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-8ubuntu0.2_amd64.deb
sudo dpkg -i libicu52_52.1-8ubuntu0.2_amd64.deb
```

**Comment by eugeneduvenage** [comment]
I have a similar issue,

OS: Ubuntu 16.04
VSCode: 1.7.1
mssql extension: 0.1.5
dotnet: 1.0.0-preview2-1-003177

I am able to create a connection to a remote sql server (2012) running on windows, however as soon as the intellisense starts to bring back results (it does work for one level deep on occasion) or I execute a very simple select query (without using any intellisense) the extension crashes with the **mssql: SQL Tools Service component could not start error**. In the sqlserviceclient output I get "**[Error - 8:31:35 AM] Connection to server got closed. Server will not be restarted.**"

**Comment by kburtram** [comment]
@eugeneduvenage this message is the generic "out-of-process component" crashed error.

Could you please configure the user setting **"mssql.logDebugInfo": true**?  This will cause the out-of-proc service to create a debug log which will hopefully contain the crashing exeception.  The log should be in the ~/.vscode/extensions/ms-mssql.mssql/sqltoolsservice/0.1.2/Ubuntu16/ directory.  If there is an error or exception messages in the log could you please provide it?

**Comment by mirao** [comment]
@kevcunnane : Installation of the packages didn't solve the error. dotnet works for me (version 1.0.0-preview2-1-003177)
@eugeneduvenage: I enabled the mssql logging. I cannot see the log in the folder you mentioned, but developer console shows this:

[Extension Host] LocalWebService: added static html content path: /home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/out/src/views/htmlcontent
[Extension Host] LocalWebService listening on port 42679
[Extension Host] activated.
mssql: SQL Tools Service component could not start.
[Extension Host] TypeError: Cannot read property 'dispose' of null
    at LanguageClient.cleanUp (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/lib/main.js:631:30)
    at LanguageClient.stop (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/lib/main.js:605:14)
    at LanguageClient.handleConnectionError (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/lib/main.js:858:18)
    at errorHandler (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/lib/main.js:720:19)
    at /home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/lib/main.js:47:42
    at CallbackList.invoke (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at writeErrorHandler (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/main.js:113:22)
    at CallbackList.invoke (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:103:39)
    at Emitter.fire (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/events.js:167:36)
    at StreamMessageWriter.AbstractMessageWriter.fireError (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:28:27)
    at Socket.<anonymous> (/home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/node_modules/vscode-languageclient/node_modules/vscode-jsonrpc/lib/messageWriter.js:60:67)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:319:10)
    at onwrite (_stream_writable.js:337:5)
mssql: SQL Tools Service component could not start.

**Comment by eugeneduvenage** [comment]
Hi,
I enabled error logging. 
I get a consistent failure doing the following:
Test1:
Open VSCode, set the unsaved file to type sql file
Bring up the msql connection picker and choose a connection.
Wait for connection to succeed.
Start typing SELECT, before the word is finished I get a crash.

[ErrorLog1.txt](https://github.com/Microsoft/vscode-mssql/files/602799/ErrorLog1.txt)

Test2:
Open VSCode, save a file with the SQL extension
Bring up the msql connection picker and choose a connection.
Wait for connection to succeed.
Start typing SELECT, before the word is finished I get a crash.

[ErrorLog2.txt](https://github.com/Microsoft/vscode-mssql/files/602800/ErrorLog2.txt)

In the first instance the log only reveals the crash happens in ResolveFilePath, but in the second instance it may indicate why. The resolved path is /home/eugened/home\eugened\Documents\MSSQLVSCODE\test.sql which is clearly not correct and the use of backslashes instead of forward slashes on Linux may further exacerbate the problem.

Hope that helps, let me know if you need anything further.

**Comment by kburtram** [comment]
@eugeneduvenage Thanks for the details, that helps a lot!

I've created a new issue at https://github.com/Microsoft/vscode-mssql/issues/406 to track that specific crash.  The title of this issue is our generic "SQL Tools Service" crashed text, so it's better to pull specific crashes into their own issue.

A lot of the team is on vacation this week, but I'll look into this week of 11/28th.

**Comment by kburtram** [comment]
@mirao Could you please try to run  /home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/sqltoolsservice/0.1.2/Ubuntu16/Microsoft.SqlTools.ServiceLayer executable directly from a command terminal?  This should launch a process that reads input from stdin.  If there are .Net Core loading issues perhaps an error will display on launch.

**Comment by mirao** [comment]
@kburtram:
I get the same error as in VScode
```
$ /home/mira/.vscode/extensions/ms-mssql.mssql-0.1.5/sqltoolsservice/0.1.2/Ubuntu16/Microsoft.SqlTools.ServiceLayer
Failed to initialize CoreCLR, HRESULT: 0x80131500
```

**Comment by kburtram** [comment]
Do you happen to have .Net Core SDK or runtime installed separately on this machine?  If so, is the DOTNET_HOME environment variable set?  I wonder if perhaps there's some interference going on there?

**Comment by kburtram** [comment]
@mirao could you please try to run "export COREHOST_TRACE=1" prior to running Microsoft.SqlTools.ServiceLayer?  This should output more diagnostic info which may help track down what's happening.

Error 0x80131500 is defined as COR_E_EXCEPTION which is the HRESULT that means a generic Exception object was thrown and unhandled.

**Comment by mirao** [comment]
> Do you happen to have .Net Core SDK or runtime installed separately on this machine?

I tried to install .Net when the issue occurred, but it didn't help me so currently it's uninstalled. DOTNET_HOME is not set

> @mirao could you please try to run "export COREHOST_TRACE=1" ...

Here it is: [sqltools.txt](https://github.com/Microsoft/vscode-mssql/files/628036/sqltools.txt)

**Comment by notalklu** [comment]
-  MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 8.1

I have the same problem.And I have tried to install the pre-req follow the instruction [https://github.com/Microsoft/vscode-mssql/wiki/windows10-universal-c-runtime-requirement](url).
But I can't install the tools successfully.
And i have set **"mssql.logDebugInfo": true**. Where  can i get the debug log in windows 8.1?

**Comment by cicorias** [comment]
I'm getting the same issue on Ubuntu fresh install of Ubuntu:
Ubuntu 16.10
VSCode: 1.8.1
[err2.txt](https://github.com/Microsoft/vscode-mssql/files/690622/err2.txt)

MSSQL 0.2.0

With `export COREHOST_TRACE=1` on the attached is the log.

.NET Core was already installed: 1.0.0-preview2-1-003177

Here is the output of `dotnet --version` with trace on.

[dotnetversion.txt](https://github.com/Microsoft/vscode-mssql/files/690629/dotnetversion.txt)

**Comment by mkurz** [comment]
Same error here using Ubuntu 16.10.

**Comment by mkurz** [comment]
```
Version 1.8.1
Commit ee428b0eead68bf0fb99ab5fdc4439be227b6281
Date 2016-12-19T14:41:20.664Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```
The log with `export COREHOST_TRACE=1`:
[error.txt](https://github.com/Microsoft/vscode-mssql/files/726398/error.txt)

**Comment by kburtram** [comment]
I'm going to close this issue since there hasn't been any recent activity, and we've had a couple public releases since the previous comment.  If this is still an issue please reactive so we can investigate.

**Comment by mkurz** [comment]
Guys, you may want to try the latest alpha which includes .Net Core 2, it may fixes your issues:
https://github.com/Microsoft/vscode-mssql/issues/718#issuecomment-307018770: 
(Works for me)
