### ISSUE TITLE
Queryplan

### ISSUE THREAD

**Issue by fhelje** [microsoft/vscode-mssql#375]
Any plans to add queryplan to the result?

**Comment by erickangMSFT** [comment]
This is a backlog item and we need to design new or find a way to leverage a showplan implementation in SSMS or one existed for Azure SQLDB in the previous portal (SAMP). No clear direction is set yet. This is also a good candidate for an extension. With SET SHOWPLAN_XML ON, the XML result is returned in the result view and the mssql extension opens the xml in the editor by clicking it. An extension may be possible to open it and render a graphical representation similar to markdown preview. -thinking loud-

**Comment by fcatae** [comment]
Can we add a basic support for query plan using SET SHOWPLAN_TEXT and SHOWPLAN_ALL? This returns a formatted plain text.

**Comment by erickangMSFT** [comment]
View as Text is a backlog item that will help user to see the text content more efficiently. The same scenario applies to sp_helptext as well. A simple UI that can toggle result in grid and result in text without re-executing the query would be ideal in this case.

**Comment by Mnior** [comment]
I see the duplicate task #17850 as **resolved** in the [October backlog](https://github.com/microsoft/vscode-mssql/milestone/40?closed=1).

**Comment by cssuh** [comment]
Added in https://github.com/microsoft/vscode-mssql/pull/17983
