### ISSUE TITLE
[FR] Add to sort columns in the result table

### ISSUE THREAD

**Issue by buzzzzer** [microsoft/vscode-mssql#376]
Any plans to add sorting columns in the result table, like sanagama.vscode-mssql extentions from market ?

**Comment by erickangMSFT** [comment]
A concern is about the sorting and rendering performance. does anyone have a suggestion from the user perspctive? would it be okay to allow sorting when the result is small enough? any suggestion on this perspective will be appreciated.

**Comment by buzzzzer** [comment]
Maybe leave it to the developer's conscience? because the performance depends on the hardware and a lot more then... 
Well request without sorting  over 100 billion records will also be not very good.

**Comment by cssuh** [comment]
Added in https://github.com/microsoft/vscode-mssql/pull/18071
