### ISSUE TITLE
Add slickgrid repository to OSS approvals list

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#381]

**Comment by erickangMSFT** [comment]
Added the following note the OSS approval records additional information page. (Internal to MS process)

Slickgrid codes are forked into a new repository for easier maintenance.
https://github.com/microsoft/angular2-slickgrid

The same code was in the extension repository https://github.com/Microsoft/vscode-mssql when the project is approved for OSS.
