### ISSUE TITLE
Troubleshooting guide for command 'extension.connect' not found issue

### ISSUE THREAD

**Issue by erickangMSFT** [microsoft/vscode-mssql#383]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Windows and Linux

Users have reported "command 'extension.connect' not found" error on Windows and Linux Ubuntu 16.4 through the gitter chat room and docs.microsoft.com channels. To better understand this issue we need a troubleshooting guide for either self-service or for the data collection so that users can provide more detail troubleshooting information to nail down this issue.

Ask / suggestion: Technical wiki about how to troubleshoot and how to collect troubleshooting data / log to report the issue with more detail.

**Comment by Kilsgaard** [comment]
Hi
I have the described problem, @erickangMSFT could you please guide me to the page on how to collect troubleshooting data, when i go to the wiki under troubleshooting, the only page i get is the known issues.
/Graves

**Comment by johnfredrik** [comment]
I had the same problem. To slove the problem for I had to uninstall an extentiong called HTML CSS Class Completion. After doing that it worked. Hope that helps.
