### ISSUE TITLE
Change shortcut for executing queries

### ISSUE THREAD

**Issue by fcatae** [Microsoft/vscode-mssql#384]
In SSMS, it is common to use either Ctrl-E or F5 to run queries. 
It would be nice to have a similar behavior to SSMS instead of using Ctrl-Shift-E. An easy way to configure is to customize the configurations in keybindings.json.

```
// keybindings.json
[
    { "key": "ctrl+e",          "command": "extension.runQuery",
                                     "when": "editorTextFocus && editorLangId == 'sql'" },
    { "key": "F5",          "command": "extension.runQuery",
                                     "when": "editorTextFocus && editorLangId == 'sql'" }                                     
]
```

**Comment by erickangMSFT** [comment]
This is fully understood case. In VS Code, many keys are already bound for VS Code actions itself and not many available keys are left for extensions. That includes CTRL+E and F5. However, shortcut keybindings are fully customizable as described in the 'customize shortcuts' wiki page. https://github.com/Microsoft/vscode-mssql/wiki/customize-shortcuts

Overriding CTRL+E or F5 for the query execution will impact existing VS Code user's established behavior. 

An approach we are taking is to collect user's feedback like this and select the shortcut key with minimum overriding impact for SQL developers. Let's collect more feedback and suggestions.

**Comment by fcatae** [comment]
Thanks for the explanation Eric.
I understand that it will affect VSCode user base. On the other hand, the current behavior blocks DBA coming from SSMS.

**Comment by thorn0** [comment]
> Overriding CTRL+E or F5 for the query execution will impact existing VS Code user's established behavior

That's exactly what happened with overriding CTRL+SHIFT+E. See #1088.

**Comment by fcatae** [comment]
@thorn0 - This suggestion is just for CTRL+E (not CTRL-SHIFT-E). But I got the idea.
