### ISSUE TITLE
Stop parsing on switching language mode from sql to any other

### ISSUE THREAD

**Issue by buzzzzer** [microsoft/vscode-mssql#390]
- MSSQL Extension Version: 0.1.5
- VSCode Version: Master
- OS Version: Windows 10

Steps to Reproduce:
1. Open any js file
2. switch to sql language mode
3. return to javascript language mode

vsсode still trying to parse sql syntax

![er](https://cloud.githubusercontent.com/assets/1981785/20473228/48533486-afd0-11e6-90d0-eb2787039e57.gif)

**Comment by MitchellSternke** [comment]
Hi @buzzzzer! Thanks for reporting this issue! After investigating end-to-end it appears that this is a bug in Visual Studio Code behavior. I've logged information in their issues page here: https://github.com/Microsoft/vscode/issues/4907. Hopefully their team will provide a fix!
