### ISSUE TITLE
Preview 2 Release Plan

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#402]
## Endgame Schedule
- _December 5th_ Create release branch, start of Ask-Mode
- _December 9th_ Merge to master, start of Escrow
- _December 12th_ Release candidate build available
- _December 15th_ Public release date

![image](https://cloud.githubusercontent.com/assets/10819925/20506985/c960db5a-b00c-11e6-938c-d4e7d15d4885.png)

| Mark | Description |
| :-: | :-- |
| :running_man: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

## Release Management
For most work items please use the Preview 2 mileston https://github.com/Microsoft/vscode-mssql/milestone/2. Specific work related to this release is listed below.

### Major Work Items
- \- [ ] Acquisition
  - \- [ ] #393 
  - \- [ ] :running_man: #364 

### Quality Exit Criteria
- \- [ ] Functional Testing
  - \- [ ] Manual testing completed on all supported platforms (Team)
  - \- [ ] All automation passing 100% (Kevin)
  - \- [ ] Code coverage remains above 70% (TBD)
  - \- [ ] ~~Customer experience validations complete~~ (Eric, Preview 3)
- \- [ ] ~~Accessibility~~ (post-CTP)
  - \- [ ] ~~Screen-reader testing~~ (post-CTP)
  - \- [ ] ~~OS High-contrast and large fonts testing~~ (post-CTP)
- \-  [ ] Defects (Karl)
  - \- [ ] 0 remaining Preview 2 defects
  - \- [ ] 24-hour ZBB
- \- [ ] Performance and stress
  - \- [ ]  :large_blue_circle: All benchmarks meeting goals for UI and service (TBD)
- \- [ ] ~~Localization and world ready~~ (post-Preview 2, double-check for GeoPol)
- \- [ ] Telemetry (TBD)
  - \- [ ] User adoption reports are validated
  - \- [ ] All new command palette entries are instrumented 
- \- [ ] Fix Feedback from customers and dogfooders (Karl)
- \- [ ] ~~Meet Quality Essentials requirements~~ (post-Preview 2)
### Additional Collateral
- \- [ ] Documentation (Eric)
  - \- [ ] Update changelog.md 
  - \- [ ] Generate and publish sqltoolsservice API documentation
- \- [ ] SMO SDK vNext Nuget release 
  - \- [ ] Create SDK Nuget package
  - \- [ ] Publish SDK Nuget package to Nuget.org (Leila)
  - \- [ ] Create release notes with known issues (Andy)
  - \- [ ] Publish examples and documentation to GitHub wiki (Andy)

**Comment by kburtram** [comment]
Missed by a few days, but this is done :)
