### ISSUE TITLE
Merge Master back into Dev

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#403]
Cherry-picking seems to have messed up Dev<->Master comparisons. We need to pull back into Dev and deal with the conflicts.

**Comment by kburtram** [comment]
I'm planning to do this next week.  There were some hotfixes directly in master for the Preview 1 release that need to be merged back to dev.

**Comment by kburtram** [comment]
Master is merged back to dev in both repos with https://github.com/Microsoft/vscode-mssql/commit/610c7f88b384481b372e90fcfb731bbe7c78aca1 and https://github.com/Microsoft/sqltoolsservice/commit/e5d577dc813ff3c527571abc6ebd580372573dd6.
