### ISSUE TITLE
Could the data grid be made easily usable from other extensions?

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode-mssql#405]
I just found this extension and saw the data grid feature. That would be super useful for the julia language extension as well, i.e. to show for example ``DataFrame`` results.

I haven't looked at the technical details, but might it make sense to somehow make the functionality of this data grid available for other extensions as well?

**Comment by kburtram** [comment]
@davidanthoff the data grid component has been factored out into its own repo at https://github.com/Microsoft/angular2-slickgrid specifically to allow it to be easily consumed outside this vscode extension.  Please let us know if you have suggestions on how to better package up that functionality for easier reuse.

**Comment by davidanthoff** [comment]
Ah, excellent! This is far down on our priority list, so it will take a while until we look at this, but once we get to it this should be really helpful.
