### ISSUE TITLE
SQL Tools Service crashes with invalid file path

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#406]
Bug report quoted from @eugeneduvenage

Hi,
I enabled error logging.
I get a consistent failure doing the following:
Test1:
Open VSCode, set the unsaved file to type sql file
Bring up the msql connection picker and choose a connection.
Wait for connection to succeed.
Start typing SELECT, before the word is finished I get a crash.

ErrorLog1.txt

Test2:
Open VSCode, save a file with the SQL extension
Bring up the msql connection picker and choose a connection.
Wait for connection to succeed.
Start typing SELECT, before the word is finished I get a crash.

ErrorLog2.txt

In the first instance the log only reveals the crash happens in ResolveFilePath, but in the second instance it may indicate why. The resolved path is /home/eugened/home\eugened\Documents\MSSQLVSCODE\test.sql which is clearly not correct and the use of backslashes instead of forward slashes on Linux may further exacerbate the problem.

Hope that helps, let me know if you need anything further.

**Comment by kburtram** [comment]
I see the messed up paths on Linux per the attached logs, but we don't actually use that path to read the file, so that doesn't appear to be causing the crash.  That's a separate bug that we need to fix :).

I'm still trying to get a repro to diagnosis the issue.

**Comment by eugeneduvenage** [comment]
If there is anyway I can help with that just let me know. I get it the error 100% of the time.

**Comment by kburtram** [comment]
@eugeneduvenage thanks for the offer.  We're looking into how to improve our diagnostics to help root cause these types of issues more easily.

I'm not sure how much time you have to help with this issue, but what would be most useful is to know what unhandled exception is being thrown to crash the out-of-proc service component.  If you have time I've outlined steps below to try to capture this exception details.

#### How to Capture SQL Tools Service Unhandled Exceptions
1.	Launch VS Code with mssql extension installed 
2.	Determine the process ID for the Microsoft.SqlTools.ServiceLayer process.  For example, this can be done with Task Manger on Windows or “ps –ef | egrep SqlTools” on Linux\Mac.  This needs to happen before step 3 since each VS Code window has its own child Microsoft.SqlTools.ServiceLayer process.
3.	Launch a second VS Code window with the New Window command.
4.	Install C# VS Code extension https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp.
5.	Create a new folder and open it in VS Code.
6.	Add new file in folder with .cs extension and open the file.  This will activate the C# extension and install the debugger binaries.
7.	Create a subdirectory **.vscode** and add a file **launch.json** with the below contents

```{
    "version": "0.2.0",
    "configurations": [        
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}",
            "justMyCode": false
        }
    ]
}
```
8.	Switch to debugger viewlet and click Start Debugging button
9.	Select the Microsoft.SqlTools.ServiceLayer process located in step 2
10.	**In the first VS Code instance execute the crash repro scenario**
11.	When the service instance crashes the unhandled exception should break in the second VS Code instance.
12.	 Copy the $exception details and stack trace (from StackTrace propery) and provide it in the GitHub issue.  Copying from the Debug Console usually works better than from Locals pane due to text truncation during copy.

**Comment by kburtram** [comment]
...switching from "important" to "freeze-slow-crash" label for crashing issues.

**Comment by eugeneduvenage** [comment]
Hi, I attempted what you described above, but each time the sql extension crashes the c# debug exits with an error "Debug adapter process has terminated unexpectedly". I noticed in the debug console that the PDBs are missing e.g. .vscode/extensions/ms-mssql.mssql-0.1.5/sqltoolsservice/0.1.2/Ubuntu16/System.Diagnostics.Debug.dll'. Cannot find or open the symbol file, not sure if I can get these from somewhere or build the extension from source, or if this can cause the debugger to fail. I am running a very fresh install of Ubuntu 16.04.1 and vscode so I don't feel some weird personal configuration to be at fault for all this.

If you have any further suggestions I'll be happy to dig deeper.

**Comment by kburtram** [comment]
@eugeneduvenage thanks for trying those steps.  I'll write up steps for how to build and patch https://github.com/Microsoft/sqltoolsservice from source to see if that helps debugging.  I'll also install a clean 16.4.1 machine and try to repro on that.  Unfortunately I can't repro on my 16.4 dev box.

**Comment by kburtram** [comment]
I'm closing this now since there hasn't been recent activity with this issue and there's been a couple public releases since the last comment.  If this is still an issue please reactive so we can investigate.
