### ISSUE TITLE
Add support for Script As operations, for example View Stored procedure

### ISSUE THREAD

**Issue by agamjot-singh** [microsoft/vscode-mssql#414]
- MSSQL Extension Version:  0.1.5
- VSCode Version:  1.7.1
- OS Version: macOSSierra 

Steps to Reproduce:

1) I can't find a way/ command to view an existing SP in VSCode. 
2) Is there any way to see all Stored Procedures for a DB in VSCode?

**Comment by kevcunnane** [comment]
We don't have support yet for script-as operations (e.g. script as create, alter, drop). Thanks for opening an issue to track this. It is definitely on our backlog and there will be some limited support via Peek Definition / Go To Definition in our next release. However we can definitely see the value of providing a more full-featured way to list objects and script them to a file. 

I am renaming the issue to add clarity that it's a more generic problem - we should have support for Script As syntax, with the exact workflow needing to be worked through before implementation.

**Comment by borgdylan** [comment]
:+1: this would help a lot all the dbas that run Linux.

**Comment by tigerhawkvok** [comment]
As far as I can tell this hasn't been touched yet? I was just looking for a way to view a stored procedure and ran into this issue ...
