### ISSUE TITLE
[suggestion] Please support Arch Linux

### ISSUE THREAD

**Issue by tinchou** [Microsoft/vscode-mssql#417]
Hi,

I haven't had time to investigate why the code for this extension has [so many special cases for specific distributions](https://github.com/Microsoft/vscode-mssql/blob/dev/src/models/platform.ts#L245), but I will assume you have a reason for that and I'll thank you for giving us a great experience.

This issue is to request support for Arch Linux. I've seen you have support for distros not as popular (based on [this list](http://distrowatch.com/dwres.php?resource=major)) such as Elementary OS, so I hope you'll take it into account.

Thanks again for your Linux efforts!

**Comment by kevcunnane** [comment]
Hi @tinchou, thanks for raising this issue. Our backing service is built on .Net Core. This lets us reuse a lot of existing code and add new features more rapidly.  The downside is that there are some distributions that .Net Core does not support. Arch Linux is one of these - the issue https://github.com/dotnet/coreclr/issues/4409 looks like the most relevant assessment of state, and this is just to compile on the platform. We'd need support for building all-in-one installers to match the other distributions. 

At present, this request is blocked by lack of support in .Net Core. We will keep it open as a tracking item, and if this support level changes we can take a look at whether it's possible to add support to our extension.

**Comment by benrr101** [comment]
However, if you're feeling particularly gutsy, it looks like there's some unofficial (at least from dotnet's point of view) means of installing the dotnet-cli via the AUR https://aur.archlinux.org/packages/dotnet-cli/

As an unpopular distro user myself (Scientific Linux), I'd like to see as many Linux distros supported as possible, even if they're not "officially supported". I'll try and keep an eye out to see if we can reduce the number of special cases for distros and enable overrides for those to allow unpopular or outdated distros to run our extension.

**Comment by kevcunnane** [comment]
It looks like Omnisharp has figured out a workaround where Ubuntu 16.04 package works - see [issue](https://github.com/OmniSharp/omnisharp-vscode/issues/564) and [pull request](https://github.com/OmniSharp/omnisharp-vscode/pull/1017).

We should look at enabling the same for our code, run testing & verification on an Arch linux platform.

@tinchou if you are feeling adventurous, you could try doing this by changing the switch statement in platform.js to be as follows and seeing if the extension works. We'll get to this after we complete the current release as we're busy focusing on that right now.

```
case 'arch':
   // NOTE: currently Arch Linux seems to be compatible enough with Ubuntu 16 that this works,
   // though in the future this may need to change as Arch follows a rolling release model.
   return ubuntu_16_04;
```

**Comment by thomfogarty** [comment]
@kevcunnane I will happily be a guinea pig for this and report back. Adding the case 'arch' into platform.js did not give the expected results as I am still seeing "mssql: The platform is not supported" in the Command Pallete

**Comment by kevcunnane** [comment]
@thomfogarty @benrr101 OK - if this works could you create a PR with the change? That will let us update and verify.

Separately, the fact that .Net Core 2.0 lets us target a single Linux architecture gives me hope that we could just build once for all Linux platforms and have this handled by the framework. However for now, the above fix could work well.

**Comment by kevcunnane** [comment]
This is now shipped. I'm going to tentatively close this and let people try it out on Arch. Let us know if this works or not - we have enabled it so it'll try to install, but we are not sure if the updates to .Net Core 2.0 mean this will "just work" or if it'll fail due to missing dependencies.
