### ISSUE TITLE
Support for Assemblies/CLR Functions from local file system

### ISSUE THREAD

**Issue by wbuchanan** [Microsoft/vscode-mssql#418]
- MSSQL Extension Version: 0.1.5 
- VSCode Version: 1.7.2
- OS Version: 10.12.1 (16B2555)

Steps to Reproduce:

1. Cloned existing code/assemblies used for [CLR Functions for Regular Expressions and String Distances](https://github.com/wbuchanan/whyWontSQLServerImplementRegexNatively)

```
cd ~/Desktop/Programs/SQL && git clone https://github.com/wbuchanan/whyWontSQLServerImplementRegexNatively sqlregex
```

2. Attempted to create an assembly from the local copy of the source referenced above:

```SQL 
CREATE ASSEMBLY SQLServerRegEx
FROM /Users/billy/Desktop/Programs/SQL/sqlregex/SQLServerRegEx/bin/Release/SQLServerRegEx.dll
WITH PERMISSION_SET = EXTERNAL_ACCESS;
```

3. Results in:

```

[9:20:38 AM]	Started executing query at Line 1
Msg 102, Level 15, State 1, Line 2 Incorrect syntax near '/'.
Msg 319, Level 15, State 1, Line 3 Incorrect syntax near the keyword 'with'. If this statement is a common table expression, an xmlnamespaces clause or a change tracking context clause, the previous statement must be terminated with a semicolon.
Total execution time: 00:00:00.144
```

Seems there is some issue with handling the file path delimiters.  It'd be nice to be able to load assemblies from OSX - particularly if people are already developing in C#/Visual Basic.

**Comment by erickangMSFT** [comment]
The message is a SQL Server parser error which means it is an issue in the SQL server itself. Let me ask SQL Server team that is responsible for enabling support for CREATE ASSEMBLY functionality itself and get an answer for this case.

Can you tell us about the target server? Is it SQL on Windows or Linux?

**Comment by wbuchanan** [comment]
@erickangMSFT It's running on a Windows box.  The hardware is owned by a third party vendor that my organization works with, but pretty sure it is running SQL Server 2012.  Do you think this might work if I used Windows style path delimiters?

**Comment by kevcunnane** [comment]
@wbuchanan yes, are far as I know Windows SQL Server requires Windows-style path delimiters, especially older server versions. 
SQL Server vNext will work to support Linux-style paths though in its current preview it also expects C: to start paths. In the future, it's likely that you should use the platform-native path syntax, e.g. for Windows C:\ path format will continue to be required.

**Comment by wbuchanan** [comment]
@kevcunnane So how would one specify Windows-style path delimiters when referencing *nix-style path delimiters?

**Comment by tmullaney** [comment]
@wbuchanan Three things that are likely causing this:

1. Need quotes around the file path in your CREATE ASSEMBLY T-SQL statement
2. As @kevcunnane says, for now you'll need to use `'c:\'` style paths in CREATE ASSEMBLY statements, where `'c:\'` represents the root of the file system. This is one of the cases we still need to fix. We're working on it.
3. SQL Server on Linux only supports SAFE assemblies for now. But this shouldn't be a problem for an assembly that does regex :)

Can you try something like this?

```
CREATE ASSEMBLY SQLServerRegEx
FROM 'c:\Users/billy/Desktop/Programs/SQL/sqlregex/SQLServerRegEx/bin/Release/SQLServerRegEx.dll'
WITH PERMISSION_SET = SAFE;
```

**Comment by wbuchanan** [comment]
@tmullaney The SQL Server instance is running on a Windows machine, but I work on a MBP.  I tried running what you suggested above:

```SQL
CREATE ASSEMBLY SQLServerRegEx
FROM 'c:\Users/billy/Desktop/Programs/SQL/sqlregex/SQLServerRegEx/bin/Release/SQLServerRegEx.dll'
WITH PERMISSION_SET = SAFE
[2016-11-29 13:51:42] [S0001][6585] Could not impersonate the client during assembly file operation.
```

**Comment by tmullaney** [comment]
@wbuchanan Ah, sorry, I misunderstood and thought the SQL Server instance was on OSX/Docker. 

I think you have two options:

1. Copy the SQLServerRegEx.dll file to the machine running SQL Server (or to a network share), then use CREATE ASSEMBLY with the file path on that machine.

2. Use CREATE ASSEMBLY with the raw bytes, e.g. CREATE ASSEMBLY MyAssembly FROM 0x4D5A900000000000 

See CREATE ASSEMBLY docs here: [https://msdn.microsoft.com/en-us/library/ms189524.aspx](https://msdn.microsoft.com/en-us/library/ms189524.aspx)

**Comment by wbuchanan** [comment]
@tmullaney The second option you mentioned worked fairly well.  I opened the .dll in a text editor, deleted all white space characters, and prefixed the string with `0x` and it seemed to work.  Now just need to figure out if the vendor will allow us to enable CLR integration.
