### ISSUE TITLE
Executing query spinner is spinning backwards

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-mssql#429]
Very small issue, the spinner is meant to be dark on a light background. In the default dark skin for VS Code, the spinner looks like it is spinning backwards. Perhaps we can get a different color spinner for the different color skins.

**Comment by erickangMSFT** [comment]
I sent an email to consult it with Smitha as she provided the icon.

**Comment by benrr101** [comment]
I'm thinking we can maybe load up something like http://cssload.net/en/horizontal-bars (the one with the circles and turn them into squares). This way we can swap out the colors with CSS to make it match whatever theme the user chose.

**Comment by kburtram** [comment]
Closing stale internally created issues.
