### ISSUE TITLE
Display Timestamp values with the milliseconds part in the result pane.

### ISSUE THREAD

**Issue by steynpjm** [Microsoft/vscode-mssql#442]
In the results pane, Timestamp values are displayed only up to the seconds:
28/11/2016 18:27:54	

when in fact it is stored up to milliseconds:
2016-11-28 18:27:54.553

Please display the milliseconds part as well.

**Comment by kevcunnane** [comment]
I took a quick look and our behavior is different to SSMS. Using the repro code below, SSMS shows milliseconds but MSSQL extension does not. We should look to fix this.

@benrr101 - any idea if this is in our service layer or if it's a display issue?

```
GO
CREATE TABLE T2
(
    C1 INT NOT NULL PRIMARY KEY,
    C2 DATETIME,
    C3 DATETIME2
)
GO
INSERT INTO T2 VALUES (1, '2016-11-28 18:27:54.553', '2016-11-28 18:27:54.553')
GO
SELECT * FROM T2
```

**SSMS**
![image](https://cloud.githubusercontent.com/assets/10819925/20842846/cd588a1e-b86d-11e6-95c8-54b64379e2a9.png)

**VSCode**
![image](https://cloud.githubusercontent.com/assets/10819925/20842902/07e15f12-b86e-11e6-9c1e-fedc35914517.png)

**Comment by benrr101** [comment]
I believe this would be a service layer issue. For cells in a table, we generate a "display value" and send that back to the extension. By default we just use the `object.ToString()` which usually works. I'll take a look into this since it should be a fairly quick fix.

**Comment by benrr101** [comment]
A solution to this issue that behaves the same as SSMS is out for review right now https://github.com/Microsoft/sqltoolsservice/pull/173

**Comment by benrr101** [comment]
Issue is checked in and will be included in the next release

**Comment by steynpjm** [comment]
It works in version 0.3.0. Thank you all.
