### ISSUE TITLE
Fix grid scaling logic

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/vscode-mssql#451]
Currently the logic on the result grid scrolling assumes that every grid is the same size (on the page) as the first one, which isn't true. (https://github.com/Microsoft/vscode-mssql/blob/dev/src/views/htmlcontent/src/js/components/app.component.ts#L555).

This should be changed to something like calculate home many actual grids (not a grid based on the first size) are being shown.

**Comment by kburtram** [comment]
@anthonydresser could you please provide some details on what is the impact of this bug so we can better triage the issue?  If there isn't a customer facing issue I'd recommend closing this out.

**Comment by anthonydresser** [comment]
If I remember correctly, the problem was that if you had many results sets (enough to trigger my scrolling logic) and the first result set had more than 8 rows (the max size cutoff) but the rest had less than 8. The scrolling logic wouldn't work properly because it assumes all the grids are the same size as the first.

A customer would hit this if the first result set had 8 or more rows, and the rest had less than 8 rows, and they had enough result sets to trigger the scrolling logic.

**Comment by kburtram** [comment]
@anthonydresser thanks!  I'll try to repro and gauge the customer impact.

**Comment by abist** [comment]
This is now fixed.
