### ISSUE TITLE
Enable the gif demo for the mssql extension package

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/vscode-mssql#456]
- MSSQL Extension Version: 0.1.5
- VSCode Version: all
- OS Version: all

The gif demo appears as a broken link on the mssql extension. Include following in the readme.md to enable the demo.

<img src="https://github.com/Microsoft/vscode-mssql/raw/master/images/mssql-demo.gif" alt="demo" style="width:480px;"/>

**Comment by kevcunnane** [comment]
Fixed by #457
