### ISSUE TITLE
CI build status banner on README.md is broken for AppVeyor

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/vscode-mssql#466]
AppVeyor CI banner is broken with a permission error.

![image](https://cloud.githubusercontent.com/assets/11077282/20937321/56839678-bb9b-11e6-9f79-4e94278fe22a.png)

**Comment by anthonydresser** [comment]
@kburtram or someone has to make the appveyor account and change the readme accordingly, I purposely broke this so people know this is a problem that needs fixing.

**Comment by kburtram** [comment]
This has been resolved.
