### ISSUE TITLE
Sqltoolsservice can't test on dotnet 1.1

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/vscode-mssql#470]
- OS Version: Linux

Currently if you installed the latest version of dotnet core (1.1) you can't run the sqltoolsservice tests. You get the following output:

dotnet test test/Microsoft.SqlTools.ServiceLayer.Test
Project Microsoft.SqlTools.ServiceLayer (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
Project Microsoft.SqlTools.ServiceLayer.Test (.NETCoreApp,Version=v1.0) will be compiled because expected outputs are missing
Compiling Microsoft.SqlTools.ServiceLayer.Test for .NETCoreApp,Version=v1.0
sqltoolsservice/test/Microsoft.SqlTools.ServiceLayer.Test/project.json(27,46): warning NU1007: Dependency specified was dotnet-test-xunit >= 1.0.0-rc2-192208-24 but ended up with dotnet-test-xunit 1.0.0-rc2-build10015.
Compilation succeeded.
    1 Warning(s)
    0 Error(s)
Time elapsed 00:00:02.2858480
 
The specified framework 'Microsoft.NETCore.App', version '1.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      /usr/share/dotnet/shared/Microsoft.NETCore.App
  - The following versions are installed:
      1.1.0
  - Alternatively, install the framework version '1.0.0'.
SUMMARY: Total: 1 targets, Passed: 0, Failed: 1.

**Comment by kevcunnane** [comment]
Fixed for now by reverting back to strict version compatibility instead of a * method. Fixed test automation to support this.
