### ISSUE TITLE
Preview Release 2 candidate: When multiple grids are rendered with larger than 8 rows, 8 is the minimum rows to display per grid.

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/vscode-mssql#472]
Each grid should display 8 or lower number of rows per grid.
![image](https://cloud.githubusercontent.com/assets/11077282/20951090/a3025c04-bbd8-11e6-8534-feffbe2e68b1.png)

**Comment by erickangMSFT** [comment]
This is a regression from Preview release 1

![image](https://cloud.githubusercontent.com/assets/11077282/20951155/055dfa0c-bbd9-11e6-8363-e46fada607c2.png)

**Comment by erickangMSFT** [comment]
This is a regression from Preview Release 1

![image](https://cloud.githubusercontent.com/assets/11077282/20951180/272fc4ee-bbd9-11e6-99ea-aed049315789.png)

**Comment by anthonydresser** [comment]
Without looking too much into it, looks like it has something to do with this.

https://github.com/Microsoft/vscode-mssql/commit/158e43e2be64f1b630f0e055c280d177b0677e63#diff-1df1f9bd5f3b0cf63b472db70bd235bfL398

**Comment by kevcunnane** [comment]
@coquagli & @benrr101 - could you take a look? This is a good chance to learn this code area for Connor, but since it may be related to your change can you help him get started Ben?

**Comment by coquagli** [comment]
Looks like "resultSet.totalRows" was renamed to "resultSet.rowCount", causing maxHeight and minHeight to always be 'inherit'.
