### ISSUE TITLE
Escape reserved words during autocomplete

### ISSUE THREAD

**Issue by jkerak** [Microsoft/vscode-mssql#473]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.2
- OS Version: OSX

In some cases, table or schema names in a database may be reserved words. For example, you may have a table named "Transaction" or "Order", or a schema called "user".

I would be nice if, during autocomplete, the reserved words were escaped with [].

For example, the results of an auto-complete while writing a query might be:

Start with:
`SELECT * FROM dbo.U`

press tab results in:
`SELECT * FROM dbo.[User]` 

instead of 
`SELECT * FROM dbo.User`

**Comment by kevcunnane** [comment]
@llali this seems like a sensible request. @abist may be able to help get this implemented.
