### ISSUE TITLE
Copy Message Error

### ISSUE THREAD

**Issue by SebastianPrieto** [Microsoft/vscode-mssql#476]
- MSSQL Extension Version:0.1.5
- VSCode Version: 1.7.2
- OS Version: WIN10

Steps to Reproduce:

1. Execute any query
2. i don't can copy message of the query in a new page

**Comment by kevcunnane** [comment]
Thanks for raising this issue. We've had 1 issues created already so I'll close this as a duplicate of #385. Ben will take a look at the issue but we'll track in the original thread #385 .

**Comment by kevcunnane** [comment]
@SebastianPrieto  this fix is checked in - it'll appear in tomorrow's nightly and our next official release. Thanks for raising.
