### ISSUE TITLE
Results table not shown when errors are encountered

### ISSUE THREAD

**Issue by ckasabula** [microsoft/vscode-mssql#477]
- MSSQL Extension Version: 0.1.5
- VSCode Version:1.7.2
- OS Version: Windows 10 Pro

Steps to Reproduce:
Run the attached sql script in SSMS and mssql. SSMS shows results and messages (rows affected and error) in separate tabs. mssql just shows the messages. no results.

[vscode-mssql-error.zip](https://github.com/Microsoft/vscode-mssql/files/637757/vscode-mssql-error.zip)

**Comment by abist** [comment]
This is now fixed in the latest version. Feel free to re-open if you see this issue persist in the latest version of the extension.
