### ISSUE TITLE
Sqltoolsservice dev build auto versions not properly ordered

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-mssql#490]
Current history from latest to oldest
* v0.1.4-alpha.4
* v0.1.4-alpha.3
* v0.1.4-alpha.2
* v0.1.4-alpha.10
* v0.1.4-beta.1
* v0.1.4-alpha.9
* v0.1.4-alpha.8
* v0.1.4-alpha.7
* v0.1.4-alpha.6
* v0.1.4-alpha.5

Uh..... what?

**Comment by kevcunnane** [comment]
I think releasing a beta.1 messed up the logic - will work to fix
