### ISSUE TITLE
Result window gets hung when executing just "GO" command

### ISSUE THREAD

**Issue by fcatae** [Microsoft/vscode-mssql#494]
- MSSQL Extension Version: 0.1.5
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Type just GO in the editor
2. Run the query
3. The extension gets into a wrong state, in which it doesnt finish the execution neither it is not possible to cancel the query.
4. The workaround is to use a new window with a new connection

Even though it doesn't seem to be a realistic scenario, I just ran into this case. I selected just the "GO" statement, and ran it by mistake.

**Comment by fcatae** [comment]
Does #485 fix it?

**Comment by kburtram** [comment]
@fcatae this looks like the issue tracked in https://github.com/Microsoft/vscode-mssql/issues/341.  This should have been fixed by https://github.com/Microsoft/sqltoolsservice/pull/157 and the fix will be included in Preview release 2.

**Comment by benrr101** [comment]
Just an update, this isn't completely fixed in the PR @kburtram mentioned. And #491 doesn't completely fix it either at the moment. I've looked into what should solve the issue and asked @abist to add it into #491. Once we get those changes in, I'll close this one up.

**Comment by kevcunnane** [comment]
This fix has been checked in and will be in the upcoming release
