### ISSUE TITLE
sendTelemetryEvent throwing nullref exception

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#500]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8
- OS Version: OpenSuse 13.2

Steps to Reproduce:

1. Run peek definition with extension being debugged

Expected: No exceptions

Actual: sendTelemetryEvent throws nullref exception in the below line.  It looks like properties isn't be correctly allocated.

Notes:

line#135 properties['userId'] = userId;

Debug Log:

typeof properties 
"object"
properties === null
true

**Comment by kevcunnane** [comment]
Fixed by Karl
