### ISSUE TITLE
Renaming a file causes connection to be lost

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#502]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8
- OS Version: OpenSuse

Steps to Reproduce:

1. Open a SQL file, e.g., test.sql
2. Connect to a database
3. Rename SQL file, e.g., test2.sql

Expected: Connection is not lost

Actual: Connect is lost

**Comment by Raymondd** [comment]
What I could do on the extension side, is automatically reconnect to the same profile after a disconnect occurs on rename. 
Instead, I am assuming we probably want keep the connection alive and just change the identifying URI. I believe I will have to create a new type of request to bind a new URI to an existing connection on the tools service side. Does this sound reasonable?

**Comment by kburtram** [comment]
@Raymondd try looking at how we handle a similar scenario when untitled files are save with an active connection https://github.com/Microsoft/vscode-mssql/search?utf8=%E2%9C%93&q=OnUntitledFileSaved.  That should be a good starting point.
