### ISSUE TITLE
Return ShowPlan data as Text or XML with Query Execution

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#509]
This is a high-level tracking task to cover query execution returning ShowPlan information alongside the query. Looking at SSMS, there are 2 scenarios:
- Include Estimated Execution Plan. This returns the data as soon as query execution begins
- Include Actual Execution plan. This returns the data once execution has completed.

By default the query plans are not queried, so this has to be set up before running commands. Therefore, we likely need the following:
- A command palette option to enable Show Plan as Text. This is a per-query session option, but if we wanted we could have a workspace/user preference to default enable this
- A button beside the `Save as JSON` button to display the ShowPlan results as text. 
  - This could replace the ResultsGrid with a read-only text pane when checked, and revert when unchecked.
  - Alternatively, it could save the results to a file and open it. This would make connecting it to extensions (such as a viewer for the XML ShowPlan results) simpler since all that's needed to be passed is a file path.

**Comment by kburtram** [comment]
Closing stale internally created issues.
