### ISSUE TITLE
Multi-line UDF formatting Issue

### ISSUE THREAD

**Issue by Raymondd** [Microsoft/vscode-mssql#511]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.7.2
- OS Version: Win10

Steps to Reproduce:

1. Add a multi-line user defined function with white space at the top
```


-- Example of DB function
CREATE FUNCTION avgSalary () 
  RETURNS MONEY 
  AS 
  BEGIN 
    DECLARE @salary MONEY 
      SELECT @salary = AVG(SALARY) 
      FROM CUSTOMERS
      RETURN(@salary) 
  END 
```
2. Execute Query to find function definitions: 
```
SELECT name, definition, type_desc 
  FROM sys.sql_modules m 
INNER JOIN sys.objects o 
  ON m.object_id=o.object_id
```

Output:
![newlines](https://cloud.githubusercontent.com/assets/3318689/21123642/bd6406b4-c08e-11e6-933e-a0d908826d63.PNG)

SSMS seems to remove all newlines and keep comments:
![ssms](https://cloud.githubusercontent.com/assets/3318689/21123585/70bd82a4-c08e-11e6-9c8f-14d829140a33.PNG)

**Comment by kevcunnane** [comment]
When fixing this, note that SSMS has options to preserve newlines or ignore when copying. So there's a difference between formatting for display vs. copy support

**Comment by Raymondd** [comment]
Would you recommend adding it as an option in the settings json file?

**Comment by kevcunnane** [comment]
Yes - looking at SSMS here's the default settings they support. CR/LF is not retained by default but the option can be enabled:

![image](https://cloud.githubusercontent.com/assets/10819925/21151205/78ca84c8-c116-11e6-93e2-2937fb3ace36.png)
