### ISSUE TITLE
Add "New Query" Command that opens new .sql temp file and prompts for connection

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#516]
We've had at least 1 person rate our extension with the comment 

> Make it perfect now and add some run query/new query button

We do actually have Run Query, but we should have a New Query command. The problem is for ad-hoc queries it's a pain to create a new untitled file and change to .sql. It'd be much nicer to create a temp file with .sql extension so it's easier to get bootstrapped. If possible we should immediately prompt to choose a connection too.

**Comment by llali** [comment]
Fixed in #569
