### ISSUE TITLE
V0 Edit Data scenario

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#517]
Edit Data is an important dev scenario The initial work on this is are follows:

**API Requirements**
- CreateEditSession event. This will create the session, executing a query against a DB and returning a resultset that can be used for editing.
  - An important note is that the format of the table, any filters applied, must be known and have a corresponding update mechanism. For example,
_Select Script_
```
SELECT C1, C2, C3 FROM T1
WHERE C1 < 1000 AND C2 LIKE '%ABC%'
```
Maps where C1 & C2 are PRIMARY KEY maps to:
 _UPDATE FORMAT_
```
INSERT INTO T1 (C1, C2, C3) VALUES (2, 'DEF', 3)
```
  This implies that we cannot accept any arbitrary query. However, for a batch with 1 select statement this could be parsed and verified for compatibility with the system. Initially, assume fixed/controlled query format
- Event to support updating a ResultSet.
- Per-row update event is likely needed / beneficial
- Needs row change, row insert, row delete handling

- Event to commit results (for a row, or a result set). This applies changes to a database
- Ideally, event to instead output the results to a file as INSERT INTO / UPDATE statements.
- EndEditSession event

**UI Requirements**
UI requirements are less clean than API side. We can prototype this entirely in Chrome for now and get this working before doing full VSCode integration. Basic work:
- Create a version of the ResultsView that has editable result sets
- Call the API to establish an edit session and display the editable resultset
  - Results View should handle row change, row delete, row insert
- Handle Commit, e.g. via a button or using auto-commit on exiting a row

Lower pri requirements for initial implementation:
- Handle copy/paste into the Results View. This may just work
- Option to "Script as T-SQL" so changes are printed as INSERT INTO statements to a file.

**Implementation approach**
SSDT and SSMS both have very thorough implementations of this code. SSDT is complicated but probably a good place to start. Porting this code over & wrapping in a service API would be a good place to start. We can verify the basic flow, then handle UI work either as a separate part

Please create sub-tasks for specific work related to this. E.g. each API event and the flow can be tracked in its own task so we can more easily manage progress on this larger feature

**Comment by borgdylan** [comment]
:+1: This would start turning the extension into some sort of SSMS light. Great idea!

**Comment by benrr101** [comment]
Since the issues for creating the basic API exist now, I'll close this one in favor of working on the smaller issues.
