### ISSUE TITLE
Result set index cannot be less than 0 or greater than the number of result sets

### ISSUE THREAD

**Issue by coquagli** [microsoft/vscode-mssql#520]
`System.ArgumentOutOfRangeException occurred
  HResult=-2146233086
  Message=Result set index cannot be less than 0 or greater than the number of result sets
Parameter name: resultSetIndex
  ParamName=resultSetIndex
  Source=Microsoft.SqlTools.ServiceLayer
  StackTrace:
       at Microsoft.SqlTools.ServiceLayer.QueryExecution.Batch.GetSubset(Int32 resultSetIndex, Int32 startRow, Int32 rowCount) in D:\repos\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\QueryExecution\Batch.cs:line 364
  InnerException:`

The user is prompted with `mssql: Something went wrong getting more rows: Result set index cannot be less than 0 or greater than the number of result sets`

The result set is sized correctly, but all entries remain blank. 
![image](https://cloud.githubusercontent.com/assets/24420239/21158958/25ec7e14-c134-11e6-9335-852de3de270b.png)

Steps to Reproduce:
1. Open the extension and connect to a database
2. Attach the debugger for sqltoolsservice 
3. Put a breakpoint in the `TryFindConnection `function in `ConnectionService.cs`.
4. Run a query. I used:
 `select * from sys.databases`
5. When the breakpoint is hit, wait like 20 seconds, then continue
6. The exception above is raised

It looks to be some sort of race condition or timeout issue, based on the fact that the debugger is required to repro.

**Comment by ransagy** [comment]
I had this happen once, but i didn't use or attach the debugger. Could be a separate issue.

**Comment by joelmartinez** [comment]
This seems to be the only mention of this error message, so I'll comment that I recently installed this code extension, and am receiving the same message. 

This is on a Mac, and I do have dotnet core/openssl installed.

**Comment by coquagli** [comment]
@joelmartinez @ransagy can you describe the scenarios when you see this error? This is obviously a query execution error, but we're trying to narrow down the exact scenario that causes this to occur.

**Comment by joelmartinez** [comment]
@coquagli Well, the scenario was that I opened a `.sql` file, created a connection profile (I had recently installed the extension), and tried to execute a query. The side-pane opened, it spun for a bit, and then gave me the error message.

For the sake of reproducing it, I just tried it again, and lo and behold, it works!

![image](https://cloud.githubusercontent.com/assets/90380/24308137/43f02d8a-109d-11e7-97ce-d93cea4fbd37.png)

I picked the same connection profile I made the other day and the same query I was trying (just a test), so unfortunately I'm not sure I can offer any more context around the precise actions that led me to that state; other than just confirmation that I did experience it :)

**Comment by ransagy** [comment]
@coquagli Sadly, haven't found anything reliable. It does happen every few hours of querying.

**Comment by coquagli** [comment]
@joelmartinez @ransagy Alright. Thanks!

**Comment by storigen** [comment]
I had the same issue because I was just typing in my table name. You must include your schema before your table name. From "mytable" to "dbo.mytable"
