### ISSUE TITLE
The shortcut for Connect doesn't work

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode-mssql#524]
- MSSQL Extension Version: 1.7+
- VSCode Version: 0.2.0
- OS Version: Windows 10

Steps to Reproduce:

1. Press Ctrl + Shift + C for accessing MS SQL: Connect (shortcut given in the drop down box)
2. Instead of opening a connection, it opens a Command Prompt window.

**Comment by kevcunnane** [comment]
Limitation in VSCode when we aren't activated yet.
