### ISSUE TITLE
PositionOfCursor returns incorrect values when no newlines are present 

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#535]
`PositionOfCursor` in `TextUtilities.cs` has a bug when there is no newline in the input SQL string.

**Example input:**
```
sql = "EXEC sys.fn_isrolemember "
startRow = 1
startColumn = 25
```

**Actual Results:**
```
return value =  51
out prevNewLine = 26
```

**Expected (or at least more reasonable) Results:**
```
return value =  1
out prevNewLine = 1
```

**Comment by kburtram** [comment]
@coquagli I think the issue is that the text utils functions are 0-based.  Please verify that all usages of those functions are correctly passing in 0-based indices.

I've create a PR with unit tests for the function related to this issue https://github.com/Microsoft/sqltoolsservice/pull/192.

**Comment by coquagli** [comment]
Looks like all usages are passing in `TextDocumentPosition.Position.Line` and `TextDocumentPosition.Position.Character`, which are documented to be 0-based.  Should I close this issue, seeing as the issue was that I was passing in a 1-based index?

**Comment by coquagli** [comment]
Not actually a bug: just me passing in a 1-based index into a function that expects a 0-based index.
