### ISSUE TITLE
Newlines not stripped from output

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#537]
When displaying string types (e.g. `NVARCHAR`) in the results grid, newlines are not stripped and all text not on the first line is unreadable. 

For example, look at the differences between how VS code and SSMS display the following query:
```
DECLARE @text NVARCHAR(100)
SET @text = 'This is line 1.' + CHAR(13) + 'This is line 2.' + CHAR(13) + 'This is line 3.'
SELECT @text
```

**Actual (VS Code):**
![image](https://cloud.githubusercontent.com/assets/24420239/21240335/be777fda-c2bf-11e6-8735-4b51226705ed.png)

**Expected (SSMS):**
![image](https://cloud.githubusercontent.com/assets/24420239/21240428/1b6b4db6-c2c0-11e6-92ca-e0b669035cee.png)

**Comment by coquagli** [comment]
Duplicate of #511

**Comment by Raymondd** [comment]
Confirmed that #527 fixes this issue and it is already merged in dev. Going to close this.
