### ISSUE TITLE
ObjectDisposedException regularly thrown in ConnectionService

### ISSUE THREAD

**Issue by coquagli** [microsoft/vscode-mssql#547]
It seems like the `cancellationTask` in `Connect()` in `ConnectionService.cs` is regularly throwing a `ObjectDisposedException`. We should investigate why and clean up the code to avoid doing this:

```
catch (ObjectDisposedException)
{
    // Ignore
}
```

https://github.com/Microsoft/sqltoolsservice/blob/dev/src/Microsoft.SqlTools.ServiceLayer/Connection/ConnectionService.cs#L203

**Comment by kburtram** [comment]
@kevcunnane Please validate if this is fixed already.
