### ISSUE TITLE
Default column for a new results pane 

### ISSUE THREAD

**Issue by Raymondd** [Microsoft/vscode-mssql#549]
MSSQL Extension Version: 0.2.0
VSCode Version: 1.8
OS Version: Win10

Steps to Reproduce:
1. Open three columns in VSCode. 
2. Run a query that opens a results pane.

Actual: 
Results pane opens in 2nd column (current default for new panes). 

Expected:
Not sure. Where should the results pane default to?

**Comment by coquagli** [comment]
I think @kevcunnane or @erickangMSFT would be the people to ask about usability and design questions.

**Comment by Raymondd** [comment]
In order to accommodate different styles of development, we will be adding a setting defined as follows:
**ResultView.splitPaneSelection = {same|next|last}**
**same**: open split pane in same window as active editor
**next**: open split pane to the right of the active editor
**last**: open split pane in last column 

default value will be 'next'

**Comment by DAD713** [comment]
Is it possible for the result pane to be on the bottom?  Similar to what SSMS does now.

**Comment by ChrisTuckerNM** [comment]
I would also request that an option to be below, or above.  

Propose also changing values next and last to left and right.
ResultView.splitPaneSelection = {current|left|right|below|above}

**Comment by JaderCM** [comment]
@Raymondd 👆
