### ISSUE TITLE
Having null cells causes problem in table selection

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode-mssql#558]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8
- OS Version: Windows 10

Steps to Reproduce:

1. Run any query that may have null value entries in the SlickGrid cells. For example, the following query works -
`SELECT * FROM sys.databases`

2. Make any selection of cells in the table which includes null cells. For example, you could right click the table and select "Select All" and right click again and click on "Copy". Paste the copied contents any where.

Expected Result - Copy-Paste should work normally

Observed Result - No contents were copy-pasted. If there was something else copied on the clipboard, that will be pasted instead.

**Comment by kburtram** [comment]
I wasn't able to repro this myself with the 0.2.0 release build.  Copy\Pasting from sys.databases I get the following with NULLS copying as expected.

name	database_id	source_database_id	owner_sid	create_date	
master	1	**null**	0x01	4/8/2003 9:13:36 AM	
tempdb	2	**null**	0x01	12/12/2016 3:05:27 PM	
model	3	**null**	0x01	4/8/2003 9:13:36 AM	
msdb	4	**null**	0x01	4/30/2016 12:46:38 AM

**Comment by abist** [comment]
> I wasn't able to repro this myself with the 0.2.0 release build

That's really strange because I can successfully repro this issue every time.

**Comment by kburtram** [comment]
If you have a repro please investigate and root cause what's going on...I was just mentioning that I've successfully tried the scenario described in the bug many times, so possibly some other step may be required to trigger the repro or something could be messed up with your current build.  Are you testing with the 0.2.0 release build?

**Comment by abist** [comment]
I agree, seems to have been fixed in the release build.
