### ISSUE TITLE
How to  goback Version 0.1.5？

### ISSUE THREAD

**Issue by frank--zhang** [Microsoft/vscode-mssql#560]

**Comment by kburtram** [comment]
We don't currently have the 0.1.5 VSIX published directly anywhere.  We can publish those bits if necessary.  Are you encountering a problem with the 0.2.0 release?

**Comment by kburtram** [comment]
@frank--zhang I've upload the 0.1.5 VSIX to this release page https://github.com/Microsoft/vscode-mssql/releases/tag/v0.1.5.0.

To downgrade you'd need to
1. Uninstall 0.2.0 and restart VS Code
2. Download the VSIX from the above release link
3. Side-load the 0.1.5 VSIX through the Extension Manager "Install from VSIX..." command in the "..." pop-up menu.

If you're encountering issues with the 0.2.0 build we'd be very interested to try to understand the details and get a fix into a future build.

**Comment by frank--zhang** [comment]
@kburtram Thanks.
My work OS is X86.

**Comment by borgdylan** [comment]
AFAIK .NET Core is not runnign on X86 (32 bits) and that means that the extension will not work for you :/ .

**Comment by kburtram** [comment]
This is correct.  Unfortunately we don't currently support x86.  I'm not sure if this is a fundamental limitation from .Net Core or how our build systems is configured.  I've opened this issue to track investigating this https://github.com/Microsoft/vscode-mssql/issues/562.

**Comment by borgdylan** [comment]
Currently it is a limitation in .NET Core: x86 is only supported on Windows. Cross-plat x86 is being worked on.

**Comment by kburtram** [comment]
@borgdylan thanks!

**Comment by kevcunnane** [comment]
Closing this out - we have x86 support coming in our next release. Thanks for raising this.
