### ISSUE TITLE
Feature Request: Show database hierarchy in solution explorer

### ISSUE THREAD

**Issue by bansalvks** [microsoft/vscode-mssql#586]
is it possible to show the table and column hierarchy in solution explorer for you? something like shown in the screen shot below?

![image](https://cloud.githubusercontent.com/assets/8565993/21740374/51ae7b7a-d4de-11e6-902f-17676ec5ed62.png)

**Comment by joeygreen** [comment]
This is what I've been using in the mean time:

SELECT TABLE_NAME1
 FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_CATALOG='<database_name>'

**Comment by kevcunnane** [comment]
Thanks for this suggestion. VSCode has an experimental API that would support an object-explorer like view. We won't be able to visualize this without this API being made official, but if it does become official we can look at implementing this.

**Comment by anthonydresser** [comment]
@kevcunnane If the api doesn't go through, another web application could be made in the same light as the results grid 🙄

**Comment by kevcunnane** [comment]
Another user has requested this - see #875. It looks like the API to enable this might be implemented soon as it's on the May roadmap for VSCode: https://github.com/Microsoft/vscode/issues/26068. We can consider implementation of this if the API is made public and included in full builds.

**Comment by alohaninja** [comment]
Hope to see " Support to contribute a tree section to the explorer" Extension API get knocked out soon! 

Thanks @kevcunnane!

**Comment by tadcrazio** [comment]
This would be huge. Love the work done so far in this extension.  Can't way to see  things like this come into the project in the future .

**Comment by richarddavenport** [comment]
Any movement on this, now that there is a tree view in the explorer?

**Comment by alohaninja** [comment]
@richarddavenport - looks like this may have taken a slightly different direction. Rather than building and expanding mssql extension for vscode - they created [**SQL Operations Studio** which leverages the treeview and vscode codebase.](https://github.com/Microsoft/sqlopsstudio) So nice to see a dark themed capable SSMS-style tool!

**Comment by richarddavenport** [comment]
@alohaninja awesome! Thanks for the info!

**Comment by Memphizzz** [comment]
If this extensions could show this server explorer:
![capture](https://user-images.githubusercontent.com/4660924/36974100-bcbd3710-2075-11e8-9b2f-f53d034d2b4b.JPG)
I wouldn't need SQL Operations Studio anymore. Is it possible to add this?

**Comment by GideonBrimleaf** [comment]
Ditto to @Memphizzz - this would really help me to adopt VS Code for SQL Sever querying!

In the mean time - any decent work-arounds?

**Comment by ek1977** [comment]
At my company we do a lot of ad-hoc data analytics using SQL server.  We have been looking for an editor that supported GIT for arbitrary scripts but still allowed users to browse Server Objects.  This addition would I think satisfy our requirements and likely that of many other data analytic professionals.

**Comment by guillaume86** [comment]
Not sure if this is still in consideration but the VS Code API to allow extensions to add tree-views is public now:
https://github.com/Microsoft/vscode/issues/4047#issuecomment-307303621

**Comment by jenseralmeida** [comment]
April 2018 (version 1.23) release has some new extension points which could allow a complete database experience on vscode.

https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by Memphizzz** [comment]
@kburtram Great! I'm sure everyone in this thread is looking forward to it!

**Comment by rramname** [comment]
+1

**Comment by njonesogre** [comment]
+1

**Comment by dfruge** [comment]
+1

**Comment by ArsCarlos** [comment]
+1

**Comment by Memphizzz** [comment]
Can you share any news on this with us @kburtram?

**Comment by sneaky323** [comment]
@kburtram @kevcunnane - Is there a status update on this feature?

**Comment by Memphizzz** [comment]
btw, why is this thread still labeled as "blocked"?

**Comment by gregiare** [comment]
+1

**Comment by kburtram** [comment]
@Memphizzz I've removed the "blocked" label.  Now we're just blocked on available resources. 😄

**Comment by adam-geisen** [comment]
This is probably the only thing keeping me from using VSCODE full time. Any thoughts on when resources might become available?

**Comment by cyrusel** [comment]
It's not fair! Mysql extension for vs code shows objects as tree but mssql (Microsoft product) doesn't. Please add this feature.

**Comment by Andrew0002** [comment]
Also would like to see this.

**Comment by oxodao** [comment]
Looking forward on this

**Comment by Poltergeisen** [comment]
Potential work-around for others that don't want to use SSMS. Azure Data Studio seems to be a really good alternative for most things and is built on top of vscode: https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-2017

**Comment by bobhy** [comment]
So, is that the resolution then?  If you want an explorer view and intellisense SQL editing, forget about vs code and mssql extension, use Azure Data Studio instead?

**Comment by Memphizzz** [comment]
@bobhy I certainly hope not, @kburtram any plans yet or ideas on when there might be some ressources to get this implemented?

**Comment by Poltergeisen** [comment]
@bobhy I would hope not for that. The reason I didn't want to use SSMS is because I didn't want to open yet another editor to do things.

**Comment by Memphizzz** [comment]
@Poltergeisen Exactly, I dont even want to  have SSMS, VSC and SQL Operations Studio installed at the same time. And as this thread has been requesting this feature for a long time and we got confirmation from @kburtram thats its doable, I'm pretty confident I will be done soon.

**Comment by dontwastetime** [comment]
This would be really be an awesome feature. Are you still planning on developing this?

**Comment by Projkt-James** [comment]
+1 for this feature

**Comment by taraansa** [comment]
+1 for this feature

**Comment by jacobchurch** [comment]
If only github would add a +1 button, hey +1 for that too! I'm helping!

**Comment by vigneshrajsb** [comment]
Waiting for this feature to have VS Code as the primary editor for sql

**Comment by Exic9999** [comment]
Adding on my +1 to keep this alive. An object explorer would complete VS Code for most of my SQL needs.

**Comment by JorisBlanken** [comment]
+1 would be great to be able to do everything from vscode

**Comment by ldnicolasmay** [comment]
+1 This would be a great feature. Thanks!

**Comment by waio1990** [comment]
+1 this would really help my current project!

**Comment by bebekim** [comment]
+1

**Comment by vtruong68** [comment]
+1 A must have for navigating large databases and tables

**Comment by MartinRiddar** [comment]
Well I'm joining the list of people who wants to see this implemented :)

**Comment by jenseralmeida** [comment]
Is this feature request refused and it will be made?

**Comment by abist** [comment]
@jenseralmeida stay tuned for updates :wink:

**Comment by gustavosmachado** [comment]
+ 1

**Comment by bobhy** [comment]
FYI, there is a perfectly usable VS Code-based SQL Server management tool available now, [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is).  It works great with local and Azure SQL Server (and, they say, PostgreSQL). It's obviously based on VSCode and has the same git and extensions tools.  

Switching between an ADS and VSCode window (pointed at same project folder) works well for me, YMMV. But that project has probably undermined the drive for enhancing this extension and seems to be the closest we'll come to full feature SQL editing and DB admin in this lifetime.

**Comment by JorisBlanken** [comment]
> FYI, there is a perfectly usable VS Code-based SQL Server management tool available now, [Azure Data Studio](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is). It works great with local and Azure SQL Server (and, they say, PostgreSQL). It's obviously based on VSCode and has the same git and extensions tools.
> 
> Switching between an ADS and VSCode window (pointed at same project folder) works well for me, YMMV. But that project has probably undermined the drive for enhancing this extension and seems to be the closest we'll come to full feature SQL editing and DB admin in this lifetime.

A good management tool, but no better than SQL Server Management Studio for me.
I suspect that the point for most of us is to get away from having to use multiple programs.

**Comment by abist** [comment]
The new version is with the Object Explorer feature is out!

**Comment by testingcan** [comment]
Thanks for all your work, this is such a major improvement!
