### ISSUE TITLE
Results Tab Renders HTML instead of plain text.

### ISSUE THREAD

**Issue by joeygreen** [Microsoft/vscode-mssql#587]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Query a table that has a column containing HTML
2. Check it out in the results tab.

**Comment by benrr101** [comment]
Oh yes, this is a very good catch! Thanks for reporting this. I'll be working on this right away.

**Comment by benrr101** [comment]
Alright, I've got a code change for this issue merged into our dev branch. It will be in our next preview release (which I believe is slated for end of January). If you want to take it for a spin, feel free to take our next nightly build and follow the instructions to side-load it via the VSIX file.

**Comment by joeygreen** [comment]
Thanks for the hard work!
