### ISSUE TITLE
Can't copy cell values or save to json/csv?

### ISSUE THREAD

**Issue by ransagy** [Microsoft/vscode-mssql#588]
- MSSQL Extension Version: 0.2.0 alpha 15 ( release with fix #585 )
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open an SQL file or create a new one and set language to SQL.
2. Connect to a database.
3. Run a query.

Expected:
Results can be selected and copied from the grid.
Results can be exported as either JSON or CSV by selecting them and clicking one of the buttons on the grid to export.

Actual:
Results can't be selected as far as i can tell. It does put the dotted-line-frame around a cell so its supposedly selected? Clicking the Save As buttons does nothing. Ctrl+C to copy does nothing as well.

I think I'm just missing something obvious here.

**Comment by anthonydresser** [comment]
@kevcunnane This is something I noticed in #581 and I fixed, as far as the selection goes, no comment on the copy problem.

**Comment by kevcunnane** [comment]
Thanks @anthonydresser. @coquagli - can we review and sign off Anthony's fix, and if it doesn't fully sort the issue out then get an additional fix as needed?

**Comment by coquagli** [comment]
Can do.

**Comment by coquagli** [comment]
Looks like #581 fixes this.

**Comment by ransagy** [comment]
Great, I'll wait for a release with that commit merged and close it after testing.

**Comment by ransagy** [comment]
Yeah, Fixed on the alpha 18 vsix released a day ago.

**Comment by ransagy** [comment]
@coquagli this is now broken again in 0.3.0 release.

**Comment by coquagli** [comment]
I'll take a look. Thanks for the heads up.

**Comment by kevcunnane** [comment]
This is due to https://github.com/Microsoft/vscode-mssql/issues/716 - the minified build is not finding SlickGrid plugins that we use for these. I'll publish the non-minified bits as the RC for now, and we should get this fixed ASAP. We can release as non-minified, the impact would be slightly larger install & potentially slower perf

**Comment by kevcunnane** [comment]
@ransagy - could you please test by deleting and re-installing the VSIX from https://github.com/Microsoft/vscode-mssql/releases/download/v0.3.0/mssql-0.3.0.vsix? This should now be fixed / mitigated by using the non-minified build. I have updated all the VSIX files to use this and tested that it resolves the issue

**Comment by ransagy** [comment]
Yes, The new release fixes it. Thanks for the quick turnaround 👍
