### ISSUE TITLE
Reenable commented out QueryExecutionTests

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/vscode-mssql#590]
A number of tests in QueryExecutionTests in the TestDriver project are commented out by https://github.com/Microsoft/sqltoolsservice/commit/dd3592fe30d231e27345d2291855c7836d185bc5. We should reenable and get them passing (or remove if duplicative)

**Comment by coquagli** [comment]
Similarly, see #577.

**Comment by kburtram** [comment]
@benrr101 this is appears to be an issue in https://github.com/Microsoft/sqltoolsservice/blob/dev/test/Microsoft.SqlTools.ServiceLayer.TestDriver.Tests/QueryExecutionTests.cs.  What are the plans to enable or delete these tests?
