### ISSUE TITLE
Install hangs !

### ISSUE THREAD

**Issue by ramana1729** [Microsoft/vscode-mssql#595]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. I clicked on the Install button waited for 1 min , 2 mins ,5 mins, 15 mins & tried few times - it just hangs...
2. No install issues with other extensions.

**Comment by kburtram** [comment]
@ramana1729 is this occurring while trying to install the extension from the VS Code Extension Manager?  If so, we unfortunately don't execute any code during that process (the entire installation implementation is inside VS Code source code).

You could try to install the VSIX from the "Install from VSIX" command in the Extension Manager by downloading the VSIX for your platform from https://github.com/Microsoft/vscode-mssql/releases/tag/v0.2.0.

**Comment by kburtram** [comment]
I'll close this now since there hasn't been any recent activity on this issue.  If this is still an issue on the latest builds please reactivate so we can investigate.
