### ISSUE TITLE
Cannot copy from results grid if selection contains null

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#596]
Steps to Reproduce:
1. Run a query that will have null values in the resultset 
2. Make a selection in the grid that includes null values

Expected Behavior:
All values are copied to clipboard, including the null values

Actual Behavior:
Nothing is copied to the clipboard. 

Copyable:
![image](https://cloud.githubusercontent.com/assets/24420239/21827598/4425b134-d741-11e6-91d4-d068c5209a9c.png)

Uncopyable:
![image](https://cloud.githubusercontent.com/assets/24420239/21827591/38a13e50-d741-11e6-93d6-671997dbb818.png)

**Comment by coquagli** [comment]
Note that SSMS supports this and simply copies "NULL" to the clipboard.

**Comment by anthonydresser** [comment]
This is controlled here https://github.com/Microsoft/vscode-mssql/blob/dev/src/controllers/QueryRunner.ts#L302 and is because the service passing back undefined or null instead of a string when it is a null value. Simply need to check if a value exists in the cell and insert the string null if it doesn't.

**Comment by benrr101** [comment]
On the other hand, this could be a decent time to fix a mistake in the service layer.. The service layer currently returns `null` for the displayValue of a DbCellValue. Originally, the intention was to add a boolean isNull flag to the DbCellValue (to allow the stylings of the grid to change for null) and then set the displayValue of a null object to "null". However, we didn't do that and here we are. Generating "null" in the service layer would allow us to keep all the localization of cell values in one place in the service layer. But generating "null" in the extension would be an easier solution.

**Comment by kburtram** [comment]
This looks like a regression since the 0.2.0 release.  Let's find out what broke and see if we can fix that.

![capture](https://cloud.githubusercontent.com/assets/599935/21905449/5026652e-d8bc-11e6-9eed-83f4c4c5567a.png)

**Comment by coquagli** [comment]
Looks like `shouldRemoveNewLines()` from [this commit](https://github.com/Microsoft/vscode-mssql/commit/76d85cd57f73e9feb66ed91563a17926b56f44ce) is the culprit. Preparing a fix now.
