### ISSUE TITLE
Support SQLCMD mode

### ISSUE THREAD

**Issue by sidewinder94** [microsoft/vscode-mssql#599]
Would it be possible to implement a SQLCMD mode for executing SQL scripts ?

As of now, the syntax is not recognized by VSCode and the execution fails if using SQLCMD features.

**Comment by kzhui125** [comment]
please support syntax first, thanks
![image](https://user-images.githubusercontent.com/11925432/34284545-bf9c703c-e70d-11e7-808f-1308a4063601.png)

**Comment by estenrye** [comment]
Also would like to see the syntax updated to support SQLCMD
![issue](https://user-images.githubusercontent.com/17356933/36800954-5c1d6b3a-1c76-11e8-9202-899540a0bd88.png)

**Comment by frank687** [comment]
This isnt a full replacement for ssms until sqlcmd mode is supported unfortunately. But great work so far.

**Comment by tlagrone** [comment]
1up

**Comment by Carthorn** [comment]
1up :)

**Comment by lwohlhart** [comment]
1up

**Comment by choo75** [comment]
1up :)

**Comment by datamc-pdetomasi** [comment]
1up

**Comment by verschaevesiebe** [comment]
1up

**Comment by raviktech11** [comment]
1up

**Comment by abist** [comment]
The new version now supports SQLCMD!

**Comment by puruzio** [comment]
Which version supports this? I'm using 1.40.10, October 2019 build but it still says ":setvar" is incorrect syntax.

**Comment by sidewinder94** [comment]
@puruzio There is an "SQLCMD: Off" button that was added in the latest version, if you click on it it will enable the SQLCMD syntax & ability to run. Otherwise, it won't recognize the SQLCMD syntax.

**Comment by puruzio** [comment]
Sorry, where can I find that button? I looked all over but couldn't find it.

**Comment by abist** [comment]
@puruzio You can either access it via the command palette (`Ctrl`/`Cmd` + `Shift` + `P`) then look for `SQLCMD` or it's in the lower most bar when a query editor is opened.

**Comment by puruzio** [comment]
Sorry. Nothing under Ctrl/Cmd+SHift+P shows SQLCMD in its description. I checked in on both Mac OS and Windows versions of VS Code v1.40.0. What am I missing?

**Comment by abist** [comment]
@puruzio What version of the extension are you using? We introduced SQLCMD in version 1.7.0

**Comment by puruzio** [comment]
1.7.0 :(

**Comment by puruzio** [comment]
Never mind. I found it in the lower right corner of the task bar. Thanks!

**Comment by puruzio** [comment]
Just one more question.  VS code still highlights ":setvar" as a syntax error even with `SQLCMD:On`. Is there a solution for that?

It seems to execute and format the code just fine. But the error message is annoying.

**Comment by Zarepheth** [comment]
SQLCMD On/Off is only available while VS Code is connected to a database. Otherwise, it is hidden.

**Comment by datamc-pdetomasi** [comment]
Zarepheth thanks for pointing that out, I have found the SQLCMD option after years of being annoyed by this issue.

Devs Is it possible to enable the SQLCMD mode regardless of the database connection as most of the time I use VSCode to open my repository of files and not to run them in VSCode directly. The syntax highlighting / problems being accurate despite a connection would be wonderful
