### ISSUE TITLE
STATISTICS Keyword formatting 

### ISSUE THREAD

**Issue by Raymondd** [Microsoft/vscode-mssql#601]
MSSQL Extension Version: v0.2.0-alpha.11
VSCode Version: 1.8.0
OS Version: Win10
Steps to Reproduce:

Enter text:
```
SET STATISTICS PROFILE ON
SET STATISTICS XML ON
```
into a .SQL File

Expected: STATISTICS should be formatted as a keyword
Actual: STATISTICS is not formatted as a keyword
![stat](https://cloud.githubusercontent.com/assets/3318689/21867665/023ad4f2-d804-11e6-9bcb-9fb355b42cee.png)

**Comment by kburtram** [comment]
@Raymondd please take a look at this issue.
