### ISSUE TITLE
HOST_NAME() does not work - client app does not provide the workstation name to the server

### ISSUE THREAD

**Issue by PierreRossouw** [microsoft/vscode-mssql#602]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1 (2016-12-19)
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Connect to a SQL Server using vscode-mssql
2. select host_name()
3. Ctrl+Shift+E

What happens:

SQL Server returns an empty string as the client's Host Name

What should happen:

The client should provide the workstation name to the server, and then the server will return that as the Host Name

I'm guessing this just have not been implemented yet, so this might be something for the backlog :)
I've attached a screenshot comparing vscode-mssql to SQL Server Management Studio:

![host_name](https://cloud.githubusercontent.com/assets/14323510/21871077/ef6ad790-d8b3-11e6-902e-a479a00907c3.png)

**Comment by Raymondd** [comment]
This looks like it's an issue with Corefx in .NET Core itself. This issue has already been addressed in Corefx [here](https://github.com/dotnet/corefx/issues/12627) in version 1.2.0. That version is ahead of the one we currently use. We may be able to do a custom upgrade of just SqlClient in Corefx, but I will have to discuss that with the rest of the team. Thanks for letting us know!

**Comment by Raymondd** [comment]
Blocked on Corefx. Waiting on downstream changes.

**Comment by abist** [comment]
This is now fixed.
