### ISSUE TITLE
Transactions for update no handled intutively

### ISSUE THREAD

**Issue by akharsh-tr** [Microsoft/vscode-mssql#603]
- MSSQL Extension Version:0.2.0
- VSCode Version:1.9.0 -insider
- OS Version: Windows 7

Steps to Reproduce:

1.  execute by using ctr-shift-e one by one 
begin tran t 
<update STMT >
commit tran  t
2.Expected transaction handling 
getting following 

"The COMMIT TRANSACTION request has no corresponding BEGIN TRANSACTION."

**Comment by kburtram** [comment]
@akharsh-tr thanks opening this issue.  This extension currently opens a new connection each time a query is executed so transactions don't persist across separate query executions.  This PR should fix this issue https://github.com/Microsoft/sqltoolsservice/pull/176.

**Comment by coquagli** [comment]
Fixed by https://github.com/Microsoft/sqltoolsservice/pull/176
