### ISSUE TITLE
Edit Data v1 API: enable editing on SlickGrid

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#614]
We will need to enable editing in the [slick grid repo](https://github.com/Microsoft/angular2-slickgrid) for the Edit Data scenario. Then we will tag a release and update the dependency in `package.json`. 

Among other things, the changes will involve adding an `@Input()` variable for edit mode, updating the `getOverridableTextEditorClass`, changing the behavior of `_gridData`, setting grid options (`editorFactory`, `editable`, `enableAddRow`), and updating `getColumnEditor`. 

There is an example of a working edit data slickgrid [here](http://mleibman.github.io/SlickGrid/examples/example3-editing.html).

**Comment by benrr101** [comment]
see also #517

**Comment by coquagli** [comment]
Closing as out of scope for VS Code extension.
