### ISSUE TITLE
Trouble with extension

### ISSUE THREAD

**Issue by GhostBasenji** [Microsoft/vscode-mssql#616]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 7

Steps to Reproduce:
1. Install this extension
2. After pressing Ctrl+Shift+P, then type sql and select option SQL Connect or Manage Connection Profiles
3. Appers this message:
3.1. SQL Connect
![2017-01-14 14_58_49-data sql visual studio code](https://cloud.githubusercontent.com/assets/3663725/21954515/89b4d382-da6c-11e6-89a5-256d2c794737.jpg)
3.2. Manage Connection Profiles
![2017-01-14 15_21_22-untitled-1 visual studio code](https://cloud.githubusercontent.com/assets/3663725/21954534/5a3e4e2a-da6d-11e6-993e-cd4df4063b3d.jpg)

**Comment by erickangMSFT** [comment]
Can you check if the Windows 7 pre-reqs are installed. You can find the instruction here https://github.com/Microsoft/vscode-mssql/wiki/windows10-universal-c-runtime-requirement

If this is not the cause, then it will require more investigation.

**Comment by GhostBasenji** [comment]
Sorry to bother you. It is already in my system, because when you try to install the patch, I was reported that has the patch. Occasionally a message appears: "mssql: The platform is not supported", but everything else is the same.
P.S. I'll have to abandon the idea of working with VS Code and will I have to work in SQL Server Management Studio.

**Comment by llali** [comment]
@GhostBasenji is it x64 or x86? The extension doesn't support x86.

**Comment by GhostBasenji** [comment]
And that's what it is. x86.
The problem is solved.

**Comment by llali** [comment]
@GhostBasenji I added support for Win x86 and it's now available in this release: https://github.com/Microsoft/vscode-mssql/releases/tag/v0.2.0-alpha.21
