### ISSUE TITLE
Feature. SQL code formatting

### ISSUE THREAD

**Issue by Yerkon** [Microsoft/vscode-mssql#617]
- MSSQL Extension Version: 0.2.0
- VSCode Version: v 1.8.1
- OS Version: Windows 10. x64

Hi guys! First of all,  Thank you for that great extension. 
Suggestion is will be better in the future to have SQL code formatting. Some extension for SQL Management Studio like ApexSQL refactor has this feature... 
For the initial realization simple formatting is enough(very common), without customization... 

So why I like use this extension with vs code? Because is working smoothly and fast. This is most important 👍

**Comment by kburtram** [comment]
@Yerkon thanks for this suggestion.  We've talked about this feature for awhile.  I'll add to our backlog to consider in future planning.
