### ISSUE TITLE
Feature. Object explorer

### ISSUE THREAD

**Issue by Yerkon** [Microsoft/vscode-mssql#619]
MSSQL Extension Version: 0.2.0
VSCode Version: v 1.8.1
OS Version: Windows 10. x64

Is it possible to do something like Object Explorer in VS Code? I mean like in SQL Management Studio, where we can see list of databases and it's tables, stored procedures... and work with them

**Comment by kevcunnane** [comment]
Thanks for this suggestion. This is captured already in issue #586. I'm going to close this issue as a duplicate and keep tracking the request in the original issue. Please keep the suggestions coming.
