### ISSUE TITLE
Save to JSON unable to save files

### ISSUE THREAD

**Issue by ransagy** [Microsoft/vscode-mssql#620]
- MSSQL Extension Version: 0.2.0 alpha 18 (release with fix #604)
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open an SQL file or create a new one.
2. Connect to a DB.
3. Query some data from the DB.
4. Select some of the cells/rows and click the Save to JSON button.
5. Enter a file name with full path to write to.

Expected:
The file is saved and is opened in the editor.

Actual:
Two feedback messages appear at the top that the file was both saved successfully and that saving it failed. No file is created nor opened in the editor. If a file already exists in that path, it is **deleted**.

The CSV counterpart works well.

**Comment by sharonravindran** [comment]
The save was failing after writing to the file because of an error in Dispose. I've created PR Microsoft.com/sqltoolsservice#216 with a fix for this.
