### ISSUE TITLE
Query hangs and cannot be cancelled when running from a file with no SQL to run

### ISSUE THREAD

**Issue by ransagy** [Microsoft/vscode-mssql#621]
- MSSQL Extension Version: 0.2.0 alpha 18 (with fix #604)
- VSCode Version: 1.8.1
- OS Version: Windows 10 x64

Steps to Reproduce:

1. Open an SQL file or create a new one.
2. Comment out all the content of the file or add just '--' to a newly created file.
3. Execute the query without selecting anything.

I'm pretty sure this works as expected in the preview 0.2.0 release.

Expected:
Nothing happens or the query ends immediately without doing anything.

Actual:
The query continues to execute indefinitely and cannot be cancelled.

**Comment by Raymondd** [comment]
This looks like a regression caused by notification changes between the sqltoolsservice and the extension. PR #615 fixes this issue. [Here](https://github.com/Microsoft/vscode-mssql/tree/fix/queueQueryRunnerHandlers) is the branch if you'd like to try it out. Thanks for the heads up!
