### ISSUE TITLE
Save as with selection - does not completely overwrite file if file already exists

### ISSUE THREAD

**Issue by sharonravindran** [Microsoft/vscode-mssql#623]
MSSQL Extension Version: 0.2.0 alpha 18

Save as JSON/CSV does not completely overwrite file if file already exists.
Save as JSON with selection misses the last column while saving to file.

**Comment by benrr101** [comment]
Thanks for reporting this, I'll get to work on it soon. I'm pretty sure this is because I elected to use File.OpenOrCreate (or something similar) which will opt to just open an existing file instead of create it from scratch.

**Comment by sharonravindran** [comment]
I'm fixed this as part of the other save bug I'm working on.
