### ISSUE TITLE
Update NewQuery command to use the new VS code open document API 

### ISSUE THREAD

**Issue by llali** [microsoft/vscode-mssql#629]
The code for "new query" command in the extension uses the vs code API that gets a valid path to create untitled document. This way the untitled document would have the SQL languages selected.  There's a new API now to do that which doesn't need a path and would work similar to the untitled document (Ctrl + N) 
After the API is released, we need to change our code to use it so the experience for new query would be similar to untitled documents with no language.  

https://github.com/Microsoft/vscode/issues/12283#issuecomment-273857630

**Comment by abist** [comment]
This was updated in the code base. Closing this issue.
