### ISSUE TITLE
Let us copy result-messages

### ISSUE THREAD

**Issue by ferpega** [Microsoft/vscode-mssql#640]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Execute a simple query
2. Try to copy result messages.  

Result messages can be selected, but copy+paste does not run. It always copy from result-data window.

**Comment by kevcunnane** [comment]
Thanks @ferpega for raising this. I'm going to look into this and see if we can fix, but as it's already been raised a #385 I will close this issue and track there since it has more context on the fix needed.

**Comment by kevcunnane** [comment]
@ferpega this fix is checked in - it'll appear in tomorrow's nightly and our next official release. Thanks for raising.
