### ISSUE TITLE
Please add option to output as text

### ISSUE THREAD

**Issue by taranttini** [microsoft/vscode-mssql#642]
Every time I run sp_helptext, the query result has added many blank lines, so I copy the result, the copy has more blank lines between the grid result lines,

 If you add option of result as text, this problem I believe it is solved.

Thanks for attention

**Comment by PierreRossouw** [comment]
I believe the next version of vscode-mssql has a setting for removing the extra newlines when copying from the grid, which should also solve your problem?

.vscode/settings.json

"mssql.copyRemoveNewLine" : true

**Comment by taranttini** [comment]
So thanks,

**Comment by abist** [comment]
Closing this as duplicate of https://github.com/microsoft/vscode-mssql/issues/1030. Please refer to this issue for tracking the feature.
