### ISSUE TITLE
Peek Definition does not work with database names when connected to master

### ISSUE THREAD

**Issue by sanagama** [microsoft/vscode-mssql#643]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:
1.	Launch VS Code and create a new .sql file
2.	Press Ctrl+Shift+C and connect to a server
3.	Don’t specify a database name – this will connect to ‘master’ by default
4.	Type the following query in the editor and execute it:

USE [some-database-in-server]
GO

5.	Right-click on [some-database-in-server] in the editor and choose ‘Peek Definition’

Result: nothing happens
Expected: see the ‘create database’ definition

**Comment by sharonravindran** [comment]
We do not support peek definition for database objects, so this is expected. We support tables, views, stored procedures, functions and user defined types.
