### ISSUE TITLE
Peek Definition does not work with table names when connected to master

### ISSUE THREAD

**Issue by sanagama** [Microsoft/vscode-mssql#644]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1.	Launch VS Code and create a new .sql file
2.	Press Ctrl+Shift+C and connect to a server
3.	Don’t specify a database name – this will connect to ‘master’ by default
4.	Type and execute the following query in the editor:

USE [some-database-in-server]
GO

SELECT * FROM [some-table-in-the-database]
GO
`
5.	Right-click [some-table-in-the-database] in the editor and choose ‘Peek Definition’

Result: nothing happens
Expected: See the create table definition for [some-table-in-the-database] table

**Comment by sharonravindran** [comment]
The fix for this bug was merged to dev.
