### ISSUE TITLE
Change connection database fails sometimes

### ISSUE THREAD

**Issue by llali** [Microsoft/vscode-mssql#645]
When executing two "Use [database]" queries to change the database name sometimes the second query fails to change the database name. The problem is that there's a data reader still open so changing the database name fails. The behavior can be reproduced in test "DatabaseChangesWhenCallingUseDatabase" in the sqltoolsservice. Also one potential problem can be in the code that changes the db name ConnectionService.ChangeConnectionDatabaseContext. This code changes a shared resource but not protected by any lock.

**Comment by coquagli** [comment]
For the case where `OnInfoMessage` is called before the query completes, we can just wait postpone the database change until after the query completes and not allow new queries to be executed until the change is complete. How can we handle the case where `OnInfoMessage` is called after the query completes?
