### ISSUE TITLE
Columns misaligned on OS X 

### ISSUE THREAD

**Issue by mathsalmi** [Microsoft/vscode-mssql#652]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: macOS Sierra 10.12.2 (16C67)

Steps to Reproduce:

1. Run a query with lots of columns (10 or more)
2. See that columns closer to the right side and their headers are misaligned.
![screen shot 2017-01-30 at 13 14 02](https://cloud.githubusercontent.com/assets/1981698/22428511/7aa8d85a-e6ee-11e6-9349-a9333e21aad6.png)

**Comment by kevcunnane** [comment]
Thanks for raising this. We will look into this as we have occasionally seen this ourselves and it is a poor experience.

**Comment by mathsalmi** [comment]
Hmmm interesting thing is when I resize any column everything works as expected. 
Anyway, thanks for the great work =)

![kapture 2017-01-31 at 15 45 58](https://cloud.githubusercontent.com/assets/1981698/22477291/98c415a0-e7cc-11e6-93e8-a9f641ca408b.gif)

**Comment by kevcunnane** [comment]
I'm actually struggling to reproduce this with the sample provided. I have definitely seen this on some occasions, so I'm wondering how to get a reliable repro case. Does this happen every time you run this command? If not, is there anything special / different that causes this?

**Comment by mathsalmi** [comment]
It happens every time and with every query. I could never make it work well 😕 

Is there anything else I can do to help debug this?

**Comment by kevcunnane** [comment]
Well, things to check are whether it happens on our latest alpha release (https://github.com/Microsoft/vscode-mssql/releases/tag/v0.2.0-alpha.26) in case we fixed it while doing a number of related fixes in our codebase. I'll keep trying to reproduce too, I'm struggling to understand why this issue went away for me / is inconsistent while it's reliable for you.

Also: what version of macOS are you using?

**Comment by mathsalmi** [comment]
Great news! I downloaded the recent release of VSCode (1.9.0) and your alpha release (.26) and the problem is gone. I can't confirm what fixed the problem (vscode upgrade or the alpha release) but so far so good!

Thanks for your help!

**Comment by mathsalmi** [comment]
FYI: I uninstalled the alpha release .26 and reinstalled the stable version and it works fine so I guess the problem was caused by vscode 1.8.1.

**Comment by kevcunnane** [comment]
Glad it is fixed. This is quite a strange one but hopefully whatever weirdness caused this (Chromium version, perhaps?) is gone away for good with 1.9.0
