### ISSUE TITLE
Cannot use Visual Studio Code (mssql extension) to connect to Azure SQL Data Warehouse

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode-mssql#667]
_From @kevinvngo on February 2, 2017 0:1_

- VSCode Version: Code 1.8.1 (ee428b0eead68bf0fb99ab5fdc4439be227b6281, 2016-12-19T14:49:23.350Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|mssql|ms-mssql|0.2.0|

---

Steps to Reproduce:

1.  Ctrl + shift + p
2.  Connect to database
3.  Connect to an Azure SQL Data Warehouse instance
     FAILS WITH: ..."Incorrect syntax near 'ANSI_NULLS'. (image attached)

Note: connecting to just the logical server and master works 

![image](https://cloud.githubusercontent.com/assets/15145589/22531717/95d78356-e897-11e6-9340-b8d569de9874.png)

_Copied from original issue: Microsoft/vscode#19700_

**Comment by kevcunnane** [comment]
@mjbvz - this has been fixed and our current daily build https://github.com/Microsoft/vscode-mssql/releases/tag/v0.2.0-alpha.26 has the fix available. If you'd like to test and verify this you can uninstall MSSQL extension, then download the mssql-0.2.0.vsix from https://github.com/Microsoft/vscode-mssql/releases/download/v0.2.0-alpha.26/mssql-0.2.0.vsix and choose "Install from VSIX" in the drop-down menu in the Extensions view to install.  

This fix will be available in our next full update. For now I'm going to close this but please reopen / comment if the fixed drop does not work for you.
