### ISSUE TITLE
Pasted columns into CSV in Excel from Results panel add extra blank column

### ISSUE THREAD

**Issue by kayessaych** [Microsoft/vscode-mssql#668]
- MSSQL Extension Version: 0.2.0
- VSCode Version: 1.8.1
- OS Version: Windows 7 Enterprise - 64-bit  - SP1

Steps to Reproduce:

1.  open new file
2.  switch language to sql
3.  connect to db
4.  run select query
5.  select column from results with cursor
6.  copy
7.  paste to CSV already open in excel (2013)
8.  column pastes correctly but extra blank column overwrites column to the immediate right

If you copy 2 columns only one blank column will end up to the right.  It's always n+1 columns pasted.

This is a minor thing because I can export to a CSV just fine and copy over to my other CSV.  It just adds a couple steps.

Thanks!

**Comment by kevcunnane** [comment]
Thanks for raising this - we will work to reproduce and get back to you.
