### ISSUE TITLE
Tools Service Travis CI build on OSX frequently timing out

### ISSUE THREAD

**Issue by benrr101** [microsoft/vscode-mssql#671]
The last week or so, the Travis CI build for the tools service has been failing because the OSX build has been timing out. This is becoming quite frequent, requiring a retry that often works.

**Comment by Raymondd** [comment]
It might be related to the OSX Emergency maintence/outage they had on Feb 1 and 2. 
https://www.traviscistatus.com/incidents/k79mjcv403c4
