### ISSUE TITLE
Go To Definition/Peek Definition not working on Stored Procedure or View on 0.2.1

### ISSUE THREAD

**Issue by renzska** [Microsoft/vscode-mssql#672]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.0
- OS Version: MacOS Sierra 10.12.3

I'm trying to look at the definition of a stored proc and it's not working.

Steps to Reproduce:

1. Open SQL document
2. Run a Select * from dbo.TABLE query
3. Choose RW connection
4. Run EXEC dbo.sp_customstoredprod
5. Right-click on stored proc and choose Go To Definition or Peek Definition (or F12 or Ctrl-F12).
6. Nothing happens.
7. Do the same thing on a table name and it shows the CREATE TABLE code.

Thanks,

John

**Comment by kevcunnane** [comment]
@sharonravindran can you look into this? In trying to reproduce I created 2 stored procedures (`dbo.P1` and `dbo.sp_customstoredprod`) with the exact same T-SQL definition. Somehow 1 is being found by PeekDefinition and the other is not. We need to improve reliability here and understand why this would fail given the intellisense binding for both works. Note that in my case, `sp_customstoredprod` was being found

**Creation Script**
```
CREATE PROCEDURE dbo.sp_customstoredprod AS
BEGIN
select * from sys.tables
END 
```

**Execution script for Peek Definition**
```
-- Failed to work in PeekDefinition for me
EXEC P1
GO
EXEC dbo.P1
GO
-- Succeeded in PeekDefinition
exec sp_customstoredprod
GO
exec dbo.sp_customstoredprod
```

**Comment by sharonravindran** [comment]
@renzska Can you give us more details on step 3? Are you connecting to a different database? Do you see 'Updating Intellisense' in the status bar below after step 3?

**Comment by Platzer** [comment]
Same problem here! But i only ran in this issue when i change the database context by `use DB_NAME`.

**Comment by abist** [comment]
@kevcunnane Can you still reproduce this? I tried this on Windows as well as MacOS but was unsucessful

**Comment by kevcunnane** [comment]
Let's close and if we run into it again even after the fixes you've done, we can re-open
