### ISSUE TITLE
View Table Definition time out

### ISSUE THREAD

**Issue by afoliaco** [Microsoft/vscode-mssql#680]
- MSSQL Extension Version: 0.02.1
- VSCode Version: 1.9
- OS Version: MACOS Sierra 10.12.3

Steps to Reproduce:

1. Right click on the table view definition
2. Nothing happens 

Logs 

Error - 2:12:15 PM] Request textDocument/definition failed.
  Message: Operation timed out.
  Code: undefined

**Comment by sharonravindran** [comment]
@afoliaco - Was it an Azure DB you were connecting to? Did it time out for other kinds of objects like 'views'?

**Comment by afoliaco** [comment]
Sorry for the late reply, I'm connecting to a server in our network, I'm able to connect with no problem and run SQL with no issue I also check with our DBA and the account is a db owner.

**Comment by sharonravindran** [comment]
@afoliaco - We currently have a 10 second timeout for peek definition. Sometimes the scripting takes longer and the operation times out. Has the timeout been happening frequently? 

We will keep this issue open to track peek definition timeouts.

**Comment by abist** [comment]
@afoliaco We have had newer releases which should have taken care of this problem. Please open a new issue if you still face this problem. I'm going to go ahead and close this issue for now.
