### ISSUE TITLE
Copy results to clipboard does not work

### ISSUE THREAD

**Issue by nilslueders** [Microsoft/vscode-mssql#681]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.0
- OS Version: ubuntu 16.04 LTS

Steps to Reproduce:
1. Execute any query
2. Select any from the results table
3. Press Ctrl+C (or click on "Copy" or click on "Copy with Headers" in the context menu)

Expected behavior: The selected Text was copied to the clipboard

Actually behavior: Nothing was copied to the clipboard. (Also, the current content of the clipboard is still there.)

**Comment by mathsalmi** [comment]
Same happens here.

![vscode](https://cloud.githubusercontent.com/assets/1981698/22689733/6d41ebb2-ed19-11e6-9921-c39569ef9dd8.gif)

**Comment by abist** [comment]
Hey @nilslueders and @mathsalmi, thanks for bringing this to our attention. Can you please verify whether your Linux machine has xclip installed? The copy-paste command needs xclip to work, and it might be possible that it's not installed on your machine. 

You can install it by running "sudo apt-get install xclip". Please let me know if it still doesn't work.

**Comment by mathsalmi** [comment]
Touché! Now it works like a charm. Would it be possible to improve the behavior of the plugin in these cases? I don't know maybe show a required dependency on the console or something.

Thanks for your help!

**Comment by nilslueders** [comment]
Thanks @abist ! Its working now. (I agree with @mathsalmi .)
Also, thank you very much for this absolutely great code editor!

**Comment by abist** [comment]
@mathsalmi @nilslueders Thanks! Will definitely change the behavior of the plugin.

**Comment by mcamou** [comment]
Solved for me too after Googling and landing on this issue. Some sort of error message/popup if `xclip` is not installed would really help.

**Comment by vonmoraes** [comment]
I'm using 
* OS W10 10.0.18362
* SQL Server v18.0
* Code 1.40.0 

**Steps to Reproduce**:

1. Execute any query
2. Select any from the results table
3. Press Ctrl+C (or click on "Copy" or click on "Copy with Headers" in the context menu)

**Expected behavior**: The selected Text was copied to the clipboard

**Actually behavior**: Last thing that was copied is inserted on the clipboard, anything less than results table, so step 3 has any effect at all.

**Comment by abist** [comment]
@vonmoraes Which version of the extension are you using?

**Comment by vonmoraes** [comment]
> @vonmoraes Which version of the extension are you using?

Version: 1.7.0

**Comment by kowalczykwiktor** [comment]
I have a little different problem but related to copy data from RESULTS window. If I using mouse and context menu to copy something from RESULTS, it works well but when I want to use keyboard shortcuts there I can not copy any data from there. On query window it works.

VSCODE: 1.83.1
Extension: v1.21.0

![2023-10-20_01-09-41](https://github.com/microsoft/vscode-mssql/assets/25594629/2440c440-1e30-427f-9059-0093144d1660)

**Comment by marcelogmonteiro** [comment]
The exact same thing happens to me as @kowalczykwiktor. Any updates?
