### ISSUE TITLE
HTML not been scape correctly on Result Grid

### ISSUE THREAD

**Issue by afoliaco** [Microsoft/vscode-mssql#687]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9
- OS Version: macOS Sierra 10.12

Steps to Reproduce:

1. Run a SQL that have html text store in one of the columns
2.The resulting grid does not render correctly 

see file attached. 

![screen shot 2017-02-08 at 11 49 24 am](https://cloud.githubusercontent.com/assets/5281768/22747285/ac848650-edf4-11e6-9fe6-8f923e2e3ead.png)

**Comment by Raymondd** [comment]
This issue is a duplicate of #587. It has already been addressed in https://github.com/Microsoft/vscode-mssql/pull/604. Thanks for letting us know anyway!
