### ISSUE TITLE
Re-use hidden results pane

### ISSUE THREAD

**Issue by Raymondd** [microsoft/vscode-mssql#689]
- MSSQL Extension Version: v0.2.0-alpha.28
- VSCode Version: 1.9.0
- OS Version: All

Detailed guide [here](https://github.com/Microsoft/vscode/issues/20075)
Steps to Reproduce:
1. Run a query
2. Hide a results pane behind your current sql file
3. Run a query again 

Expected: 
The results pane which is already open should come to the foreground and refresh. 

Actual: 
A new results pane is created.

**Comment by Raymondd** [comment]
Blocked by an issue raised to the VSCode Team https://github.com/Microsoft/vscode/issues/20075.

**Comment by abist** [comment]
This is fixed in the new extension with webview results.
