### ISSUE TITLE
With no aliases, grid contains wrong results for expressions

### ISSUE THREAD

**Issue by AaronMBertrand** [Microsoft/vscode-mssql#691]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.0
- OS Version: macOS 10.12.4

Steps to Reproduce:

    SELECT MIN(object_id), MAX(object_id) FROM sys.all_objects;

Actual results:

    2105058535        2105058535

Expected results:

    -1073624922        2105058535

Expected results are obtained with this slightly different query (only difference is aliases on the expressions):

    SELECT mino = MIN(object_id), maxo = MAX(object_id) FROM sys.all_objects;

**Comment by benrr101** [comment]
Thanks for your feedback. So far, I haven't been able to repro this on Windows, but that doesn't mean it isn't valid. I'll give it a shot on OSX and see if it's an OSX-only issue. I'll also give it a shot with a small app that runs a query directly with SqlClient. If the result can be replicated on that, it will likely point to this being a bug in .NET Core's SqlClient implementation.

**Comment by benrr101** [comment]
So I've taken a pretty good look at this and haven't been able to repro it even with the exact parameters you provided. At this point, I'd like to get some more information about your environment to see if we can track down a reliable repro scenario. What version of SQL Server are you connecting that yields this repro? The versions I've tried are SQL Server 2016 RTM and SQL Azure.

In general, our code utilizes int IDs for the columns. This is true from all the way to the bottom of the stack with SqlClient column ordinals to the top of the stack with our grid implementation. Therefore, it's unlikely that the presence of lack of alias would make a difference in the results. But, anything is possible 😃

**Comment by AaronMBertrand** [comment]
In putting together a repro for you, I realized I had both 0.1.3 and 0.2.1 extensions enabled (0.1.3 is an ancient private preview). When I uninstalled that and reloaded, this issue went away, as did another that prevented results grids from re-loading for new executions. Sorry if my mis-config ate up a lot of your time.

**Comment by benrr101** [comment]
Thanks for the clarification -- I'll close this issue for now. But feel free to comment back or open a new one if you experience this again in the future!
