### ISSUE TITLE
Disable escaping for temp table names

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode-mssql#692]
Is it possible to disable escaping for temp table names? For example in query like: select * from #MyTable. #MyTable transformes to [#MyTable].

Addressing this comment here - [Link](https://github.com/Microsoft/sqltoolsservice/pull/191#issuecomment-278622768)

**Comment by kburtram** [comment]
Let's also make sure this isn't impacting table alias identifiers starting with '$' character.
