### ISSUE TITLE
Feature. Connection Color

### ISSUE THREAD

**Issue by hedgehogface** [microsoft/vscode-mssql#703]
Add a custom connection color to show in the status bar.

This may not currently be possible in vscode.

**Comment by kevcunnane** [comment]
Thanks for this suggestion. As you mentioned, I believe this might not be possible in the current VSCode design. but if this changes we can look at how to implement this down the line.

**Comment by abist** [comment]
This is currently not possible in VSCode and doesn't seem like it will be in the near future. Closing this issue for now, feel free to reopen when VSCode updates their API to make this possible.
