### ISSUE TITLE
Grid selection flickers at (0, 0) when selecting a new grid

### ISSUE THREAD

**Issue by coquagli** [microsoft/vscode-mssql#710]
When there are more than 1 grids, there is a slight selection issue when navigating between them. Specially, the (0, 0) cell (0-indexed) is selected `onmousedown` when navigating to a new grid. The desired cell is not navigated to until `onmouseup`. This generally comes across as a "flicker" of cell (0, 0). 

Steps to Reproduce:

1. Run a query with 2 result grids
2. Click a cell in the top grid
3. Hold the mouse down on a cell (not (0, 0)) in the bottom grid. This will select (0, 0): 
![image](https://cloud.githubusercontent.com/assets/24420239/23181756/0af98a2e-f82b-11e6-9664-5e5540bb62ff.png)

4. Release the mouse. This will select the cell where the mouse actually is:
![image](https://cloud.githubusercontent.com/assets/24420239/23181773/1f06ec96-f82b-11e6-9b42-4b05856e9594.png)

This should be fixable by resetting the active cell in `navigateToGrid`. This would require the `angular2-slickgrid` library to expose this functionality. Also note that the `setActive` function in this library calls `this._grid.setActiveCell(0, 1);`, which may be the culprit here.

**Comment by abist** [comment]
Opened issue against angular2-slickgrid here - https://github.com/microsoft/angular2-slickgrid/issues/43
