### ISSUE TITLE
Don't add newlines when copying cells?

### ISSUE THREAD

**Issue by ransagy** [Microsoft/vscode-mssql#715]
A simple feature suggestion that came to really annoy me lately - Either remove or add an option NOT to append newlines when copying cells. 

Maybe it makes more sense when copying whole rows, but i find it very annoying when copying a single value or a few values around from one result to another SQL part and having almost always to remove the newline.

**Comment by kevcunnane** [comment]
This is a valid issue - related to adding an empty column at the end (which is fixed) so this should be a similarly simple fix. We could consider this for 0.3.0 if it's trivial to solve.

**Comment by kevcunnane** [comment]
This is included in the latest candidate release https://github.com/Microsoft/vscode-mssql/releases/tag/v0.3.0.1 if you want to test out.

**Comment by ransagy** [comment]
Yeah, Works great. Thanks!
