### ISSUE TITLE
0.3.0 Release Candidate results grid is broken due to minification

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/vscode-mssql#716]
- MSSQL Extension Version: 0.3.0 RC
- VSCode Version: 1.9.1
- OS Version: Mac & Windows

Steps to Reproduce:

1. Install the RC VSIX
2. Connect to a DB & run a query with results
3. Try to select from the results grid or click the copy as cvs / json buttons

This doesn't work - select and click are broken. It seems this is due to the minified build, since in testing (without minification) all works fine.

**Comment by anthonydresser** [comment]
whats the error that it surfaces?
