### ISSUE TITLE
Formatter removes newline after GO on format document but not format selection

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#721]
**Problem Summary**
Note: this comes from wide world importers sample script 3-wwi-recreate.sql.
- When formatting the selection, this doesn't remove the newline after GO
- When formatting document, this does remove the newline
- I'd expect this to be consistent, and ideally not strip the newline since it's helpful for separating statements and keeping a clean script

MSSQL Extension Version: <0.3.0>
VSCode Version: <1.9.0>
OS Version:
**Formatter Settings**
```
{
    "mssql.format.alignColumnDefinitionsInColumns": true,
    "mssql.format.keywordCasing": "lowercase",
    "mssql.format.datatypeCasing": "uppercase",
    "mssql.format.placeSelectStatementReferencesOnNewLine": true
}
```

**Input Text** - place unformatted SQL below

```
USE WideWorldImporters;
GO
 
ALTER DATABASE CURRENT COLLATE Latin1_General_100_CI_AS;
GO
 
ALTER DATABASE CURRENT SET RECOVERY SIMPLE;
GO
 
ALTER DATABASE CURRENT SET AUTO_UPDATE_STATISTICS_ASYNC ON;
GO
```

**Actual Output** - place formatted SQL (that doesn't work as expected) below
```
use WideWorldImporters;
go
alter database current collate Latin1_General_100_CI_AS;
go
alter database current set RECOVERY SIMPLE;
go
alter database current set AUTO_UPDATE_STATISTICS_ASYNC on;
go
```

**Expected Output** - place formatted SQL as you'd expect it to look below
```
use WideWorldImporters;
go

alter database current collate Latin1_General_100_CI_AS;
go

alter database current set RECOVERY SIMPLE;
go

alter database current set AUTO_UPDATE_STATISTICS_ASYNC on;
go
```

**Comment by renzska** [comment]
Any update on this? With autoformat on save set (used by other file extensions), this removes all empty lines in my .sql files every time I save the document. I'd prefer to not have to disable format on save.

**Comment by kevcunnane** [comment]
@renzska - no update yet. I plan to do another set of Formatter fixes later this month. However this is an area where we are encouraging users to get involved and help fix if they're willing. So if you (or anyone else) is interested, I'd be happy to help get people started on how to track this kind of issue down. It's likely in this case it's in the SqlBatchFormatter, so preservation or the newline would be important there.

**Comment by kevcunnane** [comment]
@renzska actually - you inspired me to take a quick look and this seems an extremely easy fix. I have a PR out for this now (see https://github.com/Microsoft/sqltoolsservice/pull/282). If all goes well it'll be available in a daily alpha build within the next few days. 
On a side note, I'm kicking myself for not using this as part of a demo video on contributing to the project. This one was really, really easy and the one I chose was harder. Oh well...

**Comment by kevcunnane** [comment]
This is now checked in. I'm closing this out, and it'll be in daily builds probably by Monday.

**Comment by renzska** [comment]
Awesome. Thanks!
