### ISSUE TITLE
GO <n> should run the batch <n> times, just like SSMS

### ISSUE THREAD

**Issue by AaronMBertrand** [microsoft/vscode-mssql#724]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. 
    SELECT 1;
    GO 5

GO is a batch separator but in SSMS also allows an integer coefficient that tells the client to run the preceding batch that many times. This is very handy especially for populating sample data for demos or to write loops without the scaffolding. Behavior should be the same as SSMS. Instead, you get an error message.

**Comment by kevcunnane** [comment]
We should take this improvement to be consistent with SSMS

**Comment by abist** [comment]
This is fixed.
