### ISSUE TITLE
# should not syntax highlight as a comment when file type is SQL

### ISSUE THREAD

**Issue by AaronMBertrand** [Microsoft/vscode-mssql#725]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.9.1
- OS Version: macOS 10.12.4

Steps to Reproduce:

1. CREATE TABLE #x(i int);

Everything after the # is green. This is a valid name for a #temp table and shouldn't be color coded like a comment.
<img width="585" alt="screen shot 2017-02-24 at 10 31 13 pm" src="https://cloud.githubusercontent.com/assets/22244117/23327854/df480b6c-fae1-11e6-89c0-eacb53321665.png">

**Comment by kevcunnane** [comment]
@AaronMBertrand we'll be releasing 0.3.0 soon and believe this should be fixed in that release. Please test once we have this ready to go and let us know if this resolves the issue. We'll also test this during a testing sweep this week. Thanks.

**Comment by kevcunnane** [comment]
@justindoeswork glad to hear it! I'll close this out.
