### ISSUE TITLE
Peek Definition fails when carat is at the left / middle of a name instead of at the end

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#741]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.9.1
- OS Version: macOS

Steps to Reproduce:

1. Create a Table T1 in the database, and type a query to select from it
```
-- 
select * from sys.databases
GO
-- 
select * from sys.tables
GO

CREATE TABLE T2 (C1 INT NOT NULL)
GO
select * from dbo.T1

GO

```
2. Move the carat to anywhere other than the right of the statement (e.g. anywhere in `dbo.`, Between `T` and `1`, and right-click then choose `Peek Definition`

Expected:
- Peek works
Actual:
- Peek fails
- If you put the carat to the right (e.g. after `T1`) it works OK.
- For longer terms, e.g. `sys.tables`, it works anywhere after `a`. This seems to hint this is an indexing error, likely we're off by 1 and missing something.

**Comment by sharonravindran** [comment]
I think this was fixed by @abist.
