### ISSUE TITLE
Clicking on connection in status bar doesn't bring up USE DB menu on 1st try

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/vscode-mssql#742]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.9.1
- OS Version: mac OS

Steps to Reproduce:

1. Open a .SQL file and execute a comment, e.g. `select * from sys.databases`
2. Click on the connection name in the status bar, e.g. `localhost : master : sa`

Expected:
- USE Database command executed, and a list of DBs is displayed

Actual:
- Most of the time, no list is shown and the context seems to switch back to the results view (the connection name, filename and other info in the status bar disappears).

Note that this is not a 100% reliable repro, but it seems like there's an issue here that we're not handling well.

**Comment by abist** [comment]
This issue is now fixed.
