### ISSUE TITLE
Release notes page doesn't display correctly

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#747]
- MSSQL Extension Version: 0.2.0+
- VSCode Version: 1.10
- OS Version: Ubuntu 16.04 and Windows 10

Steps to Reproduce:

1. Install vscode-mssql and click view release

Expected: Release notes is displayed

Actual: Release notes shows up as blank page (show below)

Note: This appears to be related to VS Code 1.10 upgrade since it also impacts 0.2.0 extension

![release notes](https://cloud.githubusercontent.com/assets/599935/23482372/bac9a250-fe83-11e6-88bc-839ba32b185c.png)

**Comment by kevcunnane** [comment]
Fixed in master by #750
