### ISSUE TITLE
Results window is blank, debug info says 404 for /dist/js/main.js

### ISSUE THREAD

**Issue by rossipedia** [Microsoft/vscode-mssql#754]
- MSSQL Extension Version: 0.2.1
- VSCode Version: 1.10.0
- OS Version: Windows 10.0.14393

Steps to Reproduce:

1. Set `"mssql.logDebugInfo": true` in settings.
2. Toggle developer tools (Help -> Toggle Developer Tools)
3. Switch to Console Tab
4. Create connection profile to localhost
5. Execute query

![image](https://cloud.githubusercontent.com/assets/96213/23488524/67b815ac-feaa-11e6-852e-c1a7dcdc8fd6.png)

I have removed my `%USERPROFILE%\.vscode` folder, as well as everything in `%APPDATA%\Code`, then reinstalled just the `mssql` extension and still got the same result.

**Comment by kevcunnane** [comment]
@rossipedia thanks for raising this. VSCode is pushing a hotfix for this as we speak - see https://github.com/Microsoft/vscode/issues/21661. Expect a 1.10.1 release shortly. Once we have verified that the fix they're rolling out resolves this, we'll close this issue.

**Comment by kevcunnane** [comment]
I've verified this is fixed in VSCode release 1.10.1. If you update your version, this will be resolved. Thanks again for raising this, and apologies for the trouble here.

**Comment by rossipedia** [comment]
Awesome, thanks!
