### ISSUE TITLE
Release Date Change Log

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode-mssql#760]
we already have 2017 ;)

**Comment by con-ssc** [comment]
![image](https://cloud.githubusercontent.com/assets/8189808/23543795/27c8407a-fff4-11e6-8c3e-ee932a01a93b.png)

**Comment by kevcunnane** [comment]
Nice catch! This one highlights the perils of copy & pasting previous release notes to bootstrap the next release. I've fixed in Master, and since we now link directly to the weblink, this should now look correct.
