### ISSUE TITLE
New MS SQL Query: untitled file should not have an associated path

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode-mssql#762]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10.1
- OS Version: macOS

Steps to Reproduce:

1. new MS SQL query
2. type something
3. close the editor

=> the user is not prompted for a file location because the untitled file has a file location in temp:

![image](https://cloud.githubusercontent.com/assets/900690/23584815/c16701ac-016c-11e7-85ac-612353de50a8.png)

=> instead, the untitled file should ask the user for a file location

This should work fine if you use the API `openTextDocument(options?: { language: string; })`

//cc @llali

**Comment by llali** [comment]
@bpasero I tried to use the new API in mssql extension but I don't see the new method signature in vscode npm module 1.0.5 for compile time. Should I manually fix it?

**Comment by bpasero** [comment]
@llali [How can I use API from my extension that was introduced in a newer release of VS Code?](http://code.visualstudio.com/docs/extensions/debugging-extensions#_common-questions)

**Comment by llali** [comment]
Thanks @bpasero 
Fixed in #766
