### ISSUE TITLE
Intelisense doesn't regconize NVARCHAR

### ISSUE THREAD

**Issue by ernesth65** [Microsoft/vscode-mssql#764]
- MSSQL Extension Version:0.30
- VSCode Version:1.10.
1
- OS Version:WIN 10

Steps to Reproduce:

1.Type NVARCHAR
2.

**Comment by kburtram** [comment]
@ernesth65 thanks for opening this issue.  I've sent a PR with a fix that will be in the next release https://github.com/Microsoft/sqltoolsservice/pull/272.

**Comment by kburtram** [comment]
This should be fixed in the dogfood builds.  We have an upcoming release in the next week or two that will contain this fix.
