### ISSUE TITLE
UTF-16LE w/o BOM CSV

### ISSUE THREAD

**Issue by benrr101** [Microsoft/vscode-mssql#774]
Exporting query results as CSV encodes as UTF-8 which is a bad choice. We should try to use UTF-16LE w/o BOM to maximize compatibility with both Unicode columns in SQL Server and with Excel on different OSs. Issue originally raised via https://github.com/Microsoft/vscode-mssql/issues/739

**Comment by benrr101** [comment]
Can't move to UTF-16LE w/o BOM because VS Code doesn't support opening files with this encoding. We could use UTF-16LE w/BOM but this doesn't open properly in Excel (all columns are in a single column).

I've raised an issue with VS Code team at https://github.com/Microsoft/vscode/issues/22564

**Comment by rmunn** [comment]
There may be good news on the UTF-8 front. Dan Battagin, from the Microsoft Excel team, wrote: "... we’ve completed our work on this feature and Excel will support a new CSV format using UTF-8 encoding.

This fix still needs to make it through our release pipeline, but you should see it as an option once you have a build equal to or later than 16.0.7466.2023."

Source: https://excel.uservoice.com/forums/304921-excel-for-windows-desktop-application/suggestions/10006149-support-saving-csv-in-utf-8-encoding

So it may be possible to keep the current UTF-8 export as the default, and allow UTF-16 for those who are stuck with older versions of Excel. I'd *strongly* suggest producing a BOM on every UTF-16 file, though, for the reasons I listed in https://github.com/Microsoft/vscode/issues/22564.

**Comment by benrr101** [comment]
It seems absolutely bizarre to me that UTF-8 isn't properly supported for opening CSVs in Excel. But I digress.

After discussing with @sharonravindran I think the approach we want to take for exporting CSVs is thus:
* Support for exporting to Excel XLSX file is currently going through PR (https://github.com/Microsoft/sqltoolsservice/pull/279)
* We'll stick with the default of exporting CSVs as UTF-8 for now (which should still work in older Excel via import and will work in newer Excel by default)
* We want to expand our config options for exporting CSVs to allow users to pick separator (tabs, commas, whatever) and encoding (UTF-8, ASCII, UTF-16, etc). This will be a backlog item for now, but it should let users "pick their poison" for how to export the CSV. @rmunn, if you're interested, we're always open to PRs for such features 😄 

Since this exact feature isn't happening I'm going to close the issue and open a new one for adding config for exporting CSVs.
