### ISSUE TITLE
sqlListTablesAndViews - Invalid object name 'information_schema.tables'

### ISSUE THREAD

**Issue by need47** [Microsoft/vscode-mssql#775]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10.1 (insider)
- OS Version: WIN7 64bit

Steps to Reproduce:

just run the code snippet: sqlListTablesAndViews, give you the following query:

-- Get a list of tables and views in the current database
SELECT table_catalog [database], table_schema [schema], table_name name, table_type type
FROM information_schema.tables
GO

I think the problem is that 'information_schema.tables' has to be uppercase. My SQL Server version is 2014.

**Comment by abist** [comment]
Hey @need47, I think the problem is indeed information_schema not being uppercase, More information [here](http://stackoverflow.com/questions/6023672/invalid-object-name-information-schema-columns-in-sql-server). 

If this problem still occurs, please let us know.
