### ISSUE TITLE
Idea: Allow Azure Portal to provide formatted profile for mssql to connect to Azure SQL

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-mssql#786]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10.2
- OS Version: osx.10.11-x64

In the azure portal, there is a provision to easily copy paste various connection strings for an Azure SQL database;

![image](https://cloud.githubusercontent.com/assets/5007120/24103648/4c3d2e56-0d56-11e7-98ce-2ff50dedf3cc.png)

It would be great if there was another tab that formatted the connection for the mssq connection profile so you don't have to go through filling out the details of a connection. Then you could copy/paste into settings.json or better yet if there was a way to import it so that it gets into settings correctly.

 "mssql.connections": [
        {
            "authenticationType": "SqlLogin",
            "server": "blahblah.database.windows.net",
            "database": "AdventureWorksSample",
            "user": "myname",
            "password": "",
            "savePassword": true,  <--maybe this would be false??
            "profileName": "AzureAWSample"
        }
    ]

**Comment by kevcunnane** [comment]
This is a good idea, though I'd pivot it slightly - we should accept standard connection strings from the most popular languages (ADO.Net, Java, Node.js) in our settings, and make it easy to pass these in during profile creation. We should also be more tolerant / add an option to save the connection data even if connection failed, so the user can try again. this would help in cases where the password is wrong but everything else is right.
We'll see where this fits in our backlog - we'd definitely like to have this feature, it's a matter of when we can do this. It's also a good public contribution candidate

**Comment by julielerman** [comment]
That sounds great. Also I like being able to save even if the connection failed. Here's what I had originally written in gitter about this:
 I had a heck of a time because I couldn't copy paste the 4 bits needed and then when I typed in the password incorrectly i had to start again and it wouldn't add it to the profiles if it wasn't able to connect.
The reason I couldn't copy/paste is because once I left the IDE to copy from somewhere else, the prompts went away. That doesn't seem like something you could control though.

**Comment by kburtram** [comment]
@MattIrv please look at this one next and let me know if there's any questions.

**Comment by kburtram** [comment]
@kevcunnane I'm moving this out of the GA milestone since it doesn't look like it will completed in time.  If it does land in a completed state in time I'll add the task back to the milestone.

**Comment by MattIrv** [comment]
With the merge of #861, adding profiles using a connection string is now supported. Specifically, you can give an ADO.NET connection string during profile creation at the server prompt.

Unfortunately it wasn't in time for the GA release, but you can install the private build at https://github.com/Microsoft/vscode-mssql/releases/tag/v1.0.0-alpha.5 if you want to try it out.

I'll go ahead and close this issue now, though feedback on the feature either here or via new issues would be appreciated.
