### ISSUE TITLE
New Setting: allow new tabs to auto select sql lang and connect

### ISSUE THREAD

**Issue by horvay** [Microsoft/vscode-mssql#788]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10.2
- OS Version: Windows 10

Steps to Reproduce:

1. Connect to a DB in an existing tab
2. Open a new tab
3. One has to change the language, reconnect, and reselect their DB.

It would be nice if there was a setting to allow new tabs (control+n) to automatically select SQL as the language and connect to the same server/DB.

**Comment by kevcunnane** [comment]
@horvay thanks for raising this. We have a "New Query" command that will open a new tab registered as a .sql file, which solves the first part of your issue. However, it doesn't currently open a ne connection based on the connection in the currently active tab. That's a good suggestion that would bring this in line with SSMS behavior. We'll keep this open on the backlog to update the New Query action to have this behavior.

**Comment by horvay** [comment]
I see it now. I added:
{ "key": "ctrl+n",         "command": "extension.newQuery",
                                     "when": "editorTextFocus && editorLangId == 'sql'" }

to my keybindings. Originally when I looked for this, I searched the default keybindings and didn't find anything. So I just guessed/figured extension.newQuery would work and it does.

**Comment by kevcunnane** [comment]
Closing as the question is answered / this is now supported
