### ISSUE TITLE
Unable to provide null password ("!! Password is required.")

### ISSUE THREAD

**Issue by Mythikos** [Microsoft/vscode-mssql#802]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.10
- OS Version: Windows 10 

The password is a required field when attempting to set up a new connection profile. I have a local database for testing where I didn't actually set a password for the master account. I realize there are ways around this (setting a password, using windows integration) but I wanted to mention it seeing there could be instances where the password may need to be null.

**Comment by buzzzzer** [comment]
#363

**Comment by kburtram** [comment]
@Mythikos I'll close this issue and we can track through the duplicate issue https://github.com/Microsoft/vscode-mssql/issues/363.  Thanks for reporting the problem.
