### ISSUE TITLE
Installing SQLToolService fails behind firewall

### ISSUE THREAD

**Issue by ssmehaffie** [microsoft/vscode-mssql#805]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.11.1
- OS Version: Windows 7

Steps to Reproduce:

1. The extension tried to download the sqltoolservice and fails when installing behing a firewall.
2. I had to download the zip manuall and uncompress it in the "C:\Users\{userID}\.vscode\extensions\ms-mssql.mssql-0.3.0\sqltoolsservice\0.3.0.5\Windows" direcotry,  Untill I did that everytime I used the extesion it would try to download it and it would fail.
3. Next time it opens up it shows option to view "What has changed"

**Comment by kburtram** [comment]
@llali could you please follow-up with @smehaffie to get repro sets?  Is it possible this is related to the proxy port issue you fixes a few weeks ago?

**Comment by llali** [comment]
@smehaffie I fixed some bug related to proxy settings in this release: https://github.com/Microsoft/vscode-mssql/releases/tag/v0.3.0-alpha.17

Can you please give it a try and let me know if you're still seeing the issue?
Thanks

**Comment by smehaffie** [comment]
Still cannot download the SQLTools.  Had to download manually and copy to extension directory.

[cid:image001.png@01D2BC82.14D4DAB0]



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by llali** [comment]
@smehaffie can you please let me know what error you're getting?

**Comment by smehaffie** [comment]
See three pictures attached to the original email.

PC Resources,  LLC
S. Shawn Mehaffie
________________________________

**Comment by llali** [comment]
@smehaffie Can you please attach the image here? I had problem loading the image in my Email. Thanks
