### ISSUE TITLE
Is it possible to work with Access Db?

### ISSUE THREAD

**Issue by makcakaya** [Microsoft/vscode-mssql#808]
Can we use this extension to work with Access 2016? 

I tried to do it but could not provide a valid connection string configuration:

`"mssql.connections": [
        {
            "profileName": "access",
            "server": "localhost",
            "database": "C:\\Users\\Pc Lab\\Documents\\Mert\\Yönetim Bilgi Sistemleri\\ders_ornek.accdb",
            "authenticationType": "Integrated",
            "password": ""
        }`

**Comment by kevcunnane** [comment]
@makcakaya that's not supported right now. Currently we only support SQL Server instances - all SQL Server Express or greater instances will work. Other database types (Access, SQLite, PostGre) are not supported right now.
