### ISSUE TITLE
When I run a query with lots of result outputs it seems to hang.

### ISSUE THREAD

**Issue by Matticusau** [microsoft/vscode-mssql#812]
When I run a query / script that produces a large number of result sets, such a cursor over a table and running a stored procedure (which returns 1 row) for each row in the source table the query results window seems to hang. I cannot run any other queries until I close that result window and all other result windows, then everything starts running as expected again. I also know that the original query completes as I can query the source row count and destination table count and they equal expected results.

- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.11.1
- OS Version: Win 10 (10.0.14393)

Steps to Reproduce:

For the record while running this I could see the status bar ticking over with the fact it was still executing but when i ran my actual code it seemed to hang and i had to run a query externally against the physical dest table to verify it had completed, maybe it has something to do with the physical vs temporary table.

1. Create a table
CREATE TABLE #testtbl
(
    id INT IDENTITY PRIMARY KEY
    , testdata varchar(100)
)

2. Run a cursor over that and perform an insert and output the inserted data.  
DECLARE @count INT = 0
WHILE (@count <= 1000)
BEGIN
    INSERT INTO #testtbl (testdata) VALUES ('Testing for github issue')
    SELECT * FROM #testtbl WHERE id = @@IDENTITY
END

3. Clean up
DROP TABLE #testtbl

**Comment by abist** [comment]
@Matticusau Please try the latest version of the extension and let us know if you still face the same problem. I'm going to go ahead and close this issue; feel free to reopen it if you find yourself running into the same problem in the latest version of the extension (1.9).
