### ISSUE TITLE
Line selection does not work if there are 2 or more newlines at the end of the document

### ISSUE THREAD

**Issue by coquagli** [Microsoft/vscode-mssql#821]
Steps to Reproduce:

1. Open a .sql file
2. Enter a query that has exactly one newline at the end of the document, e.g.:
```
select * from sys.databases

```
3. Run the query
4. Select the "Line 1" link from the message window - the region is highlighted: 
![image](https://cloud.githubusercontent.com/assets/24420239/25200806/7c190152-2504-11e7-9986-469b8e494802.png)
5. Enter 1 or more newlines at the end of the document, e.g.:
```
select * from sys.databases


```
6. Run the query
7. Select the "Line 1" link from the message window

****Expected:****
![image](https://cloud.githubusercontent.com/assets/24420239/25200855/b3d11300-2504-11e7-82bf-449854bc4547.png)

**Actual:**
![image](https://cloud.githubusercontent.com/assets/24420239/25200833/9eb5e8d8-2504-11e7-9c9a-ab9b25413644.png)

**Comment by abist** [comment]
It's a bug in the DacFx BatchParserWrapper

**Comment by abist** [comment]
This is fixed now :)
