### ISSUE TITLE
Query execution indicator has strange behavior when used with WAITFOR DELAY

### ISSUE THREAD

**Issue by coquagli** [microsoft/vscode-mssql#827]
![image](https://cloud.githubusercontent.com/assets/24420239/25256027/d1a3c89e-25e2-11e7-8e3c-757913ff4a7e.png)

When I use `WAITFOR DELAY`, I'm seeing some strange behavior with the spinner (the thing that switches between `/`, `-`, `\`, and `|` to indicate that a query is in progress). I'm not sure if the `WAITFOR DELAY` is the cause of the problem or is simply exposing it by keeping it on screen for longer. 

Specifically, the spinner will not change characters (e.g. it never changes from `/`) once the `WAITFOR DELAY` is hit. Then for all subsequent queries on the same URI (even after the query is cancelled), the spinner only displays that same character. In some cases, for subsequent queries the spinner and the `Executing query` message don't even appear. 

I don't have a great repro for this, but running the following and cancelling it a few times seems to usually do the trick:

```
select * from sys.databases
select * from sys.tables
WAITFOR DELAY '00:50:05';
```

This isn't a huge issue, but the lack of indication that a query is running will be an issue for folks with long-running queries.

**Comment by abist** [comment]
Closing as it's fixed now.
