### ISSUE TITLE
Update version to 1.0 in service and extension

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#828]
For our GA release, we need to update the versions:
- Update in the build.sh scripts that produce our releases
- Update in our package.json

**Comment by kburtram** [comment]
@kevcunnane there's also somewhere that we tell VS Code that the release is preview or GA that we need to update.  Can't recall if this is in the marketplace or in one of the settings files.

**Comment by kevcunnane** [comment]
I think it's in the package.json
