### ISSUE TITLE
Error running sql in a new unsaved document with language set to SQL.

### ISSUE THREAD

**Issue by hookem** [Microsoft/vscode-mssql#831]
Get error that no code language is defined when trying to run a new unsaved sql file where I have defined the language as SQL. Used to be able to do this in previous version. After saving the file with .sql extension it works as expected.

- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.15063
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.7.0|
|code-runner|formulahendry|0.6.16|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.3|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|0.3.0|
|PowerShell|ms-vscode|0.12.2|
|Perl6Snippets|sergot|0.0.5|;

---

![2017-04-21_16-13-08](https://cloud.githubusercontent.com/assets/1236567/25296600/b525358c-26ae-11e7-9faf-96cc31891db4.gif)

Steps to Reproduce:

See gif for video

1. Open vscode
2. Set language of new untitled file to SQL (ctrl+k, m and select sql)
3. enter valid sql statement
4. run sql statement.

**Comment by kevcunnane** [comment]
@hookem we don't provide a `Run Code` action. That's likely from your `code-runner` extension. The `Execute Query` action (Ctrl+Shift+E) is what you need to run a query. I see it at the bottom of the context menu in your gif.

**Comment by kevcunnane** [comment]
Closing this out as we haven't heard back about this.
