### ISSUE TITLE
Setting mssql.intelliSense.lowerCaseSuggestions to true no longer works

### ISSUE THREAD

**Issue by NitroGhost** [Microsoft/vscode-mssql#835]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.11.2
- OS Version: Windows 10 Professional

Steps to Reproduce:

1. open VS code
2. edit/create SQL file and type a keyword
3. mindlessly hit enter
4. cry once you realise it's in uppercase and not your beloved lowercase

![code_2017-04-24_16-35-48](https://cloud.githubusercontent.com/assets/3674467/25345346/c290b60a-290c-11e7-97bc-7ced1cc4311f.png)

![code_2017-04-24_16-36-08](https://cloud.githubusercontent.com/assets/3674467/25345359/cb8698b0-290c-11e7-8b23-66e40899d03c.png)

**Comment by MattIrv** [comment]
I was able to reproduce this on Windows 10 and on Mac with mssql 0.3.0. It looks like all the intellisense-related settings shown at [https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql](https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql) now display "Unknown configuration setting" when trying to set them.
