### ISSUE TITLE
Text always black in Messages output

### ISSUE THREAD

**Issue by rudiv** [Microsoft/vscode-mssql#847]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.12.0-insider, Shell 1.6.6, Renderer 56.0.2924.87, Node 7.4.0
- OS Version: Win10 1607 (14393.1066)

Steps to Reproduce:
1. Switch to Dark or Dark+ theme
2. Execute Query
3. View 'Messages' output

Result:
![image](https://cloud.githubusercontent.com/assets/976685/25499509/9d6cee38-2b83-11e7-9073-fa3e31d75210.png)

Issue persists throughout reload of VS Code Insiders. Note that I cannot reproduce this in VS Code 1.11.2.

**Comment by kburtram** [comment]
@kevcunnane this looks like a pretty bad regression to the messages output window.  We need to investigate before the next release.
