### ISSUE TITLE
Some UI text is not properly localized

### ISSUE THREAD

**Issue by kburtram** [Microsoft/vscode-mssql#855]
The following UI text is not properly localized.

Peek-Definition
Execute Query
Messages
Total Execution time
Save as Json, CSV …
Code snippet descriptions “Select Rows from a table or a view”

**Comment by Monasr** [comment]
Which language is this issue logged for?

**Comment by kburtram** [comment]
@Monasr this is a generic issue for all languages related to the way these components are built with hardcoded strings in the HTML templates.

**Comment by Monasr** [comment]
Thanks Karl, are these already exposed to localization? for some reason I can 't seem to find the strings in the SR.XLF file that we localize
