### ISSUE TITLE
Results Save as JSON match column type

### ISSUE THREAD

**Issue by MPVogelPaint** [microsoft/vscode-mssql#858]
- MSSQL Extension Version: 0.3.0
- VSCode Version: 1.11.2
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. Make a query:
```sql
CREATE TABLE #Temp(
  ID int identity(1,1),
  Name varchar(50)
)

INSERT INTO #Temp
(Name)
VALUES
('Robb'),
('Sansa'),
('Bran'),
('Arya')

SELECT * FROM #Temp
```

2. Run the query
3. In the results window click "Save as JSON"
4. The JSON file is:
```json
[
  {
    "ID": "1",
    "Name": "Robb"
  },
  {
    "ID": "2",
    "Name": "Sansa"
  },
  {
    "ID": "3",
    "Name": "Bran"
  },
  {
    "ID": "4",
    "Name": "Arya"
  }
]
```
But the ID values shouldn't be wrapped in quotes since they're not string values.

**Comment by eashi** [comment]
I believe this is not a "vscode-mssql" issue , rather it's a "sqltoolsservice" issue. I think this is fixed here:

[https://github.com/Microsoft/sqltoolsservice/pull/691](https://github.com/Microsoft/sqltoolsservice/pull/691)

**Comment by kburtram** [comment]
This appears fixed in latest release.  The current output from repro scenario is below without quotes around numeric fields.

```JSON
[
  {
    "ID": 1,
    "Name": "Robb"
  },
  {
    "ID": 2,
    "Name": "Sansa"
  },
  {
    "ID": 3,
    "Name": "Bran"
  },
  {
    "ID": 4,
    "Name": "Arya"
  }
]
```
