### ISSUE TITLE
Opening link for Line number in results opens a new window

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode-mssql#859]
This occurs in the VSCode insiders build. Clicking on the link for line numbers in query result opens the highlighted lines in a new window

**Comment by kburtram** [comment]
I've opened an issue in VS Code repo to track this https://github.com/Microsoft/vscode/issues/25801

**Comment by kburtram** [comment]
It looks like this was fixed on the VS Code side so I'll close this issue.
