### ISSUE TITLE
Switching tabs in result pane now loads slower

### ISSUE THREAD

**Issue by abist** [Microsoft/vscode-mssql#860]
Steps to Reproduce:

1. Run any query. Open another tab in the results window on the right.
2. Switch tabs in the results window. Rendering is slow now.

**Comment by kburtram** [comment]
@abist I am not observing any noticeable slowdown rendering the results page with 0.3.0 vs. 1.0.0 on the latest stable and insiders builds.  Could you please collect profiling data for the two versions of the extension on the two available VS Code builds to confirm if there is an actual regression.

**Comment by coquagli** [comment]
After investigating this further, I don't think this is a regression. I am seeing equally poor performance (~2-
3 seconds) from both 0.3.0 and 1.0.0. I don't know why this is performing extra slow on my machine, but it appears to not be an issue specific to 1.0.0.

**Comment by abist** [comment]
@coquagli I thought the same. I'll close the issue for now, but if you find the reason why it was that slow, let us know!

**Comment by art-ist** [comment]
+1
I can't tell why, but I experience the same poor performance up to version 1.4.0. 
I tested on a Windows 10 box as well as Linux (Ubuntu 16.04, 18.04) and with different SQL Servers from 12 to 2016 SP1. The effect shows when executing the query as well as when I tab away and then back to a previously populated result grid.
