### ISSUE TITLE
Save as JSON opens file in Plain Text mode when no extension provided

### ISSUE THREAD

**Issue by coquagli** [microsoft/vscode-mssql#863]
Note that I am using the current Insiders build:

![image](https://cloud.githubusercontent.com/assets/24420239/25678147/95cf3842-2ffd-11e7-8eb0-8109e03444dc.png)

Steps to Reproduce:

1. Run a query 
2. Click the "Save as JSON" button
3. Type a filename

**Expected:** The new file's mode is JSON, which highlights the syntax properly. 
![image](https://cloud.githubusercontent.com/assets/24420239/25677560/4ecdb0f6-2ffb-11e7-801b-a1de2cb3088c.png)

**Actual:** The new file's mode is Plain Text. 
![image](https://cloud.githubusercontent.com/assets/24420239/25677591/6c172d40-2ffb-11e7-9667-51d5251840a4.png)

**Comment by kburtram** [comment]
@coquagli I wasn't able to reproduce this.  Are you typing a file name with a JSON file extension, or some other extension?  Are there any other repro steps I need to follow?

**Comment by coquagli** [comment]
@kburtram I am using the latest Insiders build, which might be the cause:

![image](https://cloud.githubusercontent.com/assets/24420239/25678165/a3c1c17c-2ffd-11e7-996c-6d5ea0cae2f4.png)

**Comment by kburtram** [comment]
@coquagli I tried to repro on both today's insiders build and the stable build on Linux and Mac with repro.  I'll check on Windows with today's insiders build.

**Comment by coquagli** [comment]
@kburtram With repro or without repro?

It looks like adding `.json` sets the mode correctly, while adding no extension or the wrong extension sets the mode incorrectly. This may just be by design, rather than a bug.

**Comment by kburtram** [comment]
@coquagli sorry, I meant "without repro" :)  When I didn't provide an extension the file opened as plain text, but when I provided a .json extension the file was correctly opened in JSON mode.  

I'm not sure if there was a change here, since I typically provide a .json extension when testing this feature.  Do you know if this is a behavior change?

**Comment by kburtram** [comment]
...removed "needs repro" tag and updated title to better describe the observed behavior.

**Comment by benrr101** [comment]
I think whether this is considered a bug or by-design is up for debate. The tools service will write the file out to the name provided as-is, which makes logical sense. However, this also differs a bit from the behavior of save as dialogs in Windows (and probably other OSs but I don't have the data to confirm) -- if an extension is left off when typing the name of the file, but the default extension is known, it will append the extension.

For instance, if I save a file in notepad by typing in "doc", it will turn it into "doc.txt", but I can override this by typing in "doc.json" and it will save it as that filename.

Personally, I would consider this a standard behavior and it could be implemented very quickly. But, the displayed behavior also makes logical sense.

**Comment by coquagli** [comment]
I'm going to guess it's not a behavior change, but I'm not sure at the moment.

**Comment by kburtram** [comment]
I'll add this to the backlog so we can triage when review issues for the GA+1 release.
