### ISSUE TITLE
Empty String value copied to Clipboard as "null" text value

### ISSUE THREAD

**Issue by nivek7** [Microsoft/vscode-mssql#864]
- MSSQL Extension Version:  1.0.0
- VSCode Version:   1.11.2 (1.11.2)
- OS Version:  10.12.4

Issue:
I have queries written where I use either a COALESCE or ISNULL function to convert NULL values to empty strings ('') (or technically not convert, but return the first non-NULL value etc). 

The results display as intended in the results pane in VS Code, however, when I copy and paste these results to another application like Excel or a Text Editor, the empty string values are replaced with "null" (as a text value) when copied to the clipboard.

While I can appreciate seeing "NULL" to represent an actual NULL value that I have not specifically handled, empty strings ('') are not NULL values and should not be treated any differently than if I returned a normal string or character value.

Is there a way to turn off this behavior?

Steps to Reproduce:

1. Create Query with COALESCE([Column_Name],'') or ISNULL([Column_Name],'')
2. Select ALL Results
3. Copy with Headers or Copy
4. Paste results from clipboard into Excel or Text application 

Any empty string values ('') in the pasted results will appear with "null" (in lowercase text).
Interestingly, actual NULL values not handled with COALESCE or ISNULL for example, will paste as "NULL" (uppercase).

**Comment by kburtram** [comment]
@benrr101 I think this looks its related to https://github.com/Microsoft/vscode-mssql/pull/736.  Returning `''` at QueryRunner.ts line 335 (https://github.com/Microsoft/vscode-mssql/blob/dev/src/controllers/QueryRunner.ts#L335) seems to resolve this issue, but I'm not sure if this impacts the scenario your PR is addressing.  Could you take a look and make the appropriate fix here?

Here's a simple repo SQL snippet.
```
CREATE TABLE T4(id int, va VARCHAR(10));
INSERT INTO T4 VALUES(1, NULL);
INSERT INTO T4 VALUES(2, 'NOT NULL');
INSERT INTO T4 VALUES(3, NULL);
INSERT INTO T4 VALUES(4, 'NOT NULL');
SELECT id, ISNULL([va],'') as IsNullVa, va FROM T4;
```

**Comment by benrr101** [comment]
@nivek7 Thanks for reporting this, it is definitely a regression. Looking at our code for copying cells, a short-term workaround would be to turn off `copyRemoveNewLine` in your settings. This has the side effect of new lines being copied, but this might be a tolerable side effect. In either case, I'll get working on a more robust solution. 

For technical background, we get DbCellValue objects when we execute a query. This gives us a DisplayValue (what to show in the table) and an IsNull flag. Right now, when we copy the cells, we're ignoring the IsNull flag.

**Comment by benrr101** [comment]
I've coded up a solution in #865 
Thanks @kburtram for the sample table. It made verifying a lot easier!

**Comment by kburtram** [comment]
@nivek7 this private build includes @benrr101's fix https://github.com/Microsoft/vscode-mssql/releases/download/v1.0.0-alpha.6/mssql-1.0.0.vsix.  You can side-load it using the "Install from VSIX.." option in the Extension Manager "..." menu.

This fix will be included in the next release, though we don't have a date set for that yet.  Please try the private build or the workaround @benrr101 mentioned above.  I'll close this issue, but please reactive if there is anything else for this issue.
