### ISSUE TITLE
MSSQL won't work on Fedora 25

### ISSUE THREAD

**Issue by mathsalmi** [microsoft/vscode-mssql#866]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.12.1
- OS Version: Fedora 25

Steps to Reproduce:

1. Open vscode
2. Select SQL file type
3. See console below:

SqlToolsService Initialization:
Initializing SQL tools service for the mssql extension.Note: mssql commands will be available after installing the service.Platform: linux, x86_64, name=fedora, version=25 (Fedora)

SQLToolsService:
Failed to initialize CoreCLR, HRESULT: 0x80131500
[Error - 9:11:28 AM] Connection to server is erroring. Shutting down server.
[Error - 9:11:28 AM] Connection to server is erroring. Shutting down server.
[Error - 9:11:28 AM] Connection to server is erroring. Shutting down server.

**Comment by kburtram** [comment]
This is probably related to lack of .Net Core 1.0 support for newest distro versions.  I'll check if the .Net Core 2.0 upgrade is expected to fix this.

**Comment by mathsalmi** [comment]
Hmm okay. Any ideas about when it'll be released?

**Comment by mathsalmi** [comment]
@CodingPapi Sorry, nope. When I installed the beta version it did work fine. Now I'm using a Macintosh again.
