### ISSUE TITLE
[Suggestion] Create a command to execute only the current statement

### ISSUE THREAD

**Issue by GabrielDuarteM** [Microsoft/vscode-mssql#870]
- MSSQL Extension Version:1.0.0
- VSCode Version:1.12.1
- OS Version:Windows 10

Just like the CTRL+Shift+E executes the whole script, as a user, i think it would be nice to have another shortcut to execute only the current statement (the one where the cursor is lying), so that i would't have to select every statement that i want to run. This would improve my overall workflow when using that plugin.

**Comment by mathsalmi** [comment]
That'd be handy indeed. [Postico](https://eggerapps.at/postico/) does this very well perhaps it serves as an inspiration.

**Comment by GabrielDuarteM** [comment]
Just as another open-source example, [HeidiSQL](https://www.heidisql.com/) has this feature as well

**Comment by kburtram** [comment]
@GabrielDuarteM @mathsalmi this is a great suggestions.  We'll take this for the next release.

**Comment by 4mitch** [comment]
Dreaming of this since moved to SQL Server from Oracle PL/SQL Developer with it's ";"

**Comment by kburtram** [comment]
The C# portion of this change is merged with https://github.com/Microsoft/sqltoolsservice/pull/412.  I'll merge the typescript portion tomorrow https://github.com/Microsoft/vscode-mssql/pull/934.

**Comment by kburtram** [comment]
@GabrielDuarteM I'll close this now since this suggestion is available in this private build https://github.com/Microsoft/vscode-mssql/releases/tag/v1.1.0-alpha.4.  Please let me know if there are any issues with the implementation.  Thanks!
