### ISSUE TITLE
Option to automatically fit all columns in Results tab

### ISSUE THREAD

**Issue by EdwinSaenz** [microsoft/vscode-mssql#876]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.12.2
- OS Version: Windows 10

When seeing results from a query I can double click on the edge of a column to auto-fit. It would be nice to have an option to auto-fit all columns.

**Comment by abist** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-mssql/issues/798
