### ISSUE TITLE
Results Pane Scrolling Issue

### ISSUE THREAD

**Issue by nivek7** [microsoft/vscode-mssql#877]
- MSSQL Extension Version:  1.0.0
- VSCode Version:  April 1.12
- OS Version:  MAC OS Sierra

This has been an ongoing issue and I would guess, is most likely a MAC issue. The results pane, after populating the results of a query, does not seem to respond well to scrolling. 

Often, the rows disappear, then "refresh". There is usually a delay when scrolling through the rows before the actual values become visible. 

I experience a "cutoff" of rows when scrolling down. The first "page" of rows may be visible, but when scrolling down further, the rows will not become visible unless I actually click into the grid and when I do click, I am returned to the top row.

I believe this issue is because in MAC OS, scrolling is executed when simply hovering over a window, or in this case, a grid (versus clicking in the grid first, then scrolling). Meaning, a window (or grid control) does not have to have focus to receive and execute the mouse scroll events.

Steps:
1 - Enter a few queries in one batch that return multiple rows.

2 - Scroll down to see other batch results (not within a result set). There is a delay to populate the grids until they are visible.

3 - Scroll down within a result set without actually clicking in the grid. The scroll will occur, but the results will not be visible until clicking within the grid.

**Comment by abist** [comment]
@nivek7 This issue seems to be fixed now in the latest version of the extension. Feel free to reopen the issue if you still find this problem in the latest version of vscode-mssql.
