### ISSUE TITLE
Tab Navigation Re-Executes Query

### ISSUE THREAD

**Issue by nivek7** [microsoft/vscode-mssql#878]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

When navigating between tabs, there is a message "Executing Query". Is it actually re-executing the query when simply returning to a tab that had previously been populated with a recordset? 

Can this behavior that can be switched off? 

Steps to Reproduce:

1. Create 2 queries in separate tabs
2. Execute each
3. Switch from one results tab to the other
4. Message is displayed stating that the query is executing

**Comment by kevcunnane** [comment]
No, this isn't re-executing the query. What happens is that the messages sent to the UI are replayed quickly, which may result in you seeing this message temporarily. However we only execute if you send the execute command - this is separate from UI loading/reloading.

**Comment by nivek7** [comment]
Great, thanks for the clarification. I did just take note of the fact that the execution time is identical upon refresh which I would assume would fluctuate if the query was actually re-executing. Thanks again.

**Comment by anthonydresser** [comment]
Probably still a bug here to clean up the loading of the page to not show that if the query was indeed already executed
