### ISSUE TITLE
MSSQL Connection

### ISSUE THREAD

**Issue by jgcandelaria** [microsoft/vscode-mssql#880]
- MSSQL Extension Version: Latest
- VSCode Version: 1.12
- OS Version: Sierra 10.12.5

Steps to Reproduce:

1. I continue to get an connection error to a SQL Server Instance in our work domain
2. I tried creating several profiles and none connect to a SQL Server Instance

**Comment by nivek7** [comment]
What version of SQL are you attempting to connect to?

I had a similar issue and it ended up being an issue that was specific to SQL 2008/R2. We have since upgraded SQL to 2014 with no issues. I was also connecting from Sierra.

**Comment by graysonwright** [comment]
I got an error while trying to connect to a SQL Server 2000 instance:

```
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : ODBC Driver 13 for SQL Server does not support connections to SQL Server 2000 or earlier versions..
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection.
```

**Comment by kevcunnane** [comment]
@graysonwright that's a SQLCMD issue.
- This repo is for issues related to the MSSQL extension for VSCode. it's not the right place to track this
- SQL 2000 isn't supported anymore. I'd suggest you need to use an older version of SQLCMD to have a chance to connect. If you're on mac/linux it's possible no driver that can connect to SQL Server 2000 is available.

**Comment by graysonwright** [comment]
@kevcunnane thanks for the quick response. Sorry my comment was off-topic.

To circle back to the conversation at hand...

I solved my problem on the command line by switching from `sqlcmd` over to UnixODBC's `isql` command, with [FreeTDS](www.freetds.org) as a driver.

[FreeTDS claims to work with all versions of SQL Server.](www.freetds.org/faq.html#Does.FreeTDS.support.my.server)

Do you know if it's possible to use FreeTDS as a driver for `vscode-mssql` as well?
