### ISSUE TITLE
Support for ~/ and ./ for Save As CSV, JSON, Excel on Mac and Linux

### ISSUE THREAD

**Issue by erickangMSFT** [microsoft/vscode-mssql#883]

**Comment by borgdylan** [comment]
The support for ~/ would be very handy. Typing the whole path to my user profile gets old fast.

**Comment by dombarnes** [comment]
+1
It seems incredibly weird that the default save location is in /var/folders - a folder that most users don't know exists, and may not know how to get to. Default to ~ would make much more sense

**Comment by kburtram** [comment]
This appears to have been fixed at some point.  Currently the default "Export Results" location is ~/Downloads and using the `~` shortcut is working in the Save as... dialog.

![image](https://github.com/user-attachments/assets/6fa59db3-26b6-46f9-8c85-9c0c0bfd59b2)
