### ISSUE TITLE
Extension crash on open of .sql file

### ISSUE THREAD

**Issue by huypha** [Microsoft/vscode-mssql#885]
SQL Tools Services crashes or fails to start for the extension if an already-created sql file is opened. It seems this might have to do with the file's path. An example file path that crashes sql tools service is "F:\SqlDevTools\sqltoolsservice\test\Microsoft.SqlTools.ServiceLayer.Test.Common\TestData\TSqlFormatter\TestFiles\CreateProcedure.sql".

Log: [sqltools_2017052517380114960.txt](https://github.com/Microsoft/vscode-mssql/files/1030533/sqltools_2017052517380114960.txt)

To repro, take the latest sqltoolsservice dev build and transfer the appropriate bits from <sqltools service root>\Microsoft.SqlTools.ServiceLayer\bin\Debug\netcoreapp1.0\win7-x64 to <vscode-mssql>\sqltoolsservice\1.0.0-alpha.7\Windows root and launch extension.

**Comment by huypha** [comment]
This issue should have been placed under SQL Tools Service

**Comment by kburtram** [comment]
@huypha I can't repro this, so I'll close for now.  Please reactive with additional repro steps if you can still encounter this.
