### ISSUE TITLE
Is it possible refresh intellisense cache for db schema?

### ISSUE THREAD

**Issue by jtterry2856** [Microsoft/vscode-mssql#887]
I ran a query where the table was missing. Once i created the table and re-ran the query it completed successfully but editor is still showing errors. In ssms i would normally have done `CTRL + Shift + R` to refresh the cache. Is there a similar command to refresh editor intellisense so that errors are removed? I wanted to ask before reporting a bug.

**Comment by kevcunnane** [comment]
Yes - if you hit F1 and choose the `MSSQL: Refresh IntelliSense Cache` command this will work. Note that you may need to hit space or another key to kick off an intellisense refresh in the VSCode UI after this.

**Comment by kevcunnane** [comment]
I'm going to close this out for now - let us know if there's an issue after this.

**Comment by jtterry2856** [comment]
Sorry for late reply but your suggestion worked. Thanks!

**Comment by kevcunnane** [comment]
@jtterry2856 glad you're unblocked!

**Comment by jjturner** [comment]
@kevcunnane - the extra bit about adding a space in the editor after issuing the refresh command was the missing piece!  Is there any reason why this extra (undocumented) step is necessary?  Can a code fix obviate this?
