### ISSUE TITLE
Wildcard Expansion for SELECT statements

### ISSUE THREAD

**Issue by sgpeter1** [microsoft/vscode-mssql#889]
It'd be great to have wildcard expansion for SELECT statements.

**Comment by kevcunnane** [comment]
Thanks Sterling for this suggestion. We'll add to our backlog and see if we do a sweep of IntelliSense improvements in the future.

**Comment by kburtram** [comment]
This is supported in the current extension release.  If you place the cursor after the `*` and type Ctrl-Space to initiate the completion pop-up, then the wildcard can be expanded to the full list of columns (as shown in screenshot below).

![image](https://github.com/user-attachments/assets/50765e63-38b4-4808-8de0-0a5615d490d0)
