### ISSUE TITLE
Connection lost and cannot reconnect issue

### ISSUE THREAD

**Issue by TokenJedi** [microsoft/vscode-mssql#890]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.12.2
- OS Version: Win 10

I intermittently get stuck with some type of weird connection state.
Granted, this happens when the underlying DB that I've connected to has changed name; however, this does not happen in SSMS and the only solution I can find right now is to "bounce" VS Code.

It would be nice to just be able to force the disconnect and reconnect, or anything other than having to restart VS Code

Steps to Reproduce:
1. Connect to DB
2. Rename DB
2.a. Connection still shows it's connected
3. Try to execute new SQL command
3.a. Results show success...however,
4. Get error saying that I'm not connected
5. Cannot disconnect or reconnect
6. Kill VS Code
7. Restart VS Code
8. Able to connect to DB again.
9. Ponder my life choices

Here is the SQL Script I'm using to Rename a DB in flight (this works in SSMS)

use master
GO

ALTER DATABASE OldNBusted --existing name
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO  
ALTER DATABASE OldNBusted --existing name
    MODIFY NAME = NewHottness --new name
GO
ALTER DATABASE NewHottness --new name
    SET MULTI_USER
GO

![image](https://cloud.githubusercontent.com/assets/10510070/26701998/c038a38c-46e8-11e7-9bb9-87f9efb2c66d.png)

**Comment by abist** [comment]
@TokenJedi Please try the latest extension and see if you still see the same problem occurring. I would also suggest selecting a database from the `Status Bar` in the lower right corner instead of using `USE DATABASE`. Feel free to reopen this issue if you still see it in the latest version of the extension (1.9)
