### ISSUE TITLE
Create Connection Profile Aborts Without Warning

### ISSUE THREAD

**Issue by ckapilla** [Microsoft/vscode-mssql#891]
- MSSQL Extension Version:
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. Start creating a new connection profile
2. enter some data
3. change focus to another window (for example to copy a long, complex password)
4. All your work is lost without warning!

**Comment by davoscollective** [comment]
This makes it impossible to copy paste a connection profile, for example copying a complex password from a password manager.

**Comment by kevcunnane** [comment]
I've fixed this (thanks to VSCode adding a new parameter that lets us do just this!). It will be in nightly builds shortly, and will be in our next release. Unfortunately that won't be for a little while, but feel free to use the nightlies if you really want this one. Thanks!

**Comment by ckapilla** [comment]
Thanks for doing this!
