### ISSUE TITLE
Unable to load connection profiles Error Message

### ISSUE THREAD

**Issue by plambhsa** [microsoft/vscode-mssql#894]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.12.2
- OS Version: OSX 10.12.5

Steps to Reproduce:

1. Add a Connection profile through MSSQL extension prompts
2. Restart VS Code
3. Cmd + Shift + C to connect

On that third step, an error shows up every time for me in VS Code:

`mssql: Error: Unable to load connection profiles from [/Users/pjlamb12/Library/Application Support/Code/User/settings.json]. Check if the file is formatted correctly.`

![screenshot 13](https://user-images.githubusercontent.com/14982471/26893420-7fe55296-4b78-11e7-9c25-4a80ead7462a.png)

The thing is, the connections dropdown shows below it and I can still select the connection and connect. I added the connection profile through the prompts, so it should be formatted correctly, but I don't know what else could be causing this. Especially since I can still see the dropdown selection of connections.

**Comment by kburtram** [comment]
@plambhsa could you please verify if there are any JSON parsing issues in your settings file?  (you can do so using JSON editor like http://www.jsoneditoronline.org/).  

The extension will try to parse this file and if that fails you could get an error like your seeing.  We have plans to make our parsing more robust to errors in a future update.

**Comment by abist** [comment]
@plambhsa I'm going to go ahead and close this issue. Feel free to re-open the issue if you are still facing issues.
