### ISSUE TITLE
RESTORE DATABASE command not completing

### ISSUE THREAD

**Issue by oedenfield** [Microsoft/vscode-mssql#898]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.13.1
- OS Version: Windows 10 Creators Update
- SQL Server Version: Microsoft SQL Server 2017 (CTP2.1) - 14.0.600.250 (X64) 	May 10 2017 12:21:23 	Copyright (C) 2017 Microsoft Corporation. All rights reserved.	Developer Edition (64-bit) on Linux (Ubuntu 16.04.2 LTS)

Steps to Reproduce:

1.  Run SQL Server on Linux in Docker.
2.  Connect to SQL Server via localhost connection.
3.  Verify connection works by running SELECT name FROM master.dbo.sysdatabases; & SELECT @@VERSION; successfully from vscode.
4.  Copy *.bak file over to SQL Server container via docker cp command
<code>docker cp C:\Users\ored\SampleData\MillionSongDataset\graph.bak d65ce39bd425:/var/opt/mssql/data/graph.bak</code> File is 1.98 GB in size.
5.  Execute RESTORE command. Messages goes through from 5% to 100% but then message tells me connection ended abnormally.  This is restore command I'm using.
<code>RESTORE DATABASE [graph] FROM  DISK = N'/var/opt/mssql/data/graph.bak' WITH  FILE = 1,  MOVE N'graph' TO N'/var/opt/mssql/data\graph.mdf',  MOVE N'graph_log' TO N'/var/opt/mssql/data\graph_log.ldf',  NOUNLOAD,  STATS = 5</code>

I can run the exact same RESTORE DATABASE command in SSMS (at step 5) without issue.

**Comment by llali** [comment]
Hi @oedenfield 
I tried your script in the extension in RHEL and it worked but I didn't have the same environment as yours. That's what I'm going to do next. So you run the extension in Windows and connecting to SQL server on Docker. But are you running the docker in your Windows machine? 

Also can you give me the error message you get?

**Comment by oedenfield** [comment]
Yes, I'm running Docker on Windows (now updated to 17.06.0-ce-in19 (12801), Channel Stable).

I just re-ran the steps above and received this message:
[2:21:58 PM]	Started executing query at Line 12
	5 percent processed. 
	10 percent processed. 
	15 percent processed. 
	20 percent processed. 
	25 percent processed. 
	30 percent processed. 
	35 percent processed. 
	40 percent processed. 
	45 percent processed. 
	50 percent processed. 
	55 percent processed. 
	60 percent processed. 
	65 percent processed. 
	70 percent processed. 
	75 percent processed. 
	80 percent processed. 
	85 percent processed. 
	90 percent processed. 
	95 percent processed. 
	100 percent processed. 
	Processed 260264 pages for database 'graph', file 'graph' on file 1. 
	Processed 4 pages for database 'graph', file 'graph_log' on file 1. 
	RESTORE DATABASE successfully processed 260268 pages in 76.185 seconds (26.689 MB/sec). 
	Total execution time: 00:01:18.891

After executing this time it looks like it worked properly.

**Comment by kevcunnane** [comment]
@oedenfield thanks - looks like this was a transient SQL Server error in that case. We'll close this here since it's independent of our tool.
