### ISSUE TITLE
Service component could not start when viewing diff

### ISSUE THREAD

**Issue by shwick** [microsoft/vscode-mssql#902]
- MSSQL Extension Version:1.0
- VSCode Version:1.13.1
- OS Version:Windows 10

Steps to Reproduce:

1. Work on a file in a git controlled folder
2. Save some changes to file
3. Find that file in VS Code's Source Control side panel
4. Open differences for that file

I get an error saying
`mssql: SQL Tools Service component could not start.`

Existing connections do not work and no new connections can be made until I reload that window (or close and reopen the window).

**Comment by kevcunnane** [comment]
@shwick I'm struggling to reproduce this on Windows or Mac. I updated to the latest VSCode, installed MSSQL cleanly and opened a Git diff window. No problems. I was even able to execute results on it. Some questions:
- Is there any chance it's a non-Git source code provider? We have filtering / handling for git URIs sent to the service, but not sure about other providers
- Does this only happen on specific files / repositories? If so, could you help with a repro that includes this?
