### ISSUE TITLE
Inconsistent Connection Profile Settings (Encryption)

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-mssql#905]
- MSSQL Extension Version: 1.0
- VSCode Version: 1.13.1
- OS Version: Windows

Steps to Reproduce:
Save Password/No Encryption, connection timeout info
Connected to Azure SQL database
Choose YES to Save Password question

Resulting settings: 
 "server": "mydbservername.database.windows.net",
            "database": "",
            "authenticationType": "SqlLogin",
            "user": "me",
            "password": "",
            "savePassword": true,
            "profileName": "AzureSQLSavePassword"
        }

Hovering over connection in status bar:
Sometimes it says that the connection is "not encrypted" and sometimes it says it is "encrypted" ala: 
![image](https://user-images.githubusercontent.com/5007120/27667545-66f8ee1e-5c49-11e7-929c-9efb630759a4.png)

I *beleve* that the pattern is taht when you first create a new connection it says not encrypted. But then every subsequent time you open that connection it is "encrypted". I haven't thoroughly tested this theory but I've tried quite a number of times now. I also think this is the pattern for both profiles with  stored passwords and profiles without stored passwords. I don't trust that status now.

Also at one point this is the connection profile  that got stored for the same connection to the same database using the same login .
// {
//     "server": "mydbservername.database.windows.net",
//     "database": "",
//     "authenticationType": "SqlLogin",
//     "user": "me",
//     "password": "",
//     "savePassword": false,
//     "profileName": "AzureSQLDefault",
//     "connectTimeout": 30,
//     "encrypt": true,
//     "applicationName": "vscode-mssql"
// }

 I happened to comment it out then recreate two more profiles for that same connection but they had fewer fields, It was the same whether I saved the Password or not.

 {
            "server": "mydbservername.database.windows.net",
            "database": "",
            "authenticationType": "SqlLogin",
            "user": "me",
            "password": "",
            "savePassword": false,
            "profileName": "AzureSQLNoSavePW"
        }

I don't know where those last 3 fields came from in the commented out profile!

Is there a known pattern? I searched this repo and gitter and haven't found any relevant discussion.

**Comment by kevcunnane** [comment]
Per email discussion this has been hard to reproduce for me. The additional settings are likely from a very early version, but it's not clear why it would claim it's not encrypted - encrypted is the default for Azure.

Are there objections to closing this one out?
