### ISSUE TITLE
Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON' on linked server

### ISSUE THREAD

**Issue by TechWatching** [Microsoft/vscode-mssql#909]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.13.1
- OS Version: Windows 8.1 Entreprise

Steps to Reproduce:

1. Connect to a SQL Server with "authenticationType": "Integrated"
2. Do a select request with a join on the table of a linked server
3. The following error appears : Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON' 

Other requests work correctly.
This works correctly on SSMS so I guess it is not an issue linked to a bad configuration.

**Comment by kevcunnane** [comment]
This looks like the same issue in #778. The root problem here is in the SqlClient implementation for .Net Core - we're relaying the messages as sent by them. I'd recommend opening an issue against  https://github.com/dotnet/corefx as that's where the correct fix would be.

**Comment by TechWatching** [comment]
Partially solved so I will close it as there is a way around the issue. If I already have a connection opened with SSMS, requests from vs code work correctly. Issue probably due to a configuration specific to my company.
