### ISSUE TITLE
Feature: Support SQL on Linux Availability Group Syntax 

### ISSUE THREAD

**Issue by clayton006** [Microsoft/vscode-mssql#910]
- MSSQL Extension Version: 1.0
- VSCode Version: 1.13.1
- OS Version: Windows 10 Creators Edition

Feature:

1. Add syntax support for SQL on Linux Availability Groups for FAILOVER_MODE = EXTERNAL when creating an availability group.
2. Add syntax support for SQL on Linux Availability Groups for CLUSTER_TYPE = EXTERNAL when joining availability group.

**Comment by kevcunnane** [comment]
@clayton006 could you give a full example of the syntax? Is the issue that IntelliSense is showing it as an error, and if so does the latest SSMS release (17.1) also have this error? If it's fixed, an update of the Intellisense DLLs we use should be enough to resolve this.

**Comment by clayton006** [comment]
Yes the issue is with IntelliSense. I can provide full syntax for both. In SSMS 17.1 it does NOT show up as an error:

CREATE AVAILABILITY GROUP [ag1]
    WITH (DB_FAILOVER = ON, CLUSTER_TYPE = EXTERNAL)
    FOR REPLICA ON
        N'midersql01' WITH (
            ENDPOINT_URL = N'tcp://midersql01:5022',
            AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
            FAILOVER_MODE = EXTERNAL,
            SEEDING_MODE = AUTOMATIC,
            SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
            ),
        N'midersql02' WITH ( 
            ENDPOINT_URL = N'tcp://midersql02:5022', 
            AVAILABILITY_MODE = SYNCHRONOUS_COMMIT,
            FAILOVER_MODE = EXTERNAL,
            SEEDING_MODE = AUTOMATIC,
            SECONDARY_ROLE (ALLOW_CONNECTIONS = ALL)
            )

And for the other (CLUSTER_TYPE = EXTERNAL):

ALTER AVAILABILITY GROUP [ag1] JOIN WITH (CLUSTER_TYPE = EXTERNAL)

**Comment by kevcunnane** [comment]
@clayton006 our recent refresh of SMO and Intellisense bits has fixed this. I verified on the latest bits in master. This will be included in our upcoming 1.1 release.
