### ISSUE TITLE
Results row position is lost when switching tabs

### ISSUE THREAD

**Issue by nivek7** [microsoft/vscode-mssql#916]
- MSSQL Extension Version:  1.0.0
- VSCode Version:  1.13.1
- OS Version:  Mac Sierra  (10.12.5)

Row position is lost when navigating to other result tabs and back again.

Steps to Reproduce:

1.  Execute 1+ queries in separate document windows so you end up with multiple result set tabs
2.  Scroll through one of the result sets and position the cursor on a cell in a row
3.  Navigate to the other result set by switching tabs
4.  Navigate back to the initial result set where you positioned the cursor on a row
5. That row that you were positioned on previously is no longer visible in the grid and the cursor is now reset to row 1

**Comment by abist** [comment]
@nivek7 You can maintain your scroll position of your results using the following setting -
```
"mssql.persistQueryResultTabs": true
```
which says "Should query result selections and scroll positions be saved when switching tabs"
