### ISSUE TITLE
Installing SQL tools service failed 

### ISSUE THREAD

**Issue by kaushik1990** [Microsoft/vscode-mssql#918]
- MSSQL Extension Version: 1.0.0
- VSCode Version: 1.13.1
- OS Version: ubuntu 16.10

Steps to Reproduce:
1. Open vs code.
2. Create a new file.
3. Change the file type to SQL.
Output:
Initializing SQL tools service for the mssql extension.
Note: mssql commands will be available after installing the service.

Platform: linux, x86_64, name=ubuntu, version=16.10 (Ubuntu16)

Installing SQL tools service to /home/kaushik/.vscode/extensions/ms-mssql.mssql-1.0.0/sqltoolsservice/1.0.0/Ubuntu16.
Downloading https://download.microsoft.com/download/3/A/E/3AE0DD0F-86A1-46CD-BFE2-E106E7CC8508/microsoft.sqltools.servicelayer-ubuntu16-x64-netcoreapp1.0.tar.gz
[ERROR] Error: Request error: ENOTFOUND

**Comment by kburtram** [comment]
@kaushik1990 the error appears to be related to downloading https://download.microsoft.com/download/3/A/E/3AE0DD0F-86A1-46CD-BFE2-E106E7CC8508/microsoft.sqltools.servicelayer-ubuntu16-x64-netcoreapp1.0.tar.gz.  Could you please check if you have access to download this file?

**Comment by kaushik1990** [comment]
I can download the file manually. But from vs code, it's giving me an error. I tried to place the downloaded files in "/home/kaushik/.vscode/extensions/ms-mssql.mssql-1.0.0/sqltoolsservice/1.0.0/Ubuntu16" but it didn't work.

**Comment by TechWatching** [comment]
I had a similar issue before, it was linked to my proxy. Do you have a proxy and is it correctly configured on vs code ?

**Comment by abist** [comment]
@kaushik1990 Please re-open the issue if you still have issues downloading the files for the extension.
