### ISSUE TITLE
Database name with $ is not showing up correctly in database list

### ISSUE THREAD

**Issue by llali** [Microsoft/vscode-mssql#924]
Steps to Reproduce:

1. Create a database with $ in a server. "$(DatabaseName)"
2. Connect to the server
3. Run "Use Database" command to get the list of databases

Expected: The database name should show up in the list
Actual: The database name is showing up as an empty string in the list

**Comment by kevcunnane** [comment]
We should take this fix for our next release

**Comment by llali** [comment]
Cannot repro this anymore. looks like fixed already
