### ISSUE TITLE
When connected using a connection string, changing database (in bottom-right) does not work

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/vscode-mssql#929]
- MSSQL Extension Version: Master@41aeeaf
- VSCode Version: 1.13.1
- OS Version: OS X 10.12

Steps to Reproduce:
1. Open a connection using an ADO.Net connection string
2. Click on the bottom-right connection status to change database. Nothing happens, even though the prompt to select a new database should pop up.

Additional Notes:
- If you're debugging, VS Code shows a rejected promise message after clicking on the button
- It seems to fail on the call `self.client.sendRequest(ConnectionContracts.ListDatabasesRequest.type, listParams)` on line 385 of `connectionManager.ts`

**Comment by kevcunnane** [comment]
Sounds like we should take this for the release.

**Comment by MattIrv** [comment]
I'll take a look at this. The stack trace shows it's an issue with how we handle connection strings in SQL Tools Service.
