### ISSUE TITLE
Allow messages to display run time for each batch when there are multiple batches

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-mssql#939]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.0
- OS Version: Windows 10

Steps to Reproduce:

1. enter two separate queries, separated by GO in teh editor window
2. execute query for the full windows
3. Messages window will display start time, starting line # and # of affected rows for each message. Then it will display the total running time. 

Is it possible to display the running time for each batch in addition to the total?
THanks

**Comment by kevcunnane** [comment]
It's a nice suggestion and coding it was quick - I'll have a PR out shortly. I'm going to put this behind a feature flag since I suspect most people will be happy without this level of granularity. If that's wrong we can always change the default in future versions to enable by default. Thanks!
