### ISSUE TITLE
drop database fails most of the time because the db is in used

### ISSUE THREAD

**Issue by llali** [Microsoft/vscode-mssql#949]
- MSSQL Extension Version:
- VSCode Version: 
- OS Version: RHEL

Steps to Reproduce:

1. Create a new database
2. Close mssl extension
3. Open the extension, open new sql query and connect
4. Execute "Drop database [db name]

Expected: the database should get dropped successfully since there's not any other open window accessing the database

Actual: The query failed: Cannot drop database "[db name]" because it is currently in use.

**Comment by kevcunnane** [comment]
We can look at this for the next release - we should better handle our open connections and try to ensure this works as well as it does in SSMS

**Comment by llali** [comment]
A change Karl made in sqltoolsservice should be related to this issue. I'll verify to make sure it's really fixed

**Comment by llali** [comment]
fixed in https://github.com/Microsoft/sqltoolsservice/pull/460
