### ISSUE TITLE
Issue with escaped character and syntax color

### ISSUE THREAD

**Issue by Jalkar** [microsoft/vscode-mssql#955]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.1
- OS Version: Win 10

Steps to Reproduce:
The syntax color doesn't take account of the escaped character when applying color

1. put  `insert into TABLE(col1, col2, col3,...) Values ('This data will break the color because of this escaped character  \' everything behind is scrambled','data');` in a SQL file

**Comment by abist** [comment]
This is now fixed by https://github.com/microsoft/vscode-mssql/pull/1630
