### ISSUE TITLE
Confused as to where I should see localization effect

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-mssql#957]
- MSSQL Extension Version: 1.1 RTM
- VSCode Version: 1.14.2
- OS Version: Windows 10

Steps to Reproduce:

1. Command pallete to Configure Language
2. Change setting to fr
3. Close VS Code and reopen
4. Localization of IDE is quite obvious
4. Reconnect to mssql and a server
5. Execute a simple query eg. sqllistdatabases

I expect to see messages and also mssql output messages in French but they are still in English. 

![image](https://user-images.githubusercontent.com/5007120/28530952-50d13b9a-7063-11e7-99e3-13c792b97040.png)

I have looked at the localization/xliff files and can see that the various execution messages have been translated. So I'm not sure exactly where I should be witnessing the translations.

Thanks

**Comment by kevcunnane** [comment]
@llali can you help list where Julie will see localized strings?

@julielerman  we have a couple of limitations:
- Commands can't be localized, since the text is defined statically in package.json
- Snippets have the same issue
- We have a bug #947 where the results grid isn't localized. This is limiting the localization of the most visible components.

Basically in the next release we'll get the main results page localized, and that should help a lot. For now you can definitely see messages returned from the tools service, and anything coming from the extensions that's not defined in a json file.

**Comment by llali** [comment]
@julielerman 
The messages coming from the service are localized now. As you can see bellow, the text "Started executing query at Line 1" s localized.
![image](https://user-images.githubusercontent.com/17187348/28583999-0461aeee-7120-11e7-8063-2a0e0a064847.png)

**Comment by julielerman** [comment]
Thanks. @llali you say "localized now" do you mean post 1.1 ? Using 1.1, where should I be able to see evidence of it? I understand as per @kevcunnane comment, that I won't see it in the grid

**Comment by llali** [comment]
@julielerman yes using 1.1, when  execute a query, in the query panel, I see one of the messages is localized:
Démarrage de l’exécution de la requête à Ligne 1

![image](https://user-images.githubusercontent.com/17187348/28586893-182aa4da-712a-11e7-8b7b-978369516e1f.png)

**Comment by julielerman** [comment]
In addition to the mssql connection strings the only other settings I've overridden are these:

```
{
    "files.autoSave": "afterDelay",
    "window.zoomLevel": 1,
    "files.associations": {
        "*.json": "json"
}
```
So I'm not sure what else is different on our systems. I do have my location set to United States. I just changed it to France and closed and opened Code and tried again but the results were the same. Do you think the computer ALSO has to be set to a location and should I reboot?

**Comment by llali** [comment]
try adding this setting:
"mssql.applyLocalization": true

**Comment by julielerman** [comment]
YES! that did it. Is that supposed to be part of the steps for enabling it? I only remember seeing Configure Language

**Comment by llali** [comment]
@kevcunnane is mssql.applyLocalization documented anywhere? I cannot find it

**Comment by julielerman** [comment]
it will be in my course! LOL

**Comment by kevcunnane** [comment]
Doesn’t it have Intellisense doc in the user / workspace settings?

**Comment by julielerman** [comment]
it's got a description for the setting but I had been under the impression that it was a matter of changing config language. Though I can't find the source. But I wouldn't naturally look in settings for documentation. I'm looking around to see where on github (readme? wiki?) it would deserve a mention

**Comment by julielerman** [comment]
Im okay with this now that I've been using it so I'm going to close this as an issue.
