### ISSUE TITLE
Can't open sql file on mac

### ISSUE THREAD

**Issue by starostin** [Microsoft/vscode-mssql#958]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.2 
- OS Version: macOS Sierra 10.12.5

Steps to Reproduce:

1. When I try to open .sql file, I see this message
http://prntscr.com/fzx642

**Comment by kevcunnane** [comment]
@starostin how big is the file? This is likely a known issue in VSCode: has a built-in limit of ~50MB - see https://github.com/Microsoft/vscode/issues/6474 which mostly references SQL files. It looks like this is actively being worked on and the ability to increase the limit investigated. However, for now I believe this is blocked as an upstream issue in VSCode.

I'd suggest we should close this and let you track the issue in VSCode.

**Comment by starostin** [comment]
Yes, this file more than 80 mb. Thanks for advice, closing issue.
