### ISSUE TITLE
FeatureSuggestion : Object Browser / Object Lookup

### ISSUE THREAD

**Issue by valkcon** [microsoft/vscode-mssql#962]
Looks great so far, I'm almost (but not quite) convinced to use this daily....however:

A  db-object-browser would be great.  Given intellisense is already a feature, shouldn't this be almost as simple as a Pretty-Dump-to-someTreeViewThingy of the intellisense data?  

We tend to use StoredProcedures a lot, it's difficult to actually load a definition of a StoredProc in the extension (or view, or table) without first writing some sql and then using "go to definition".  If I want to `alter procedure dbo.deleteWholeDataBase`, I have to type `exec dbo.deleteWholeDataBase` and then use "go to definition", there's an inherent danger there I might actually execute `exec dbo.deleteWholeDataBase`!!

Actually, a full-ux-object-browser is not entirely required, just a single auto-complete-lookup input for the intellisense-data with a button beside results for "go to definition" would be great.  Maybe even possible to put this into the command pallette.  In fact a simpler lookup for `db-object-name-contains` could even be more useful than a treeview as half the time I forget which schema has the StProc or view I'm looking for, or that one schema StProc is calling the other.

Just a few thoughts.

**Comment by sean256** [comment]
I came here to ask for the same thing. A UI view would be ideal!

**Comment by mika76** [comment]
I think this is the same request as #1031 ?

**Comment by abist** [comment]
Closing this issue as it's being tracked here - https://github.com/microsoft/vscode-mssql/issues/586
