### ISSUE TITLE
Question about Prompt overwrite for save as csv/json/excel

### ISSUE THREAD

**Issue by julielerman** [microsoft/vscode-mssql#964]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.2
- OS Version: Win10

I was saving some results as CSV and used a file name that I'd already used and got a prompt about overwriting the file and it showed me a diff of the old and new. 

I have not been able to repeat this.

Is there a particular scenario in which I should expect this behavior?

I do see a feature for prompting was added last September: https://github.com/Microsoft/vscode-mssql/pull/117

Thakns

**Comment by kevcunnane** [comment]
Sorry I thought I'd responded to this already. I've never seen us show a diff. Definitely not expected

**Comment by julielerman** [comment]
I think it's VS Code doing it. I've seen it again in a few weird cases. One was when I didn't have an extension. Another ...could it be? I had selected the same content from the grid and exported to a new file name and it popped up. So bizarre. Hard to nail down though.

**Comment by abist** [comment]
This should be fixed in the latest version of the extension. Feel free to re-open if you face this issue again in the latest version of the extension.
