### ISSUE TITLE
Not able to connect to SQL Server anymore

### ISSUE THREAD

**Issue by Spenmetsa** [microsoft/vscode-mssql#965]
- MSSQL Extension Version:1.1
- VSCode Version:Code 1.14.2
- OS Version:10.11

Steps to Reproduce:

1.
2.

**Comment by kevcunnane** [comment]
@Spenmetsa could you provide more information about what is going wrong for you?

**Comment by Spenmetsa** [comment]
@kevcunnane I have all the connections set up properly when I do MSSQL: Connect, it is saying connecting to server "Server Name" but never establishes any connection, not sure what is happening. Please let me know if you need more details?

**Comment by Spenmetsa** [comment]
@kevcunnane I restarted the VS Code and i see this error `mssql: SQL Tools Service component could not start.` I went and installed OpenSSL and i still get the same warnings, can you please let me know if any work around here?

**Comment by abist** [comment]
@Spenmetsa I'm going to go ahead and close this issue. Feel free to reopen if you still see this issue in the latest version of the extension.
