### ISSUE TITLE
Opening link for Line number in batched results selects incorrectly when no blank line after GO

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-mssql#966]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.14.2
- OS Version: windows 10

Steps to Reproduce:

1. Following 3 batch statement in editor window. Note there are no blank lines between the batches
```
SELECT c.CompanyName, c.EmailAddress 
FROM SalesLT.Customer AS c 
WHERE  c.CompanyName LIKE 'A%'  
GO
SELECT * FROM SalesLT.SalesOrderHeader
GO
SELECT TOP 10 * FROM SalesLT.Product
```
2. Execute the query.
3. Click the link for first batch (starting at line 1)
It selects the first query, the GO and the first 2 chars of the next line. 

After clicking Line 1 link

![image](https://user-images.githubusercontent.com/5007120/28848610-9c94a61e-76e1-11e7-898a-3e923a120365.png)

After clicking Line 4 link
![image](https://user-images.githubusercontent.com/5007120/28848684-e9dd9764-76e1-11e7-820b-49744da30183.png)

**Comment by kevcunnane** [comment]
@abist I wonder is this due to line ending handling?

**Comment by abist** [comment]
@kevcunnane I'll look into this.

**Comment by abist** [comment]
This issue should now be fixed. If it seems that it still hasn't fixed on your end yet, please feel free to re-open the issue.
