### ISSUE TITLE
Connections defined in User Settings not showing

### ISSUE THREAD

**Issue by MaxDiOrio** [Microsoft/vscode-mssql#971]
- MSSQL Extension Version: 1.1.0
- VSCode Version: 1.16.0-insider
- OS Version:  Windows 10

Steps to Reproduce:

1. Ctrl+Shift+P
2. Manage Connection Profiles
3. Edit
4. Create settings for "mssql.connections" in the User Settings.
5. Save, close, reopen VS Code.  Attempt to use a connection profile and it's not there.  The list of connections is blank.

**Comment by kevcunnane** [comment]
@MaxDiOrio thanks for raising this. This is currently a known issue tracked in #242. We think that with recent changes to the VSCode API we can try again to update and resolve this so will consider fixing in our next release. For now, I'm going to close this bug as #242 is the main tracker we're using for the issue. Let us know if you run into more issues!
