### ISSUE TITLE
Expose connection name/details as variable for use in window.title

### ISSUE THREAD

**Issue by ransagy** [microsoft/vscode-mssql#975]
Would it be possible to expose the connection name or details and/or DB name/details as a variable that can be used in VScode's window.title setting?

Since i use vscode as my day to day dev editor for SQL, I often have quite a few "Untitled #" tabs open with connections to different DBs and/or servers, Making it very hard to distinguish who is connected to what.

Using VScode's native approach to title bar naming would be sensible, i think, to allow that distinction.

**Comment by abist** [comment]
@ransagy You could see the connection for each editor in the bottom right corner on the Status Bar. Clicking on it also lets you switch the database.
