### ISSUE TITLE
Add Language Flavor notification support to allow disabling MSSQL processing on a per-file basis

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/vscode-mssql#978]
We implemented Language Flavor notifications in the backend so that we can filter out SQL files we don't want to be treated as MSSQL. This is useful for dynamically skipping files if you have a mix of MSSQL and non-MSSQL files with a .sql extension. We should implement the front-end to:
- Show a button with `MSSQL` or `Other SQL` as the option
- On click, allow user to apply the filter and send the notification

This will mean users can easily opt out of the processing for each file and save some pain. We have a number of issues raised related to this.

**Comment by klukiyan** [comment]
@kevcunnane , very nice idea about MSSQL button.
Before I switched to VScode, I quite enjoyed the option in sublime text that when working with MS SQL I could select T-SQL syntax language, and when working with MySQL I've used the MySQL syntax language. Both appeared as such in the top right corner where you select the language.
