### ISSUE TITLE
sqltoolsservice crashes if sql server is not available. sqltoolsservice does not recover from the failure unless restarting vscode.

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/vscode-mssql#986]
1. Make a connection to a local sql server instance on the editor.
2. restart or stop the sql server instance.

3. sqltoolsservice crashes.

Expected: sqltoolsservice does not crash. gracefully handle the connection error due to the server is not available which was previously available.

This occurs often in a dev environment e.g. all running in a laptop where sql server instance is not always up.

**Comment by ransagy** [comment]
For what's it worth, This happens even when the SQL instance is still up, but your connection is lost. In my case, frequent moves between WiFi and Ethernet.

**Comment by erickangMSFT** [comment]
@ransagy That is correct. I think it's the same root cause.

**Comment by kevcunnane** [comment]
I have a repro for this (at least, the core issue identified here) and will have a PR out shortly that should address this. Thread error handling was the culprit.
