### ISSUE TITLE
Any plans to support this with monaco-editor ?

### ISSUE THREAD

**Issue by ghedwards** [microsoft/vscode-mssql#999]
Any plans to support this with monaco-editor ?

**Comment by ghedwards** [comment]
Hoping to create an internal embedded editor with connections to our internal mssql servers

**Comment by kburtram** [comment]
@ghedwards we haven't looked into hooking up vscode-mssql functionality into monaco-editor project yet.  I'm not sure about that editor's extensibility model.  If it's similar to VS Code with VS Code Language Service Protocol support it may be relatively straightforward to hook-up the SQL Language Service Server ( https://github.com/Microsoft/sqltoolsservice) in that environment.

We'll take a look and see if there's anything we can do in this area.  If you wanted to take a shot at the integration we'd be happy to provide guidance or answer any questions you had.

**Comment by ghedwards** [comment]
Would I be correct in saying this plugin relies on the server for the Intellisense? Is there any scope for better parsing of the SQL on the client using JavaScript ?

**Comment by kburtram** [comment]
That's correct that the Intellisense support in this extension is fully implemented in the out-of-proc .Net Core server.  To implement that feature we ported over the T-SQL parser and online metadata support from SSMS, which is a fairly large block of C# code.  Unfortunately to replicate that logic in pure JavaScript would be a rather big effort that we currently don't have scoped.

This stateful, out-of-proc service is one of the challenges we're investigating regarding how best to host a SQL devops scenario in multi-user web browser app.  Though we don't have any concrete plans in that area at this time.
